### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pratikt4f** [AtomLinter/linter-eslint#1001]
## Issue Type
Bug

## Issue Description
when the error comes, it stops working ( some time ) and after solving all syntax error still shows old error
and also when we restart atom it's working properly but in some time it will give the again same issue

## Bug Checklist
```
Error
ESLint
client\containers\checkout\paynow.js
536
'Index' is defined but never used. (no-unused-vars)
Error
ESLint
client\containers\checkout\paynow.js
539
'travelerIndex' is defined but never used. (no-unused-vars)
Error
ESLint
client\containers\checkout\paynow.js
539
A space is required after ','. (comma-spacing)
Error
ESLint
client\containers\checkout\paynow.js
540
Expected an assignment or function call and instead saw an expression. (no-unused-expressions)
Error
ESLint
client\containers\checkout\paynow.js
540
Expected indentation of 20 space characters but found 16. (react/jsx-indent)
Error
ESLint
client\containers\checkout\paynow.js
540
Expected indentation of 20 spaces but found 16. (indent)
```

**Comment by Arcanemagus** [comment]
@pratikt4f We would need the actual debug output from running the `Linter Eslint: Debug` command to even start looking into what might be going on here. What you posted looks to just be the output of the ESLint messages for a few of the files you were working on.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems @pratikt4f please address the comment above with some further details!
