### ISSUE TITLE
Global .eslintrc file not being used?

### ISSUE THREAD

**Issue by Luminaire117** [AtomLinter/linter-eslint#1002]
## Issue Type

Bug/Question

## Issue Description

Settings that I put in my .eslintrc.js and set in the settings seem to be ignored. I don't have eslint installed outside of the the atom package. There's definitely a large possibility of me doing something wrong, but I'm out if ideas on what to try next. Here is my .eslintrc.js file (just a test file to see if it works):
```
module.exports = {
    "extends": "eslint:recommended",
    "parserOptions": {
      "ecmaVersion": 7
    },
    "rules": {
      "no-inner-declarations": ["off", "both"],
      "quotes": ["error", "single"]
    }
}
```

## Bug Checklist
-Restarted multiple times
-I don't have global eslint installed, 
-Other packages I have installed are:
atom-beautify, busy-signal, highlight-selected, intentions, linter, linter-ui-default, pigments, platformio-ide-terminal

```
Linter Eslint: Debug output here
Atom version: 1.19.6
linter-eslint version: 8.2.1
ESLint version: 3.19.0
Hours since last Atom restart: 0
Platform: win32
Using bundled fallback ESLint from: C:\Users\Alex\.atom\packages\linter-eslint\node_modules\eslint
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "eslintrcPath": "C:\\Users\\Alex\\.eslintrc.js",
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
How are you verifying that they are ignored? Although not recommended, that _should_ work.

**Comment by Luminaire117** [comment]
I'm still getting linter error that I need to use double quotes (even though I set it to single), and that I need to get rid of inner declarations (set to off).

**Comment by IanVS** [comment]
Is there another eslint config file between your project and the root?  Where are the errors coming from?  `eslintrcPath` is only used if another config can't be found using normal config resolution.

**Comment by Luminaire117** [comment]
Oh, the errors are just linter errors coming from linter gui plugin telling me to only use double quotes for strings (when the config is set to single quote).
Where does eslint start looking for a config file from? Atom's current project directory? or from atom's install location? or from the bundled eslint path? My project was set to desktop (and I didn't have a config file there), and global config file was in my users folder so it's only one directory. And nothing from there to C root.
is there anyway to see what config file is currently being loaded?

**Comment by Arcanemagus** [comment]
@Luminaire117 The package emulates ESLint's own config resolution and starts searching for configuration files in the current (and all parent) directory of the file being edited. If it can't find a configuration file under the normal resolution _then_ it will attempt to use the fallback path set in the ".eslintrc Path" setting (as stated in the description).

As @IanVS asked, are you _sure_ there is no other configuration file that might be being used? Unfortunately there is no way to get what configuration file is being used, although that's an excellent idea of something to add to the debug text...

**Comment by IanVS** [comment]
Something you can do to find out what config is being used, is to run `eslint --print-config <path-to-file>` ([docs](https://eslint.org/docs/user-guide/command-line-interface#--print-config)).  If you don't have eslint installed, you can either install it globally for testing and then uninstall it, or if you're using npm v5, you can use `npx eslint --print-config`.

**Comment by skylize** [comment]
> Unfortunately there is no way to get what configuration file is being used, although that's an excellent idea of something to add to the debug text...

@Arcanemagus  +1 for adding this to debug

**Comment by Luminaire117** [comment]
I think it may have been related to plugin Ftp-Remote-Edit, eslint was pointing to the same config as it was using in global settings but still wasn't being loaded. Just updated a few days ago and after testing global config now, seems to work as expected. Thanks for the help!
