### ISSUE TITLE
Arrow function used ambiguously ...

### ISSUE THREAD

**Issue by icetee** [AtomLinter/linter-eslint#1003]
## Issue Type
Question

## Issue Description
I write this line:
```javascript
const locals = $('.tree-view .selected').map((elem) => {
  return elem.getPath ? elem.getPath() : '';
}).get();
```
This will automatically be converted. It's ok, but I get now this error:
`Arrow function used ambiguously with a conditional expression`. ([no-confusing-arrow](https://eslint.org/docs/rules/no-confusing-arrow))

Basically like this function, rule. I do not want to turn it off.

Is this a mistake, or do I break something?

Old code:
```javascript
const locals = $('.tree-view .selected').map(function MAP() {
  return this.getPath ? this.getPath() : '';
}).get();
```

**Comment by IanVS** [comment]
Sorry, but this is not an issue with linter-eslint, but rather a question about using eslint.  If you can give some more details about your linting configuration for the rules in question, I can try to help out, but I'm going to close the issue in the meantime.
