### ISSUE TITLE
Enable for .vue files

### ISSUE THREAD

**Issue by qm3ster** [AtomLinter/linter-eslint#1005]
## Issue Type
Feature Request

## Issue Description
Please add linting vue files. This can be generalized to exposing the scopes array in the configuration pane.

**Comment by IanVS** [comment]
This is already possible using the "List of scopes to run ESLint on" setting:

![image](https://user-images.githubusercontent.com/4616705/30224584-550752d6-949d-11e7-8749-19b4523dd880.png)

**Comment by qm3ster** [comment]
Herpaderp

**Comment by claytonrcarter** [comment]
@qm3ster What scope did you add to the config to get `.vue` files to lint? "Log Scope" reports `text.html.vue` as the correct scope, but that doesn't seem to work here.

**Comment by qm3ster** [comment]
Iirc the relevant one was actually `source.js.embedded.html`
But I am using `ts-lint`+`prettier` on `vscode` nowadays.

**Comment by Arcanemagus** [comment]
@claytonrcarter Scopes are dependent on your cursor position, you need to place your cursor where you are expecting `linter-eslint` to run, and _then_ run `Editor: Log Cursor Scope`.

**Comment by claytonrcarter** [comment]
It turns out I had the scope right ("Lint HTML Files" is checked and `text.html.vue` added to scopes) but had accidentally disabled eslint in the main linter package. Reenabled it and everything is working. Thank you both!
