### ISSUE TITLE
Not formatting closing brackets at last line

### ISSUE THREAD

**Issue by James2516** [AtomLinter/linter-eslint#1010]
## Issue Type

Bug

## Issue Description

![image](https://user-images.githubusercontent.com/427137/30289767-0c44b8da-96e2-11e7-8596-6215c781d805.png)

The last line ```);``` does not get auto formatted (format on save is turned on) to the start of the line at save.
Correct formatting:
![image](https://user-images.githubusercontent.com/427137/30289777-127ba9a2-96e2-11e7-8fea-ba8a08e4b872.png)

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```

**Comment by Arcanemagus** [comment]
Did you go through the bug checklist? We call out to ESLint to perform what fixes it can, since that last `);` isn't even highlighted as an error I doubt that ESLint even knows it needs to be de-denting the line, maybe check your ESLint configuration?

**Comment by IanVS** [comment]
I'm going to close this due to lack of activity, but please let us know if you're still having this problem and we'll reopen.
