### ISSUE TITLE
Windows7 fileDir/filePath are missing \ separator (disk letter and dir joined without \)

### ISSUE THREAD

**Issue by petrdanecek** [AtomLinter/linter-eslint#1011]
## Bug
It seems to be bug probably. I'm using customized configuration. My JSX source code and webpack are in VM/CentOS. The project is exported by Samba and mounted as N: drive to windows. Atom is configured on Win7 OS. The windows node is installed and all the plugins as well (eslint, eslint-plugin-react and so on.) The eslint works fine in Windows PowerShell console. Even Atom works fine until first change in the source code.

## Description
getting error: ENOENT: no such file or directory, uv_chdir Error: ENOENT: no such file or directory, uv_chdir

I added console.log to worker-helpers.js:
```
export function getRelativePath(fileDir, filePath, config) {
  console.log('=>', fileDir, filePath);
```

and the result is:
```
=> N:frontend\Templates N:frontend\Templates\TemplatesList.jsx
```

As per above output it seems that there is no `\` separator between disk and directory (N: and frontend dir).

Any attempt to modify something in the JSX file results in:

```
ENOENT: no such file or directory, uv_chdir Error: ENOENT: no such file or directory, uv_chdir
```

```
linter-eslint debugging information
Atom version: 1.20.0-beta7
linter-eslint version: 8.2.1
ESLint version: 4.6.1
Hours since last Atom restart: 1.5
Platform: win32
Using global ESLint from: C:\Users\petr\node-v7.7.1-win-x64\node_modules\eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.function.js",
  "meta.function.parameters.js",
  "meta.delimiter.comma.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": true,
  "useGlobalEslint": true,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
That path is coming directly from Atom, if you open Developer Tools (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>) and run this in the console, what do you get?
```js
atom.workspace.getActiveTextEditor().getPath()
```

**Comment by petrdanecek** [comment]
I can confirm that I'm getting the same path:

`"N:frontend\Templates\TemplatesList.jsx"`

what should be next step? Report a atom bug?
Or can I apply some workaround to make the plugin working?

BTW the issue is gone once the file is moved to local C: or Z: drives. So it seems to be related to my network N: drive only.

**Comment by Arcanemagus** [comment]
You'll have to file a bug on Atom, there is nothing we can do about it here unfortunately. 😞

**Comment by Arcanemagus** [comment]
Is there anything different from how your `N:\` and `Z:\` drives are mapped?

**Comment by petrdanecek** [comment]
z is local drive. Most likely it is related to network drives only.
thanks anyway for guiding me right direction.

**Comment by Arcanemagus** [comment]
Interesting, paths on my network drives show correctly in Atom.
