### ISSUE TITLE
What is the recommended way to install `linter-eslint` github version for testing.

### ISSUE THREAD

**Issue by skylize** [AtomLinter/linter-eslint#1020]
Trying to help out with development, and unsure if I'm using the best way to install dev files for use within Atom. What are the preferred steps for installing `linter-eslint` to Atom for development from a local fork?

**Comment by Arcanemagus** [comment]
Hmmm, maybe [CONTRIBUTING.md](https://github.com/AtomLinter/linter-eslint/blob/5353699e1bd01204674c1d9372c1a792dc800746/CONTRIBUTING.md) needs expansion?

The way I work on it at least is I have the `atom.io` version installed in Atom normally, and I ran `apm link --dev` from the location I have `linter-eslint` checked out to, so that when I run `atom --dev` it loads the current code state.

**Comment by skylize** [comment]
That sounds roughly like what I did, though I can't quite remember for sure because I only did it once. so far. It took me a bit of googling to work out what to do.

If you know somewhere that lays it out nicely in step by step format, then a link on CONTRIBUTING.md seems sufficient to me. Otherwise, I agree it needs to be added.

It would have been very easy for me to try to `npm` install over top of my standard version if I didn't take the time to research, which obviously would have been a bad choice.

**Comment by Arcanemagus** [comment]
It looks like the flight manual only talks about using the package generator, which does that for you.

**Comment by skylize** [comment]
Hmmmm. I seem to have discovered some unexpected behavior while trying to test this out. I wanted to check out the new error handling. So I deleted `node_modules` from a project and type `atom --dev` hoping that I had it set up to use a linked folder as described. My files in this project are getting linted instead of throwing error, even though I have global turned off. Also happens not in dev mode. 😦

Is there an easy way to check if my dev mode is using the same version as regular? The package version doesn't really help since that doesn't get updated until new publish.

**Comment by Arcanemagus** [comment]
`Linter Eslint: Debug` would tell you where it is loading from. Note that if you deleted that _after_ you had already ran it once it would still be running from memory.

Are you on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638)? That's a better format for discussions like this generally.

**Comment by skylize** [comment]
Yeah, I'll head over to slack. The original question seemed like something worth documenting as an issue, but this is starting to go way off track. :)

**Comment by skylize** [comment]
Solved by #1089. Updated documentation at [Contributing](../blob/master/CONTRIBUTING.md).
