### ISSUE TITLE
TextEditor.editorElement is deprecated.

### ISSUE THREAD

**Issue by sr1994lu** [AtomLinter/linter-eslint#1022]
`TextEditor.prototype.editorElement` has always been private, but now
it is gone. Reading the `editorElement` property still returns a
reference to the editor element but this field will be removed in a
later version of Atom, so we recommend using the `element` property instead.
```
TextEditor.editorElement (<embedded>:2392:20)
evt.path.some.elem (/Users/sr1994lu/.atom/packages/linter-eslint/src/main.js:172:23)
Array.some (native)
Object.shouldDisplay (/Users/sr1994lu/.atom/packages/linter-eslint/src/main.js:168:46)
ContextMenuManager.cloneItemForEvent (<embedded>:24930:25)
ContextMenuManager.templateForEvent (<embedded>:24863:39)
```

**Comment by Arcanemagus** [comment]
Fixed by #1019. It can safely be ignored as it's already using the correct way to do this, it's just _also_ using the (now) incorrect way.
