### ISSUE TITLE
Hang while editing default parameter value.

### ISSUE THREAD

**Issue by danfuzz** [AtomLinter/linter-eslint#1028]
## Issue Type
Bug.

## Issue Description
When editing a `@param` tag that has a default value, the system will hang long enough to prompt Atom to issue a "not responding" dialog box. Depending on the editor contents, sometimes it will eventually complete, but sometimes it looks like it will hang indefinitely.

For example, save this file as `doc-fun.js`:

```javascript
/**
 * Testing.
 *
 * @param {string} foo This is a param.
 * @param {array} [bar = 'x'] REMOVE THE CLOSE BRACKET HERE.
 * @returns {string} A string. Really!
 */
function foo(foo, bar = 'x') {
  return foo + bar;
}

function bar() {
  foo('x');
}

bar();
```

And use this `.eslintrc`:

```javascript
{
  "extends": "eslint:recommended",
  "env": {
    "es6": true
  },  
  "rules": {
    "valid-jsdoc": [
      "warn",
      {
        "prefer": {
          "arg": "param",
          "argument": "param",
          "return": "returns"
        },
        "requireReturn": false
      }
    ]
  }
}
```

Move your caret to just after the `]` on the line that starts `* @param {array}`, and then hit backspace to erase the `]`. The editor will hang, per above.

**Expectation:** No hang.

**Note:** Running `eslint` from a shell on a file that is identical to `doc-fun.js` per above, with the `]` removed, runs to completion promptly without hanging.

```
$ eslint doc-fun2.js

.../doc-fun2.js
  1:1  warning  Missing JSDoc parameter type for 'array'         valid-jsdoc
  1:1  warning  Missing JSDoc parameter description for 'array'  valid-jsdoc
  1:1  warning  Expected JSDoc for 'bar' but found 'array'       valid-jsdoc

✖ 3 problems (0 errors, 3 warnings)
```

## Bug Checklist
[x] Restart Atom
[x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
[x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.20.1
linter-eslint version: 8.3.2
ESLint version: 4.7.0
Hours since last Atom restart: 0.2
Platform: darwin
Using bundled fallback ESLint from: /Users/danfuzz/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js",
  "comment.block.documentation.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by danfuzz** [comment]
Looks like this might be the same root issue as #925, but maybe this issue is still worthwhile as it's a pretty concise example with steps-to-repro.

**Comment by Arcanemagus** [comment]
Amazing, I can reproduce with this, looking into it!

**Comment by Arcanemagus** [comment]
Ah ha, this is actually an Atom bug. You can see this in `atom --safe .` which disables all community packages. I'm _guessing_ that that text triggers an infinite loop in the regex parser, I'll file a bug over on `language-javascript`.

**Comment by Arcanemagus** [comment]
@danfuzz The bug is fixed in `language-javascript`. I'm not sure when it will be released, but as it crashes the editor I'm guessing it will be in the next hotfix release. Thanks again for reporting it, even if it didn't end up being the bug here in `linter-eslint`. 😉
