### ISSUE TITLE
Linting does not work when typing in <template> sections in .vue files

### ISSUE THREAD

**Issue by ryaposov** [AtomLinter/linter-eslint#1031]
## Issue Type
Bug

## Issue Description
Linting-on-type works only if you are typing in <script> section. Errors that are present in `template` are not recognized until you type anything in <script>. Using [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) and [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html)

## Bug Checklist
- Open project with .vue file
- Enter some code with parsing error in `template` section of a file
- Notice that there are no linting errors and warnings in Atom UI
- Type anything in <script> section of a file
- Notice that linting errors in `template` section are now present Atom UI

```
Atom version: 1.20.1
linter-eslint version: 8.3.2
ESLint version: 4.7.2
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/paul/Projects/ulime/cordova-test/com.example.projectname/node_modules/eslint
Current file's scopes: [
  "text.html.vue",
  "source.js.embedded.html",
  "punctuation.definition.tag.html"
]
linter-eslint configuration: {
  "eslintrcPath": "/",
  "lintHtmlFiles": true,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic",
    "source.vue"
  ],
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5815992/30808099-5754aeec-a205-11e7-9604-e7cb430696f3.gif)

**Comment by IanVS** [comment]
I'm not so familiar with vue files, could you put your cursor into the `template` section and then run `Log cursor scopes` from the command palette, and let us know what comes back?  My uneducated guess is that it's a different scope which isn't covered by your configuration.

**Comment by ryaposov** [comment]
Here it is for <template>:
```
text.html.vue
meta.tag.other.html
meta.attribute-with-value.id.html
string.quoted.double.html
meta.toc-list.id.html
```

And for <script>:
```
text.html.vue
source.js.embedded.html
```

**Comment by IanVS** [comment]
Yep, you'll notice that nothing from the `template` scope is in your scope configuration:

```
linter-eslint configuration: {
  "eslintrcPath": "/",
  "lintHtmlFiles": true,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic",
    "source.vue"
  ],
```

Try adding `text.html.vue` to your linter-eslint scopes setting, and see if that fixes it.

**Comment by ryaposov** [comment]
Fixed, thanks a lot!
