### ISSUE TITLE
atom linter not working

### ISSUE THREAD

**Issue by sachour** [AtomLinter/linter-eslint#1032]
## Linter stopped working. My machine is mac running on macOS Sierra 10.12.6. It was running before, then one day it stopped. I tried linting python and fortran but both didn't work, and the python linter spits out this error message:"

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: 'linter-ui-plus' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/sofianeachour/.atom/packages/linter-ui-plus/lib/index.js:134

TypeError: Cannot read property 'indexOf' of undefined
    at subscriptions.add.textEditor.onDidDestroy (/packages/linter-ui-plus/lib/index.js:134:36)
    at wrapped (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:661:26)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:707:66)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
  3x -5:38.4.0 core:confirm (input.hidden-input)
     -3:19.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -2:46.1.0 core:backspace (input.hidden-input)
     -2:40.1.0 core:confirm (input.hidden-input)
     -2:27.5.0 core:backspace (input.hidden-input)
     -2:27.2.0 core:confirm (input.hidden-input)
     -1:37.7.0 application:new-file (input.hidden-input)
  6x -1:32.6.0 core:backspace (input.hidden-input)
     -1:30.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-fortran 2.1.6 
linter 2.2.0 
linter-gfortran 0.5.0 
linter-python 3.1.2 
linter-ui-default 1.6.10 
markdown-table-editor 0.6.4 
script 3.16.0 
```
"
I am completely new to programming, never taken a class so I have very weak basis and unfamiliar to most of the technical language like i have no idea what the instructions below mean. Plz help me getting it to work again!

Thanks!

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```

**Comment by Arcanemagus** [comment]
It looks like you have `linter-ui-plus` installed from the stack trace. That is an experimental UI that is meant to explore a new UI concept. It has many known bugs with Linter v1 API providers such as `linter-python` and `linter-gfortran`. Please disable/uninstall that package and use the standard `linter-ui-default` package.

If you have further questions it might be better to discuss this in chat. Please hop into [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638) and ask your questions in the [#linter](https://atomio.slack.com/messages/C06KUJMA4/) channel.

Closing this issue as it doesn't appear to have anything to do with `linter-eslint`.

**Comment by sachour** [comment]
![screen shot 2017-09-25 at 6 14 28 pm](https://user-images.githubusercontent.com/32281484/30835344-6ab601bc-a21d-11e7-95f5-65b2dce82df0.png)
![screen shot 2017-09-25 at 6 14 36 pm](https://user-images.githubusercontent.com/32281484/30835343-6ab44dae-a21d-11e7-9737-c24f88712d4f.png)
linter-ui-plus is not actually installed though, I have attached two screenshots as a proof.

**Comment by Arcanemagus** [comment]
![image](https://user-images.githubusercontent.com/427137/30835795-fdc8951e-a20e-11e7-9806-796a7aa87b47.png)

Your screenshot shows that it's at least _partially_ there. You should close all instances of Atom and delete the folder. Again, this isn't the place to be going through this though as this has _nothing_ to do with `linter-eslint`.
