### ISSUE TITLE
Issues With Setup

### ISSUE THREAD

**Issue by bdelanghe** [AtomLinter/linter-eslint#1036]
# Question

## Issue Description

I'm unable to get ESlint Fix to run. I have ESlint installed globally and my '.eslintrc' json file is created. 
I've gone and installed the 'read-pkg-up' node globally as well. But the error is the same:

```
'Cannot find module 'read-pkg-up' Referenced from: 
....\node_modules/eslint-config-airbnb-base/index.js'

```
## Eslint Debug
```
atom version: 1.21.0
linter-eslint version: 8.3.2
ESLint version: 4.8.0
Hours since last Atom restart: 0.6
Platform: darwin
Using global ESLint from: /usr/local/lib/node_modules/eslint
Current file's scopes: [
  "source.js"
]
linter-eslint configuration: {
  "fixOnSave": true,
  "globalNodePath": "/usr/local",
  "ignoreFixableRulesWhileTyping": true,
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
Is that the literal error message (the `....` part), or did you remove part of it? It's _very_ hard to diagnose these global install user setup issues, especially when information is hidden.

It's highly recommended you use a project local setup btw.

**Comment by bdelanghe** [comment]
Appologies for hiding the file path. I was able to capture a more in depth error:

<img width="805" alt="screenshot 2017-10-14 12 16 57" src="https://user-images.githubusercontent.com/1240090/31577299-0b612360-b0da-11e7-8ee6-17ad6a82ce4f.png">

@Arcanemagu I might switch to a local setup. I figured this would be a node I'd use globally but might be in over my head.

**Comment by skylize** [comment]
If using global ESLint, you also need to install all your plugins to global.
