### ISSUE TITLE
Linting <script> elements in HTML files.

### ISSUE THREAD

**Issue by mysticatea** [AtomLinter/linter-eslint#104]
Could I lint those?

**Comment by k2b6s9j** [comment]
This may be possible with the new API. /cc @steelbrain

**Comment by steelbrain** [comment]
It is, 'cause the JS embedded inside the `<script>` elements adds `source.js` to it's scope or something similar, if the provider adds it in their `grammarScopes` then sure.

**Comment by iam4x** [comment]
@mysticatea This is in the scope of ESLint directly, you may want to use: https://github.com/BenoitZugmeyer/eslint-plugin-html

**Comment by mysticatea** [comment]
@iam4x Thank you for the information. It works good on command line. :) 

But I could not find how to show warnings on Atom.
I guess `linter-eslint` does not lint on `.html` files, could I add extensions by setting?

**Comment by pitaj** [comment]
Why was this closed? It is a perfectly viable request for the `linter-eslint` plugin to at least *have the option* to lint HTML files. 

I haven't found a way of getting this to work. I tried this:

+ Assigning `.html` files with `source.js` via `file-types`
+ `npm install eslint eslint-plugin-html --save-dev`
+ Adding `html` to the `.eslintrc` `plugins` array

However, while this caused linter to run eslint on HTML files, it removed HTML code highlighting. 
Also, I could not get linter-eslint to recognize the local eslint install (so a bunch of unexpected `<` errors.

As mentioned in #194, GrammarScopes would be the best way to go about this. It would allow syntax highlighting to work while simultaneously not even requiring `eslint-plugin-html`
