### ISSUE TITLE
Disable all errors and warnings while typing.

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [AtomLinter/linter-eslint#1043]
## Issue Type
Feature Request

## Issue Description
I just started using linter-eslint with linter and linter-gui, I love it except for one little detail that really gets on my nerves.
In between me typing, I get warnings and error, there's already an option to disable alerting about 'fixable errors' while typing.

But this is not enough, whenever I type `if ( )` for example, I get an error, and I find that distracting. I wish there was an option to disable ALL warnings and errors while typing, only show them on save.

**Comment by skylize** [comment]
Uncheck "Lint on Change" in the `linter` package.

**Comment by AbdelrahmanHafez** [comment]
You are my new hero. 😄
