### ISSUE TITLE
Closes autocomplete prompt

### ISSUE THREAD

**Issue by msaspence** [AtomLinter/linter-eslint#1052]
## Issue Type

Bug

## Issue Description

Autocomplete prompt closes when eslint runs as I type. Potentially an external issue.
 
```
Atom version: 1.21.1
linter-eslint version: 8.4.0
ESLint version: 4.9.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/msaspence/Projects/timeteam/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "string.quoted.module.js",
  "punctuation.definition.string.end.js"
]
linter-eslint configuration: {
  "fixOnSave": true,
  "rulesToDisableWhileFixing": [
    "no-debugger"
  ],
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by IanVS** [comment]
I was noticing a problem where autocomplete was closing unexpectedly as well, but nothing has changed in linter-eslint lately, so I'm not sure it's due to linting.  What makes you think it has something to do with this package?  Also, out of curiosity, are you using nuclide?  I feel like it started happening for me after I updated nuclide, but could be coincidence.

**Comment by msaspence** [comment]
I’m not using Nuclide but do have atom-ide-ui installed which I think is
related, not sure? My main reason that I think it has something to do with
this package, is that this is the only one I install when it started
occurring. And the autocomplete is closed as the file is linted.

**Comment by IanVS** [comment]
Are you using the `linter` package to do the linting, or does `atom-ide-ui` run the linting?  If you're using `linter`, could you try to disable the `"Lint on Change"` option, and see if that resolves the issue?  If so, it would seem indeed that there's a bad interaction somehow.  You could also try to disable `atom-ide-ui`, and see if that resolves the issue, which will further help to narrow down the cause.

Thanks!

**Comment by msaspence** [comment]
I've been unable to replicate more recently. I've recently updated a few IDE packages to hopefully it was something in there. Will reopen with more details if it reemerges.
