### ISSUE TITLE
Not working when file is ignored by git

### ISSUE THREAD

**Issue by nickjanssen** [AtomLinter/linter-eslint#1053]
## Issue Type
Bug

## Issue Description
When a file is ignored by git, atom won't show any linter errors/warnings.

To reproduce: add a file to `.gitignore` and then open it.

```
Atom version: 1.22.0
linter-eslint version: 8.4.0
ESLint version: 4.11.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/nickjanssen/Documents/docs/eslint-test/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.function.arrow.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by skylize** [comment]
Hmm. I think that's a feature, not an issue. Do you _really_ want to lint your whole node_modules folder against your project config? 

If you uncheck Exclude VCS Ignored Paths in Atom Core Settings, then all project files will be available for linting, including node_modules and any other files/folder ignored by your .gitignore.

**Comment by nickjanssen** [comment]
@skylize `node_modules` is ignored by default by eslint. When I manually run `./node_modules/.bin/eslint .`the file is linted as expected. 

I do not wish to uncheck `Exclude VCS Ignored Paths` as this makes global project searches a pain. I don't understand why the atom linter would also want to ignore these paths, as there is already functionality built into eslint by using `.eslintignore` should the user desire to do so.

**Comment by Arcanemagus** [comment]
@nickjanssen As @skylize pointed out, this is controlled by the Atom wide setting in `linter` itself (not `linter-eslint`).

You can either:
* Temporarily disable that setting
* Create a git repo in the sub-folder you are editing (`git init`), it doesn't need to have anything in it. Add that folder as a separate Project in Atom and edit the file from there. That way the `.gitignore` in your main project will be ignored.
