### ISSUE TITLE
Linter Eslint: Debug throws error when no eslintconfig

### ISSUE THREAD

**Issue by skylize** [AtomLinter/linter-eslint#1054]
## Issue Type

Bug

## Issue Description

Attempted to debug a project that was not linting because I forgot to add an eslintconfig, but debug threw an exception instead of offering useful debugging info.

## Linter Eslint: Debug output here
```
Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined
    at Object.<anonymous> (C:/Users/sky/.atom/packages/linter-eslint/helpers.js:130:22)
    at Generator.next (<anonymous>)
    at step (C:/Users/sky/.atom/packages/linter-eslint/helpers.js:9:1)
    at C:/Users/sky/.atom/packages/linter-eslint/helpers.js:9:1
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by IanVS** [comment]
Good catch.  Want to take a crack at a PR to avoid that?

**Comment by Arcanemagus** [comment]
@skylize Would you be interested in becoming a maintainer here? You've been active on helping out with the issues which is great, and if you want to take on a bit more responsibility, even if it's just continuing to help out there with the added ability to do labels on issues that would be great 😉.

**Comment by skylize** [comment]
@Arcanemagus 

Seems my github notifier got disabled somehow. I was wondering why it was so quiet the last couple weeks. Haha

>Would you be interested in becoming a maintainer here?

Let me think about that and get back to you. It seems I haven't even been able to get to the updates I said I would look into, so not sure if more responsibility is appropriate at the moment.

**Comment by IanVS** [comment]
Eh, it's not so much about additional responsibility, just an indication that we appreciate your involvement and wanted to offer the chance to make it more formal.  There's no expectations--this is open source after all, we're all just doing this in our "spare time."

**Comment by skylize** [comment]
Looks like this was fixed.
Current behavior with missing config is linter message with description "...No ESLint configuration..." 👍

**Comment by skylize** [comment]
@Arcanemagus I'll accept your offer for maintainer status if it's still available.
