### ISSUE TITLE
How do I turn off or modify eslint highlighting 

### ISSUE THREAD

**Issue by backspaces** [AtomLinter/linter-eslint#1055]
## Issue Type

Bug

## Issue Description

eslint highlighting of errors is so opaque that the code beneath is unreadable and makes fixing errors impossible:
![snap 11 12 17-13 08 10](https://user-images.githubusercontent.com/124366/33040248-c04a873a-ce3a-11e7-8647-0ee58157c485.jpg)

At the very least, eslint should document how to modify the error highlighting. Css etc would be fine.

This was submitted to the Atom Forum, but with no response. 
  https://discuss.atom.io/t/how-do-i-turn-off-or-modify-eslint-highlighting/49610

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

There are no crashes related to this, and the cli reports errors correctly. The issue is that it fails to be useful in the editor.

```
Linter Eslint: Debug output here
```
None

**Comment by Arcanemagus** [comment]
This package only provides the interface between `eslint` and Atom's linting ecosystem, it has no UI of its own.

None of the methods of getting those messages to show in Atom look like that though (`linter` + `linter-ui-default` or `linter-ui-plus`, `atom-ide-ui`) so I'm not sure what you have going on there. My best guess is that you are using `linter` and `linter-ui-default` and decided to apply the "fix" in https://github.com/steelbrain/linter-ui-default/issues/441, that looks about as broken as I would expect from what they posted.

I'm closing this issue as it has nothing to do with `linter-eslint` (or `eslint` for that matter), but if the above isn't enough to point you to what broke the normal way of things working feel free to comment again and we'll try to help out!

**Comment by backspaces** [comment]
Fixed: I just needed latest updates. Thanks for pointers and info.

**Comment by pzhine** [comment]
Just go to Settings -> Packages -> linter-eslint and click `Disable` (see screenshot)
<img width="993" alt="captura de pantalla 2018-12-21 17 43 01" src="https://user-images.githubusercontent.com/2692844/50353300-120ae980-0548-11e9-9f72-2bea8b353ea1.png">

**Comment by fonziemedia** [comment]
Hi, 

Would be great to have a shortcut for this so we don't have to go into the settings.

Eslint can make atom really slow when making extensive code changes..

Cheers

**Comment by Arcanemagus** [comment]
You can add a command that toggles that: [The Init File](https://flight-manual.atom.io/hacking-atom/sections/the-init-file/)

A better idea is to just create a [custom keybinding](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings) for the `linter:toggle-active-editor` command.

In any case none of this has _anything_ to do with `linter-eslint` so I'm going to lock this issue.
