### ISSUE TITLE
ESLint: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by noe132** [AtomLinter/linter-eslint#1056]
## Issue Type

Bug

## Issue Description

I have a project using webpack and eslint with eslint-plugin-import. In my webpack config I used a [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin) for build cache, which dependencies includes a package named "leveldown".

```js
// webpack.conf.js
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin')
// blah blah
plugins: [
      new HardSourceWebpackPlugin()
]
```
every first time open atom, eslint gets some errors, along some other rules seems broken too
```
Resolve error: A dynamic link library (DLL) initialization routine failed.
\\?\F:\backup\Desktop\s\node_modules\leveldown\build\Release\leveldown.node (import/extensions) 1:1
Resolve error: A dynamic link library (DLL) initialization routine failed.
\\?\F:\backup\Desktop\s\node_modules\leveldown\build\Release\leveldown.node (import/no-extraneous-dependencies) 1:1
```

![](https://user-images.githubusercontent.com/2271900/33115478-1dd99e92-cf9c-11e7-8cdf-3de07becd01c.png)

after try disabled something, I found that after open Atom, comment out
```js
// webpack.conf.js
// const HardSourceWebpackPlugin = require('hard-source-webpack-plugin') 
// new HardSourceWebpackPlugin()
```
these two lines, and save the webpack.conf.js, it all works normal. And then I cancel the comments of HardSourceWebpackPlugin, it still working properly

### steps in short
1. open atom
2. getting error
3. comment two lines above
4. working fine
5. cancel the comment above
6. working fine

or  

0. comment two lines before open/restart atom
1. open atom
2. works fine
3. cancel comment
4. works fine

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

using eslint cli works fine with no error
```
F:\backup\Desktop\s [master +2 ~1 -0 !]
λ .\node_modules\.bin\eslint .\src\
F:\backup\Desktop\s [master +2 ~1 -0 !]
λ
```

```json
Linter Eslint: Debug output here
Atom version: 1.22.1
linter-eslint version: 8.4.0
ESLint version: 4.11.0
Hours since last Atom restart: 0.2
Platform: win32
Using local project ESLint from: F:\backup\Desktop\s\node_modules\eslint
Current file's scopes: [
  "source.js",
  "meta.import.js",
  "string.quoted.single.js",
  "punctuation.definition.string.end.js"
]
linter-eslint configuration: {
  "ignoreFixableRulesWhileTyping": true,
  "lintHtmlFiles": true,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
I'm guessing this is yet another bug in the `webpack` code. Most of the time this is due to assumptions in the configuration file about running in a CLI environment (there are no arguments when running here!), but it could be anything.

If you want this investigated please create a minimal repository that reproduces this, but this is almost certainly a bug in [`eslint-import-resolver-webpack`](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack).

**Comment by noe132** [comment]
@Arcanemagus 
hi, I create a minimal repo to reproduce this
[https://github.com/noe132/resolve-error-reproduce](https://github.com/noe132/resolve-error-reproduce)

**Comment by skylize** [comment]
@noe132 Sorry nobody had a chance to respond to you. Is this still an issue you need looked into?

**Comment by noe132** [comment]
I'll close this that it no longer bothers me now after upgrading some of the dependencies. It might be something related to the earlier version of [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin).
