### ISSUE TITLE
eslint global not working

### ISSUE THREAD

**Issue by broros** [AtomLinter/linter-eslint#1057]
installing eslint 
```
~: brodyr$ sudo npm i -g eslint
Password:
/usr/local/bin/eslint -> /usr/local/lib/node_modules/eslint/bin/eslint.js
+ eslint@4.11.0
added 3 packages, removed 6 packages and updated 122 packages in 2.855s
~: brodyr$ apm install linter-eslint
Installing linter-eslint to /Users/brodyr/.atom/packages ✓
```

Global node installation path: /usr/local 

use global enlist installation is checked

 do I need to do anything else?

**Comment by IanVS** [comment]
Do you have an eslint configuration file in your project?  If not, you can run `eslint --init` in your project directory to walk through creating one.

**Comment by broros** [comment]
is there a way without initiating enlist in my local project?

I thought that by installing eslint globally I don't have to do eslint --init in my local project

**Comment by Arcanemagus** [comment]
@broros Whether your ESLint installation is global or not isn't relevant to needing a configuration telling ESLint what to do for that specific project.

Note that it is _highly_ recommended that you use a local installation:
* Other people working on the project get the same configuration you are using
* Updating your global install doesn't suddenly make a project that worked fine before seem broken
* When you come back to the project after a long break you can see exactly the setup needed to start working on it again

Although _supported_, global installs are very much not recommended.

**Comment by skylize** [comment]
I absolutely second this recommendation.

> Note that it is highly recommended that you use a local installation

However, the eslint binary will always fall back to searching the user home directory for a config. So if you really must use a global installation, then `eslint --init` in your home directory instead should get you going as long as you don't want to use any plugins.
