### ISSUE TITLE
ESLint not found, please ensure the global Node path is set correctly

### ISSUE THREAD

**Issue by MattLWong** [AtomLinter/linter-eslint#1060]
## Question
I get an error on the first line of every file that says, "ESLint not found, please ensure the global Node path is set correctly..." Is there a step in the configuration process I omitted? Thanks in advance.

**Comment by Arcanemagus** [comment]
How do you have ESLint setup for your project? Local installation in the project (recommended)? Or are you trying to use a global ESLint installation on your computer?

**Comment by MattLWong** [comment]
I am trying the global ESLint installation.

**Comment by MattLWong** [comment]
I've solved the problem. I unselected "Use global ESLint installation"

**Comment by andrewclavin** [comment]
Where do you select or unselect "Use global ESLint installation"?

**Comment by Arcanemagus** [comment]
Under the package settings within Atom @andrewclavin.

**Comment by roberto-slopez** [comment]
I installed `npm install -g eslint` but still it does not work, I have selected the global configuration; I'm executing `eslint` in the cmd and it recognizes the command, but as I mentioned, it keeps throwing me the same error 

> ESLint not found, please ensure the global Node path is set correctly

I use windows 10

**Comment by newaeonweb** [comment]
Old question but never resolved, what i missed something?

**Comment by elliotaplant** [comment]
For anyone who _does_ want to use global eslint, make sure a few things are true:
- You have a global eslint config file and that it has been set (eg, `~/.eslintrc.js`)
- Your eslintrc file is valid
- You installed eslint is installed globally with *npm*

I installed eslint globally with `yarn`, and linter-eslint wasn't able to find it, but `npm install -g eslint` worked just fine
