### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by 719Ben** [AtomLinter/linter-eslint#1062]
## Issue Type
Bug

## Issue Description
Hello, I have webpack (webpacker) set up with rails. My project has `.babelrc` and `.eslintrc.json` at the root, but due to webpacker config, my config is located in `{root}/config/webpack`. I am trying to set up linting but I get the following errors on Atom:

```
Error	ESLint	Resolve error: Unexpected token import (import/no-named-as-default)	1:1
Error	ESLint	Resolve error: Unexpected token import (import/no-extraneous-dependencies)	1:1
Error	ESLint	Resolve error: Unexpected token import (import/no-named-as-default-member)	1:1
Error	ESLint	Resolve error: Unexpected token import (import/no-duplicates)	1:1
Error	ESLint	Resolve error: Unexpected token import (import/extensions)	1:1
Error	ESLint	Resolve error: Unexpected token import (import/no-unresolved)	1:1
Error	ESLint	'modules' should be listed in the project's dependencies. Run 'npm i -S modules' to add it (import/no-extraneous-dependencies)	2:1
Error	ESLint	Missing file extension for "modules/segmentTracker" (import/extensions)	2:28
Error	ESLint	Unable to resolve path to module 'modules/segmentTracker'. (import/no-unresolved)	2:28
Error	ESLint	'modules' should be listed in the project's dependencies. Run 'npm i -S modules' to add it (import/no-extraneous-dependencies)	3:1
```

my .eslintrc.json has the following settings for webpack:
```
"settings": {
    "import/resolver": {
      "webpack": {
        "config": "config/webpack/resolvers.babel.js"
      }
    }
  }
```
and `config/webpack/resolvers.babel.js` looks like the following:

```
import path from 'path'

module.exports = {
  resolve: {
    alias: {
      modules: path.resolve('app/javascript/modules'),
    },
  },
}
``` 
and on that file I get the following errors:
```
Error	ESLint	Error while running ESLint: (node:82491) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
```
I do not get the errors when running `./node_modules/.bin/eslint app/javascript`. I also do not get the errors when I use plugins for Sublime or VSCode.

## Bug Checklist
Output of the `Linter Eslint: Debug` command from the Command Palette below:

```
Atom version: 1.23.1
linter-eslint version: 8.4.0
ESLint version: 4.12.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/benwilliams/GitHub/masterclass/node_modules/eslint
Current file's scopes: [
  "source.js",
  "meta.import.js",
  "string.quoted.single.js",
  "punctuation.definition.string.end.js"
]
linter-eslint configuration: {
  "disableFSCache": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment]
It looks like webpack configs aren't treated as `module`s, so the `import` syntax isn't valid there. From https://github.com/benmosher/eslint-plugin-import/issues/536#issuecomment-250946844 it seems you can work around this by "require `'babel-register'` from the file".

**Comment by 719Ben** [comment]
That fixed it, but it's strange because I hit that issue when trying to get this to run on Sublime and it was fixed by changing the filename from `resolvers.js` to `resolvers.babel.js`. This makes the config run through babel, so the `import` syntax should work. Any reason you could think of why there is different behavior with this package? Thanks for all your help!

**Comment by Arcanemagus** [comment]
The loading of that configuration is done through ESLint itself, so I'm not sure why there would be a difference. Possibly the Sublime version is using ESLint through the CLI instead of the Node.js API?
