### ISSUE TITLE
"overrides" key in eslintrc not being used?

### ISSUE THREAD

**Issue by macgyver** [AtomLinter/linter-eslint#1063]
## Issue Type
Bug

## Issue Description
A project I work on uses module colocation so script files meant for different environments might be in the same folder (e.g. model and test files for a component, which are run as a node server process might be in the same folder as a client script which is meant to run in the browser), so I need to use the file glob overrides feature of eslint https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

In Atom, it seems like this client script is being linted according to the top-level rules (which apply to the node scripts) and not by the overrides rules for client scripts.

here's my `eslintrc.js` file:
```js
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 6
  },
  env: {
    node: true
  },
  rules: {
  	"no-undef": 1
  },
  overrides: [
    {
      files: [
        "components/**/client.js"
      ],
      env: {
        node: false,
        browser: true,
        amd: true
      },
    }
  ]
}

```

For one of my client files, this is the output in Atom:
![screen shot 2017-12-15 at 11 10 17](https://user-images.githubusercontent.com/1163/34050368-9c5e670e-e188-11e7-91ac-beaf82f0d36e.png)

Whereas on the cli, this is what I see (no errors or warnings):
```zsh
$ eslint -v
v4.13.1
$ eslint components/__component__/client.js

$
```

I believe the cli is working correctly, and the behavior in the Atom package is a bug?

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.23.1
linter-eslint version: 8.4.0
ESLint version: 3.19.0
Hours since last Atom restart: 0.3
Platform: darwin
Using local project ESLint from: /Users/__username__/__repo__/node_modules/eslint
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js"
]
linter-eslint configuration: {
  "fixOnSave": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment]
Would you be able to create a `.zip` file / gist / repo that shows the structure you are working with in order to test this further? I'm guessing that something is messing up when trying to find the configuration file.

**Comment by macgyver** [comment]
Hmm this is very peculiar - I tried to make a reduced test case and I can't repro the bug, but the issue still exists in the complete repo. I'll try to figure out what the difference is but this is the structure:

```
.
├── .eslintrc.js
└── components
    └── foo-foo
        ├── client.js
        └── model.js
```

**Comment by macgyver** [comment]
here's some new info - it seems like something in the `node_modules` folder is causing the issue, I'll keep working to make a reduced test case but can you think of any reason why something in there could affect the functionality of this atom plugin for the repo?

**Comment by macgyver** [comment]
ok I just started deleting files from `node_modules` and checking to see if the linting was working as expected, and (this is obvious in hindsight) the folder that is messing things up is `eslint`, but for a crazy reason:  `node_modules/eslint` can be an empty folder!

You should be able to reproduce the bug by creating this folder structure:
```zsh
├── .eslintrc.js
├── components
│   └── foo
│       ├── client.js
└── node_modules
    └── eslint
```

where `.eslintrc.js` is:
```js
module.exports = {
  root: true,
  env: {
    node: true
  },
  rules: {
  	"no-undef": 1
  },
  overrides: [
    {
      files: [
        "components/**/client.js"
      ],
      env: {
        node: false,
        browser: true,
      },
    }
  ]
}

```

and `client.js` is simply:
```
window
```

expected: `client.js` file is parsed according to the `overrides` rules (which enable the browser env) and should trigger no warnings
observed: client.js triggers the `no-undef` warning for the `window` variable

**Comment by macgyver** [comment]
You know what? after restarting Atom this error has gone away. 🤷‍♂️

**Comment by Arcanemagus** [comment]
Ah, sorry I should have mentioned that when testing something like this you should restart Atom to ensure the worker process is restarted since a _lot_ of stuff gets cached on the first run of the worker so lints take ~30ms instead of ~2000ms.

**Comment by macgyver** [comment]
Thanks for helping investigate - I really did restart it at some point in the process (when checking off that item in the bug description template). I don't think a new version of any of the linter packages got installed since then, so I'm not quite clear on when during the process a restart is required - changes to `eslintrc` and other files seem to get picked up immediately. Anyway, I'm just glad it's working now! Great package.

**Comment by macgyver** [comment]
Also one last update for anybody else who stumbles onto this page - I just set this up again on a different computer (also macOS) and had the same issue. I tried updating everything and restarting multiple times but the issue persisted.

It finally ended up getting fixed after I deleted the `node_modules/eslint` folder. I was able to reinstall it later w/o causing the error to re-appear. I can't claim to understand why this works, but it seems repeatable (based on my two experiences)

**Comment by Arcanemagus** [comment]
Are the versions of `eslint` being installed initially and when you "fix" it different maybe?

**Comment by macgyver** [comment]
Seems like that is part of the problem - the version of `eslint` that is
part of my project's dependency tree is ^3.19. I guess the fix for the
problem is to specify eslint as a top-level dependency for my project. It
feels a little wrong because it's not really a code dependency, I'm just
trying to set up linting for my editor. On the other hand though, it's good
to be explicit about the version of eslint the eslintrc file in the repo is
designed to work with, and in any case it doesn't hurt to add.

If there's any bug in this package, it's this: I set the Global Node
Installation Path in the settings for the package, so I would expect for
that version of eslint to be used (the same one that runs when I type
`eslint` on the command line) rather than the version that is local to the
repo, but it seems like the local one is being used.

**Comment by skylize** [comment]
@macgyver 
>  guess the fix for the problem is to specify eslint as a top-level dependency for my project. It
feels a little wrong because it's not really a code dependency, I'm just trying to set up linting for my editor.

That is _exactly_ the suggested way of using it. Install `eslint` as a `devDependency` and include a `.eslintrc.*` local to the project as well. That way you know that other people, (or yourself in the future) are using compatible linting setup. This ***is*** a development dependency, just like any other build-pipeline tool (i.e. `babel`, `webpack`, `gulp`, etc.) that does not land inside the production code. 

If you publish to `npm`, users won't download dev dependencies unless they manually type `npm install` from the project folder. But if someone is working on the project with you, you want to be sure they use the same linting setup.

**Comment by macgyver** [comment]
Thanks Sky and Landon - I'm starting to understand now. I'm not really into "code-style" lints or enforcing rigid contribution guidelines for a project, I'm just trying to get the editor to alert me to things I probably didn't mean to do, like accessing undeclared variables, etc..  maybe that explains a little bit why I didn't expect to be making updates to the repo, but your explanations are helping me to understand. Anyway I'm psyched to have resolved the issues, thanks again for all your help and guidance!
