### ISSUE TITLE
Asks for eslint-plugin-react, despite being globally installed

### ISSUE THREAD

**Issue by atombender** [AtomLinter/linter-eslint#107]
Getting this request for `eslint-plugin-react` to be installed *in my project*, despite the fact that it's globally installed and part of the global `~/.eslintrc`.

![screen shot 2015-06-17 at 00 46 11](https://cloud.githubusercontent.com/assets/50314/8199863/7d2e2aa4-148a-11e5-8ee1-dc8ff9d3e9e0.png)

This is the only debug output:

![screen shot 2015-06-17 at 00 48 59](https://cloud.githubusercontent.com/assets/50314/8199885/cd1ca8ba-148a-11e5-9fb1-65b613c4fc0a.png)

Running `eslint` in the shell works fine.

From `~/.eslintrc`:

```
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
...
```

**Comment by iam4x** [comment]
linter-eslint won't look for plugins globally installed yet, you should install it locally to your project.

**Comment by atombender** [comment]
Do you plan to fix this? We are not going to pollute our projects' `package.json` file with editor-specific modules and versions thereof.

**Comment by ivanoats** [comment]
I can confirm this error. My default ~/.eslintrc requires eslint-plugin-react but the project I am working on does not. Still errors.

**Comment by iam4x** [comment]
Discussion continued into #128
