### ISSUE TITLE
Linting JavaScript embedded in HTML is not working

### ISSUE THREAD

**Issue by darthmall** [AtomLinter/linter-eslint#1071]
## Issue Type

Bug

## Issue Description

I've turned on "Lint HTML Files", but I get no linting errors in Atom in HTML files. It does work for JavaScript files, and if I run `./node_modules/.bin/eslint test.html` from the command line, it works on the embedded JavaScript.

```
$ ./node_modules/.bin/eslint test.html
test.html
  11:5   warning  Unexpected console statement  no-console
  11:17  error    Strings must use singlequote  quotes
  11:27  error    Missing semicolon             semi
```

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.23.3
linter-eslint version: 8.4.0
ESLint version: 4.15.0
Hours since last Atom restart: 0.2
Platform: darwin
Using local project ESLint from: /Users/evan/Documents/ixda/node_modules/eslint
Current file's scopes: [
  "text.html.basic",
  "meta.tag.script.html",
  "source.js.embedded.html",
  "entity.name.type.object.console.js"
]
linter-eslint configuration: {
  "showRuleIdInMessage": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

![screen shot 2018-01-10 at 2 04 15 pm](https://user-images.githubusercontent.com/52247/34790639-53bd791c-f610-11e7-867a-da90d8e7be3d.png)

**Comment by Arcanemagus** [comment]
> `"lintHtmlFiles": false,`

Looks like the setting is disabled, at least for whenever you ran `Linter ESLint: Debug`.

**Comment by darthmall** [comment]
You're right. I was trying several different combinations of that boolean and the custom scopes list to get it working and I must've copied the wrong debug output. I set up a [test project](https://github.com/darthmall/linter-eslint-embedded-js-test) this morning and checked again. It's still not working for me.

```
Atom version: 1.23.3
linter-eslint version: 8.4.0
ESLint version: 4.15.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/evan/Documents/html-linter-test/node_modules/eslint
Current file's scopes: [
  "text.html.basic",
  "meta.tag.script.html",
  "source.js.embedded.html",
  "meta.method-call.js",
  "meta.arguments.js",
  "punctuation.definition.arguments.end.bracket.round.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": true,
  "showRuleIdInMessage": false,
  "useGlobalEslint": false,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}```

**Comment by Arcanemagus** [comment]
Oh _fascinating_, are you using `atom-ide-ui` by any chance? This works perfectly fine in `linter` + `linter-ui-default`, but it looks like `atom-ide-ui` doesn't show the results.

**Comment by darthmall** [comment]
I was, yes. I have also tried it with `linter` and `linter-ui-default` and I still get no results. I have completely uninstalled any `atom-ide` packages I had, cleaned out my `config.cson`, reinstalled the linter packages from scratch, upgraded to linter 2.2.0, and restarted Atom. I still get no output on that file.

**Comment by Arcanemagus** [comment]
Hmmm, can you close _all_ your Atom instances, run `mv ~/.atom ~/.atom.bak` to backup your current Atom profile, then launch Atom in the test project you posted (after running `npm i` in it) with `atom .`, install `linter` and `linter-ui-default`, make sure they are up to date, and then run `Linter: Debug` in there?

You should see `ESLint` listed in the "Matching Linter Providers" section of the Linter debug, as well as "Opened file is ignored: No".

(Note: I'm filing an issue on `atom-ide-ui` about them not showing the results.)

**Comment by darthmall** [comment]
Ok, that seems to have fixed it. Thanks for opening that issue with `atom-ide-ui`.

**Comment by Arcanemagus** [comment]
Marking this as closed here since you've got a working setup and the initial bug is in `atom-ide-ui`.
