### ISSUE TITLE
Spec failure on master branch if config file in user home directory

### ISSUE THREAD

**Issue by skylize** [AtomLinter/linter-eslint#1072]
## Issue Type

Bug

## Issue Description

* `apm link --dev` from local repo
* rebase clean local master to upstream/master
* force remove `node_modules` and run `npm install`
* open repo folder in atom dev mode
* run specs

Failed spec: When setting `disableWhenNoEslintConfig` is false it errors when no config file found.

Did not return no config error, instead returned lint error messages, causing failed test.

![image](https://user-images.githubusercontent.com/844400/34857002-7af15330-f716-11e7-8088-e38e1355b3cf.png)

## Bug Checklist
- [ x] Restart Atom
- not applicable: Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not  
- not applicable: Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

**Comment by skylize** [comment]
Still occurring with a fresh clone directly from the AtomLinter repo and almost every package disabled. 

Looks like @IanVS just added PR a few minutes ago that had no problems building on Circle CI, so I guess this must be a local issue.

Any ideas what could be causing this in my local setup?

**Comment by IanVS** [comment]
Do you have an eslint config in your home root directory (e.g. `~/.eslintrc`)?

**Comment by skylize** [comment]
Haha. Yep. That's exactly it. I put one there while trying to figure out how to build the Fallback to Global feature. Jumping through a bunch of hoops here and forgot the obvious. 🙈

Is there some way we could hide the home directory from eslint during this test? A proper test should be isolated enough to not fail in this scenario.

**Comment by IanVS** [comment]
I believe we are already copying the files to the OS temp directory to try to isolate them, but the global config is still used, unfortunately.  I don't know any way to prevent that, personally.

**Comment by IanVS** [comment]
Honestly, if we want to do anything, I would rather have a test that detects the presence of a global config, and fails if it finds one.  I'd rather not be moving developers files around.

**Comment by skylize** [comment]
The bot in gitter pointed me to a `root` config option which prevents fallthrough past project directory. So the feature exists. Hopefully someone can tell me a way to access that feature without a config file.

**Comment by skylize** [comment]
Still no more response on Gitter, but a bit of digging turned up a couple possibilities in the options passed to `CLIEngine`.

* `baseConfig`
    * Promising: Maybe we could use this to manually invoke `root` config option,
    * Concern: Poorly described, so not certain it does what I think it does.
*`ignorePattern`
   * Promising: Maybe we could use this to manually ignore the home directory
    * Concern: I'm not sure how it interacts with `ignorePath`

I'm also a bit unclear how difficult it will be to get a custom option passed from a spec down to the CLIEngine.

**Comment by Arcanemagus** [comment]
* `baseConfig`
    * This would provide a configuration, when the test is explicitly checking that a configuration isn't found so it can't be used. The same goes for any attempt to use the `root` configuration option.
* `ignorePattern` only relates to the files to lint, not the configuration files.

I don't think there is a way to make that spec work when the user has a configuration file in their home directory. The specs are written with the assumption that there is no such file, the "best" solution I can think of is what @IanVS suggested in writing a tests that sees if there is such a config and bailing out if so.

**Comment by skylize** [comment]
I'll keep this in the back of my mind in case a solution presents itself. But it's clear the consensus at this point is won't fix, so closing.
