### ISSUE TITLE
ignoreFixableRulesWhileTyping overrides ignoredRulesWhenModified

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-eslint#1081]
## Issue Type
Bug

## Issue Description
If the user has enabled the `ignoreFixableRulesWhileTyping` option _and_ has rules set in `ignoredRulesWhenModified` the rules specified in `ignoredRulesWhenModified` are overridden by the list of rules determined to be fixable.

These two lists should be combined into a single list of rules to ignore.

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [X] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

**Comment by skylize** [comment]
That's bad. Is that happening on released version or just current master? I'm surprised nobody has complained about that already.

**Comment by Arcanemagus** [comment]
I'm guessing that most of the rules that somebody would disable using `ignoredRulesWhenModified` are duplicates of the rules coming from `ignoreFixableRulesWhileTyping` since `ignoredRulesWhenModified` was added _long_ before `ignoreFixableRulesWhileTyping`.
