### ISSUE TITLE
ESLint configuration is invalid

### ISSUE THREAD

**Issue by lZzozZl** [AtomLinter/linter-eslint#1086]
## Issue Type
Question, issue

## Issue Description

I follow this article: https://hackernoon.com/what-is-eslint-how-do-i-set-it-up-on-atom-70f270f57296

Have installed linter 2.2.0 and linter-eslint 8.4.0
![image](https://user-images.githubusercontent.com/16064130/35183264-985d169e-fdeb-11e7-9f2c-82f8c5cddca7.png)

make new folder than npm init

```
{

  "name": "testing",
  "version": "1.0.0",
  "description": "TestingLinter",
  "main": "qqq.js",
  "scripts": {
    "test": "tryme"
  },
  "repository": {
    "type": "git",
    "url": "tralala"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "eslint": "^4.16.0",
    "eslint-config-google": "^0.9.1"
  }
}
```

Than i run npm install --save-dev eslint eslint-config-google

after that i open a new file than try to write example code but i see this error
![image](https://user-images.githubusercontent.com/16064130/35183282-eadc8008-fdeb-11e7-9886-54b4c665b3b2.png)
![image](https://user-images.githubusercontent.com/16064130/35183284-f3f3fe28-fdeb-11e7-918e-a02f579ff6df.png)

## Bug Checklist
- [*] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
do not know how to do this
- [*] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```
![image](https://user-images.githubusercontent.com/16064130/35183284-f3f3fe28-fdeb-11e7-918e-a02f579ff6df.png)

**Comment by Arcanemagus** [comment]
![image](https://user-images.githubusercontent.com/16064130/35183284-f3f3fe28-fdeb-11e7-918e-a02f579ff6df.png)

As the error says, it looks like your `.eslintrc` file is invalid. You didn't post its contents so I can't help with what is wrong with it, but I'd suggest you look over the documentation on [Configuring ESLint](https://eslint.org/docs/user-guide/configuring).

> Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
> do not know how to do this

The simplest way of doing this is to run `npx eslint .` from your project. That will automatically find your locally installed ESLint instance and run it in your project.

**Comment by lZzozZl** [comment]
Hi. Thanx for answering.
So i have .eslintrc file in my root directory where are node_modules and my qqq.js file.
The content in that file is
```
{
“extends”: “eslint-config-google”
}

```

**Comment by Arcanemagus** [comment]
Whatever program you used to create your `.eslintrc` is using the wrong quote marks (probably a "document editor" like Word?).

ESlint (and every other tool...) requires you to use the bare `"` marks, while whatever you used inserted the "smart" quotes of `“` and `”`.

**Comment by lZzozZl** [comment]
Thanx :) Now its working :D

**Comment by heroly** [comment]
> 

Noobie mistake. I also copied and pasted the wrong quote marks also. Thanks for helping!
