### ISSUE TITLE
<removed>

### ISSUE THREAD

**Issue by skylize** [AtomLinter/linter-eslint#1099]
`<removed>`

**Comment by skylize** [comment]
I can't exactly grab a copy of what was said, because I am already kicked out. But would not mind at all if somebody chose to add it here for posterity. I was instantly kicked out of Atom Slack and Atom Github Issues after @lee-dohm goaded me into sharing my raw disgust for a bad PR to Atom, instead of, as I intended, just gently nudging people to take a look and see if they agreed with the plan.

Happy to hear any ideas on how we might be able to communicate cleanly about further development.

___

@Arcanemagus  So you are shunning me too, that quickly? You are just removing my post without even bothering to comment? **What happenened to Atom being a supportive community?** I would quite honestly have expected you to see this and try to liaison a peaceful resolution, and instead you are shutting me out without a second thought?

**Comment by Arcanemagus** [comment]
Check your email, issues are _not_ the place for discussions like this.
