### ISSUE TITLE
Uncaught Error: Cannot find module 'eslint-config-' Referenced from: .eslintrc

### ISSUE THREAD

**Issue by Volox** [AtomLinter/linter-eslint#110]
1. Createa sharable config with `eslint` (See [here](http://eslint.org/docs/developer-guide/shareable-configs)).
2. Install globally the configuration `npm i -g eslint-config-name`
3. In the `.eslintrc` file use the `extend` property.

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.9

### Stack Trace

Uncaught Error: Cannot find module 'eslint-config-volox'
Referenced from: /Users/volox/dev/SocialCrawler/.eslintrc

```
At /Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:129

Error: Cannot find module 'eslint-config-volox'
Referenced from: /Users/volox/dev/SocialCrawler/.eslintrc
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at loadConfig (/Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:96:48)
  at /Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:123:46
  at Array.reduceRight (native)
  at loadConfig (/Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:111:36)
  at getLocalConfig (/Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:225:23)
  at Config.getConfig (/Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:363:22)
  at CLIEngine.getConfigForFile (/Users/volox/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:382:29)
  at /Users/volox/.atom/packages/linter-eslint/lib/linter-eslint.coffee:81:23
  at exports.allowUnsafeNewFunction (/Users/volox/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at LinterESLint.lintFile (/Users/volox/.atom/packages/linter-eslint/lib/linter-eslint.coffee:80:5)
  at /Users/volox/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/volox/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -3:45.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:44.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:44.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:43.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -3:37.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:36.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:36.4.0 application:add-project-folder (atom-text-editor.editor)
     -3:07.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:03.0 core:save (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -2:56 core:backspace (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -2:55.6.0 core:save (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -2:48.1.0 core:backspace (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -2:47.7.0 core:save (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -2:19.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:03.6.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
linter, v0.12.7
linter-eslint, v0.5.9
monokai, v0.14.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by iam4x** [comment]
`eslint-config-volox` should be installed locally to your project.

**Comment by Volox** [comment]
Is not required.
I installed it globally for another project and (in SublimeText and command line) it works.

**Comment by iam4x** [comment]
@Volox With `AtomLinter/linter-eslint` it is :)

We might change this to find globally installed package.

**Comment by Volox** [comment]
ahhh, ok sorry.
I thought it uses the globally installed `eslint` command.

**Comment by iam4x** [comment]
@Volox it will uses the globally instal eslint as fallback but won't load globally plugins at all. This might be interesting to add.

**Comment by Volox** [comment]
@iam4x the `eslint` command does, what do you mean? Is just a node require, it will fallback to globally installed packeges by default.

**Comment by iam4x** [comment]
Not everything is sandboxed into Atom, we need need to provide full path of modules to require. Global module would be an Atom module.

**Comment by polarathene** [comment]
@iam4x are you sure global works for local installed config? I installed eslint globally, added into my config boolean value to set it, eslint was working. When I npm installed a shareable config and created a .eslintrc file with correct `extends` value, I got the error `Cannot find Module..`. Did an npm install of eslint locally to my project and then it was able to locate the shareable config to extend.

It's possible it might just be an issue with Atom, with another package I updated recently the fix didn't apply until I reset Atom.

**Comment by codeinaire** [comment]
If anyone else was still getting this error: `Error running ESLint Error: Cannot find module 'eslint-config-airbnb-base'` I solved it by going into `Edit > Preferences > Open Config Folder`.

In this file look for: 
```
"linter-eslint":
    eslintrcPath: "<path to your application>"
    useGlobalEslint: true
```
Change the value of `useGlobalEslint` from `true` to `false`. 
I didn't have eslint installed globally and it must've been trying to use the globally installed version. I don't know why it was doing this because a week or so ago the linter was working fine. Anyway, once changed to false it'll look for the local install of eslint.
