### ISSUE TITLE
"Casing of [import] does not match the underlying filesystem" when opening project with `atom .`

### ISSUE THREAD

**Issue by andreidobrinski** [AtomLinter/linter-eslint#1100]
## Issue Type
Bug

## Issue Description
Steps:
- Create instance of `create-react-app`
- Install eslint with Airbnb config
- Open the project by navigating to it in terminal and using `atom .`
- See the no-unresolved issue #934 
- The linter reads "Casing of [import] does not match the underlying filesystem."

It's worth noting that the issue does not exist when the project is opened thru the Atom menu via File > Add Project Folder and selecting it from the dropdown.

Also worth noting that @Arcanemagus mentioned that it might be an OS level issue. Wondering if anyone else is having the same issue.

Found some similar issues in my searches:
https://github.com/benmosher/eslint-plugin-import/issues/945
https://github.com/benmosher/eslint-plugin-import/issues/720

## Bug Checklist
- [x] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

Linter Eslint: Debug output here
```
Atom version: 1.23.3
linter-eslint version: 8.4.1
ESLint version: 4.17.0
Hours since last Atom restart: 0.3
Platform: darwin
Using local project ESLint from: /Users/andreidobrinski/downloads/test-app/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "string.quoted.module.js",
  "punctuation.definition.string.begin.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment]
What do you get for `npm ls eslint-plugin-import`?

**Comment by andreidobrinski** [comment]
2.8.0, unfortunately

**Comment by andreidobrinski** [comment]
Tested again today and I was able to open the project with `atom .`. The issue was with my navigation to the project. Changing to the proper case of the folder removed the listing issue. i.e. entering `cd Documents` instead of `cd documents` did the trick, when the folder was actually "Documents"

**Comment by skylize** [comment]
Closing as this appears to be resolved. 

Atom has some quirks about casing on Systems that are supposed to be case-insensitive. The correct solution (workaround?) is to ensure you have properly cased folder-names displayed in your terminal before typing cli commands for Atom.
