### ISSUE TITLE
Need to have ability to run linter inside docker container

### ISSUE THREAD

**Issue by artempartos** [AtomLinter/linter-eslint#1110]
## Issue Type
Feature Request

## Issue Description
Need to have ability to run linter inside docker container

**Comment by Arcanemagus** [comment]
This is a package for Atom, if you are looking for how to run ESLint from a Docker container you should try a [Google search](https://www.google.com/search?q=eslint+docker) as it is _far_ beyond the scope of this package 😉.

**Comment by Arcanemagus** [comment]
Note that this package will _not_ work with any of those setups, it is designed for working on code locally and assumes you have installed `eslint` as a dependency in your project, or have configured a global ESLint installation.
