### ISSUE TITLE
Feature request / trigger eslint update in non script tag

### ISSUE THREAD

**Issue by simongcc** [AtomLinter/linter-eslint#1117]
## Feature Request
Hello! I have installed `eslint-plugin-vue` and `vue-eslint-parser` respectively to lint for Vuejs's vue file.
I understand that linter-eslint is designed to trigger recheck if any code inside `<script>` tag is detected to be updated with flaw(oppose to rules).
I think it can be allowed also for other optional tags. In Vuejs case, it is the single component file `.vue` with also `template tag` and `style tag` respectively so that the lint result will be triggered to update, no need to edit code inside `script tag` manually to trigger it. I think the `linter-eslint` can then be more generic to support other kind of scripting in the future with this support.

The support can be done through settings or config(based on the project's config for individual projects).

Many thanks.

**Comment by Arcanemagus** [comment]
You can add whatever scopes you want `linter-eslint` to activate on in the [settings](https://github.com/AtomLinter/linter-eslint/blob/1427e52364351cbbe5ca433c23c6e8a23f72bfd3/package.json#L78-L91) 😉.
