### ISSUE TITLE
Incompatibility with useTreeSitterParsers

### ISSUE THREAD

**Issue by mneumark** [AtomLinter/linter-eslint#1119]
## Issue Type
Bug

## Issue Description
I am using atom-ide-ui rather than linter to hook into. Until recently all was well. Then I upgraded 1.25.0 and out of curiosity I enabled: `useTreeSitterParsers: true`. Pretty neat stuff. Until today when I realized that I wasn't seeing any linting from eslint. I tried a bunch of stuff, none of which fixed it, until finally I thought to disable the tree sitter parsers again, and then the eslinting started working again. So something buggy is causing an incompatibility.

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [X] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.25.0
linter-eslint version: 8.4.1
ESLint version: 4.15.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/mneumark/source/react-ui/packages/react-ui-core/node_modules/eslint
Current file's scopes: [
  "javascript",
  "program",
  "export_statement",
  "class",
  "class_body",
  "public_field_definition",
  "object"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by skylize** [comment]
Tree Sitter changes the scope name from `source.js` to `javascript`.

Add `javascript` to the scopes list in `linter-eslint` Settings. There is a patch committed already to add it by default, but has not been released yet.

**Comment by mneumark** [comment]
Thank you! Glad to hear its already fixed! I'll add that workaround but now at least folks who have this issue will have this Issue to guide them until that fix is released.
