### ISSUE TITLE
Only show linter errors when saving file

### ISSUE THREAD

**Issue by jasonleonhard** [AtomLinter/linter-eslint#1121]
## Issue Type
"Feature Request", "Question"

## Issue Description
Is there already a way to only show linter errors in Atom.io when saving a file?
If not, would you consider the feature?

Thank you,
Jason

**Comment by skylize** [comment]
That setting is in the base `linter` package. Uncheck `Lint on Change`.

**Comment by Arcanemagus** [comment]
Note that if you are using `atom-ide-ui` they currently have no way to control this behavior.

**Comment by skylize** [comment]
Closing as resolved. Let us know if you still have questions.
