### ISSUE TITLE
linter-eslint no longer reporting anything

### ISSUE THREAD

**Issue by bennypowers** [AtomLinter/linter-eslint#1122]
## Issue Type
Bug

## Issue Description
I've noticed that for the last week or so, I no longer get eslint messages in diagnostics. `ts` errors from ide-typescript still appear, and there are plenty of linting errors in my file (see screenshot). Apologies for the vague description but I'm so far unable to uncover more information. Could be related to https://github.com/AtomLinter/linter-eslint/issues/1029 but I don't have any error messages in the js console.

![screen shot 2018-03-24 at 19 34 31](https://user-images.githubusercontent.com/1466420/37866960-6512d31a-2f9a-11e8-9e11-961f0c406509.png)

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.25.0
linter-eslint version: 8.4.1
ESLint version: 4.19.1
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/bennyp/Documents/mws-restaurant-stage-1/node_modules/eslint
Current file's scopes: [
  "javascript",
  "program",
  "lexical_declaration",
  "variable_declarator",
  "arrow_function",
  "arrow_function",
  "parenthesized_expression",
  "sequence_expression"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "eslintrcPath": "/Users/bennyp/.config/eslintrc.json",
  "fixOnSave": true,
  "globalNodePath": "/Users/bennyp/.config/yarn/global",
  "ignoreFixableRulesWhileTyping": true,
  "lintHtmlFiles": true,
  "rulesToDisableWhileFixing": [
    "no-debugger"
  ],
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic",
    "text.html.basic"
  ],
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "rulesToSilenceWhileTyping": []
}

```

You're welcome to try it in this repo: https://github.com/bennypowers/mws-restaurant-stage-1.git

**Comment by skylize** [comment]
Looks like you are using experimental Tree Sitter, which changes the default scope for JS files from `source.js` to `javascript`. This scope is not currently enabled by default, but you can enable it by adding it to the list of scopes in `linter-eslint` settings.

**Comment by bennypowers** [comment]
That was 🎯 spot on, and solved the issue. 

*thank* you very much.

**Comment by bennypowers** [comment]
As an endnote, Please consider adding `javascript` to the default list of scopes.
