### ISSUE TITLE
no-implicit requires an atom restart

### ISSUE THREAD

**Issue by pward123** [AtomLinter/linter-eslint#1124]
## Issue Type
Bug

## Issue Description
I have `implicit-dependencies/no-implicit` set as an error in my .eslintrc.js file. When I require a new module and add it to the dependencies in my package.json, linter-eslint still shows an error. Restarting atom removes the error.

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [X] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.25.0
linter-eslint version: 8.4.1
ESLint version: 4.19.0
Hours since last Atom restart: 0.2
Platform: darwin
Using global ESLint from: /Users/pward/.nvm/versions/node/v8.8.1/lib/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "constant.other.object.key.js",
  "string.quoted.single.js",
  "punctuation.definition.string.end.js"
]
linter-eslint configuration: {
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}```

**Comment by Arcanemagus** [comment]
If I had to guess I would say that `implicit-dependencies/no-implicit` is storing state globally that it is expecting to get cleared (as it normally would in a CLI environment), however since the environment here stays active between runs it is probably causing issues with itself caching things it shouldn't be.

If you can provide an example repository or Gist I can look into it further for you.

**Comment by skylize** [comment]
No response on an example repository. Based on the current information, this appears to be an external issue, caused by the `implicit-dependencies` plugin. 

Closing as "won't fix", but we can reconsider if you provide a minimal case project.
