### ISSUE TITLE
Extension makes Atom hang on startup

### ISSUE THREAD

**Issue by wolfy1339** [AtomLinter/linter-eslint#1125]
## Issue Type
Bug

## Issue Description
When I open a directory (git repository, JS project) in Atom with this plugin, Atom hangs on startup.
I have disabled all extensions then enabled all the requirements one-by-one up until this extension and tested whether it still hangs on startup. 

Atom: 1.25.0 x64
Electron: 1.7.11
OS: Microsoft Windows 10 Pro (1710)
ESLint: 4.19.1

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```

**Comment by IanVS** [comment]
Can you please share your eslint config and the settings of linter-eslint?

**Comment by wolfy1339** [comment]
eslint Config:
```js
module.exports = {
    "env": {
        "es6": true,
        "node": true
    },
    "parserOptions": {
        "ecmaVersion": 8,
        "sourceType": "module",
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true
        }
    },
    "extends": ["eslint:recommended", "google"],
    "rules": {
        "require-jsdoc": [
            "warn",
            {
                "require": {
                    "FunctionDeclaration": true,
                    "MethodDefinition": true,
                    "ClassDeclaration": true,
                    "ArrowFunctionExpression": true,
                    "FunctionExpression": true
                }
            }
        ],
        "comma-dangle": [
            "error",
            "never"
        ],
        "padded-blocks": [
            "error",
            {
                "blocks": "never"
            }
        ],
        "arrow-parens": [
            "error",
            "as-needed"
        ],
        "one-var": "off",
        "camelcase": "off",
        "max-len": [
            "error",
            {
                "code": 120,
                "tabWidth": 4,
                "ignoreComments": true,
                "ignoreTrailingComments": true,
                "ignoreUrls": true
            }
        ],
        "id-match": "off", // Google sets this
        "curly": "off", // Can't configure this enough
        "block-spacing": [
            "error",
            "always"
        ],
        "brace-style": [
            "error",
            "1tbs",
            {
                "allowSingleLine": true
            }
        ],
        "object-curly-spacing": [
            "error",
            "always"
        ],
        "space-unary-ops": [
            "error",
            {
                "words": true,
                "nonwords": false
            }
        ],
        "padding-line-between-statements": [
            "error",
            { "blankLine": "always", "prev": "*", "next": "return" },
            { "blankLine": "always", "prev": ["const", "let"], "next": "*" },
            { "blankLine": "any", "prev": ["const", "let"], "next": ["const", "let"] }
        ],
        "eqeqeq": [
            "warn",
            "smart"
        ],
        "no-redeclare": [
            "error",
            {
                "builtinGlobals": true
            }
        ],
        "no-shadow": "error",
        "no-useless-return": "error",
        "no-cond-assign": "error",
        "block-scoped-var": "error",
        "no-else-return": "error",
        "no-undef-init": "error",
        "quote-props": [
            "error",
            "as-needed"
        ]
    }
};
```
Settings: Everything unchecked/ unconfigured except for Disable ESLint when no config is found, Fix errors on save, show rule I'd in messages

**Comment by skylize** [comment]
Does this always happen or only specific projects? If only certain projects, could you make a sample repo demonstrating the minimum case to invoke the problem?

Backup, then delete your `~/.atom` settings folder. Atom will create a fresh settings folder when you next start it. Do you still have issues with a clean settings folder?

Try clearing Atom's saved state using `atom --clear-window-state` from the command line.

**Comment by Arcanemagus** [comment]
For a bit more detail, you can find instructions on a Factory Reset of Atom here: https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Clearing the window state has instructions here: https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

Both of these _do_ have dangers with them, so please read that documentation to ensure you know what is going on 😉.

**Comment by wolfy1339** [comment]
I managed to fix this bug by clearing Atom's saved state. 👍 
With that, I have come up with the conclusion that it only happens on a particular project when multiple file tabs are open.
I will try to create a minimal repo.

**Comment by skylize** [comment]
Closing this as *essentially* resolved. Please reopen if you can create minimal repro for a verifiable bug.
