### ISSUE TITLE
linter-eslint not showing errors (or even working ?)

### ISSUE THREAD

**Issue by WiliTest** [AtomLinter/linter-eslint#1127]
## Issue Type

question or bug

## Issue Description
I installed eslint 8.4.1 on atom. 

eslint isn't working (it doesn't show anything). 

I see this error on the consol of the inpect tool: 

```
C:\Users\Me\.atom\packages\linter-eslint\src\helpers.js:172 Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined
    at Object.generateDebugString (C:/Users/Me/.atom/packages/linter-eslint/src/helpers.js:146:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

## Bug Checklist
- [x] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
                sorry, I don't understand what I should do.

- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

When I use linter eslint : debug (control palet) it gives also an error:
`TypeError: Path must be a string. Received undefined`

**Comment by IanVS** [comment]
Have you tried restarting atom?

**Comment by WiliTest** [comment]
yes, several time

**Comment by WiliTest** [comment]
My settings
![2018-04-13_19-42-47](https://user-images.githubusercontent.com/24194840/38749742-fe8a72ec-3f52-11e8-8614-eced86acef10.gif)

**Comment by IanVS** [comment]
Is eslint installed in your project?   I see that you have not checked the box in the issue template that ESLint is working correctly outside of atom.

**Comment by WiliTest** [comment]
> Is eslint installed in your project? 
I don't understand. I installed eslint in atom using the button "install".

**Comment by Arcanemagus** [comment]
This package is just a wrapper around running ESLint, you should have ESLint installed in your project itself, or configure a global installation.

**Comment by IanVS** [comment]
And I bet you are opening a project / file without a `package.json`, aren't you?

The best way to use ESLint is to install it as a dependency of your project, as @Arcanemagus mentions.  Check out the docs at eslint.org to find out more about how to do this.

**Comment by WiliTest** [comment]
> And I bet you are opening a project / file without a package.json, aren't you?

well, since I understand what you mean, I bet you are right! I have several folders on my tree view, I guess it's a "project". (I'm just working on some files/scripts which aren't connected). Thanks for the link, I will try to understand what it means.

**Comment by IanVS** [comment]
Alrighty, I'll close this out, but feel free to come back here if you've got questions.

**Comment by WiliTest** [comment]
I finally made it. For those who struggle you basically need 3 things to make it work 
1: install linter package in atom
2: install eslint
3: you need to add some set of rules such as this one below. To install it run in a command:
`npm install --save-dev eslint eslint-config-google`

Then create a file names `.erlintrc` (with the dot) in the folder you are working on: and write on it
```
{
    “extends”: “eslint-config-google”
}

```
Then open the code you want to check (you have first to close it)

The [video ](https://www.youtube.com/watch?v=aWFwJVjfDlE) and the super [short tuto ](https://hackernoon.com/what-is-eslint-how-do-i-set-it-up-on-atom-70f270f57296) which helped me.


(It's basic, but I would have loved to have seen that under the package settings):
