### ISSUE TITLE
ESLint not found, please ensure the global Node path is set correctly

### ISSUE THREAD

**Issue by roberto-slopez** [AtomLinter/linter-eslint#1134]
## Bug

I installed `npm install -g eslint` but still it does not work, I have selected the global configuration; I'm executing `eslint` in the cmd and it recognizes the command, but as I mentioned, it keeps throwing me the same error

> ESLint not found, please ensure the global Node path is set correctly

I use windows 10

`npm root -g`
`C:\Users\myUser\AppData\Roaming\npm\node_modules`

![debug]( https://i.imgur.com/YIpMluf.png "debug1")

**Comment by skylize** [comment]
What is the output of `Linter Eslint: Debug` command in Atom Command Palette?

**Comment by roberto-slopez** [comment]
Sorry, fix it by adding this
![debug](https://i.imgur.com/RE9fy1Z.png)


Thanks.

**Comment by skylize** [comment]
Glad you go it worked out.

So to clarify: If properly installed global `eslint` cannot be found, then add the result of `npm get prefix` to the Global Node Installation Path setting.

Closing as resolved.
