### ISSUE TITLE
Cascading configuration file - config from parent directory not applied

### ISSUE THREAD

**Issue by jaydgruber** [AtomLinter/linter-eslint#1138]
## Issue Type
Question

## Issue Description
I have a project with directory structure:

```
my-project
├── .eslintrc.js
├── server
│ └── file1.js
└─┬ client
  ├── .eslintrc.js
  └── file2.js
```

In file1, the rules from my-project/.eslintrc.js are applied. 
In file2 
- the rules from my-project/client/.eslintrc.js are applied
- the rules from my-project/.eslintrc.js are *not* applied
I would expect both sets of rules to apply, based on the [eslint docs](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.27.1
linter-eslint version: 8.4.1
ESLint version: 4.19.1
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/jay.gruber/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.coffee",
  "keyword.operator.assignment.coffee"
]
linter-eslint configuration: {
  "disableFSCache": true,
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by skylize** [comment]
The rules in `my-project/.eslintrc.js` should be applied first to all files in the project. Then the rules in `my-project/client/.eslintrc.js` should apply to only files in the `client` directory, overriding the project-level rules.

You need to be sure to open the full project folder in Atom first, and not just directly open the the single file, so we do not mistake the `client` folder for the project root. 

Alternatively, placing an `.eslintignore` file (even if empty) in your project's root directory should take priority over the Atom Project when we search for the project root.

**Comment by jaydgruber** [comment]
> You need to be sure to open the full project folder in Atom first
Ok, done that

> Alternatively, placing an .eslintignore file (even if empty) in your project's root directory should take priority over the Atom Project when we search for the project root.
I have an .eslintignore file in root directory. That seems to be applying correctly.

> The rules in my-project/.eslintrc.js should be applied first to all files in the project.
The rules in my-project/.eslintrc.js are not being applied to files in my-project/client

> the rules in my-project/client/.eslintrc.js should apply to only files in the client directory, overriding the project-level rules.
The rules in my-project/client/.eslintrc.js are being properly applied, but none of the rules defined in my-project/.eslintrc.js are being applied to files in my-project/client. 

> overriding the project-level rules. 
*when there are conflicting descriptions.* 
Given: 
```
// my-project/.eslintrc.js
"rules": {
  "A": 0,
  "B": 0,
  "C": 0
}
```
and
```
// my-project/client/.eslintrc.js
"rules": {
  "D": 0
}
```
*Expected*
files in my-project/ should have rules: `A, B, C` applied.
files in my-project/client/ should have rules: `A, B, C, D` applied.

*Actual*
files in my-project/client/ have rules: `D` applied.

**Comment by IanVS** [comment]
This could be because atom is using the bundled fallback that's included in case users do not have eslint installed in their project.  This is not the recommended way to proceed, however, especially if you are using `.eslintrc` files.  

You mentioned in your report that running eslint manually gives the correct result.  Are you using a global eslint installation?  

We recommend adding eslint as a dev dependency to your project.  Could you try that, and then let us know if it solves your issues?

**Comment by jaydgruber** [comment]
> Are you using a global eslint installation?
Nope

> We recommend adding eslint as a dev dependency to your project.
I've got two package.json files, one at my-project/package.json & one at my-project/client/package.json. 
eslint is a dev dependency in the first, but not the second.
Installing eslint as a dev dependency in my-project/client does not change the behavior.

**Comment by IanVS** [comment]
Ah ok.

One thing I'm curious about, in your debug output, you've got:

```
Current file's scopes: [
  "source.coffee",
  "keyword.operator.assignment.coffee"
]
```

But you don't include either source type in 

```
"scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
```

Did you run the `Linter-Eslint: debug` command from a different file than what you are actually experiencing problems with?  In your issue, you only mention `.js` files...

**Comment by jaydgruber** [comment]
Hm that's odd. I don't have coffeescript in this project. Maybe I goofed on the debug. 
Here's a fresh one from my-project/client/file2.js
```
Atom version: 1.27.1
linter-eslint version: 8.4.1
ESLint version: 4.19.1
Hours since last Atom restart: 0.3
Platform: darwin
Using local project ESLint from: /Users/jay.gruber/Documents/achillestang/cup-client/node_modules/eslint
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "comment.block.documentation.js"
]
linter-eslint configuration: {
  "disableFSCache": true,
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by IanVS** [comment]
Is this your parent project or `client` child project?

```
Using local project ESLint from: /Users/jay.gruber/Documents/achillestang/cup-client/node_modules/eslint
```

Oh, and you don't happen to have `root: true` in your child `.eslintrc` file, do you?  

I don't suppose you're able to share this project so we can try it out ourselves, can you?

**Comment by jaydgruber** [comment]
achillestang/ = my-project/ & cup-client/ = client/

> you don't happen to have root: true in your child .eslintrc file, do you?

Nope not in either file.

Normally I have:
> Using local project ESLint from: /Users/jay.gruber/Documents/achillestang/node_modules/eslint

Sorry, was still on branch where I tried installing eslint as dev dependency in client/ as well

**Comment by IanVS** [comment]
Hm, you've stumped me.  I've been running with nested configs for years without any problems.  Is there any chance you could create a minimal reproduction repo that you could share with us?  I'd be happy to try troubleshooting it, but it'll be tough without a way to reproduce.

**Comment by skylize** [comment]
Did you try turning it off and back on again? :laughing:

Seriously though. There are caching behaviors that can make `linter-eslint` get pretty wonky if you make structural changes to your project folder without restarting Atom.

**Comment by jaydgruber** [comment]
Hey all, sorry for delay. While setting up a little repro repo, I was able to get things working by adding 

```
extends: [
    '../.eslintrc.js',
]
```

to the child .eslintrc.js 
Thanks for all the help!
