### ISSUE TITLE
Support for eslint-plugin-vue

### ISSUE THREAD

**Issue by randomstuff** [AtomLinter/linter-eslint#1139]
## Issue Type

Feature Request

## Issue Description

The [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) adds support for Vue.js `.vue` files in `eslint. However this generated errors do not show up in `linter.eslint`.

## Bug Checklist

- [ ] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.22.1
linter-eslint version: 8.4.1
ESLint version: 4.19.1
Hours since last Atom restart: 0.1
Platform: linux
Using local project ESLint from: /home/myself/my_project/node_modules/eslint
Current file's scopes: [
  "text.html.vue",
  "source.js.embedded.html"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by IanVS** [comment]
Please add `text.html.vue` to the "List of scopes to run ESLint on" setting.

**Comment by randomstuff** [comment]
Indeed, it works. Sorry for the noise. I somehow missed this setting.

**Comment by IanVS** [comment]
Cool, no problem.
