### ISSUE TITLE
Uncaught JS-YAML: missed comma between flow collection entries at line 2, column 18:        ecma...

### ISSUE THREAD

**Issue by rossPatton** [AtomLinter/linter-eslint#115]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.5.10

### Stack Trace

Uncaught JS-YAML: missed comma between flow collection entries at line 2, column 18:
        ecmaFeatures {
                     ^

```
At /Users/ross/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:77

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "highlight-css-color",
      "ide-flow",
      "linter-golint",
      "linter-golint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.7
linter-eslint, v0.5.10
linter-flow, v0.1.6
linter-stylint, v0.6.0

# Dev
No dev packages
```

**Comment by iam4x** [comment]
@rossPatton The error is thrown from `eslint, it has been updated since is it working now?
