### ISSUE TITLE
linter-eslint not showing errors (or even working ?)

### ISSUE THREAD

**Issue by trusktr** [AtomLinter/linter-eslint#1157]
## Issue Type

question, maybe bug?

## Issue Description

I tried to configure a specific file name,

![screen shot 2018-08-01 at 3 26 52 pm](https://user-images.githubusercontent.com/297678/43552526-ab591774-959f-11e8-864a-7508ad5eb7ae.png)

(which is not ideal anyways because it will be different in different projects) and I can't get anything to happen:

![screen shot 2018-08-01 at 3 29 57 pm](https://user-images.githubusercontent.com/297678/43552550-c615564a-959f-11e8-9b7a-d7f6284f7a7e.png)

Besides that, how can we configure specific config files per project? What about multiple config files for different types of files in a project?

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.28.1
linter-eslint version: 8.4.1
ESLint version: 5.2.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/trusktr/src/OMITTED/node_modules/eslint
Current file's scopes: [
  "typescript",
  "program",
  "import_statement"
]
linter-eslint configuration: {
  "eslintrcPath": ".eslintrc-ts.js",
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}

```

**Comment by trusktr** [comment]
Alright, I've modified my project, so it uses only `.eslintrc.js` files nested inside directories. So, `linter-eslint` should be able to simply pick up the correct eslint file automatically now.

But still nothing happens. I tried restarting.

**Comment by trusktr** [comment]
I also removed that filename override I had added in settings, so it's empty now (defaults to it's default).

**Comment by trusktr** [comment]
Running `eslint` from command line works fine, like this:

```
> ./node_modules/.bin/eslint '{src,etc}/**/*.ts'
```

It finds eslintrc file just fine and outputs expected results.

**Comment by trusktr** [comment]
I tried disabling `linter-ui-default` and using Atom IDE, but still shows no errors in the bottom panel. Also nothing in the gutter, though I did notice that it added a gutter space.

**Comment by skylize** [comment]
Add `typescript` to the list of scopes in linter-eslint settings.

**Comment by skylize** [comment]
> Besides that, how can we configure specific config files per project? 

The recommended setup is to install ESLint to your project and `.eslintrc.*` file in the top of the project. You can override this project config file per folder with additional config files placed in the folders.

> What about multiple config files for different types of files in a project?

No direct support for this non-standard use case. The best way to replicate would be a project structure that separates different file types into different folders, and then use folder level config files.

I would probably just put all the rules in the same file and roll with it. The biggest risk is the linter misses accidental use some Typescript in a JS file.

**Comment by IanVS** [comment]
>What about multiple config files for different types of files in a project?

This can be accomplished with `overrides`.  See the ESLint documentation for how it works: https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

**Comment by haggen** [comment]
Same deal here. Brand new Atom (1.30) installation. Disabled every other extension. Still it does nothing, does not work and does not throw any errors either.

```
Atom version: 1.30.0
linter-eslint version: 8.4.1
ESLint version: 4.19.1
Hours since last Atom restart: 0.1
Platform: linux
Using local project ESLint from: /home/arthur/Work/otmdata/node_modules/eslint
Current file's scopes: [
  "javascript",
  "program"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by skylize** [comment]
@haggen Please see this comment [in Issue 1163](https://github.com/AtomLinter/linter-eslint/issues/1163#issuecomment-414443561).

**Comment by haggen** [comment]
@skylize Oh I see.. That worked great! Thank you!

**Comment by Arcanemagus** [comment]
Note that Tree-sitter is still _experimental_, although it's getting closer to ready for a wider audience... part of that effort is that the new parent scope names have been reverted in https://github.com/atom/atom/pull/17881, so if you update to Atom v1.31.0-beta0 or higher you will no longer run into this.

> May I suggest it to throw some error or warning because silent failure is the worst.

Also, it's not a "silent failure", as far as this package knows until you add `javascript` to the list of supported scopes in those older versions of Atom the file you have opened isn't something it understands. We would have to show a message on _every_ file it doesn't understand to do that.

**Comment by haggen** [comment]
@Arcanemagus I see what you mean, but the fact still that what should've worked didn't and also didn't show any error, warning, etc.

Since we've established that there's a new option in Atom that is prohibiting the linter from working normally the extension could add an additional (and temporary) check to see if we're using the experimental Tree-sitter and throw a warning in the console, or something to that effect, saying that it can cause problems.

**Comment by skylize** [comment]
> could add an additional (and temporary) check

We already have a patch on the master branch which fully solves the problem with no need for throwing an error.

With such an easy workaround available, and the fact it is still officially an experimental feature, we concluded it is not worth the effort of pushing a Release out for *only* this problem.

**Comment by Arcanemagus** [comment]
Especially since, as I already said, that workaround is no longer needed as of Atom v1.31.0-beta0.
