### ISSUE TITLE
Update for newer rules

### ISSUE THREAD

**Issue by BreakTruth** [AtomLinter/linter-eslint#1158]
## Issue Type

Question

## Issue Description

When will the package be updated for newer ESLint versions? I wanted to use the `implicit-arrow-linebreak` rule, but it doesnt work, as it is ESLint 4.12.0.

**Comment by Arcanemagus** [comment]
This package uses the version of ESLint from your project, as such the question is really when will you update your project for ESLint v4.12.0 😉.

**Comment by BreakTruth** [comment]
well I got v5.3.0

**Comment by Arcanemagus** [comment]
Double check that it is using the installation you expect by running `Linter Eslint: Debug` while you have a file open from that project.

**Comment by BreakTruth** [comment]
now, for whatever reason, the rule works, without having done anything, except having restarted my pc in that time, odd tbh

**Comment by Arcanemagus** [comment]
Glad to hear it!

It's possible the worker process had already been started _before_ you installed dependencies so it wasn't using the project local one, and the computer restart coincidentally restarted the worker thread.
