### ISSUE TITLE
Silence parsing errors while typing

### ISSUE THREAD

**Issue by aleclarson** [AtomLinter/linter-eslint#1160]
**Issue Type:** Question

**Description:**
What do I put in the "Silence specific rules while typing" text box to ignore parsing errors while typing?

**Versions:**
- `eslint v4.19.1`
- `linter-eslint v8.4.1`
- `atom v1.22.0`

**Comment by UziTech** [comment]
comma separated list of rule ids (e.g. `no-trailing-spaces, eol-last`)
