### ISSUE TITLE
Please add next and previous error keybinds

### ISSUE THREAD

**Issue by KonradHoeffner** [AtomLinter/linter-eslint#1173]
## Issue Type
Feature Request

## Issue Description
In Eclipse, there are keybinds to jump to the next error, <kbd>CTRL</kbd>+<kbd>.</kbd>, and 
to jump to the previous error, <kbd>CTRL</kbd>+<kbd>.</kbd>. While these specific hotkeys are already used in Atom, those operations are used frequently, so having some keybindings would speed up development and would be much appreciated.

**Comment by Arcanemagus** [comment]
This is just a service provider, and has no interface of its own. You'll want to file this on `linter-ui-default` or `atom-ide-ui`, whichever you are using.
