### ISSUE TITLE
What is generating a particular warning? And why is linter-eslint working even without eslint...?

### ISSUE THREAD

**Issue by mercmobily** [AtomLinter/linter-eslint#1177]
## Issue Type

Question

## Issue Description

I am experiencing a problem where I have a lint message which shouldn't be there. I would like to try and use different versions of eslint, but I am finding it very hard to figure out where the message is  actually coming from.

The message is `Expected indentation of 4 spaces but found 8`. So, surely enough, I got into `~/.atom/packages/linter-eslint/` and found the string:

    merc@merc-ThinkPad-X250:~/.atom/packages/linter-eslint$ grep -r 'Expected indentation' *
    node_modules/eslint/lib/rules/indent.js:            return `Expected indentation of ${expectedStatement} but found ${foundStatement}.`;
    node_modules/eslint/lib/rules/indent-legacy.js:            return `Expected indentation of ${expectedStatement} but found ${foundStatement}.`;
    merc@merc-ThinkPad-X250:~/.atom/packages/linter-eslint$ 

I thought I was on the right track. Just to test things, I changed those lines into:

    node_modules/eslint/lib/rules/indent.js:            return `Expected1 indentation of ${expectedStatement}  but found ${foundStatement}.`;
    node_modules/eslint/lib/rules/indent-legacy.js:            return `Expected2 indentation of 
 ${expectedStatement} but found ${foundStatement}.`;

Running eslint from the command line showed that the change worked:

    merc@merc-ThinkPad-X250:~/Development/node/pwa-jsonreststores-starter-kit$ /home/merc/.atom/packages/linter-eslint/node_modules/eslint/bin/eslint.js src/components/shop-cart.js 

    /home/merc/Development/node/pwa-jsonreststores-starter-kit/src/components/shop-cart.js
      40:1  error  Expected1 indentation of 4 spaces but found 8  indent
      51:1  error  Expected1 indentation of 2 spaces but found 6  indent

    ✖ 2 problems (2 errors, 0 warnings)
      2 errors, 0 warnings potentially fixable with the `--fix` option.

    merc@merc-ThinkPad-X250:~/Development/node/pwa-jsonreststores-starter-kit$ 

The problem I am having is that no matter what I do, I cannot get the "modified" message in atom.
Yes, I restarted it. reloated it, etc.

What is even worse, is that in a moment of utter frustration I moved `eslint` totally out of the equation... and .linter-eslint. Still. Worked.

    merc@merc-ThinkPad-X250:~/.atom/packages/linter-eslint$ mv node_modules/eslint ~
    merc@merc-ThinkPad-X250:~/.atom/packages/linter-eslint$ 

This is really puzzling. There is no other `eslint` module anywhere in the `packages` tree, not in a subtree, or in another node-module. linter-eslint doesn't seem to blink if `eslint` disappears, which doesn't seem to make sense.

I really thought that message was coming from `eslint`. but... now I wonder if it isn't. but I looked and looked and looked at the code, and I just couldn't find anything that would generate the `indent` warning.

Note that this issue is NOT about the indent warning, but about being able to actually figure out what is generating that warning in the first place. 

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below -- I don't think I need to do this?

**Comment by IanVS** [comment]
I understand your confusion. linter-eslint comes bundled with its own fallback version of eslint, which we plan to remove in a future release because of the confusion it can cause. It looks like you found that and moved it. But did you restart atom after doing so?  If you want to find out which eslint is being used, you can run the `linter eslint: debug` command from the command palette, and the output should tell you.

As for the configuration, eslint will look for a config file starting in the file directory and moving up the tree untill root, and then it will also check in your home directory.  So you could have a rule configured there. By default no rules are enabled, so somewhere it is finding something.

Please let us know of any of this info is helpful.

**Comment by mercmobily** [comment]
I am not at my computer now, and cannot check. I so want to find out... I don't get it though. There is NO other eslint module installed anywhere, I ran a find on `eslint` and nothing came up at all in the `mode_modules` directory.

Where could it possibly be?

**Comment by IanVS** [comment]
Linter-eslint loads an eslint worker into memory, and also searches up the file tree to root for an eslint executable. So my guess is that either you didn't restart atom after removing both eslint from your project as well as the eslint that is bundled with this package, or there's another eslint in your tree.  Running the debug command will tell you either way.

**Comment by mercmobily** [comment]
Thanks for the answers. I will let you know. I am not exactly a junior programmer, but this one really got me stuck -- sorry about the hassle, I am very grateful for your answers.
I am very curious to run that command on my laptop, frankly. That's the key I was missing in solving this impasse.
While you are here, is there a way to force linter-eslint to use the bundled eslint?

**Comment by mercmobily** [comment]
Oh my. Now it's all clear. Thank you so much for helping.
