### ISSUE TITLE
Atom hangs for 20 seconds+ and the used cpu goes to 100% on linting

### ISSUE THREAD

**Issue by BenSower** [AtomLinter/linter-eslint#1187]
## Issue Type
Bug

## Issue Description
When I open a "large" file (600+ lines) atom just freezes and hangs for 20-30 seconds, then resumes for a couple of seconds and hangs again once I click , until I close the file
If I disable linter-eslint (linter-jscs seems to work fine), everything is back to normal (only I don't have any linting going on). 

It seems to be working to some degree, since sometimes it adds some linter errors to some of the first lines. I updated to a new computer today, and synced my atom-settings from my way older machine, which could handle the file with the same linter version perfectly.

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not.
The eslint output:
![image](https://user-images.githubusercontent.com/1158039/47295806-de2b4a80-d610-11e8-8f0c-9740fbd642fa.png)
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
I currently can't since it just freezes 
```

**Comment by Arcanemagus** [comment]
Are you able to share the file + eslint config + eslint and plugin versions that trigger this?

`linter-eslint` does all the work in a separate thread specifically to avoid this issue, so _something_ isn't right here.

**Comment by IanVS** [comment]
`apm ls` would also be helpful, to know what what other packages you have installed.

**Comment by BenSower** [comment]
Hey guys, 
sorry for the late feedback, but in the last days I wasn't able to reproduce the issue and linter-eslint seems to work as expected. I did some kernel-updating, which might have caused this rather weird occurence. For now, I'll close this ticket and open a new one, if this problem should reappear. 

Thank you for your time
