### ISSUE TITLE
ESlint not showing any errors/warnings

### ISSUE THREAD

**Issue by seve** [AtomLinter/linter-eslint#1198]
## Issue Type
Bug

## Issue Description
I have ESlint working via CLI, I have ESlint installed globally alongside a global config.  But when I try and use the atom package, nothing is happening.

## Bug Checklist
- [ ✔️] Restart Atom
- [ ✔️] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ✔️] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
TypeError: Path must be a string. Received undefined
```
In developer panel console: 
```
Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined
    at Object.generateDebugString (/Users/severiano/.atom/packages/linter-eslint/src/helpers.js:146:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by IanVS** [comment]
Are you working inside a project that has a `package.json` file?

**Comment by seve** [comment]
@IanVS No I'm not

**Comment by IanVS** [comment]
Interesting.  I bet this line is failing, in that case: https://github.com/AtomLinter/linter-eslint/blob/7d434ad84239cf65aba547ecd7bfe6521c86e90e/src/helpers.js#L114

We should add some safety around that.  Nevertheless, that's just preventing you from running the `debug` command, it shouldn't prevent linting altogether.  

Can you share your linter-eslint settings?  Have you enabled the `Use global` option?

**Comment by IanVS** [comment]
Ah hah, you have the option to `Disable when no ESLint config is found`.  Currently, that does not consider the home directory (where I assume you have your global config defined).  https://github.com/AtomLinter/linter-eslint/pull/1068 will change that behavior, but that has not been merged/released yet. 

In the meantime, try disabling that setting and see if it works better.

**Comment by skylize** [comment]
Also, if I remember correctly, `.eslintrc Path` should point to a file, not a directory.

**Comment by seve** [comment]
All working now! Looks like it was both what @IanVS and @skylize said. Thanks!
