### ISSUE TITLE
ESLINT freezes atom on startup savem as #1125

### ISSUE THREAD

**Issue by benoitcerrina** [AtomLinter/linter-eslint#1207]
## Issue Type
Bug

## Issue Description
Atom freeze on startup when some files need to be reopened.
I have narrowed it to a list of 5 files which if they are all there will cause the problem, different lists without them have caused the problems in the past but those five is the smallest I could create.
Disabling the eslint plugin or the linter plugin will fix it

## Bug Checklist
- [X ] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

I'd rather not attach the files to the bug as they contain some code proprietary to my company.  I could ever run some diagnosis or provide the files to a single person.

**Comment by briangleeson** [comment]
I've found since updating linter-eslint recently that when I save a file, atom grinds to a halt and/or no linting occurs. I've had to uninstall this package

**Comment by Arcanemagus** [comment]
Are either of you able to share the ESLint configuration (including versions of ESLint and all plugins you are using) in order to attempt to reproduce this? We aren't seeing this ourselves so it's likely to be something unique to your setup.
