### ISSUE TITLE
Allow import for Node.mjs files

### ISSUE THREAD

**Issue by Lonniebiz** [AtomLinter/linter-eslint#1227]
I can't seem to make linter-eslint work properly with node.mjs files that use es6 modules:
https://stackoverflow.com/questions/54337576/atom-linter-eslint-node-mjs-es-modules-fatal-error

Is this supported yet?

**Comment by Arcanemagus** [comment]
Until Atom itself updates to a version of Node.js that supports this natively, you'll need to configure your ESLint in a manner similar to that described in https://github.com/eslint/eslint/issues/11189.
