### ISSUE TITLE
doesn't respect .eslintignore

### ISSUE THREAD

**Issue by AprilArcus** [AtomLinter/linter-eslint#123]
linter-eslint doesn't appear to be respecting the globs in my `.eslintignore` file.

**Comment by AprilArcus** [comment]
Edit: This works if my .eslintignore is a JSON array of strings, but not if it is a plain text file of newline delimited globs. [eslint.org](http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories) claims that it should be a plain text file but perhaps this has recently changed in upstream and is now out of date?

**Comment by ismay** [comment]
I've encountered the same problem. In an ember project I want to ignore my `Brocfile.js`, which is at the projects root. Some methods of ignoring it work, some don't:

```bash
# My .eslintignore

# doesn't ignore:
/Brocfile.js

# doesn't ignore
Brocfile.js

# ignores succesfully
**/Brocfile.js
```
The same goes for folders:

```bash
# My .eslintignore

# doesn't ignore:
/bower_components

# ignores succesfully
/bower_components/**/*.js
```

**Comment by ismay** [comment]
Nevermind my latest comment. It seemed like the examples above were correct, but after a restart, linter-eslint started linting everything again. So the ignores weren't respected.

**Comment by techniq** [comment]
I'm having the same problems with my `gulpfile.js`.  I've tried all the following without success:

```
gulpfile.js
/gulpfile.js
**/gulpfile.js
```

**Comment by Spy-Seth** [comment]
I've the same issue with the `.eslintignore` file. This is a must have feature!

**Comment by Pleasurazy** [comment]
:+1:

**Comment by ismay** [comment]
For me this issue still isn't resolved with the latest update (1.0.17). With this `.eslintignore` (ember-cli project):

```
# Folders
/bower_components
/config
/dist
/node_modules
/public
/tmp
/vendor

# Files
Brocfile.js
```

It ignores `Brocfile.js` and `/node_modules` successfully, but still lints files in `bower_components`, `config`, `dist`, `public`, `tmp` and `vendor`.

**Comment by iam4x** [comment]
@ismay Path are relatives, so starting with `/` will try to match files on the root of filesystem. Use:

```
# Folders
bower_components/
config/
dist/
node_modules/
public/
tmp/
vendor/

# Files
Brocfile.js
```

**Comment by Spy-Seth** [comment]
And restart Atom. After the plugin update I have to restart Atom to have everything working.

**Comment by iam4x** [comment]
@Spy-Seth I recommend to reload Atom after every updates.

**Comment by ismay** [comment]
@iam4x Ah right, that solved it. Thanks!

**Comment by silvenon** [comment]
Now it displays a warning that the file is ignored when I view it. I don't think that should be a warning…

**Comment by stremlenye** [comment]
Agree with @silvenon: looks frustrating and takes a moment to realise the file just ignored, not having real warnings.

**Comment by oriSomething** [comment]
linter-eslint version 5.1.0,
not ignoring folders in `.eslintignore`

**Comment by steelbrain** [comment]
@oriSomething Can you open a new issue about it?
