### ISSUE TITLE
AtomLinter can't find some plugins

### ISSUE THREAD

**Issue by BopItFreak** [AtomLinter/linter-eslint#1238]
## Issue Type
Bug

## Issue Description
Everytime I use Atom with eslint, it gives me these annoying not found messages. How can I remove them? I updated eslint and AtomLinter to the latest version just now, and it still happenes.

## Bug Checklist
- [✓ ] Restart Atom
- [?] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not

![image](https://user-images.githubusercontent.com/41522720/52086925-2219de00-2576-11e9-81da-8247e86805a5.png)

**Comment by IanVS** [comment]
Hi, can you please post the output of `Linter Eslint: Debug` from the command palette?

**Comment by BopItFreak** [comment]
`Atom version: 1.34.0
linter-eslint version: 8.5.1
ESLint version: 5.10.0
Hours since last Atom restart: 0.3
Platform: win32
Using global ESLint from: C:\Users\augus\AppData\Roaming\npm\node_modules\eslint
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.semicolon"
]
linter-eslint configuration: {
  "disabling": {
    "disableWhenNoEslintConfig": false,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "useGlobalEslint": true,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}`

**Comment by IanVS** [comment]
`Using global ESLint from: C:\Users\augus\AppData\Roaming\npm\node_modules\eslint`

You are using a globally installed verison of eslint.  Do you also have your plugins installed globally?

**Comment by BopItFreak** [comment]
I had some of these problems when I first got Eslint, I was able to fix some of them, these are all that are left. So I guess I could uninstall eslint and re-install it, but I don't know if the plugins would uninstall as well.

**Comment by IanVS** [comment]
I strongly recommend to install eslint into your project, along with the plugins that you're using in that project, and unselect the `Use global` setting.

**Comment by BopItFreak** [comment]
ok so I disabled that, and now i get this
`Error while running ESLint: Failed to load plugin react: Cannot find module 'eslint-plugin-react'.`

**Comment by IanVS** [comment]
To verify, you've installed `eslint-plugin-react` locally as well, right?  Try restarting atom, and then post the debug output again please.

**Comment by BopItFreak** [comment]
done. 
```
Atom version: 1.34.0
linter-eslint version: 8.5.1
ESLint version: 4.19.1
Hours since last Atom restart: 0
Platform: win32
Using bundled fallback ESLint from: C:\Users\augus\.atom\packages\linter-eslint\node_modules\eslint
Current file's scopes: [
  "source.js",
  "variable.other.object.property.unquoted"
]
linter-eslint configuration: {
  "disabling": {
    "disableWhenNoEslintConfig": false,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}

**Comment by IanVS** [comment]
`Using bundled fallback ESLint from: C:\Users\augus\.atom\packages\linter-eslint\node_modules\eslint`

Means that `linter-eslint` was not able to find `eslint` installed in your project.  I suggest trying to install it locally again.

**Comment by BopItFreak** [comment]
so do npm install eslint? Or do you mean the Atom Package?

**Comment by IanVS** [comment]
Yes, I mean `npm install --save-dev eslint eslint-plugin-react`.

**Comment by BopItFreak** [comment]
it returned 
```
-- eslint@5.12.1

**Comment by IanVS** [comment]
Can you please answer my first two questions?

**Comment by BopItFreak** [comment]
I ran the command in the root dir of my project. My project is in C:\Users\augus\Desktop\MPP

**Comment by IanVS** [comment]
Very strange.  I think you'll need to figure out why it is installing into `C:\Users\augus\node_modules\eslint`, instead of `C:\Users\augus\Desktop\MPP\node_modules\eslint`.  I'm not sure there's anything else I can do to help until eslint gets installed into the correct location.

**Comment by IanVS** [comment]
You have a `packabe.json` in your `C:\Users\augus\Desktop\MPP` folder, right?

**Comment by BopItFreak** [comment]
nah I don't really do package.json, only when I'm uploading to heroku or something. I guess I'll just play around with this until i figure it out. Thanks Anyway.

**Comment by IanVS** [comment]
OK, that's the problem then.  If you're working on a project like this and you want to set up linting, you'll need a package.json, and _then_ run the `npm install` command.  Having that file is necessary for npm and many other tools (like linter-eslint) to treat your code as a project. 

If you don't want to make a real project, you can try installing `eslint-plugin-react` globally (`npm i -g eslint-plugin-react`), and turn back on `use global` in linter-eslint, and it might work.  But again, that's not typically what we recommend doing.

**Comment by skylize** [comment]
You can get npm to create a basic `package.json` for you.

```bash
# Generate package.json *in current folder* after answering a few questions.
npm init

# Or use -y option to automatically accept *all* the default answers.
npm init -y

# *Then* you can properly install ESLint and any plugins to the project (current) directory.
npm install --save-dev eslint eslint-plugin-react
```
