### ISSUE TITLE
Linter JSON extension (ruleId must be a string, got number)

### ISSUE THREAD

**Issue by vidavidorra** [AtomLinter/linter-eslint#1240]
## Issue Type

Bug

## Issue Description

When I add `source.json` as a scope, I get this error in Atom when either I type something or I save the file. 

```
[Linter] Error running ESLint TypeError: ruleId must be a string, got number
    at getRuleURI (/Users/jdebruijn/.atom/packages/linter-eslint/node_modules/eslint-rule-documentation/index.js:20)
    at Rules.getRuleUrl (rules.js? [sm]:39)
    at Promise.all.messages.map (helpers.js? [sm]:289)
    at Array.map (<anonymous>)
    at processESLintMessages (helpers.js? [sm]:240)
    at Object.processJobResponse (helpers.js? [sm]:344)
    at Object.lint (main.js? [sm]:283)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.34.0
linter-eslint version: 8.5.2
ESLint version: 5.13.0
Hours since last Atom restart: 0.3
Platform: darwin
Using local project ESLint from: /Users/jdebruijn/Projects/tools/node_modules/eslint
Current file's scopes: [
  "source.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "punctuation.separator.dictionary.pair.json"
]
linter-eslint configuration: {
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "scopes": [
    "source.ts",
    "source.tsx",
    "source.json",
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}
```

**Comment by Arcanemagus** [comment]
Can you provide an example repository to replicate this? From what you have posted so far it seems one of your plugins for ESLint is providing an invalid rule name, but without the ESLint configuration and package versions it's impossible to track this down further.

**Comment by vidavidorra** [comment]
See [this](https://github.com/vidavidorra/tools/tree/example) repo, where the example branch contains the code.

<br>
I've got only a few Atom packages installed myself, see the list below in case that provides useful information.

Installed packages

- `linter`
  - `linter-ui-default`
    - `intentions`
    - `busy-signal`
- `linter-eslint`
- `atom-typescript`
- `hyperclick`

<br>

See below also my output from running eslint CLI, where it shows the error in a JSON file.

```shell
$ yarn lint
yarn run v1.10.1
$ npx eslint --ext=.ts,.tsx,.json,.js,.jsx .

/Users/jdebruijn/Projects/tools/src/example.ts
  1:13  error    Delete `··`                               prettier/prettier
  3:7   warning  'foo' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/jdebruijn/Projects/tools/src/test.js
  1:13  error    Delete `··`                               prettier/prettier
  3:7   warning  'foo' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/jdebruijn/Projects/tools/src/tt.json
  2:20  error  Trailing comma  519

/Users/jdebruijn/Projects/tools/tsconfig.json
  10:23  error  Trailing comma  519

✖ 6 problems (4 errors, 2 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Arcanemagus** [comment]
It looks like that's a private repository, I'm getting a 404 when I try to visit that.

**Comment by vidavidorra** [comment]
> It looks like that's a private repository, I'm getting a 404 when I try to visit that.

My bad, it is public now!

**Comment by Arcanemagus** [comment]
_Wow_, `eslint-plugin-json` is implemented very.... "interestingly".

For the purposes of the discussion here though, although `519` definitely doesn't follow the [Rule Naming Conventions](https://eslint.org/docs/developer-guide/working-with-rules#rule-naming-conventions) I can't find anything that explicitly _prevents_ a raw number being used as the name, so we should guard against that here.

**Comment by Arcanemagus** [comment]
FYI, I would _highly_ recommend simply specifying a different ESLint configuration for JSON files specifically, using [Configuration Based on Glob Patterns](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns).

**Comment by Arcanemagus** [comment]
Actually, on further investigation although the documentation doesn't explicitly state it, the [ESLint code](https://github.com/eslint/eslint/blob/c0df9febb7c7e045ababc10b88dbcbb3f28c724c/lib/rules.js#L67-L75) expects the `ruleID` to be a string as well.

I'll be filing a PR on `eslint-plugin-json` fixing their implementation in this aspect. Until they fix this bug I would suggest you either use an ESLint configuration specific to JSON files as suggested above, or simply disable that plugin until it is fixed.

**Comment by Arcanemagus** [comment]
@vidavidorra If you update to `eslint-plugin-json@1.4.0` this _should_ be fixed there now.

**Comment by vidavidorra** [comment]
@Arcanemagus Thanks for the quick responses and fix!
