### ISSUE TITLE
Invalid position given by 'prettier/prettier'

### ISSUE THREAD

**Issue by EpykOS** [AtomLinter/linter-eslint#1249]
ESLint returned a point that did not exist in the document being edited.
Rule: `prettier/prettier`
Requested start point: 7:53 - 7:55

Debug information:
```json
{
  "atomVersion": "1.35.1",
  "linterEslintVersion": "8.5.2",
  "linterEslintConfig": {
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.flow",
      "source.babel",
      "source.js-semantic"
    ],
    "lintHtmlFiles": false,
    "autofix": {
      "fixOnSave": false,
      "ignoreFixableRulesWhileTyping": false,
      "rulesToDisableWhileFixing": []
    },
    "global": {
      "useGlobalEslint": false,
      "eslintrcPath": "",
      "globalNodePath": ""
    },
    "disabling": {
      "disableWhenNoEslintConfig": true,
      "rulesToSilenceWhileTyping": []
    },
    "advanced": {
      "disableEslintIgnore": false,
      "disableFSCache": false,
      "showRuleIdInMessage": true,
      "eslintRulesDirs": [],
      "localNodeModules": ""
    }
  },
  "eslintVersion": "5.11.1",
  "hoursSinceRestart": 0,
  "platform": "win32",
  "eslintType": "local project",
  "eslintPath": "C:\\Users\\Diego\\Documents\\Projects\\RAN\\node_modules\\eslint",
  "editorScopes": [
    "source.yaml"
  ]
}
```

**Comment by Arcanemagus** [comment]
If you want us to look into this please create a repository that consistently reproduces this. Bugs like this come from ESLint plugins and are indicative of problems that need to be fixed there.

**Comment by schelmo** [comment]
here is an example repo
https://github.com/schelmo/vue-prettier-atom-lint
it was created by vue-cli
i think this is the same issue because it is also using prettier
Steps to reproduce:
open clean atom
install linter-eslint (and its dependencies) and language-vue
add text.html.vue to list of scopes
open src/App.vue
mouse over line 3 and click "Fix"
mouse over next line and click Fix
result:
![wrong-fix](https://user-images.githubusercontent.com/47602/56850080-8e01ad80-68fd-11e9-9100-317b6dc4edca.png)

**Comment by someAndroidDeveloper** [comment]
Same here for me in react native at first line of .js file:
`import React from 'react';`
and it also gets this annoying:
![Annotation 2020-08-11 124912](https://user-images.githubusercontent.com/53018491/89874525-31e59a00-dbd1-11ea-9c50-17db3eb642f7.png)
more code i write more it copies itself.

Please someone tell me how to disable this in config file.

**Comment by ErhanAlgl** [comment]
I installed this package and the problem was fixed.
`npm i eslint-config-prettier
`
References: https://www.npmjs.com/package/eslint-config-prettier

**Comment by YigitcanOzturk** [comment]
Run this line "npm run lint -- --fix" on the command terminal after saving the project.

**Comment by aminya** [comment]
> If you want us to look into this please create a repository that consistently reproduces this. Bugs like this come from ESLint plugins and are indicative of problems that need to be fixed there.


I can reproduce this bug in this repository: 

https://github.com/steelbrain/package-deps

**Comment by aminya** [comment]
This seems to be an issue with the line endings. 

For example, Prettier wants to fix the invisible line-endings, but the function that checks this is buggy:
https://github.com/AtomLinter/linter-eslint/blob/6c8d9e82cb15224450ea0d9834fa82c8521c64c6/src/validate/editor.js#L7
