### ISSUE TITLE
Documentation is insufficient

### ISSUE THREAD

**Issue by cronoklee** [AtomLinter/linter-eslint#1250]
I have installed this package via the Atom package manager. It does not work out of the box and the installation instructions do not fully explain the steps to configure it. 

**For example:**
> To do this in a straightforward way run this:
> eslint --init
> Alternatively you can create the .eslintrc file by yourself. It is a good idea to have a look at the ESLint documentation, including the list of rules.

I cannot run terminal commands. Where should the .eslintrc file be placed? What should it look like? Can you please provide a file with some default rules for Javascript?

> If Use Global is on, Atom will use the global ESLint. The path to it is figured out by running npm get prefix. If this fails for any reason, you can set the global path manually in Global Node Installation Path.

What does global mode do? What is the "global ESLint"? What exactly should the path point to?

Is it possible to update the docs with more details for newbies like me?

**Comment by Arcanemagus** [comment]
> I cannot run terminal commands.

This is going to prevent you from doing pretty much anything, how did you create your project? Install its dependencies?

> Where should the .eslintrc file be placed? What should it look like? Can you please provide a file with some default rules for Javascript?

This package is meant to be used when you are _already_ using ESLint, if you are looking for basic tutorials on how to setup ESLint I would recommend their [Getting Started](https://eslint.org/docs/user-guide/getting-started) guide.

> What does global mode do? What is the "global ESLint"? What exactly should the path point to?

You should be installing ESLint in your project locally, global installations are not recommended. Again, this is gone over in ESLint's getting started guide.

**Comment by cronoklee** [comment]
> How did you create your project? Install its dependencies?

I'm a web developer and use HTML/PHP/CSS/Javascript only. I have no dependencies or projects to create. I just work in folders. I've had a PHP linter working nicely in Atom in Windows for 2 years or daily use and have never needed the terminal until now. Is node.js required to install ESlint? I'd prefer not to install it if possible.

**Comment by Arcanemagus** [comment]
If you create a configuration file then the bundled version of ESLint _will_ work, as long as the configuration is simple enough to not require any plugins.

For anything more than the most basic of configurations though it's likely you will need to install Node.js and start learning how to use it.

I'm going to close this issue as there isn't anything that needs to be done here. I can answer further questions related to `linter-eslint`, but I would recommend searching around on the internet for tutorials on how to use ESLint first as there are _many_ out there to help you get started.

**Comment by cronoklee** [comment]
Cool thanks. I added a `.eslintrc` to my project root and pasted into it:

    {
        "rules": {
            "semi": ["error", "always"],
            "quotes": ["error", "double"]
        }
    }

And ES lint sprang into life. I don't quite follow why you don't include a default definitions file and a line in the readme about where to put it but I appreciate your help!
