### ISSUE TITLE
"import/named" file ignore

### ISSUE THREAD

**Issue by AnderLuiz** [AtomLinter/linter-eslint#1254]
## Issue Type
Bug

## Issue Description
Eslint Cli is ignoring properly a file exception of "import/named" rule but linter-eslint does not. 

My `.eslintrc.json`:

```
{
    "extends": ["airbnb-base"],
    "rules": {
      ... [rules here]
    },
    "settings": {
      "import/ignore": "app/models/index.js"
    }
}
```
![image](https://user-images.githubusercontent.com/1660564/56215448-1ba7e800-6036-11e9-9f9f-67edc26121bc.png)

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.36.0
linter-eslint version: 8.5.4
ESLint version: 5.14.1
Hours since last Atom restart: 0.6
Platform: win32
Using local project ESLint from: D:\development\node_js\api\node_modules\eslint
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.semicolon"
]
linter-eslint configuration: {
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  },
  "autofix": {
    "fixOnSave": true,
    "ignoreFixableRulesWhileTyping": true,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false
}
```

**Comment by Arcanemagus** [comment]
`eslint-plugin-import` is a somewhat flakey plugin in my experience. Can you lay out your _exact_ directory structure of all the relevant files, including your `.eslintrc.json`, or even better provide an example repository that you can share that replicates this?

We'll also need the location you were running ESLint at, as well as the command used.

**Comment by AnderLuiz** [comment]
Hi Arcanemagus,

example repository: [repository](https://github.com/AnderLuiz/test-atom-eslint) 

![image](https://user-images.githubusercontent.com/1660564/56232977-689cb600-6058-11e9-9ead-bf2e319df71d.png)

**Comment by UziTech** [comment]
Is this still an issue?
