### ISSUE TITLE
don't fix "color-hex-case": "lower" rule in rgba functinos.

### ISSUE THREAD

**Issue by adFedorovich** [AtomLinter/linter-eslint#1256]
## Issue Type
Bug

## Issue Description
Has rule "color-hex-case": "lower" in .stylelintrc, after save colors in rgba functions remain in upper case

## Bug Checklist
- [ ] create rgba function in scss file (color: rgba(#E2E2E2, .5))

**Comment by IanVS** [comment]
Hi, this is the eslint plugin, which does not apply to css (or scss) files.  Perhaps you meant to file this in the `linter-stylelint` repo?
