### ISSUE TITLE
Package no longer displays rule key/id

### ISSUE THREAD

**Issue by nesukun** [AtomLinter/linter-eslint#127]
Hi,
It seems that in a recent update the format of the error/warning messages was changed and no longer displays the rule id/key. This was very useful when crafting the eslintrc file as one didn't need to search eslint's documentation. Please bring back this or make it available as a configuration option.

Please ignore if this change was introduced by other package such as atom-linter itself and thanks for this great package.

**Comment by AsaAyers** [comment]
I don't know why it was made a config option, but it looks like that was restored in #126. IMO if it used to show the rule name, then that should be the default now.

**Comment by iam4x** [comment]
Fixed with f90d1b8
