### ISSUE TITLE
linter-eslint freezes atom on startup

### ISSUE THREAD

**Issue by danielocdh** [AtomLinter/linter-eslint#1271]
## Issue Type

Bug

## Issue Description

linter-eslint freezes atom on startup.

I finally found a consistent way to reproduce it, some details:
- I tested this on my machine and a VM
- My machine has a few extra packages, the VM was a new fresh install
- My machine has kaspersky antivirus, the VM has no antivirus, I also tested both with my machine antivirus disabled
- Happens without a "linter-ui", with linter-ui-default or with linter-ui-plus
- Both running english windows 10 x64 1803, I wasn't able to reproduce it on an Ubuntu VM
- Both on atom 1.37.0 x64

Reproducing:
- Create a sample project folder with 3 files: .eslintrc.js, 1.jsx, 2.jsx
- fill 1.jsx with any js code but the file size has to be at least 72KiB, I just repeated the line `console.log('test');` 3600~ times
- 2.jsx can be empty
- Open atom and close all files/remove project folders
- Open the sample project folder, close all files (if any opened)
- Open 1.jsx and 2.jsx
- Right click on 1.jsx tab and select split right (do this twice)
- Close atom (and wait a few seconds for it to finish closing)
- Open atom

Most of the time having 2 panes triggered the bug but having 3 panes was completely consistent. Also sometimes when moving tabs around panes I could close and open atom without the bug being triggered. I believe the key to reproduce the bug is to have the same file on at least 2 different panes and also have more than 72KiB~ in jsx files open.

my .eslintrc.js:
```
module.exports = {
    "env": {
        browser: true,
        "es6": true,
        "node": true
    },
    //"extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
    }
};
```

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below
(output got on a previos atom run, before the freeze)

```
Atom version: 1.37.0
linter-eslint version: 8.5.5
ESLint version: 5.16.0
Hours since last Atom restart: 0.1
Platform: win32
Using global ESLint from: C:\Users\Test\AppData\Roaming\npm\node_modules\eslint
Current file's scopes: [
  "source.js"
]
linter-eslint configuration: {
  "disabling": {
    "disableWhenNoEslintConfig": false,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "useGlobalEslint": true,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}
```

**Comment by vilvai** [comment]
I'm having problems with this issue as well

**Comment by UziTech** [comment]
Is this still an issue?

**Comment by danielocdh** [comment]
> Is this still an issue?

tested on global and local install, latest atom and windows version, could not reproduce it

**Comment by UziTech** [comment]
Ok I'm going to close this. If it happens again feel free to reopen it.
