### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bogdandobanda** [AtomLinter/linter-eslint#1283]
## Issue Type
Bug

## Issue Description
Infinite recursion for getConfigPath() in worker-helpers.js if package.json is present in root.
atom-linter.findCached will return package.json and getConfigPath will be called infinitely with root path (as it cannot go up anymore)

**Comment by Arcanemagus** [comment]
Are you saying you have a `/package.json` file???

**Comment by bogdandobanda** [comment]
> Are you saying you have a `/package.json` file???

Yes, It was there by mistake. Took me a while to see where the error came from.

**Comment by Arcanemagus** [comment]
Looks like we'll need to add a guard in here to prevent further iteration upwards once it hits `/`:
https://github.com/AtomLinter/linter-eslint/blob/b5ed17f5e41a2cad05aa459e66074930e69cffc7/src/worker-helpers.js#L127-L134
