### ISSUE TITLE
--fix only a selection of code

### ISSUE THREAD

**Issue by AxelJunker** [AtomLinter/linter-eslint#1288]
## Issue Type

Feature Request

## Issue Description

It would be neat to have the possibility to only `--fix` a selection of code, not the whole file. Don't know if this is possible since eslint doesn't seem to support this. Please let me know if this is a feature request for eslint.

**Comment by Arcanemagus** [comment]
You can fix individual messages using the method the UI you are using provides, or you can fix the entire file at once using ESLint's built in method. Note that fixing individual methods can lead to a _different_ rule telling you the "fixed" code is problematic as there is no conflict resolution for individual fixes. It's recommended to use the whole-file fix if possible.

If you wanted to select a range and have all known fixes applied that would be a feature request for ESLint as we aren't going to blindly apply the fixes it provides for each message as there is no conflict resolution.
