### ISSUE TITLE
linter-eslint is ignoring *.ts *.tsx files

### ISSUE THREAD

**Issue by HectorLS** [AtomLinter/linter-eslint#1293]
## Issue Description
Linter works fine with .js files but is ignoring the *.ts *.tsx typescript extension

## Bug Checklist
- [X ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not

If i run `yarn lint` if take this code and show me perfectly the list of lint warning/errors in the terminal.
> Atom is showing nothing of this while im typing, as it does with *.js files.
> I have all the linters installed locally for the project. does Atom need it globally in order to work ?

```js
// .eslintrc.json
```
```json
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true,
    "jest": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true
    }
  },
  "plugins": [
    "react",
    "@typescript-eslint",
    "prettier"
  ],
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}
```

Any idea how to fix this ? thank you in advance.

**Comment by Arcanemagus** [comment]
You need to tell `linter-eslint` that it actually knows how to handle TypeScript files.

You can do that by adding the scope for TypeScript files (`source.ts`) here:
![image](https://user-images.githubusercontent.com/427137/61649100-a451a800-ac65-11e9-8f38-067afbbffb08.png)

Let us know if you run into any problems!

**Comment by HectorLS** [comment]
Thank you so much !
By the way, since ESLINT is taking care of TS, dont you think this should be a default setting ?
again thanks

**Comment by Arcanemagus** [comment]
Hmmm, possibly, from what I understand it's not part of the base ESLint though, so no matter what the user will need to configure things for it to work correctly.

**Comment by Gataniel** [comment]
Not sure if I need to open another issue for this, but in my case it does not help.
Here is my debug info
`Atom version: 1.45.0
linter-eslint version: 8.5.5
ESLint version: 6.8.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/azatgataullin/kafka-ui/kafka-ui-react-app/node_modules/eslint
Current file's scopes: [
  "source.tsx",
  "source.ts",
  "string.quoted.template"
]
linter-eslint configuration: {
  "advanced": {
    "disableFSCache": true,
    "disableEslintIgnore": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  },
  "autofix": {
    "fixOnSave": true,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic",
    "source.ts",
    "source.tsx"
  ],
  "lintHtmlFiles": false,
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  }
}`
