### ISSUE TITLE
linter-eslint is unable to find private npm plugins

### ISSUE THREAD

**Issue by zertosh** [AtomLinter/linter-eslint#130]
They briefly worked after https://github.com/AtomLinter/linter-eslint/commit/c3438d882a0787c001bab28230ce5fbdd365a26c, but in 1.x (last tested with 1.0.8) they stopped working.

I've got a plugin that is located in `./node_modules/@sc/eslint-plugin-sc` that I reference from `.eslintrc` with `{"plugins": ["@sc/sc"]}`. The exact error reads `[Linter-ESLint] plugin @sc/sc not found`.

eslint itself had a bug with [scoped modules](https://docs.npmjs.com/misc/scope) that was fixed in v0.20.0 by https://github.com/eslint/eslint/issues/2360.

**Comment by iam4x** [comment]
I can't test it, I've replicated the changes from https://github.com/AtomLinter/linter-eslint/commit/c3438d882a0787c001bab28230ce5fbdd365a26c and published a new version, can you confirm me it's working @zertosh ?

**Comment by zertosh** [comment]
@iam4x: I can confirm that this is fixed and working in v1.0.11. Thank you!
