### ISSUE TITLE
Still linting even without a config and Disable without a config is checked

### ISSUE THREAD

**Issue by ricardograca** [AtomLinter/linter-eslint#1300]
## Issue Type
Bug

## Issue Description

I have checked the option to "Disable when no ESLint config is found". There is no `.eslintrc` file or a `"eslint"` config in package.json. The `eslint` package is not installed in this project.  `linter-eslint` still lints my JS files.

Note that there doesn't appear to be any "Linter Eslint: Debug" command in the Command Palette of the project that exhibits this issue, but if I go to a project where ESLint does have a config and is enabled I can get the required information, that I pasted below.

## Bug Checklist
- [x] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.39.0
linter-eslint version: 8.5.5
ESLint version: 6.1.0
Hours since last Atom restart: 0
Platform: linux
Using local project ESLint from: /home/ricardo/src/bookshelf/node_modules/eslint
Current file's scopes: [
  "source.js",
  "meta.class"
]
linter-eslint configuration: {
  "advanced": {
    "disableFSCache": true,
    "disableEslintIgnore": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  },
  "autofix": {
    "fixOnSave": true,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  }
}
```

**Comment by IanVS** [comment]
Hmmm, the fact that there's no `Linter Eslint: Debug` command when you're in that project is a bit strange.  It usually means that the scope of the file you're viewing is not one that linter-eslint is configured to recognize.  

Do you have an eslint config file in your home directory?  ESLint will traverse up to the root directory looking for a config file, and if it doesn't find anything, it will also check your home directory.

**Comment by ricardograca** [comment]
No, I don't have a eslint config file in my home directory directly but, in the case of this particular project that exhibits the behavior I reported, there was indeed a eslint config in its parent directory. After deleting it the problem was gone.

However I still think it may be worth pondering if this behavior is worth all the issues it seems to cause. If I open a project directory in Atom, I surely don't expect that any eslint config files in an ancestor directory to influence linting behavior.

I've seen a few open issues about this, so it seems to be causing some confusion, and it's not always obvious what the problem is.

**Comment by IanVS** [comment]
>If I open a project directory in Atom, I surely don't expect that any
eslint config files in an ancestor directory to influence linting behavior.

I understand it can cause confusion, but for better or worse, this is how
ESLint config resolution works. If we stopped looking for config files only
at the directory opened in Atom, it would undoubtedly break the experience
for others who expect linting to be identical to the CLI. I'd be happy to
review a PR to the docs, though, if you think you can help make the
behavior more clear.

**Comment by ricardograca** [comment]
I think the problem here is also that "Disable when no ESLint config is found (in package.json or .eslintrc)" is misleading, since it seems to imply that linting will be disabled if no config file is found **in the current project**. At least that's how I read it. I wasn't expecting that there would be extra caveats to it.

Maybe it should read "Disable when no ESLint config is found (in package.json, .eslintrc, ancestor or home directories)".

But anyway I'll add a note to the Readme about this and submit a PR.

**Comment by ricardograca** [comment]
I get what you're saying about using the rules of ESLint, but I don't think it makes sense in this case. Unless I'm missing something ESLint doesn't have a "Disable when no ESLint config is found" option, so there's no parallel in terms of expectations on how checking this in `linter-eslint` would behave.

I just compared the behavior to the [SublimeLinter-eslint](https://packagecontrol.io/packages/SublimeLinter-eslint) package in Sublime Text and it does what most users would expect it to. It does not lint a project unless there's a config in that project. It doesn't go look for configs in magic places that require deep knowledge of the ins and outs of eslint.

Maybe some people would be surprised if "Disable when no ESLint config is found" would actually do that, but we can always add an option to "Look for config files all the way up to a user's home directory". Would that work?
