### ISSUE TITLE
Rule meta.docs.url seems to not functioning properly

### ISSUE THREAD

**Issue by cjtaylor1990** [AtomLinter/linter-eslint#1308]
I have been trying to add rule documentation URLs for the ESLint plugin You-Dont-Know-Lodash-Underscore (https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/149), and have been able to successfully link to the documentation by adding in the URL into the plugins.json file in eslint-rule-documentation.

I have since been working to use the new meta.docs.url method, as it seems to be the preferred method of doing it, however, I've found that linter-eslinter seems to ignore the information in meta.docs.url for the rules.

For example, for eslint-plugin-mocha, linter-eslint gives the link https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/prefer-arrow-callback.md for the "mocha/prefer-arrow-callback" rule. However, looking into the object for this rule, the actual URL provided by eslint-plugin-mocha is https://eslint.org/docs/rules/prefer-arrow-callback

The link provided by linter-eslint in Atom ends up being what is provided via the older method in eslint-rule-documentation. If I remove the mocha entry from plugins.json, the URL link simply links to the default: https://github.com/jfmengels/eslint-rule-documentation/blob/master/contributing.md

I was curious if you had any solutions to this? Has this been noticed before?

**Comment by Arcanemagus** [comment]
`linter-eslint` has supported the `meta.docs.url` property since before it was in a released version... we were part of the inspiration for it's creation.

The code should only be falling back to that default URL if it can't find a URL property:
https://github.com/AtomLinter/linter-eslint/blob/9eb5bbb2c771394b6bbe6aef172a4636cece9c4b/src/rules.js#L39-L56

I'm not seeing a PR up adding the property to that plugin, so I can't tell what you're doing wrong here, but if you want me to take a look I'd be happy to.

**Comment by cjtaylor1990** [comment]
Thanks for the response, and I apologize if I at all sounded like I was being critical. I actually prefer the new method of documentation URLs (meta.docs.url), so thank you for inspiring that.

I haven't done a PR to the plugin because I haven't gotten it to link properly, which is why I was messing around with the Mocha plugin to experiment to see where I was going wrong. I had seen that bit of code that you posted, hence why I was especially confused. I apologize for any inconvenience.

Here is my fork with the branch I am working on:
https://github.com/cjtaylor1990/You-Dont-Need-Lodash-Underscore/tree/metaUrl

with the specific commit:
https://github.com/cjtaylor1990/You-Dont-Need-Lodash-Underscore/commit/7f39edd35a101ea56bc2b7ffcf1ec3755f53ad8b

I just committed my changes because I was doing the experiments in a local test node project, which I had a copy of the plugin as a dev dependency and I was just messing around with the copy to see if I could get it to work with linter-eslint in Atom.

Once again, thanks for taking the time to respond.
