### ISSUE TITLE
RFC: add support for the --reset flag to turn off all defaults

### ISSUE THREAD

**Issue by jkroso** [AtomLinter/linter-eslint#131]
Looking at the code it correctly figures out where my .eslintrc file is but then it never actually uses it :confused:

**Comment by iam4x** [comment]
Can I have more information?

* Your `.eslintrc`
* The file you are linting

Is `eslint` is installed to your package?

**Comment by jkroso** [comment]
.eslintrc: ~/.eslintrc
target file: ~/projects/a/index.js

And my project doesn't have eslint installed but the linter-eslint package does. I also had it globally installed but I removed it to see if it would fix it.

**Comment by jkroso** [comment]
actually it turns out it is loading my config. Its just that it also adds a bunch more defaults than it used to. And the fact that line 54 is basically never used made me think it blatantly wasn't loading my .eslintrc. But I guess it happens inside the CLIEngine thing

**Comment by jkroso** [comment]
A config flag that turns off all defaults would be handy. I think I must of used that flag in the past. Its been a while since I used eslint. The eslint CLI tool has a --reset flag for this.

**Comment by AsaAyers** [comment]
Tweet to https://twitter.com/geteslint I thought I saw something recently about that getting implemented, but now I'm having trouble finding it. I think it was releated to the new ability to extend another config file.

**Comment by jkroso** [comment]
@AsaAyers eslint already supports the reset flag

**Comment by AsaAyers** [comment]
yes, but what I'm saying is that I think they added the ability to do that in your configuration so you don't have to use the flag on the CLI. This plugin doesn't use the CLI, it loads the eslint library

**Comment by jkroso** [comment]
Oh right sorry. Yea looks like its just a matter of putting `"reset":true` in you .eslintrc. But for some reason this option needs to be passed into `CLIEngine`. So maybe there is actually a bug in `CLIEngine.prototype.getConfigForFile`

**Comment by iam4x** [comment]
@jkroso Do you have the reference to how passing reset to CLIEngine?

**Comment by jkroso** [comment]
I just read the source of the eslint CLI https://github.com/eslint/eslint/blob/master/lib/cli.js I haven’t looked any deeper yet

**Comment by iam4x** [comment]
I'll investigate :)

**Comment by iam4x** [comment]
Didn't have any time this week, I'll try next week sorry for delay @jkroso

**Comment by ilyavolodin** [comment]
This is how you pass `reset` to CLIEngine:
```js
var CLIEngine = require("eslint").CLIEngine;

var cli = new CLIEngine({
    rules: {
        semi: 2
    },
    reset: true
});
```

Btw, starting with version 1.0.0 `reset` will become default behavior and there will be no default rules configuration unless you extend your config with `eslint:recommended`.

**Comment by iam4x** [comment]
Version 2.0 has been released now using CLI, please open a new issue if something is wrong.
