### ISSUE TITLE
Set indentation length automatically, based on config (tab vs space)

### ISSUE THREAD

**Issue by caravinci** [AtomLinter/linter-eslint#1317]
## Issue Type
Feature Request

## Issue Description
When using a config file, you can enforce a specific tab length (e.g. hard tab, 2-4 spaces, etc.)
It would be useful if Atom's indent length was automatically updated based on the eslint config.
Not sure this is in the scope of this package, but it'd be nice to have, methinks.

## ~Bug Checklist~
- [ ] ~Restart Atom~
- [ ] ~Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not~
- [ ] ~Paste the output of the `Linter Eslint: Debug` command from the Command Palette below~

```
Linter Eslint: Debug output here

Atom version: 1.42.0
linter-eslint version: 8.5.5
ESLint version: 6.8.0
Hours since last Atom restart: 6.7
Platform: darwin
Using global ESLint from: /usr/local/lib/node_modules/eslint
Current file's scopes: [
  "source.ts",
  "punctuation.definition.function.body.end.bracket.curly"
]
linter-eslint configuration: {
  "advanced": {
    "disableFSCache": true,
    "disableEslintIgnore": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  },
  "autofix": {
    "fixOnSave": true,
    "ignoreFixableRulesWhileTyping": true,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": false,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "eslintrcPath": "~/.eslintrc.js",
    "useGlobalEslint": true,
    "globalNodePath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic",
    "source.ts",
    "source.tsx"
  ],
  "lintHtmlFiles": false
}
```

**Comment by Arcanemagus** [comment]
I'd consider this outside the scope of this package. You should check out https://atom.io/packages/editorconfig as it is a semi-standard way of accomplishing what you are asking here.
