### ISSUE TITLE
Latest release (1.0.9) broke usage of global npm packages as plugins

### ISSUE THREAD

**Issue by yamalight** [AtomLinter/linter-eslint#132]
After updating to 1.0.9 I can no longer use global npm packages, linter always fails to load plugins.

**Comment by yamalight** [comment]
There's a typo in source code

**Comment by yamalight** [comment]
Submitting PR with fix in a moment...

**Comment by iam4x** [comment]
@yamalight I've published `v1.0.10` it's early in the morning and it's monday :')

**Comment by yamalight** [comment]
ah, great, thanks! :D

**Comment by yamalight** [comment]
hmm.. nope, v1.0.10 still broke

**Comment by yamalight** [comment]
@iam4x see my comment to the previous commit - there's a typo in code and a wrong var used for plugin loading

**Comment by iam4x** [comment]
@yamalight Should be good now :+1:

**Comment by yamalight** [comment]
yep, works good. thanks! :+1:
