### ISSUE TITLE
deprecated core-js@2.6.11

### ISSUE THREAD

**Issue by emha** [AtomLinter/linter-eslint#1348]
## Issue Type

Bug, Question

## Issue Description

When I try to install `apm install linter-eslint` I get the error that Core-JS is deprecated. Also happens over the Atom GUI.

`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
`

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
> core-js@2.6.11 postinstall /tmp/apm-install-dir-120317-28579-1migwp8.bpmi/node_modules/linter-eslint/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120317-28579-1migwp8.bpmi/package.json'
npm WARN apm-install-dir-120317-28579-1migwp8.bpmi No description
npm WARN apm-install-dir-120317-28579-1migwp8.bpmi No repository field.
npm WARN apm-install-dir-120317-28579-1migwp8.bpmi No README data
npm WARN apm-install-dir-120317-28579-1migwp8.bpmi No license field.

npm ERR! Maximum call stack size exceeded
```

I'am not sure if this is a `linter-eslint` issue or not. I tried to upgrade several packages, searched the OS for `core-js@2.6.11` to find where the deprecated package comes from but I couldn't find anything useful.

If you need more informations please let me know.

**Comment by sitekick** [comment]
i have this same error, @emha could you possibly share your solution?

**Comment by emha** [comment]
@sitekick I can't because I have none. Still need help here :)

**Comment by emha** [comment]
@sitekick It was late and I thought this was a different ticket. The posted error message was wrong. The error I get is not the core-js Version. Have a look at this Ticket: https://github.com/atom/atom/issues/20656
