### ISSUE TITLE
Invalid position given by 'prettier/prettier'

### ISSUE THREAD

**Issue by MarwaShwani** [AtomLinter/linter-eslint#1349]
ESLint returned a point that did not exist in the document being edited.
Rule: `prettier/prettier`
Requested start point: 1:2 - 1:4

Debug information:
```json

```

**Comment by MarwaShwani** [comment]
//
 import React from 'react';
 import {AppRegistry} from 'react-native';
 import Header from './src/component/header';
//create a component
 const  App = () => {
   return (
     <Header />
    );
  };
AppRegistry.registerComponent( 'album', () => App );

**Comment by YigitcanOzturk** [comment]
Run this line "npm run lint -- --fix" on the command terminal after saving the project.

**Comment by UziTech** [comment]
Is this still an issue?

**Comment by aminya** [comment]
Yes, I can reproduce it in the package-deps repo.

Duplicate of #1249
