### ISSUE TITLE
Error while running ESLint: createRequire is not a function

### ISSUE THREAD

**Issue by robinloeffel** [AtomLinter/linter-eslint#1351]
## Issue Type
Bug

## Issue Description
Installing ESLint@7 breaks `linter-eslint`, throwing

```
> Error while running ESLint: createRequire is not a function.
```

<img width="1440" alt="Screenshot 2020-05-10 at 14 59 53" src="https://user-images.githubusercontent.com/6851646/81499953-37300180-92cf-11ea-8bbd-33d68d29e69e.png">
<img width="1440" alt="Screenshot 2020-05-10 at 14 59 57" src="https://user-images.githubusercontent.com/6851646/81499955-3b5c1f00-92cf-11ea-92fe-1b99ef672bcb.png">
<img width="1082" alt="Screenshot 2020-05-10 at 15 00 35" src="https://user-images.githubusercontent.com/6851646/81499956-3bf4b580-92cf-11ea-8fda-2c297ec3340d.png">

Most probably has to do with [ESLint@7 requiring a more recent version of Node.js](https://github.com/eslint/eslint/blob/master/package.json#L144) than Atom is built on, so I don't know how much you can do. See https://github.com/prettier/prettier-atom/issues/725#issuecomment-613325853, as well. 

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.46.0
linter-eslint version: 8.5.5
ESLint version: 7.0.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/robin/Sites/cosha/node_modules/eslint
Current file's scopes: [
  "source.js",
  "constant.numeric"
]
linter-eslint configuration: {
  "autofix": {
    "fixOnSave": true,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}
```

**Comment by robinloeffel** [comment]
Just saw https://github.com/AtomLinter/linter-eslint/issues/1350. Closing it.

**Comment by hersh-kat** [comment]
I'm experiencing this same error whilst trying to load any plugins in my .eslintrc.json file:

<img width="1244" alt="Screenshot 2020-05-10 at 15 31 44" src="https://user-images.githubusercontent.com/43843678/81502034-63e61800-92d3-11ea-8270-ed17093058c0.png">

The "createRequire is not a function" error made me think it was the [prettier bug too](https://github.com/prettier/prettier-atom/issues/725#issuecomment-613325853), but still got the same error after uninstalling prettier.

**Comment by whaaaley** [comment]
I downgraded to 6.8.0 works fine now.

**Comment by SomniumDigital** [comment]
> I downgraded to 6.8.0 works fine now.

This worked for me too 👍🏼

**Comment by TheBillyIsMe** [comment]
Downgrading ESLint to 6.8.0 seems to have fixed the issue for me aswell. 

**If anyone else out there is experiencing this issue:**
```bash
npm remove eslint -global
npm install eslint@6.8.0 -global
```
and **Restarting Atom** should fix it.

**Comment by vDiFoung** [comment]
> Downgrading ESLint to 6.8.0 seems to have fixed the issue for me aswell.
> 
> **If anyone else out there is experiencing this issue:**
> 
> ```shell
> npm remove eslint -global
> npm install eslint@6.8.0 -global
> ```
> 
> and **Restarting Atom** should fix it.

Thank a lot, you saved my life

**Comment by ktrzos** [comment]
Well... I'm experiencing the same problem in PhpStorm :/.

**Comment by robinloeffel** [comment]
Upgrading to Atom 1.47.0 fixed the issue.

**Comment by viktor-equinix** [comment]
Is there a possibility to fix for atom 1.36.1? I cannot upgrade to new version otherwise Nuclide will stop to work -- I wish to move to new version but unfortunately there is no great implementation of search like Omni search which has Nuclide.

**Comment by yigres** [comment]
Thank a lot, you saved my life!:)

**Comment by yigres** [comment]
> > Downgrading ESLint to 6.8.0 seems to have fixed the issue for me aswell.
> > **If anyone else out there is experiencing this issue:**
> > ```shell
> > npm remove eslint -global
> > npm install eslint@6.8.0 -global
> > ```
> > 
> > 
> > and **Restarting Atom** should fix it.
> 
> Thank a lot, you saved my life

Thank a lot, you saved my life!:)

**Comment by yigres** [comment]
> Downgrading ESLint to 6.8.0 seems to have fixed the issue for me aswell.
> 
> **If anyone else out there is experiencing this issue:**
> 
> ```shell
> npm remove eslint -global
> npm install eslint@6.8.0 -global
> ```
> 
> and **Restarting Atom** should fix it.

Thank a lot, you saved my life!:)

**Comment by mahanmashoof** [comment]
Just upgrading Atom (1.53.0) removed the issue..seems like the 1.44 version was running with node 10.x.x

**Comment by allen-tran** [comment]
> ```shell
> npm install eslint@6.8.0 -global
> ```

This worked for me, thank you!
