### ISSUE TITLE
Can't find ESLint modules unless node_modules is in the directory

### ISSUE THREAD

**Issue by tommydmcdonald** [AtomLinter/linter-eslint#1362]
## Issue Type

Bug

## Issue Description

I am working on a project that uses Yarn 2, so there is no `node_modules` directory, only a yarn cache of 3rd party modules. I have tried a few things that I think should work, but they aren't. The only thing that has worked is actually running `npm i` and creating a `node_modules` directory in the project root.

1. Tried using the yarn 2 cache with nothing else changed. This didn't work and I got the error `Error while running ESLint: Failed to load plugin react: Cannot find module 'eslint-plugin-react'.`
output of the `Linter Eslint: Debug`
```
Atom version: 1.49.0
linter-eslint version: 8.5.5
ESLint version: 4.19.1
Hours since last Atom restart: 0.3
Platform: darwin
Using bundled fallback ESLint from: /Users/tmcd11/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js",
  "keyword.control"
]
linter-eslint configuration: {
  "advanced": {
    "localNodeModules": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  }
}
```

2. Tried using the global node_modules installation. I installed all the `eslint-plugin`s to npm globally and turned on `Use global ESLint installation`. Got the same error as above.
output of the `Linter Eslint: Debug`
```
Atom version: 1.49.0
linter-eslint version: 8.5.5
ESLint version: 4.19.1
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/tmcd11/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js",
  "punctuation.terminator.statement.semicolon"
]
linter-eslint configuration: {
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "globalNodePath": "/Users/tmcd11/.nvm/versions/node/v12.16.1",
    "useGlobalEslint": false,
    "eslintrcPath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  }
}
```

3. Tried using a local node_modules installation in a project
I copied the `package.json` to another directory that wasn't within the project and ran `npm i`. Then I put that path in `Path to the local node_modules folder` in settings. Still the same error.
output of the `Linter Eslint: Debug`
```
Atom version: 1.49.0
linter-eslint version: 8.5.5
ESLint version: 7.5.0
Hours since last Atom restart: 0
Platform: darwin
Using advanced specified ESLint from: /Users/tmcd11/dev/eslint-modules/node_modules/eslint
Current file's scopes: [
  "source.js",
  "punctuation.section.embedded"
]
linter-eslint configuration: {
  "advanced": {
    "localNodeModules": "/Users/tmcd11/dev/eslint-modules/node_modules/",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "globalNodePath": "/Users/tmcd11/.nvm/versions/node/v12.16.1",
    "useGlobalEslint": false,
    "eslintrcPath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  }
}
```

**Comment by UziTech** [comment]
Is this still an issue?

**Comment by poziminski** [comment]
I also have this issue and couldn't find a solution yet. Does anyone has the working setup of atom + yarn + eslint?

**Comment by UziTech** [comment]
I use it with yarn all the time and it works fine. Do you have eslint as a devdependency?

**Comment by poziminski** [comment]
Okay so I found a working solution for me: `nodeLinker: "node-modules"` setting in `.yarnrc`. This also sets up a node_modules directory so may not be viable for everyone. But nevertheless now my eslint plugin works fine.

Point 5. in migration guide.
https://yarnpkg.com/getting-started/migration

**Comment by UziTech** [comment]
Ya with PNP I don't think it is possible for us to find eslint.

There is a setting under "Uncommon" where you should be able to specify the path to the node_modules folder or you can install eslint globally and use that.

![image](https://user-images.githubusercontent.com/97994/116422039-f9d8c280-a804-11eb-9b38-cfa3b09b435f.png)

**Comment by tommydmcdonald** [comment]
What worked for me was installing the node modules using yarn even though the rest of the project used yarn2. Not sure if this was ever resolved or not.
