### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by DaggLo** [AtomLinter/linter-eslint#1369]
## Issue Type

Bug (probably).

## Issue Description

Installation using `apm install linter-eslint` or via Atom Install Packages fails with error.

My setup:
- Linux 5.8.11-1-MANJARO 
- Atom v1.51.0
- Node v14.13.1 (installed via [asdf](https://asdf-vm.com/))
- npm v6.14.8

Preliminary installation of the [Linter](https://github.com/steelbrain/linter) package finished fine and without errors via Atom Install Packages. This may indirectly point at problems with current package.

## Bug Checklist
- [x] Restart Atom (**Doesn't help**)
~~- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not~~ (**Not relevant**)
~~- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below~~  (**Not relevant**)

```
>>> apm install linter-eslint                        ±[A2][master]
Installing linter-eslint to /home/xyz/.atom/packages ✗

> core-js@2.6.11 postinstall /tmp/apm-install-dir-202098-12975-eklit3.d8p/node_modules/linter-eslint/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN lifecycle The node binary used for scripts is /home/xyz/.asdf/shims/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
unknown command: node. Perhaps you have to reshim?
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-202098-12975-eklit3.d8p/package.json'
npm WARN apm-install-dir-202098-12975-eklit3.d8p No description
npm WARN apm-install-dir-202098-12975-eklit3.d8p No repository field.
npm WARN apm-install-dir-202098-12975-eklit3.d8p No README data
npm WARN apm-install-dir-202098-12975-eklit3.d8p No license field.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xyz/.atom/.apm/_logs/2020-10-08T11_50_10_918Z-debug.log

```
- `npm config set scripts-prepend-node-path true` - **didn't do the job**
- `sudo apm install linter-eslint`  - **didn't do the job**
- Reinstalling Atom via Add/Remove Software  - **didn't do the job**

**Comment by sgpinkus** [comment]
+1 getting the same error. Went back trying different version. Last of 8.1.x versions, 8.1.7 installs without error, 8.2.0 I get above. 

 - OS: Debian GNU/Linux 10 (buster)
 - Atom: 1.4.7
 - NPM: 6.14.8
 - Node: 12.18.1
