### ISSUE TITLE
[v1.0.14] EBADF: bad file descriptor, write

### ISSUE THREAD

**Issue by clintwood** [AtomLinter/linter-eslint#138]
In Atom devtools if I do `require('child_process').execSync('npm config get prefix', {encoding: 'utf8'})` I get `Error: EBADF: bad file descriptor, write` which is essentially where it is breaking in `findGlobalNPMdir`.  If I call the async version (i.e. `require('child_process').exec('npm config get prefix', {encoding: 'utf8'}, function(err, stdout, stderr) { console.log(stdout); })`) the call works and logs out the correct path.

Also I'm not sure that join should include `lib` on this line in the same function: `globalNpmPath = path.join globalNodeDir, 'lib', 'node_modules'`

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v1.0.14

### Stack Trace

Failed to activate the linter-eslint package

```
At EBADF: bad file descriptor, write

Error: EBADF: bad file descriptor, write
    at Error (native)
    at Object.fs.writeSync (fs.js:657:20)
    at SyncWriteStream.write (fs.js:1906:6)
    at execSync (child_process.js:1372:20)
    at Object.module.exports.findGlobalNPMdir (C:\Users\Clinton\.atom\packages\linter-eslint\lib\linter-eslint.coffee:212:23)
    at Object.module.exports.activate (C:\Users\Clinton\.atom\packages\linter-eslint\lib\linter-eslint.coffee:52:21)
    at Package.module.exports.Package.activateNow (C:\Users\Clinton\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
    at C:\Users\Clinton\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30
    at Package.module.exports.Package.measure (C:\Users\Clinton\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
    at Package.module.exports.Package.activate (C:\Users\Clinton\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\ITNodeJS"
  },
  "linter-eslint": {
    "useGlobalEslint": true
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.8
highlight-selected, v0.10.1
linter, v1.1.0
linter-eslint, v1.0.14
minimap, v4.10.2
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
project-manager, v1.15.10
run-in-terminal, v0.2.2

# Dev
No dev packages
```

**Comment by iam4x** [comment]
The join is definitely needed, I may suspect this is a bug with the sync version and Windows like you said.

Can you update to `1.0.15` and set yourself the correct path in the options as workaround?

**Comment by clintwood** [comment]
Awesome thanks! Will give it a go!

**Comment by clintwood** [comment]
Works if I remove the `'lib'` from the path join this line:
`      globalNpmPath = path.join globalNodePath, 'lib', 'node_modules'`
like this
`      globalNpmPath = path.join globalNodePath, 'node_modules'`

FYI:
`npm config get prefix` returns `C:\Users\Clinton\AppData\Roaming\npm` for me and `node_modules` is directly under that (i.e. `C:\Users\Clinton\AppData\Roaming\npm\node_modules`)

**Comment by iam4x** [comment]
@clintwood oh! May be specific to windows? How nodejs is installed?

**Comment by iam4x** [comment]
Just tried in a vm, let me fix this :)

**Comment by clintwood** [comment]
I'm taking a look at npm to see why we have a difference in global path to node_modules... weird...

**Comment by clintwood** [comment]
The difference is explained here: https://docs.npmjs.com/files/folders#node-modules.  I see the fix thanks!

**Comment by iam4x** [comment]
Fixed with new version.

Thank's for the reference :+1:

**Comment by clintwood** [comment]
Will give it a go. Thanks!

**Comment by clintwood** [comment]
I think you got a typo at https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L224 `statsSync` should be `statSync`.

**Comment by iam4x** [comment]
c49d0b3

**Comment by clintwood** [comment]
Nice, thank you!
