### ISSUE TITLE
Eslint binary not found locally in spite of local grunt-eslint is installed

### ISSUE THREAD

**Issue by joseluisq** [AtomLinter/linter-eslint#140]
I have [`grunt-eslint`](https://github.com/sindresorhus/grunt-eslint) installed on my local node project.
But I got this error

![image](https://cloud.githubusercontent.com/assets/1700322/8527472/643085cc-23d2-11e5-9fb3-1793fa648c99.png)
So I don't need to check global eslint or installing eslint for each project.
Regards.

**Comment by iam4x** [comment]
`$ npm install --save-dev eslint`

**Comment by joseluisq** [comment]
:+1:
