### ISSUE TITLE
can't find global eslint

### ISSUE THREAD

**Issue by mattsawyer77** [AtomLinter/linter-eslint#141]
For some reason I'm frequently getting this error now:

> [Linter-ESLint] eslint binary not found localy, falling back to packaged one. Plugins won't be loaded and linting will possibly not work. (Try Use Global ESLint option, or install localy eslint to your project.)

In my terminal, I can do ```which eslint``` and it does find my global eslint. If it makes a difference, I'm using Mac OSX 10.10.4, and nvm.

**Comment by iam4x** [comment]
The message is telling you that it can't find the locally eslint, not the global system one.

Two options:

* `$ npm install --save-dev eslint` to your project

or

* Set `Use global ESLint` option from the package

**Comment by mattsawyer77** [comment]
I have the "use global ESLint" option checked. Maybe the real problem here is that option isn't working? I wonder if that doesn't work well with nvm?

**Comment by iam4x** [comment]
@mattsawyer77 On what OS are you running Atom? And what does return `$ npm config get prefix` return?

Sounds like a bug.

**Comment by mattsawyer77** [comment]
I'm on OSX 10.10.4, Atom 1.0.0, and I've run ```npm config get prefix``` and pasted the output in the prefix box in your settings. It is ```/usr/local/opt/nvm/versions/node/v0.12.2```

**Comment by chriskrycho** [comment]
I'm seeing the exact same problem. `npm config get prefix` → `/usr/local/var/nvm/versions/io.js/v2.3.0`.

**Comment by mattsawyer77** [comment]
I could probably tolerate the bug, but with on-the-fly linting enabled, error notifications appear every few seconds and pile up.

**Comment by iam4x** [comment]
Do you have an `eslint` directory into `(npm config get prefix)/lib/node_modules` ?

**Comment by chriskrycho** [comment]
Switching it to `/usr/local/var/nvm/versions/io.js/v2.3.0/lib/node_modules` fixed the problem, FWIW. I do have a symlinked `eslint` to that:

```bash
$ ls -l $(which eslint)
lrwxr-xr-x  1 chris  admin  40 Jul  6 20:49 /usr/local/var/nvm/versions/io.js/v2.3.0/bin/eslint -> ../lib/node_modules/eslint/bin/eslint.js
```

**Comment by mattsawyer77** [comment]
@iam4x I do:

```
file $(npm config get prefix)/lib/node_modules/eslint
/usr/local/opt/nvm/versions/node/v0.12.2/lib/node_modules/eslint: directory
```

**Comment by Raigen** [comment]
I do have the same problem on Windows 8.1 with Atom 1.0
```
$ npm config get prefix
C:\Users\foellerich\AppData\Roaming\npm
```
Global eslint is in `C:\Users\foellerich\AppData\Roaming\npm\node_modules\eslint` (yes, without `\lib`)
`Use global eslint` is checked of course.
```
$ which eslint
/c/Users/foellerich/AppData/Roaming/npm/eslint
(C:\Users\foellerich\AppData\Roaming\npm\eslint)
```
```
$ npm --version
2.11.2
$ node --version
v0.12.5
```

**Comment by iam4x** [comment]
Could you guys put: `console.log globalNpmPath`

https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L224
https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L230

And see if it goes in this condition:
https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L231

I can't reproduce it...

**Comment by msafi** [comment]
I added `console.log` at lines 225 and 232. Here's the results:

![Results](http://i.imgur.com/vWf6Uj8.png)

My global node modules are at `/usr/local/bin/`. I don't have a `/usr/local/node_modules`. My `Global node path` config is `/usr/local`.

The result of `npm config get prefix` for me is `/usr/local`

**Comment by iam4x** [comment]
Guys, tomorrow I will rewrite `linter-eslint` to match the CLI usage, we are using right now eslint programmatically and it's source of too many issues.

I'll leave this open until the rewrite is done.

**Comment by mattsawyer77** [comment]
So, I just reinstalled nvm completely (I had remnants of a homebrew nvm install plus the normal ~/.nvm install). Now I don't see the error, and linter-eslint is working for me.

**Comment by chriskrycho** [comment]
Quirky in the extreme. I’ll try that tomorrow or this weekend and see what it gives me.

**Comment by seanparmelee** [comment]
I was running this issue too, but then I realized that I didn't have anything entered in the "Global Node Path" setting. Once I set that to `/usr/local` (I'm on OS X 10.10.4) it started working again.

**Comment by iam4x** [comment]
Version 2.0 has been released now using CLI, please open a new issue if something is wrong.

**Comment by mattsawyer77** [comment]
Now it seems totally broken. It was working for me with the previous version, once I cleaned up my nvm install and reinstalled eslint globally. But now I'm getting these errors frequently again:
```
Local/Global ESLint binary not found. Fallback to packaged one. Set binary in preferences.
```
I have set my node path in the preferences, and as far as I can tell, it's correct.

along with these:
```
spawn ../node_modules/.bin/eslint ENOENT
Error: spawn ../node_modules/.bin/eslint ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
```

**Comment by iam4x** [comment]
@mattsawyer77 Can you prove a full path in the preferences? I should catch this error.

**Comment by mattsawyer77** [comment]
I did a hard uninstall of linter-eslint, cleaned out my eslint config, reinstalled it. Now I have `/Users/sawyer/.nvm/versions/node/v0.12.6/bin/eslint` set as the global eslint path. When I reload Atom, this is what I see in the console (filtering for "eslint"):
```
activate `linter-eslint`
linter-eslint.js:126 [Linter-ESLint] no output from CLI
linter-eslint.js:127 eslint binary: /Users/sawyer/.nvm/versions/node/v0.12.6/bin/eslint
linter-eslint.js:128 params: --stdin-filename web/framework/js/panels/directives/panelset.js --config web/.eslintrc --format /Users/sawyer/.atom/packages/linter-eslint/node_modules/eslint-json/json.js --stdin
linter-eslint.js:129 cwd: /home/sawyer/workspaces/sawyer-bigiq4.5.1/f5web/bigiq_ui
linter-eslint.js:126 [Linter-ESLint] no output from CLI
linter-eslint.js:127 eslint binary: /Users/sawyer/.nvm/versions/node/v0.12.6/bin/eslint
linter-eslint.js:128 params: --stdin-filename web/framework/js/panels/directives/panelset.js --config web/.eslintrc --format /Users/sawyer/.atom/packages/linter-eslint/node_modules/eslint-json/json.js --stdin
linter-eslint.js:129 cwd: /home/sawyer/workspaces/sawyer-bigiq4.5.1/f5web/bigiq_ui
```

**Comment by mattsawyer77** [comment]
Well I managed to get it working, though I'd consider it a bit of a workaround. I realized I had an out-of-sync .zshenv file with the wrong path to node. Once I fixed that, and put the node bin path in my $PATH, linter-eslint is working...

**Comment by msafi** [comment]
@mattsawyer77 So maybe even `eslint` CLI wasn't working before this last fix you applied, in which caused it would be understandable why `linter-eslint` didn't work...

**Comment by mattsawyer77** [comment]
It was working from the CLI, because I am loading up nvm in my .zshrc, but the path isn't explicitly set in .zshenv, and Atom didn't have the full PATH that is set via .zshrc.

**Comment by iam4x** [comment]
Guys we have an issue with Atom / Electron / OSX from running process from Atom. $PATH env is not set correctly. See: #149 

Just try to keep the discussion in one place.
