### ISSUE TITLE
atom-package-deps needs a bump

### ISSUE THREAD

**Issue by lierdakil** [AtomLinter/linter-eslint#1421]
## Issue Type

Bug

## Issue Description

atom-package-deps is pinned to 7.2.2 in package.json, which contains a bug. Should be bumped to 7.2.3 and rebuilt.

**Comment by aminya** [comment]
Fixed in https://github.com/AtomLinter/linter-eslint/commit/5db97221e16a8c1bafbd798650f0fd885d6d4a55
