### ISSUE TITLE
Option to point to Node executable

### ISSUE THREAD

**Issue by brettz9** [AtomLinter/linter-eslint#1437]
## Issue Type

Feature Request

## Issue Description

I'm running into problems with the Node version baked into the Electron version used by Atom being behind what my linting tools require. I assume this problem could occur for others and might continue to do so into the future especially for developers using the latest Node features.

It would be great if there could be an option to spawn a new Node process using an optionally supplied Node executable path (not for determining ESLint's location but for running the Node binary). Since you gather the Node location for another purpose, I suppose that same preference field could be reused for this purpose.

I also assume the results of a spawned process could be parsed as there is a JSON formatter: https://eslint.org/docs/user-guide/formatters/#json .

Thanks!

## Bug Checklist
- [ ] Restart Atom
- [ ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

**N/A**

```
Linter Eslint: Debug output here
```

**Comment by UziTech** [comment]
This is available in [linter-eslint-node](https://atom.io/packages/linter-eslint-node).
