### ISSUE TITLE
Linter messages not appearing when using NextJs extension in .eslintrc.json

### ISSUE THREAD

**Issue by robertsamarji** [AtomLinter/linter-eslint#1453]
## Issue Type
Question or bug

## Issue Description
I'm setting up a new Next JS project. When my eslintrc.json looks like the below, linting errors and warnings show up in the Atom editor without issue:

```
{
  "extends": "eslint:recommended"
}
```

However, when my eslintrc.json uses what NextJs recommend (as below), errors and warnings no longer show up in the Atom editor itself, but only appear in my terminal when I run `npm run lint`, which runs the linter.

```
{
  "extends": "next/core-web-vitals"
}
```

Does anyone know why this is and how to get the messages to appear in Atom editor itself?

FYI, when I open the same project in VS Code, the linting messages do appear. It's just in Atom that they don't.

## Bug Checklist
- [✓] Restart Atom
- [✓] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

**Comment by UziTech** [comment]
What version of eslint and plugins are you using?

**Comment by robertsamarji** [comment]
In the project:

"eslint": "8.5.0",
"eslint-config-next": "12.0.7"

Atom package linter-eslint 9.0.0

**Comment by hugentobler** [comment]
Same issue as Robert.

**Comment by UziTech** [comment]
For eslint v8+ you should use [linter-eslint-node](https://atom.io/packages/linter-eslint-node).
