### ISSUE TITLE
Bug: .ts and .tsx Issue with eslint 8.0.0 or above. Works fine with 7.32.0 or below. #15659

### ISSUE THREAD

**Issue by varunshekharrai** [AtomLinter/linter-eslint#1462]
## Issue Description
I have added source.ts and source.tsx in the list of scopes in linter-eslint. I expected the rules defined in the .eslintrc should work.
The errors were not being highlighted in the Atom ide. But if I downgrade the eslint version to 7.32.0 or below it works.

## Bug Checklist
- [Done] Restart Atom
- [Done] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [Done] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

## .eslintrc
```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
      "react/prop-types": 0,
      "no-prototype-builtins": 0,
      "@typescript-eslint/no-explicit-any": 0,
      "semi": [2, "never"],
      "@typescript-eslint/no-unused-vars": ["error"]
    }
}
```

## CLI of npx eslint
![image](https://user-images.githubusercontent.com/51792215/156188156-3d422b78-c0a9-4c19-ad80-28e935918efb.png)

## Atom IDE with eslint version 8.0.0 or above
![Screenshot from 2022-03-01 20-07-58](https://user-images.githubusercontent.com/51792215/156188888-fd166825-d881-4774-8f00-d482faa2870f.png)

## Atom IDE with eslint version 7.32.0 or below
![image](https://user-images.githubusercontent.com/51792215/156188290-c41193ee-01a0-4968-a66c-b39f58beed5c.png)

**Comment by UziTech** [comment]
See #1440
