### ISSUE TITLE
Fix on save has stopped working

### ISSUE THREAD

**Issue by jrj2211** [AtomLinter/linter-eslint#1465]
## Issue Type
Bug/Question

## Issue Description
I'm not sure if this is a problem in this package or because of linter/atom but within the last couple days my eslint has stopped fixing on save. I haven't touched my atom packages or eslint config in a very long time and it has been working. Looks like there was a new atom update 10 days ago, not sure when mine updated to it but possibly could be the cause of my problems.

It still shows me my errors and I'm able to hover it and click fix for each lint issue. Saving however will not auto fix the simple issues like formatting anymore.

![image](https://user-images.githubusercontent.com/6005836/159085825-f0486024-521f-46b1-8bfd-d4d5a97db179.png)

Fix errors on save is enabled:
![image](https://user-images.githubusercontent.com/6005836/159085880-58daf470-b897-4eff-8a66-c24003753d96.png)

Interestingly, using "fix" in the command palette does not work even though it says it ran successfully. Clicking each issue can fix it.
![image](https://user-images.githubusercontent.com/6005836/159086374-0428a7d5-701e-4b24-9902-f797020105d9.png)

Running eslint via command line fixes the file properly.
```eslint src/. app/. --fix```

Just curious if anyone else has seen this issue.

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.60.0
linter-eslint version: 9.0.0
ESLint version: 7.32.0
Hours since last Atom restart: 0.1
Platform: win32
Using local project ESLint from: C:\Users\Joe\projects\zyphox\mrp\node_modules\eslint
Current file's scopes: [
  "source.js",
  "punctuation.definition.function.body.begin.bracket.curly"
]
linter-eslint configuration: {
  "advanced": {
    "disableFSCache": true,
    "disableEslintIgnore": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  },
  "autofix": {
    "fixOnSave": true,
    "ignoreFixableRulesWhileTyping": true,
    "rulesToDisableWhileFixing": []
  },
  "disabling": {
    "disableWhenNoEslintConfig": true,
    "rulesToSilenceWhileTyping": []
  },
  "global": {
    "globalNodePath": "C:\\Users\\Joe\\AppData\\Roaming\\npm",
    "useGlobalEslint": true,
    "eslintrcPath": ""
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic"
  ],
  "lintHtmlFiles": false
}
```

**Comment by UziTech** [comment]
Fix on save works on this repo with Atom 1.60.0. If you clone this repo does fix on save work? If it does not I would say something is being overridden by one of your other settings in Atom.

**Comment by jrj2211** [comment]
This repo worked fine so I committed my code, deleted my project, and rechecked it out. Now everything works. Didn't change any of my configs or atom settings so I'm not sure what was wrong there. I'm curious if I had just opened a new window and added my project folder to it if that would have worked and something was getting messed up in the "atom project".

I'll close this comment as my issue is fixed and debugging what went wrong here is pretty much impossible now since I wiped my previous repo.

**Comment by nelson6e65** [comment]
In my case is working, but it takes like 10 minutes after save in order to fix errors or even the first check or if I edit the file is constantly _"ESLint runing on..."_:

![image](https://user-images.githubusercontent.com/9272498/162254557-d71d2077-254e-4e27-9e86-b25b3658c432.png)
