### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by lubuger** [AtomLinter/linter-eslint#1469]
## Issue Type

 Cannot find module

Running Atom-1.61.0-beta0 on Windows 10

## Issue Description

When opening developer console shows this error (error below)

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
C:\Users\windows\.atom\packages\linter-eslint\node_modules\underscore-plus\lib\underscore-plus.js'. Please verify that the package.json has a valid "main"
```

**Comment by UziTech** [comment]
What version of eslint?

**Comment by lubuger** [comment]
https://github.com/facebook/create-react-app

I guess it's 8.3...
