### ISSUE TITLE
Using eslint v8.x results in "Error while running ESLint: eslint.CLIEngine is not a constructor"

### ISSUE THREAD

**Issue by smoyte** [AtomLinter/linter-eslint#1480]
## Issue Type

Bug

## Issue Description

Using eslint v8.x results in "Error while running ESLint: eslint.CLIEngine is not a constructor"

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Error: eslint.CLIEngine is not a constructor
```

See this related issue: Error: [eslint.CLIEngine is not a constructor](https://github.com/eslint/eslint/issues/15175#issuecomment-944858897)

It seems some changes are needed to support eslint 8.x.

Thanks.

**Comment by UziTech** [comment]
Yes atom comes bundled with an old version of node that is incompatible with eslint v8. If you want to use v8 use [linter-eslint-node](https://github.com/AtomLinter/linter-eslint-node)
