### ISSUE TITLE
[2.3.0] error while parsing output

### ISSUE THREAD

**Issue by jeromemacias** [AtomLinter/linter-eslint#149]
![image](https://cloud.githubusercontent.com/assets/582446/8616931/721ebcfa-26ff-11e5-96f2-05870131462d.png)

My config:
![image](https://cloud.githubusercontent.com/assets/582446/8616977/b5be702c-26ff-11e5-9819-5dd1abfaeb4c.png)

Thanks.

**Comment by JulienWeiler** [comment]
+1

**Comment by iam4x** [comment]
I've released a new version catching empty output, it will print more information in the console for debugging. Could you provide me a new screenshot?

How do you start Atom?

**Comment by jeromemacias** [comment]
I launched Atom from Dock.

**Comment by JulienWeiler** [comment]
```
/Users/Julien/.atom/packages/linter-eslint/lib/linter-eslint.js:53 activate `linter-eslint`
index.js:56 Window load time: 2595ms
events.js:141 Uncaught Error: write EPIPE
/Users/Julien/.atom/packages/linter-eslint/lib/linter-eslint.js:136 [Linter-ESLint] no output from CLI
/Users/Julien/.atom/packages/linter-eslint/lib/linter-eslint.js:137 eslint binary: /Users/Julien/.atom/packages/linter-eslint/node_modules/.bin/eslint
/Users/Julien/.atom/packages/linter-eslint/lib/linter-eslint.js:138 params: --stdin-filename /path/to/project/app/server/app.js --config /path/to/project/app/.eslintrc --format /Users/Julien/.atom/packages/linter-eslint/node_modules/eslint-json/json.js --stdin
/Users/Julien/.atom/packages/linter-eslint/lib/linter-eslint.js:139 cwd: /Users/Julien/.atom/packages/linter-eslint/lib
```
Note: I replaced project folder with `/path/to/project/`

I launched Atom from Dock as well

**Comment by jeromemacias** [comment]
Here is the new screenshot:
![image](https://cloud.githubusercontent.com/assets/582446/8618230/63183d1e-270c-11e5-92dd-553fd136594e.png)

**Comment by jeromemacias** [comment]
Just trying to launch Atom from command line, in the project folder, it works fine.

**Comment by iam4x** [comment]
I'm trying to find the culprit, I think there's an issue with spawning child process when Atom isn't launched from CLI.

But I can't reproduce it myself so it's hard to debug!

**Comment by sebastiendavid** [comment]
Same here, when I launch Atom from OSX dock it does not work, but from terminal it works fine.

**Comment by jeromemacias** [comment]
Thanks for your reactivity @iam4x!
I think I (we ?) can deal with this issue by launching Atom from the command line unitl you find the culprit ;)

**Comment by JulienWeiler** [comment]
Yes, thanks @iam4x! Exact same behavior here. I will launch it via console as long as the bug exists.

**Comment by vramana** [comment]
Does anybody feels that linter is a bit less responsive or I am the only one?

**Comment by sebastiendavid** [comment]
@vramana yep I feels the same

**Comment by rosston** [comment]
@iam4x Not sure how much this will help, but:

I added an exit handler to the spawned child process within atom-linter/lib/helpers.coffee. When starting from the Dock in OS X, the exit code is 127, with no data from stdout. When starting Atom from the terminal, the exit code is 1, with proper results on stdout.

**Comment by MethodGrab** [comment]
I was getting the `EPIPE` error as well. Your "fallback eslint path" setting should be a *path* to your `bin` folder, not a link to the binary: `/usr/local/var/nvm/versions/io.js/v2.3.3/bin`.
The wording could be clearer!

**Comment by rosston** [comment]
I don't think this is just a matter of changing the "fallback eslint path". When opening Atom from the Dock in OS X, it fails with either the directory or full path. See full explanation below.

-

When launching Atom from the command line, linter-eslint works fine for me with the eslintPath setting set to either `/Users/ross/.nvm/v0.10.29/bin` or `/Users/ross/.nvm/v0.10.29/bin/eslint`.

When launching Atom from the Dock in OS X and the eslintPath is set to `/Users/ross/.nvm/v0.10.29/bin/eslint`, the only user-visible error is `[Linter-ESLint] no output provided by eslint, open console for more informations` `at line 1 col 1`.

When launching Atom from the Dock in OS X and the eslintPath is set to `/Users/ross/.nvm/v0.10.29/bin`, I get the following exception: 

![screen shot 2015-07-10 at 11 49 47 am](https://cloud.githubusercontent.com/assets/108518/8622506/dd1767d8-26f9-11e5-8fe0-86d123e8f91a.png)

**Comment by rosston** [comment]
This issue appears to be due to https://github.com/atom/atom/issues/6956.

If I change linter-eslint.js to set my `$PATH` to include the directory containing my `node` binary, everything works when opened from the Dock in OS X. So I think the breaking point here is that `/bin/sh` returns 127 after choking on the `/usr/bin/env node` at the top of the eslint binary.

**Comment by mnquintana** [comment]
This shouldn't depend on the value of `$PATH` though - it should default to using the binary that ships with the package (and is what it used to do).

**Comment by rosston** [comment]
I just removed my eslintPath to test this scenario. The package falls back to the packaged eslint binary like it should, but it still fails to actually run the eslint binary (when launched from the Dock in OS X).

The problem is that the `#!/usr/bin/env node` line of the eslint binary depends on the value of `$PATH`.

**Comment by MethodGrab** [comment]
Ah yes @rosston you are correct, I'm also getting the `spawn EACCES` errors now!

@iam4x, you might be able to reproduce this issue by only having node installed via `nvm` so it's not available from `/usr/bin/env`.

**Comment by framerate** [comment]
strange..

```
apm uninstall linter-eslint && apm install linter-eslint && atom ~/code/project-folder
```

and everything is fine again....

**Comment by wzxu** [comment]
@framerate Likely because you start Atom from CLI. When I do this it works and when I start Atom from Dock it doesn't.

**Comment by framerate** [comment]
@wzxu gotcha. Thanks.

**Comment by josebalius** [comment]
@vramana @sebastiendavid it feels slower for me as well, have you guys found a solution?

**Comment by vramana** [comment]
@josebalius Can you check what is your CPU usage is like ? My machine is bit old so the CPU usage hits 100% for sometime. I want to check if others also running into the same issue.

**Comment by sebastiendavid** [comment]
My CPU usage is quiet low during linting, maybe it's related with the new way the plugin call eslint (ESLint CLI tool instead of node module)

Otherwise about launching Atom from dock, add this in ```~/.atom/init.coffee```:

```
process.env.PATH = ["/usr/bin", "/usr/local/bin", process.env.PATH].join(":")
```

It works for me because I installed NodeJS with Brew, so NodeJS & global modules binaries are in ```/usr/local/bin```. If you installed Node with NVM, add the correct path (```~/.nvm/...```).

**Comment by iam4x** [comment]
I'll just link this issue to https://github.com/AtomLinter/Linter/issues/726

**Comment by nkt** [comment]
Is there way to create something like `eslint-server` keeping eslint in memory for faster validating?

**Comment by joseluisq** [comment]
@iam4x I hope team can find the solution :+1:

**Comment by declandewet** [comment]
I seem to be getting this same error regardless of what settings I use for both starting through the Dock and from the terminal...

**Comment by AlexKvazos** [comment]
@rosston Were you able to fix the EACCES path thing? I am using nvm and this was not happening before.

**Comment by rosston** [comment]
@AlexKvazos Assuming you're on OS X, and it's not some other issue, it should work fine if you launch Atom from the command line.

**Comment by AlexKvazos** [comment]
@rosston Oh wow! I wondered why it stopped working out of nowhere. Thank you so much, you saved me a big headache I've been having for days now. Is there an open issue regarding this? I don't see why packages should only work when opening atom from the CLI.

**Comment by rosston** [comment]
@AlexKvazos This is the open issue. https://github.com/AtomLinter/linter-eslint/issues/160, https://github.com/AtomLinter/Linter/issues/726, and https://github.com/atom/atom/issues/6956 are all related, as well.

**Comment by AlexKvazos** [comment]
@rosston Setting the path in the init script sounds like a good way of allowing eslint to work even if we open atom from the dock or app folder https://github.com/AtomLinter/Linter/issues/726#issuecomment-120666636

**Comment by josebalius** [comment]
@vramana @sebastiendavid @iam4x CPU usage for me is low as well, I think like @iam4x said the linter is just slower with the new method of starting the eslint process.

Any ideas what we can do to improve this @iam4x or is it something we'll have to live with? Open to helping in any way i can.

**Comment by mnquintana** [comment]
I'm not quite sure I follow - @iam4x what was the motivation for moving away from using ESLint's API directly and towards spawning a child process? I don't think I quite understand why this change was needed.

**Comment by liyaodong** [comment]
why not set fixed `path` ?

plugin setting panel,  set **Eslint Path** to `/usr/local/bin/eslint`, works for me .

**Comment by iam4x** [comment]
I've pushed a new version that would be using the `node` packaged into Atom to run `eslint`, it should fixes the issue. Can I have confirmation?

**Comment by johngeorgewright** [comment]
Adding the following to my init script seems to fix this issue:

```coffee
childProcess = require('child_process');

process.env.PATH = String(
  childProcess.execFileSync(\
    process.env.SHELL,
    ['-c', 'source $HOME/.bash_profile; echo $PATH']
  )
).trim()
```

**Comment by andykenward** [comment]
@iam4x i having issue with using eslint-plugin-react

`Error: Cannot find module 'eslint-plugin-react'`

**Comment by MoOx** [comment]
It seems Atom is messing with the PATH (related https://github.com/webBoxio/atom-term2/issues/50) or something...

It also seems most people that pasted stacktrace or some path are using nvm to use node/iojs. Might be a clue.

**Comment by rosston** [comment]
@iam4x Confirmed, 2.4.2 fixes the `$PATH` issue. Thanks!

**Comment by iam4x** [comment]
@MoOx Yes, since `eslint` is node executable it cannot run without `node` in path.

**Comment by andykenward** [comment]
updated to 2.4.3 now get no errors. But no longer linting for me. -1:

**Comment by djindjic** [comment]
I also have this issue, there is red or yellow underlines added by linter-eslint, but for messages I need to run CLI. Is there some new config to enable error message labeling?

**Comment by polarathene** [comment]
I'm no longer getting errors, just the warning about not having a local/global eslint falling back to package :) Is there no rules being used by default now? I've yet to try a adding config file.

**Comment by globexdesigns** [comment]
Still having issues in 2.4.3 on OSX. Seeing this warning message:

```
[Linter-ESLint] Local/Global ESLint binary not found. Fallback to packaged one. Set binary in preferences.
```

The console reads:

```
Uncaught Error: write EPIPE
[Linter-ESLint] no output from CLI
linter-eslint.js:127 eslint binary: /Users/me/.atom/packages/linter-eslint/node_modules/.bin/eslint
linter-eslint.js:128 params: --stdin-filename /Users/me/Git/ux/html/js/main.js --config /Users/me/Git/ux/.eslintrc --format /Users/me/.atom/packages/linter-eslint/node_modules/eslint-json/json.js --stdin
linter-eslint.js:129 cwd: /Users/me/.atom/packages/linter-eslint/lib
```

**Comment by genexp** [comment]
Having the same issue

**Comment by framerate** [comment]
I tried to APM the 1.X branch and it seems broken for me as well.

Anyone have a work around so I'm not writing shitty code this week?

**Comment by rosston** [comment]
@framerate `apm install linter-eslint@1.0.18` worked for me.

**Comment by framerate** [comment]
@rosston thanks. I managed to fix it by manually setting the path to my `node_modules/eslint/bin` folder, apparently. But I swear I tried that before so now I'm just not going to touch anything...

**Comment by andykenward** [comment]
@rosston @framerate both of those fixed it for me. Just had to reload atom after applying them. Thank you!

**Comment by jeromemacias** [comment]
It now works, thanks @iam4x

**Comment by djindjic** [comment]
@jeromemacias , I still can't see eslint error/warn messages in atom status bar (as it was before few linter-eslint releases), does it related to this issue or I need to open new one?

**Comment by JulienWeiler** [comment]
Same for me. Still working when launching atom via console. (But then linting while editing the file isn't working, only on save)

**Comment by jeromemacias** [comment]
Good catch, I can't see issues on the status bar, both launching Atom on dock or by CLI, don't know if it's related to `linter-eslint` or base `linter` package.
And "linting while editing" option has no effect.

I think we should open new issues.

**Comment by declandewet** [comment]
eslint works now, but I do have an issue where some rules aren't mapping to the correct values in `.eslintrc` - for example, if I have `curly` set to warn me if there are no curly braces, but I have enabled the `multi-line` option, this code triggers the rule, when it should not:

```js
if (condition)
  console.log('something')
```

I *am* using YAML in my .eslintrc, so that might have something to do with it...

**Comment by ochervak** [comment]
have the same issue
