### ISSUE TITLE
Persistent Error Notifications

### ISSUE THREAD

**Issue by jacobp100** [AtomLinter/linter-eslint#157]
```
[Linter-ESLint] Local/Global ESLint binary not found. Fallback to packaged one. Set binary in preferences.
```

I have eslint installed: the latest update appears to have caused this.

Using Atom 1.0.2 on OS X 10.10.4 and eslint 0.24.1

**Comment by qubyte** [comment]
Seeing the same issue. The console shows the error:

`Uncaught Error: write EPIPE` at `events.js:141`

**Comment by globexdesigns** [comment]
+ 1

**Comment by ascariandrea** [comment]
+1

**Comment by iam4x** [comment]
This is related to #149 let's keep the discussion in one place.
