### ISSUE TITLE
Allow setting of file extension (.jsx)

### ISSUE THREAD

**Issue by ludovico** [AtomLinter/linter-eslint#158]
I am using eslint for both .js and .jsx (react) files. I may be wrong, but I can't see anywhere to add
extra file extensions to the settings. Am I missing something? I would be happy to implement it myself if it as actually missing, but I thought it better to ask here first.

**Comment by ludovico** [comment]
I just added a pull request for it, simple as it is.

**Comment by iam4x** [comment]
`.jsx` should be linted too, I'm using `source.js.jsx` to recognize the file syntax and process them into `eslint`

Do you have `react` or `babel` package installed into Atom?

**Comment by ludovico** [comment]
I tried to go back to the official version and try it now, but I am having some trouble with it (unrelated). I am sure you are right and that the problem is on my end, even though I did have `react` installed. But I still think that it would be nice to be able to specify file extensions without any extra packages, if it doesn't slow the linting down too much.

**Comment by iam4x** [comment]
I've rollbacked linter to 1.x with the 3.0.0 version published. Please open a new issue if it's still happening.

Make sure to quit Atom and `$ apm uninstall linter-eslint && apm install linter-eslint`.
