### ISSUE TITLE
Use JS instead of CLI for linting?

### ISSUE THREAD

**Issue by rosston** [AtomLinter/linter-eslint#160]
I'm not trying to be a pain. :) Just creating this issue to throw the idea out there. Feel free to close it if I'm way off base.

I know the package was only just switched to use the CLI in 2.0, and that it was done for maintenance reasons—via https://github.com/AtomLinter/linter-eslint/issues/149#issuecomment-120545807.

But, the `$PATH` issue (https://github.com/AtomLinter/Linter/issues/726 and https://github.com/atom/atom/issues/6956) doesn't seem to have an easy solution. And the CLI will always be significantly slower than using JS directly since a new `node` process needs to be started up every time the linter runs.

Using ESLint as a JS lib solves both of those issues, but I guess I don't know just how bad the maintenance of that would be.

**Comment by AlexKvazos** [comment]
+1

**Comment by johanneslumpe** [comment]
I haven't followed the project very much, so I cannot really comment on the maintenance part. But I do have to say, that after the recent upgrade the linter became painfully slow. Prior to the update it would lint in real-time. Now it can take 5+ seconds for it to update the screen with errors etc.

**Comment by marudor** [comment]
I can confirm that. I did downgrade back to 1.0.18 for that reason.

**Comment by vkbansal** [comment]
I too am switching back to `1.x`.

**Comment by astephenb** [comment]
:+1: I have noticed a decrease in performance as well.

**Comment by clintwood** [comment]
+1

**Comment by iam4x** [comment]
I'm with you guys, though this could have been a good idea that we discussed with the team (cc @AsaAyers).

The best way to achieve this, is to add an option on how to use the linter (CLI or programatically).

**Comment by AsaAyers** [comment]
@iam4x What do you think about opening an issue in [eslint](https://github.com/eslint/eslint/issues) asking for advice?

It seemed to me like the CLI does a bunch of work that had to be duplicated, finding/parsing the config, locating plugins to `require()`, adding all the plugins to the Engine before executing lint. I think going back to programmatic access might only be worth the maintenance effort if we can push all this work back into eslint.

**Comment by AsaAyers** [comment]
@marudor @vkbansal If you downgraded you should notice you're getting a deprecation warning. `linter` will be removing the code to support the old linters, so I expect downgrading to only work for a few more weeks.

**Comment by iam4x** [comment]
@AsaAyers I was looking at @MoOx https://github.com/MoOx/eslint-loader/blob/master/index.js he doesn't have to deal with parsing config and everything, it works out of the box.

It's more Atom specific that the process is ran from somewhere else than the project, not sure we should open an issue on `eslint`.

**Comment by AsaAyers** [comment]
@iam4x `require('eslint').cli` [exists](https://github.com/eslint/eslint/blob/master/lib/api.js#L10). It looks like you could make up a fake `process.argv` and run `exitCode = cli.execute(fakeArgv);` except I don't see how you would capture the output.

**Comment by iam4x** [comment]
@AsaAyers https://github.com/eslint/eslint/blob/master/lib%2Fcli.js#L149

**Comment by rosston** [comment]
If you used the `cli` module, you could just add an `outputFile` to the options to get the results out, right?

Not sure how helpful it is, but both [gulp-eslint](https://github.com/adametry/gulp-eslint/blob/master/index.js#L15) and [grunt-eslint](https://github.com/sindresorhus/grunt-eslint/blob/master/tasks/eslint.js#L46) use the `CLIEngine` module (which I know linter-eslint was using before).

**Comment by clintwood** [comment]
@rosston, `cli` is a deprecated according to [this doc](https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md#deprecated-apis).
@iam4x, there is also a `nodejs-api` in [this doc](https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md).

**Comment by iam4x** [comment]
I've rollbacked linter to 1.x with the 3.0.0 version published. Please open a new issue if it's still happening.

Make sure to quit Atom and `$ apm uninstall linter-eslint && apm install linter-eslint`.

**Comment by clintwood** [comment]
Awesome!  Will give it a try. Thank you.

**Comment by clintwood** [comment]
@iam4x, Working great for me on Windows using global ESLint, nice and responsive... Thanks!
