### ISSUE TITLE
How to debug this error?

### ISSUE THREAD

**Issue by AlexKvazos** [AtomLinter/linter-eslint#161]
For some reason, the package can not get output from the eslint on my system. I am getting the following error on Atom 1.0.2.

![](https://i.alexkvazos.me/init_js_-__Users_alexkvazos_Documents_Projects_CubedHost_Prisma-Daemon_-_Atom_1B52C6DD.png)

**Comment by AlexKvazos** [comment]
*UPDATE*

I was able to properly point to my node bin path but now I get an `EACCES` error.

![](https://i.alexkvazos.me/init_js_-__Users_alexkvazos_Documents_Projects_CubedHost_Prisma-Daemon_-_Atom_1B52CA29.png)

**Comment by iam4x** [comment]
It's related to #149 let's keep the discussion in one place.
