### ISSUE TITLE
How to configure Global Node Path?

### ISSUE THREAD

**Issue by montogeek** [AtomLinter/linter-eslint#163]
Since 2 versions ago I keep getting this error.
It was working just fine 2 versions ago.

How should I configure the Global Node Path?

![screen shot 2015-07-13 at 15 02 04](https://cloud.githubusercontent.com/assets/1002461/8659383/2995d0b8-2970-11e5-8a87-7929abc90a7d.png)

Thanks!

**Comment by iam4x** [comment]
Related to #149 let's keep the discussion in one place.
