### ISSUE TITLE
disableWhenNoEslintrcFileInPath unexpected behaviour

### ISSUE THREAD

**Issue by johngeorgewright** [AtomLinter/linter-eslint#164]
Hey,

Looks like if you have an `.eslintrc` file in the project's parent directory, the `disableWhenNoEslintrcFilePath` configuration still doesn't disable linting.

**Comment by johngeorgewright** [comment]
Actually, looks like a problem with Mac. Using the following in my init script seems to fix the problem:

```coffee
childProcess = require('child_process');

process.env.PATH = String(
  childProcess.execFileSync(\
    process.env.SHELL,
    ['-c', 'source $HOME/.bash_profile; echo $PATH']
  )
).trim()
```

Found this mentioned [in another linter issue](https://github.com/AtomLinter/Linter/issues/726). It also fixes the errors mentioned [in another issue of yours currently open](https://github.com/AtomLinter/linter-eslint/issues/149).

**Comment by johngeorgewright** [comment]
I spoke too soon... that didn't fix this issue. But it does seem to fix #149.

**Comment by keirlawson** [comment]
I am experiencing the same issue on Fedora, using Atom 1.0.2

**Comment by iam4x** [comment]
I've rollbacked linter to 1.x with the 3.0.0 version published. Please open a new issue if it's still happening.

Make sure to quit Atom and `$ apm uninstall linter-eslint && apm install linter-eslint`.
