### ISSUE TITLE
"Lint on fly" not happening after update from 2.4.1 -> 2.4.3

### ISSUE THREAD

**Issue by bjmiller** [AtomLinter/linter-eslint#166]
I'm not sure what happened, but now I'm only getting message changes when I save, and not as I type.  This is despite the fact that I have lintOnFly set to `true`, and lintOnSave set to `false`.

What could have happened?  There was no update to Linter core preceding this change, only to linter-eslint.

**Comment by brianblakely** [comment]
Linting doesn't take place for me at all since the 2.4.3 update.

**Comment by 0x2206** [comment]
Just confirming that linting stopped working for me in 2.4.3 as well. But it's happening only when eslint is installed as a local dependency. When I remove it and linter-eslint uses inbuilt eslint, linting works again.

**Comment by sebastiendavid** [comment]
+1 For me the plugin lint on save, "lint on fly" does not work anymore.

**Comment by hugihlynsson** [comment]
+1. It only lints on save even if `Lint On Edit` is checked

**Comment by PhilippBaschke** [comment]
+1. It only lints on save.

**Comment by ChuckPierce** [comment]
yea I don't know what you did.  My linter is not working at all now with the latest update.  its not doing it on save, its not working when I uninstall the local eslint dependency...not sure what you did but  its not working at all now.  Might have to move back to sublime because of this change and I don't want to

**Comment by jscissr** [comment]
+1. For me it doesn't even lint on save.

**Comment by ChuckPierce** [comment]
I'll continue to follow this and maybe when I have time checkout out to see what's wrong but I've moved back to a release that works for now

**Comment by MoOx** [comment]
Linting doesn't take place for me neither.

**Comment by iam4x** [comment]
I've rollbacked linter to 1.x with the 3.0.0 version published. Please open a new issue if it's still happening.

Make sure to quit Atom and `$ apm uninstall linter-eslint && apm install linter-eslint`.

**Comment by sebastiendavid** [comment]
@iam4x Thanks it works fine and it's more responsive like before v2.

**Comment by 0x2206** [comment]
@iam4x Works again. Many thanks!

**Comment by ChuckPierce** [comment]
@iam4x yea good call on the change back to linter 1.x everything is fine and dandy.  Thanks again
