### ISSUE TITLE
Significant Performance Drop in 2.4.1

### ISSUE THREAD

**Issue by damassi** [AtomLinter/linter-eslint#167]
After installing the latest version I'm experiencing a significant performance drop in use.  Where every save (and bit of feedback) used to be instant, now there is often a 1 second lag.  Willing to provide more details if necessary, but curious if this is to be expected?

**Comment by PhilippBaschke** [comment]
I am experiencing the same with **CPU spikes (100% load)**. Editing becomes painfully slow. Disabled eslint and everything works fine again.

**Comment by iam4x** [comment]
I've rollbacked linter to 1.x with the 3.0.0 version published. Please open a new issue if it's still happening.

Make sure to quit Atom and `$ apm uninstall linter-eslint && apm install linter-eslint`.

**Comment by damassi** [comment]
@iam4x - Thanks so much for rolling back -- everything is super snappy again like it was before.
