### ISSUE TITLE
Different results to command line

### ISSUE THREAD

**Issue by johngeorgewright** [AtomLinter/linter-eslint#175]
I can't understand where I'm going wrong here... but if I use the eslint directly I get different results to when I use it in atom. It's obviously using a different eslint version or a different configuration file, but from where?

The below image is pretty poor, but what I'm trying to prove is that the terminal on the right can't find any errors, yet linter-eslint doesn't want me to use any es6 features. It's telling me "(use esnext option)"... I cannot find that option documented anywhere and if I try putting it somewhere in my config it makes no difference.

![eslint](https://cloud.githubusercontent.com/assets/1423566/8847345/ca7f1e14-3125-11e5-9c1d-78ef900836cc.jpg)

![linter-eslint](https://cloud.githubusercontent.com/assets/1423566/8847499/1dd82ab4-3127-11e5-952a-250e13b9115e.png)

![linter-eslint-settings](https://cloud.githubusercontent.com/assets/1423566/8847505/24de5bb2-3127-11e5-9b62-610ec09317d0.png)

Here's a closer look at my `.eslintrc`:

```js
{
    "rules": {
        "indent": [
            2,
            4
        ],
        "quotes": [
            2,
            "single"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ]
    },
    "env": {
        "es6": true,
        "node": true
    },
    "ecmaFeatures": {
        "modules": true
    }
}
```

Any idea what's going on here?

**Comment by PhilippBaschke** [comment]
Are you sure that these warnings do not come from **JsHint**?
See: https://github.com/AtomLinter/linter-eslint/issues/174

**Comment by johngeorgewright** [comment]
Ha. Sorry, you're very right. I still have a JSHint plugin installed. Doh!
