### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by mnquintana** [AtomLinter/linter-eslint#176]
There has been quite a lot of user pain felt over the last several releases because of regressions and new bugs introduced from at least one rewrite. Would you mind adding a test suite for this package? As a user it can be extremely confusing and frustrating when updates seem to break more things than they resolve. Thanks!

**Comment by pitaj** [comment]
This is a good thing for *any* and *every* project *ever* to include.

**Comment by Arcanemagus** [comment]
Started here: https://github.com/AtomLinter/linter-eslint/pull/310

**Comment by Arcanemagus** [comment]
The rest will be in here: https://github.com/AtomLinter/linter-eslint/pull/312
