### ISSUE TITLE
Linter produces duplicate warnings about `eslint` binary not being available locally per-project

### ISSUE THREAD

**Issue by adammw** [AtomLinter/linter-eslint#178]
![screen shot 2015-07-25 at 10 57 11 pm](https://cloud.githubusercontent.com/assets/153219/8889514/8f45eda8-3320-11e5-96f4-5d85ee70a49e.png)

Really only need to see one warning (if at all), rather than have a new one after each keypress.

**Comment by Globegitter** [comment]
Yep agree. Another great option would be to have `fall back to global eslint`. Or `prefer local eslint`. So when it finds a local eslint install it takes that and if not it silently falls back to global. That would be amazing if that was supported.

**Comment by ide** [comment]
Anyone want to submit a PR for this? It shouldn't be too hard to limit the message to show once per project each time Atom is launched.

**Comment by mehcode** [comment]
> Yep agree. Another great option would be to have fall back to global eslint. Or prefer local eslint.

Huge :+1: to this.

**Comment by iam4x** [comment]
fixed with dd757b1849ac521ea6f0aa167f1911eaa821c771
