### ISSUE TITLE
Error every time it gets updated

### ISSUE THREAD

**Issue by montogeek** [AtomLinter/linter-eslint#181]
Hi! I get this Atom error every time the package is updated
![screen shot 2015-07-28 at 13 39 43](https://cloud.githubusercontent.com/assets/1002461/8940184/22c1177e-352e-11e5-8041-e431dbc2fa88.png)

Should I restart Atom or something?

Thanks!

**Comment by ide** [comment]
Try reloading Atom with Ctrl+Option+Cmd + L. If you still get the error, look in the console with Option+Cmd + I.

**Comment by steelbrain** [comment]
Fixed by v5.0.0
