### ISSUE TITLE
Make warnings passive

### ISSUE THREAD

**Issue by ChuckPierce** [AtomLinter/linter-eslint#190]
Is there anything on the road map for getting in an option to make warnings passive? Legacy code gets riddled with warnings with my new eslint config.  It would be great if there was a passive warnings option just like SublimeLinter.

If its not on the roadmap then I might have to switch back to sublime.

Thanks!

**Comment by pitaj** [comment]
What do you mean by *passive*?

I'd like an option to *ignore* certain warnings and errors on a case-by-case basis.

**Comment by ChuckPierce** [comment]
Yea I guess I meant toggling the ability to ignore errors within the linter itself.  I have to use preset rules in the organization I am currently working for and there are a lot of ES6 warnings that I would like to turn off when I'm working with legacy code.  Sublimelinter has a great way of turning them off by using CLI arguments as an option in the linter settings

**Comment by steelbrain** [comment]
We have an option to disable any type of errors in the settings of base linter
