### ISSUE TITLE
eslint not linting in one project but is in another

### ISSUE THREAD

**Issue by Robert-W** [AtomLinter/linter-eslint#191]
So Im not really even sure the best way to explain this or if this is even related to you guys, I guess I'm kind of hoping there is a trick to reset this or something.  The issue Im having is I am using linter-eslint in one project and everything works as expected.  I tried adding it to another project and got the error local eslint not found, so I installed it and it started 'sort of' working.  It works but it is missing tons of errors.  It doesn't catch trailing commas or spaces, missing semicolons, plus tons more.  Not sure why or what could be the cause.  I am using the same eslint version and .eslintrc as the project that works fine.  I have tried the following and cannot get it to work.

Tried deleting the project and re-cloning from github and reinstalling all node modules.
Tried deleting and reinstalling eslint.
Tried disabling and re-enabling linter-eslint in atom.
Tried uninstalling and reinstalling linter-eslint.
Tried different versions of eslint.
Tried restarting my laptop and Atom.

Have you guys seen this happen before or know what the culprit might be?  I don't think it's eslint since the same version works in another project but not sure if this could be an atom issue that I need to file with them.

**Comment by hasssan** [comment]
I've same problem with you. One of my project which linter working use "eslint": "0.24.1". So I downgrade it and it's working now.

**Comment by IanVS** [comment]
Please note that in ESLint version 1.x, there are no rules enabled by default.  If you were relying on the ESLint defaults in `0.24`, those should be explicitly set in your project's `.eslintrc` now.  See http://eslint.org/docs/user-guide/migrating-to-1.0.0 for more information.

**Comment by hasssan** [comment]
@IanVS my bad, after adding recommendation from the docs, now everything works again. Thanks.

**Comment by Robert-W** [comment]
Hey thanks @IanVS, I stumbled across that a little while back and that got things back, I forgot about this post otherwise I would have came back sooner and posted something.  The thing that was confusing me was that when I use the Global eslint option, even though Global is 1.3.1, it seemed to lint like it did with 0.24 but when I used the same version locally it did not unless I added all the rules back that I wanted.  Not really an issue anymore though as I am now using it locally for all my projects.

**Comment by IanVS** [comment]
I've heard that the "use global" option doesn't quite work, but I haven't tried it.

**Comment by Robert-W** [comment]
Ah ok, good to know.  I am using the local versions now so its not an issue for me anymore. Thanks again.

**Comment by Arcanemagus** [comment]
Marking this as closed since it was initially a configuration issue and the linter has went through a major re-write since it was filed :wink:.
