### ISSUE TITLE
Feature Request: option to ignore any files in node_modules

### ISSUE THREAD

**Issue by zyklus** [AtomLinter/linter-eslint#192]
If you run eslint on a directory, it ignores `node_modules` by default.  Unfortunately if you tell it to _explicitly_ lint a file in `node_modules`, it will.  So when I often go digging into a module to see how something works, half my screen gets filled with linter errors/warnings.

I'd like to suggest an option that simply turns off the plugin for files that match `**/node_modules/**/*.js`, as I don't really care to see linter errors on code that isn't mine :)

Note that this can't be easily solved with an `.eslintignore` file since I'd basically need to put a copy of a baseline "ignore node_modules" instance of that file in _every_ project.  I could put it in a root folder, e.g. `~`, but since eslint only takes _one_ `.eslintignore` file, that means the issue persists everywhere I already have an `.eslintignore` file.

**Comment by Arcanemagus** [comment]
This has been fixed in the core `linter` package with the "Do Not Lint Files Ignored by VCS" option.
