### ISSUE TITLE
Lint within <script> tags in HTML files

### ISSUE THREAD

**Issue by klebba** [AtomLinter/linter-eslint#194]
Plugins like this: https://github.com/BenoitZugmeyer/eslint-plugin-html won't work because linter-eslint ignores html files.

linter-jshint recently added this feature by modifying grammarScopes: https://github.com/AtomLinter/linter-jshint/issues/106

**Comment by pitaj** [comment]
:+1:

**Comment by pitaj** [comment]
ref #104

**Comment by iam4x** [comment]
@klebba This is an easy PR could you do it to support HTML?

**Comment by klebba** [comment]
@iam4x I wish I could but I'm on a deadline; it will be a while until I could actually get to it. Sorry I can't be of more help right now!

**Comment by mehwww** [comment]
It seems that [linter](http://eslint.org/docs/developer-guide/nodejs-api.html#linter) wont work properly with plugins, so I create a PR use [executeOnText](http://eslint.org/docs/developer-guide/nodejs-api.html#executeontext) instead and extend grammarScopes make it work with HTML files

**Comment by klebba** [comment]
@mehwww thanks!
