### ISSUE TITLE
Working with eslint over networked drive/sshfs

### ISSUE THREAD

**Issue by mrapogee** [AtomLinter/linter-eslint#195]
Hey,

Looking for some help from someone who knows the project.  When I have eslint enabled when working on a networked drive, linter-eslint freezes atom every time it tries to lint the file. I imagine this is because some file operation is happening(since the connection is remote, the file operations are very slow). Do you know what could be going on here?

**Comment by Arcanemagus** [comment]
As of v5.0.0 linting is no longer happening on the render thread, so this should no longer freeze up everything, although linting may take a while based on file access. If you are still seeing lockups after updating to v5.0.0 please reopen the issue.
