### ISSUE TITLE
linter-eslint throws errors even though there's no .eslintrc file in the project

### ISSUE THREAD

**Issue by szimek** [AtomLinter/linter-eslint#201]
I've got "Disable When No Eslintrc File In Path" option checked, but when I open a project without `.eslintrc` file, I'm still getting the following errors:
```
[Linter-ESLint] eslint binary not found locally, falling back to packaged one. Plugins won't be loaded and linting will possibly not work. (Try Use Global ESLint option, or install locally eslint to your project.)
[Linter-ESLint] plugin react not found
```

**Comment by frosas** [comment]
@szimek is there any `.eslintrc` in any parent directory up to the root of the file system.

**Comment by szimek** [comment]
@frosas Uh... I completely forgot about `.eslintrc` I had in my user's directory after testing `linter-eslint` with global `eslint` package... Thanks!
