### ISSUE TITLE
Update to ESLint 1.0.0

### ISSUE THREAD

**Issue by IanVS** [AtomLinter/linter-eslint#205]
The title says it all.  Will you consider releasing a new major version which uses the latest ESLint version?

**Comment by silvenon** [comment]
It works for me, just update the eslint module.

**Comment by IanVS** [comment]
Yes, it works, but it's a breaking change.  See http://eslint.org/docs/user-guide/migrating-to-1.0.0.

**Comment by willpracht** [comment]
If I "Use Global eslint", does this version matter?

**Comment by MadLittleMods** [comment]
:+1:

**Comment by SpainTrain** [comment]
I do not see a compelling reason not to.  Thoughts @steelbrain @Arcanemagus @iam4x ?

**Comment by steelbrain** [comment]
@SpainTrain You have my :+1:

**Comment by Arcanemagus** [comment]
Just a heads up, this is already in https://github.com/AtomLinter/linter-eslint/pull/197, which will probably be merged soon pending (lots of) testing.

**Comment by SpainTrain** [comment]
Ah good point.

**Comment by iam4x** [comment]
Closed with https://github.com/AtomLinter/linter-eslint/releases/tag/v3.2.0

**Comment by IanVS** [comment]
Since this was a breaking change of ESLint version, shouldn't the version of this package have been incremented to `4.0.0`?

**Comment by willpracht** [comment]
Sure, I'll +1.

**Comment by Arcanemagus** [comment]
Makes sense to me, any objections @iam4x, @steelbrain?

**Comment by steelbrain** [comment]
I already gave my opinion in [comment above](#issuecomment-151667458)

**Comment by IanVS** [comment]
I guess what I'm saying is that the upgrade snuck in with  #197, when really the change to ESLint 1.x should have brought with it a major version bump in this package as well.  I don't know what the best way forward is from here.

Or, it's entirely possible I don't fully grasp the implications of semver.

**Comment by Arcanemagus** [comment]
Well, it's a tricky one, this package all by itself would be a minor update, but since it can utilize external `eslint` instances the removal of support for <1.0.0 would be considered a breaking change in my book, thus I agree with you that this should be a major version bump.

**Comment by Arcanemagus** [comment]
Tagged v4.0.0 :wink:
