### ISSUE TITLE
ESLint config file detection does not work accross multiple Atom windows

### ISSUE THREAD

**Issue by keirlawson** [AtomLinter/linter-eslint#209]
Often I will have multiple projects open in different Atom windows, some with ESLint and some using other linters or no linting at all.  I have the eslint plugin set up to only activate when an eslint config file is detected however even when a config file is only detected in one project in one window, ESLint seems to then be turned on in all windows which is a bit counter-intuitive.

**Comment by Arcanemagus** [comment]
This should be on a per-file basis, if you still see this after updating to v5.0.0 please reopen the issue.
