### ISSUE TITLE
Use local version if available

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-eslint#21]
Since -g should be avoided for node modules, I always install every tool I use on each project. So I've eslint for each project. Would be nice if that the linter-* can use local version if available (in /node_modules/eslint in this case).

That would allow for example to test new version like current @es6jsx branch :)

**Comment by nelix** [comment]
Would it be possible to check the current projects package.json and then spawn the current projects ./node_modules/eslint in a new process? (I assume you can't just require it directly)
This way we could have customer plugins and be in line with the projects intended eslint version, it would also make updating eslint versions easier?

**Comment by jfaissolle** [comment]
Yes, it is the only solution I see at the moment. See my comment in #26 which is related to this issue.
