### ISSUE TITLE
Error: cannot read config file

### ISSUE THREAD

**Issue by tnguyen14** [AtomLinter/linter-eslint#213]
I use [`esling-config-defaults`](https://github.com/walmartlabs/eslint-config-defaults), but get this error
```
Error: Cannot read config file: ../rules/eslint/variables/eslint.js
Error: ENOENT: no such file or directory, open '../rules/eslint/variables/eslint.js'
Referenced from: defaults
Referenced from: path/to/project/.eslintrc
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
...
```

**Comment by chaseadamsio** [comment]
@tnguyen14 what version of `eslint-config-defaults` are you using? Also, do you have a specific `.eslintrc` in your root and if so, can you share it?

**Comment by tnguyen14** [comment]
hey @chaseadamsio, I use the latest version, so `6.0.0`.

It looks something like this:

```js
{
  "extends": "defaults",
  "rules": {
    "indent": [2, "tab"]
  }
}
```

**Comment by mendlik** [comment]
I have the same problem. My `.eslintrc`:

```js
{
	"extends": "defaults",
	"env": {
		"node": true
	},
	"rules": {
		"strict": [2, "global"]
	}
}
```

**Comment by tnguyen14** [comment]
@mendlik interesting, because the console worked for me.

**Comment by mendlik** [comment]
@tnguyen14 Let's compare some details

```js
$ eslint -v
v1.5.1
$ cat node_modules/eslint-config-defaults/package.json | grep 'version'
  "version": "6.0.0",
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by tnguyen14** [comment]
@mendlik I just double checked, and the command line is throwing me an error too. However, it's slightly different from Atom's error

```
/usr/local/lib/node_modules/eslint/lib/config.js:209
                    throw e;
                    ^

Error: Cannot find module 'eslint-config-defaults'
```

**Comment by mendlik** [comment]
@tnguyen14 When using console you're using global `eslint`. Make sure you have installed `eslint-config-defaults` globally as well.

```bash
sudo npm install -g eslint-config-defaults
```

**Comment by mendlik** [comment]
As a quick fix I recommend using `eslint:recommended`.

```js
{
	"root": true,
	"extends": "eslint:recommended",
	"env": {
		"node": true
	},
	"rules": {
		"strict": [2, "global"]
	}
}
```

**Comment by tnguyen14** [comment]
@mendlik you're right, I removed the global `eslint` and use the local one instead. I got the same error on the command line as in atom as described in my original post to this issue.

**Comment by ryan-roemer** [comment]
@tnguyen14 @mendlik -- Can one of you give me a tight reproduction of the issue with a bash command that exposes the issue?

For a random smattering of thoughts:

* I forget why, but I seem to remember something about having a project-root level `.eslintrc` mucking with things. Maybe try renaming the file to anything besides `.eslintrc`?
* Which configurations are you actually trying to use? For example `"defaults/configurations/walmart/es6-react"`, etc.?

**Comment by tnguyen14** [comment]
@ryan-roemer sure, something like this:

```sh
:; mkdir test-eslint && cd test-eslint
:; npm install eslint eslint-config-defaults
:; vim .eslintrc
:; vim index.js
:; eslint .
```

The content of `.eslintrc` is just:
```js
{
  "extends": "defaults"
}
```

I just tried these steps and get that error. As @mendlik pointed out, this might just be an issue with the `eslint-config-defaults` project, not this one.

**Comment by ryan-roemer** [comment]
@tnguyen14 -- You have to _choose_ a configuration `defaults/` just goes to the root of the repo, which has nothing. Choose any configuration from anywhere within: https://github.com/walmartlabs/eslint-config-defaults/tree/master/configurations

For example, for me with your basic repro setup:

```js
// index.js
// Google style requires singlequote, so an eslint error.
var foo = "HI";
```

then for configuration:

```js
{
  "extends": "defaults/configurations/google"
}
```

Running this gives the expected result:

```
$ eslint .

/Users/rye/Desktop/TEMP/index.js
  1:11  error  Strings must use singlequote  quotes

✖ 1 problem (1 error, 0 warnings)
```

@baer @chaseadamsio -- I don't think this bullet point is accurate in the README:

```
* `defaults` - The default ESLint config
```

And this doesn't work either:

```
---
"extends":
  - "defaults"
```

Since there is no pointer to anything that would match. Can one of you perhaps ticket and research? Maybe that we a need `ROOT/index.js` file with the eslint default config. Or, maybe we just revise the docs and don't have this be an example?

**Comment by tnguyen14** [comment]
I see. Yes it is the README doc that threw me off.

**Comment by ryan-roemer** [comment]
We now have an upstream bug in https://github.com/walmartlabs/eslint-config-defaults/issues/34 to either make `"defaults"` work as the docs state or revise the docs.

Hopefully, you can scrape by for now, and then follow the upstream issue for when we fix it. Thanks!

**Comment by tnguyen14** [comment]
Ok thanks!
