### ISSUE TITLE
Option to run eslint --fix

### ISSUE THREAD

**Issue by KnutHelland** [AtomLinter/linter-eslint#214]
This is a feature request.

Don't know if this would be a good idea. But eslint has this new `--fix` flag which enables fixing some of the different errors. I think it would be great if linter-eslint optionally could automatically apply fixes.

Since I couldn't find any issues about this I thought it would be an idea to post one.

**Comment by Moeriki** [comment]
I was working on this for `linter-eslint`. Got an almost-done solution but needed access to their SourceCodeFixer. I opened a request at `eslint` for this.

https://github.com/eslint/eslint/issues/3918

Unfortunately the `--fix` flag is in an experimental phase and they recommended not integrating it for now.

**Comment by dominicbarnes** [comment]
+1

This would be an amazing feature to include! (once they grow out of the "experiment" phase, that is)

**Comment by falcondai** [comment]
:+1: 

maybe leave it open to the adventurous users in the package setting?

**Comment by globexdesigns** [comment]
+1

I would like to have this as a context menu open so that you can either "Run ESLint fix on entire document" or "Run ESLint fix on selection".

**Comment by hugoduraes** [comment]
+1

I would like an option to be able to apply the fixes on file save.

**Comment by polarathene** [comment]
Would like to see this as a toggle in settings, it's unfortunate that it doesn't seem to report the errors it fixed which would be useful if the autofix caused a bug. I guess linting, autofix, linting and having a diff before/after the fix of errors isn't easy?

@globexdesigns From what I've read, `--fix` doesn't seem to support selections :(
> **Limitations:** the *--fix* flag does not work for piped-in text and has no effect on code that uses ESLint processors.

**Comment by jokeyrhyme** [comment]
For me, it isn't too important for it to report what it did. That's for `git diff` is for. :)

**Comment by steelbrain** [comment]
I've implemented the fix command but it doesn't fix selections, it fixes files saved on disk
