### ISSUE TITLE
Add support for eslint_d

### ISSUE THREAD

**Issue by roman01la** [AtomLinter/linter-eslint#215]
[eslint_d](https://github.com/mantoni/eslint_d.js) support just landed in [SublimeLinter-eslint](https://github.com/roadhump/SublimeLinter-eslint/commit/d33b395e8bd7238d72b86625282658da714d1b0c).
Can we have it in this package? 
Maybe like another option: `Use eslint_d`.

**Comment by denji** [comment]
:+1:

**Comment by rosston** [comment]
There should be little to no performance benefit to using `eslint_d` over the current method. `eslint_d`'s key performance gain is in not starting up a new node process, but this package already avoids that problem by using eslint's `CLIEngine` module from within Atom's (already running) node process.

**Comment by roman01la** [comment]
@rosston Didn't know about that. Thanks!

**Comment by mantoni** [comment]
Yes, this is important to know. I've added a note for Atom users to the `eslint_d` readme.
