### ISSUE TITLE
Bunch of errors

### ISSUE THREAD

**Issue by alexandrdragin** [AtomLinter/linter-eslint#218]
hi, maybe you saw something like that early

I get it, after any changes, again and again

https://www.dropbox.com/s/w8jhsm848hv9vti/Screenshot%202015-09-29%2013.56.32.png?dl=0

**Comment by tlhunter** [comment]
Are you completely sure your .eslintrc file is valid?

**Comment by alexandrdragin** [comment]
Yes, I tested it on other devices, and everything is working.

**Comment by eppsilon** [comment]
I am getting this too. I noticed from the stack trace it appears to be using a copy of eslint within the linter-eslint package. I tried setting it to use my global eslint, but that had no effect (and the stack trace still mentioned the linter-eslint copy).

**Comment by Arcanemagus** [comment]
@alexandrdragin The version of `eslint` bundled with this package is usually quite old, install `eslint` globally, or in the project you are working on as @eppsilon suggested.

Marking this as closed as this is an issue with your configuration using syntax that is too new for the built in `eslint`.

Feel free to ask any questions you have though :wink:.
