### ISSUE TITLE
"extends": "eslint:recommended" not honored

### ISSUE THREAD

**Issue by cdaringe** [AtomLinter/linter-eslint#220]
Hello:

eslint by default inserts "extends": "eslint:recommended" into a freshling `--init`'d rc.  This plugin barks that module "eslint-config-eslint" cannot be found.  I am using it global mode.  The plugin also doesn't seem to like finding globally installed `eslint-config-` modules or eslint plugins, globally installed.  Any tips would be appreciated.

Thanks!

-Chris

**Comment by toddbluhm** [comment]
I was running into the same issue and I figure out that the path to my global node_modules dir was wrong. I had just re-installed brew as non-super user and it changed my globals path from `/usr/local` to be located in my home directory. I would try checking to make sure you have the correct path to global node_modules. If you go under the linter-eslinter package settings in atom you will see a field to manually input that path along with the command to run to find the correct directory (`npm config get prefix`).

Hopefully that will help you in some way track down your issue, as it appears to have solved mine.

**Comment by cdaringe** [comment]
thanks @toddbluhm.  indeed, i did check that, and it is correct.  mine is also /usr/local.  The npm confirms  the directory. further, all of my global node bins are workin' just dandy!  Thanks for the tip!

**Comment by steelbrain** [comment]
Fixed by v5.0.0
