### ISSUE TITLE
Error when attempting to lint

### ISSUE THREAD

**Issue by frewsxcv** [AtomLinter/linter-eslint#221]
![screen shot 2015-10-01 at 11 46 07 am](https://cloud.githubusercontent.com/assets/416575/10225761/3be0aeea-6832-11e5-8f88-99378a31495b.png)

**Comment by steelbrain** [comment]
Did it happen just once or were you able to repro this again?

**Comment by frewsxcv** [comment]
Once. It worked when I opened up Atom this morning, so maybe it needed a restart (which I'm surprised I didn't try yesterday) ¯\_(ツ)_/¯

**Comment by steelbrain** [comment]
I am glad you got it working :tada:
