### ISSUE TITLE
rename/update disableWhenNoEslintrcFileInPath to disableWhenNoEslintConfig

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-eslint#226]
eslint config can be in the package.json under an "eslintConfig" field.
That could be a nice enhancement.

**Comment by MoOx** [comment]
Anyone thinking it's a good idea?

**Comment by Arcanemagus** [comment]
You should probably file this over on the [`eslint` repository](https://github.com/eslint/eslint) as this project is simply a runner for that.

**Comment by drazik** [comment]
I totally agree with @MoOx's proposition

**Comment by Arcanemagus** [comment]
@drazik I agree that it's not a bad idea, it just has _nothing_ to do with this project as `linter-eslint` is just a service provider that runs `eslint` on files. The proper place to support this is within `eslint` itself.

That being said, once `eslint` supports it this package would also need to be modified to feed `eslint` the `package.json` file (if it exists) :stuck_out_tongue:.

**Comment by MoOx** [comment]
Eslint already support eslintConfig field in package.json... This issue totally make sense here.

**Comment by drazik** [comment]
That's a `linter-eslint` config property, so yes I think the issue makes sens here. As @MoOx said, an `eslintConfig` field is already supported by `eslint`.

See http://eslint.org/docs/user-guide/configuring : 
"Configuration Files - use a JSON or YAML file to specify configuration information for an entire directory and all of its subdirectories. This can be in the form of an .eslintrc file or **an eslintConfig field in a package.json file**, both of which ESLint will look for and read automatically, or you can specify a configuration file on the command line."

**Comment by SpainTrain** [comment]
Thanks for the additional info.  I think it's a good idea.  Definitely more involved than a rename.  PR welcome.

**Comment by drazik** [comment]
I will try do make a PR in the coming days

**Comment by basecode** [comment]
I think it's a good idea. Actually I just tried exactly that and saw that it does not work currently ;)

```
"eslintConfig": {
  "extends": "eslint-config-from-other-npm-package"
} 
```

**Comment by Arcanemagus** [comment]
I had misunderstood what this PR was for earlier, as was pointed out :wink:

The package uses `eslint` to figure out the config for us [here](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L104), but it doesn't seem to be working properly. There is a bit more discussion about that over [here](https://github.com/AtomLinter/linter-eslint/issues/257), but it looks like it should be working in any current `eslint`. I haven't had a chance to debug this myself yet though.

**Comment by Arcanemagus** [comment]
With the v5.0.0 rewrite we now support loading the config from the `package.json`, so this is even more relevant.

**Comment by tschaub** [comment]
See #318 for a proposed fix.
