### ISSUE TITLE
Feature Request: Overview/Filter of rules

### ISSUE THREAD

**Issue by polarathene** [AtomLinter/linter-eslint#229]
Would it be difficult to provide an overview of errors/warnings like [visualized here](https://github.com/IanVS/eslint-nibble):
![ESLint stats](https://github.com/IanVS/eslint-nibble/raw/master/docs/eslint-stats-screenshot.png)

When using ESLint on an existing codebase it gets quite noisy, filtering by rule or having a good idea of what rules are most prominent so that they can be temporarily disabled/hidden would be nice. Perhaps this is out of the scope for linter-eslint though?

**Comment by steelbrain** [comment]
I am afraid this is out of scope of `linter-eslint` :)
