### ISSUE TITLE
Does not lint all file in project but only opening files

### ISSUE THREAD

**Issue by huytd** [AtomLinter/linter-eslint#232]
Hi everybody,

I'm just installed and found out that `eslint` only lint current opening files. 
What I am expected is it will lint all files in current project. 

Is there anyway to do so?

I had a look at `eslint-watch` but it's not what I'm looking for. I want it displayed inside Atom.

Thanks

**Comment by Arcanemagus** [comment]
Besides opening all the files I don't believe anything like that exists currently. You could write your own consumer of the `linter-*` packages that iterates them over all files in a directory if this is something you really need, but it's going to be far simpler to just run the linter against the directory in your shell.

**Comment by huytd** [comment]
yeah, but all I want is capture the linter result and display it directly inside atom, should learning to write atom plugin now, hehe. thank you so much for replying.

**Comment by SpainTrain** [comment]
@huytd I bet you could use an existing plugin like https://atom.io/packages/atom-terminal-panel to get what you want (e.g., run `eslint-watch` within the atom terminal panel).

**Comment by SpainTrain** [comment]
Also, if either of these solutions seems satisfactory, please feel free to close the issue =-D

**Comment by huytd** [comment]
Yeah I think I will close this issue
