### ISSUE TITLE
Using plugins globally - "plugin react not found"

### ISSUE THREAD

**Issue by MadLittleMods** [AtomLinter/linter-eslint#234]
I have a `.eslintrc` in the root of my drive which applies to projects which I don't have one specified yet. The rules do use [`eslint-plugin-react`](https://www.npmjs.com/package/eslint-plugin-react) but I have the plugin installed globally `npm install eslint eslint-plugin-react -g`

I have the global option checked.

Why is `eslint` complaining about `[Linter-ESLint] plugin react not found`? 

---

 - Atom 1.0.19
 - `linter-eslint@3.1.1`
 - `eslint@v0.24.1`
 - `eslint-plugin-react@3.5.1`

**Comment by MadLittleMods** [comment]
Related to https://github.com/AtomLinter/linter-eslint/issues/220

**Comment by MadLittleMods** [comment]
Adding the `Global node path` setting seems to have fixed it.

![](http://i.imgur.com/qig7G3y.png)

Could this be looked up in the path environment variable?

**Comment by MadLittleMods** [comment]
hmm, I am still running into this on Mac OS X where the global node path is `/usr/local`

**Comment by MoOx** [comment]
Using global node package is a really bad practise :/

**Comment by MadLittleMods** [comment]
@MoOx I would rather it the local version and then fallback to global but that doesn't seem to be available.

> I have a .eslintrc in the root of my drive which applies to projects which I don't have one specified yet.

**Comment by MadLittleMods** [comment]
Just saw this message pop up. I have the global option checked and the path input filled.

```
[Linter-ESLint] eslint binary not found locally, falling back to packaged one. Plugins won't be loaded and linting will possibly not work. (Try Use Global ESLint option, or install locally eslint
```

![](https://i.imgur.com/KzGObmK.png)

**Comment by MadLittleMods** [comment]
This may have been a problem with my path as I seemed to have an old node install with eslint. I cleaned up those symlinks and I haven't seen the message for days.

 - `/opt/local`
 - `/usr/local`
