### ISSUE TITLE
packaged eslint becomes stale without `apm rebuild`

### ISSUE THREAD

**Issue by bjonica** [AtomLinter/linter-eslint#235]
I just had to `apm rebuild` to prevent this package from falsely reporting issues with my .eslintrc -- as I was using updated rule definitions that weren't compatible with the packaged version of eslint (though they are compatible with my system eslint).

It doesn't look like updates to this package cause the packaged eslint to be update since [this line](https://github.com/AtomLinter/linter-eslint/blob/master/package.json#L14) sees that there is *some* eslint version above 0.24.0 already installed and doesn't fetch a newer one.

Why set the minimum at such an old version? It's not obvious to newcomers that they have to pull up a console and rebuild apm packages when their otherwise valid .eslintrc starts throwing errors.

**Comment by Arcanemagus** [comment]
I believe the author of this package strongly discourages using the built in one, preferring the "right" version to be installed within your project itself.

That being said, probably the only reason it is still that old is due to nobody updating it in a long time so submit a PR :wink:.

**Comment by bjonica** [comment]
I'm actually not using the built-in one, and if the built-in one is being used unintentionally here than there's another bug I'll have to look into. From what I can tell, this package installs `eslint` in order to validate the rules inside of your .eslintrc file, while the actual linting was performed using my system's/project's `eslint`.

Hm, so since it doesn't really need a bundled eslint to do linting, it makes sense that it shouldn't need a bundled eslint for rule verification. It would be nice to remove that dependency entirely and avoid this issue in the future. I'll work on that.
