### ISSUE TITLE
Expand link to line/column to work with clicks on all error text

### ISSUE THREAD

**Issue by brettz9** [AtomLinter/linter-eslint#236]
Hi,

Great plug-in.

Would like to request though that the links which lead one to the specific problematic line and column be expanded so that clicking anywhere on that line, such as the name of the error, explanation of the error, etc. would also go to that same line. I'm used to Notepad++'s JSLint plug-in, and it is very convenient not to have to fine tune one's cursor to navigate specifically to "at line 504 col 1" or whatever.

**Comment by Arcanemagus** [comment]
This would need to be raised over on the [`linter`](https://github.com/atom-community/linter) package as `linter-eslint` has nothing to do with the display of messages, only providing them to `linter`. As such I'm marking this issue as closed.

As a note, from the sounds of it `linter` supports far more complex messages than the Notepad++ plugin, as it can handle things like multi-line messages and trace sections to show related code for example.

**Comment by brettz9** [comment]
Per my understanding of atom-community/linter/issues/974 , you may be able to implement this now? I think my preference would still be for most of the line to allow clicking to the line in question, but with the specific warning (e.g., `no-trailing-spaces`) linking to the HTML page describing the rule in question...

**Comment by Arcanemagus** [comment]
Again, this is _not_ the place to handle your "click the entire line leads to the relevant part of the code" request.

The linking to the relevant rule's description though is a great idea, do you want to file a new issue for that? Or even better submit a PR :stuck_out_tongue:?
