### ISSUE TITLE
Toggle by warning/error or all

### ISSUE THREAD

**Issue by brettz9** [AtomLinter/linter-eslint#237]
It would be very handy to have the ability to sort by error rule (e.g., all of the "max-len" errors together) or by error level (grouping errors and warnings separately).

It would be ideal if that sorting could allow for multiple sorts together, e.g., errors and warnings grouped together but then sorted by document order, or grouped by error level and then by error rule (and then by document order).

**Comment by brettz9** [comment]
A toggle to completely hide warnings or errors would also be very handy

**Comment by Arcanemagus** [comment]
This package merely provides a service that supplies messages to the `linter` package, which would be near impossible to sort in this manner unfortunately as it needs to be generic to any `linter-*` package.

Assuming you mean hiding the warnings say, but still showing the errors that would need to be handled in this package. If you just mean to hide the display of _all_ messages, you can toggle that in the `linter` package.

**Comment by brettz9** [comment]
As far as hiding the warnings but still showing the errors (or vice versa), yes, I'd very much be interested in that.

However, as far as the sorting of messages being done by the `linter` package, why couldn't it be supplied with an array of "columns" (if it is not already) and then just allow a generic alphabetic sorting against any column desired? (Speaking of which, should this discussion be moved to atom-community/linter/issues/865  ?).

**Comment by Arcanemagus** [comment]
Yes, that's the current place discussion on sorting messages is happening :wink:.

**Comment by brettz9** [comment]
And while I'm making requests uncertain where they should go--would the ability to click on part of say the inline linting message to be able to open in the browser the page which documents the rule in question?

**Comment by Arcanemagus** [comment]
`linter-*` providers (such as this project) _only_ run the related linter on code and then provide the results to the `linter` package. Everything you interact with is part of the `linter` package.

I _think_ that functionality already exists, but I don't know of any provider that utilizes it myself.

**Comment by steelbrain** [comment]
This should be discussed in the core linter.

PS. We have a UI service in the works which will allow you to use the UI of your choice
