### ISSUE TITLE
Error: Got both html and text fields on Linter Response, expecting only one

### ISSUE THREAD

**Issue by tothandras** [AtomLinter/linter-eslint#249]
![image](https://cloud.githubusercontent.com/assets/4157749/10844235/500c88e8-7efe-11e5-833b-8a0f0a8924ee.png)

**Comment by davemackintosh** [comment]
Was just about to report this myself.

**Comment by RemiAWE** [comment]
I got the same error on OSX El Capitan everytime I save a document (with lint on save).

**Comment by iam4x** [comment]
Is this happening with `3.2.1` version?

**Comment by tothandras** [comment]
With version `3.2.0`, update is not available for me.

**Comment by tothandras** [comment]
Managed to update (reinstall). The error is still present.

**Comment by davemackintosh** [comment]
3.2.1 fixes it but I still don't have a linter. Even when I manually `eslint --init`

**Comment by Arcanemagus** [comment]
This was mistakenly introduced in https://github.com/AtomLinter/linter-eslint/pull/240, checks to prevent this incorrect use of the Linter API added to `linter` in https://github.com/atom-community/linter/pull/975, and the change that created that bug in this linter reverted in https://github.com/AtomLinter/linter-eslint/pull/243, which was released as v3.2.1.

@tothandras if you are on v3.2.1 it should be impossible to see that error, if you are still seeing it something went wrong with the update, you might want to verify it was actually updated properly.
@davemackintosh I would say that is a separate issue that you should report on your own, but you already did :stuck_out_tongue:, let's work on that there.

Marking this as closed.

**Comment by davemackintosh** [comment]
:+1:

**Comment by tothandras** [comment]
:+1: it's good now, thanks!

**Comment by steelbrain** [comment]
Related https://github.com/atom-community/linter/issues/982
