### ISSUE TITLE
Upgrade to v3.2.0 ignores .eslintrc

### ISSUE THREAD

**Issue by MikeDimmick** [AtomLinter/linter-eslint#250]
This is a continuation of https://github.com/AtomLinter/linter-eslint/issues/247 which got closed while I was writing this comment.

I've just tried updating to eslint 1.7.3. It won't actually run on my project at the moment, because there's an incompatibility in our .eslintrc. linter-eslint is now producing the same error as running it from the command line, so it is loading the expected eslint - it's just using the wrong config.

The problematic commit is  c5671ff , 'Lint javascript inside HTML file'. Reading the documentation for  CLIEngine.executeOnText , it appears that it will only find an  .eslintrc  in the current working directory, unless we specify the path in the options.

Looking at the pull request #197, the author stated that plugins weren't supported - but the previous line of code loads any configured plugins, and I can confirm that our plugins were previously being loaded. We use the jasmine, require, requirejs and our own custom plugin. I don't immediately see why linter-eslint shouldn't load the html plugin in the same fashion and call  linter.verify  as before. However, I'm not using eslint on any source files with embedded JavaScript - this project is a pretty large Single Page Application using durandal.

As for dropped support - you said you dropped support for 0.20 and lower. I'm using 0.22 and @danoc is using 0.21, so we should still be supported.

**Comment by iam4x** [comment]
Keep discussion into #247
