### ISSUE TITLE
sub-folders not being linted

### ISSUE THREAD

**Issue by davemackintosh** [AtomLinter/linter-eslint#251]
After upgrading Atom to 1.1 and getting the 3.2.1 update none of my subfolders are being linted. Only files that share the same directory as my `.eslintrc` are being linted.

**Comment by Arcanemagus** [comment]
`eslint` no longer enables rules by default with v1+, are you saying it is showing messages for some files but not others, or just that it isn't working?

**Comment by davemackintosh** [comment]
Yeah, any files that share the same directory as my `.eslintrc` it works fine but any files in folders it doesn't lint. Does it ignore `node_modules` by default? I'm working on a few things inside of the `node_modules` folder which is where the cruft of the issue seems to be.

**Comment by Arcanemagus** [comment]
Ah ha, `linter` recently added an option to ignore VCS ignored files, which is enabled by default. Check your `linter` settings and try disabling that option if you are working inside `node_modules` as that is almost certainly inside your `.gitignore` (or equivalent).

**Comment by davemackintosh** [comment]
Yep, it was. Disabled and boom. Cheers bud!
