### ISSUE TITLE
Possible bug on eslintRulesDir

### ISSUE THREAD

**Issue by dacodekid** [AtomLinter/linter-eslint#255]
If you have your `.eslintrc` file inside another folder (config) on project's folder, this will fail and also since  `findFile` from `atom-linter` package search in backwards (I believe), there is no way this'll find a config file that is above project root.

```javascript
onlyConfig: true
eslintRulesDir: './config/'
```
https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L68-L71

**Comment by steelbrain** [comment]
We are being as much compatible with the CLI `eslint` as possible, it also searches in the top directories and not the children ones. If you have a good use case for this and are able to get enough public support, I won't mind re-opening

**Comment by dacodekid** [comment]
Sure. My use case is mostly just personal preference, since the number of `rc` file list grows longer than our project files, I would like to keep them all under a `.dotfiles` sub-folder. No issues otherwise. Hope enough people feel the same way.

**Comment by steelbrain** [comment]
You might wanna subscribe to #216
