### ISSUE TITLE
How to set these settings globally

### ISSUE THREAD

**Issue by darkred** [AtomLinter/linter-eslint#257]
I use Atom 1.1.0 in win10 x64. I have installed eslint globally.

I want to set these settings globally *(i.e. not having to put them in a `.eslintrc` file every time)*

```
{
    "rules": {
        "indent": [
            2,
            "tab"
        ],
        "quotes": [
            2,
            "single"
        ],
        "linebreak-style": [
            2,
            "windows"
        ],
        "semi": [
            2,
            "always"
        ]
    },
    "env": {
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended"
}
```

As it says in the [README](https://github.com/AtomLinter/linter-eslint) that: 
> You can configure linter-eslint by editing ~/.atom/config.cson (choose Open Your Config in Atom menu) or in Preferences

<br/>
First of all, in `File|Settings|Packages|linter-eslint Settings`
there's isn't a textbox to add extra settings.

Secondly,  clicking FIle|Open your Config (i.e. ` ~/.atom/config.cson` )
the "linter"-related entries are:
  
```
  "linter-eslint":
    useGlobalEslint: true    
  linter: {}

```

How can I modify these entries in order to include the above settings? Is it possible?

**Comment by Arcanemagus** [comment]
The settings you are seeing above are the _package_ settings, not your eslint settings. You really should be storing those in the project, but if you don't want to do that though it should search up in directories until it hits the root of your file system, so you could put one in your home directory (assuming all your projects are within that).

**Comment by darkred** [comment]
So, [if I got this right](http://eslint.org/docs/user-guide/configuring.html)
I may add my settings as an extra entry in `package.json`
which is located in `C:\Users\Kostas\AppData\Roaming\npm\node_modules\eslint`?
Like this:


```
"eslintConfig" : 
{
    "rules": {
        "indent": [
            2,
            "tab"
        ],
        "quotes": [
            2,
            "single"
        ],
        "linebreak-style": [
            2,
            "windows"
        ],
        "semi": [
            2,
            "always"
        ]
    },
    "env": {
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended"
}
```

**Comment by Arcanemagus** [comment]
Assuming [this](http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile) works properly, yes :wink:.

**Comment by darkred** [comment]
Sorry, but it don't understand what `getConfigForFile()` has to do with this :flushed:

Anyway, I just modified `package.json` it, but unfortunately it didn't work.

**Comment by Arcanemagus** [comment]
This linter calls that function of `eslint` to figure out the configuration, if it is working properly then it should work but it sounds like it isn't...

**Comment by darkred** [comment]
This is supposed to be fix in this eslint issue  [Cannot use "extends" within package.json #2754](https://github.com/eslint/eslint/issues/2754)

Could you (or anyone else) please confirm that this still occurs, so that I may report it there?

**Comment by Arcanemagus** [comment]
So just to confirm, you have `linter-eslint` set to use the globally installed `eslint`?
Which version of `eslint` did you install?

**Comment by darkred** [comment]
> So just to confirm, you have `linter-eslint` set to use the globally installed `eslint`?  

Yes, exactly.

> Which version of `eslint` did you install?

1.9.0

**Comment by ilyavolodin** [comment]
@darkred You misunderstood how package.json config entry works. It's just another way to setup rules for a given project. As in `eslintConfig` entry should go into your package.json file, not into eslint's file. It's just a shortcut for linting npm packages, instead of creating a separate .eslintrc file, you can just put the same thing into package.json file directly.
I think what you are looking for is global settings that are available everywhere on a machine. You have a few choices on how to get that to work. Easiest one is to create an `.eslintrc` file in `~/` directory. ESLint will pick up that file for all projects on the machine, unless it finds a local config file.
Another way is to create a separate `.eslintrc` file and then create local configs inside each project that extend from the root config. You can find more information about ESLint configs [here](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)

**Comment by Arcanemagus** [comment]
@ilyavolodin as @darkred said [here](https://github.com/AtomLinter/linter-eslint/issues/257#issuecomment-155962747), they actually _had_ added that to their package.json.

**Comment by darkred** [comment]
[**@ilyavolodin**](https://github.com/ilyavolodin) commented on [Nov 13, 2015, 6:40 PM GMT+2](https://github.com/AtomLinter/linter-eslint/issues/257#issuecomment-156482829 "2015-11-13T16:40:41Z - Replied by Github Comment Enhancer"):
> [@darkred](https://github.com/darkred) You misunderstood how package.json config entry works. It's just another way to setup rules for a given project. As in `eslintConfig` entry should go into your package.json file, not into eslint's file. It's just a shortcut for linting npm packages, instead of creating a separate .eslintrc file, you can just put the same thing into package.json file directly.  
> 
> I think what you are looking for is global settings that are available everywhere on a machine. You have a few choices on how to get that to work. Easiest one is to create an `.eslintrc` file in `~/` directory. ESLint will pick up that file for all projects on the machine, unless it finds a local config file.  
> 
> Another way is to create a separate `.eslintrc` file and then create local configs inside each project that extend from the root config. You can find more information about ESLint configs [here](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)

@ilyavolodin Thanks for your reply, but as I've written, I use Atom mostly as the default editor for Greasemonkey (Firefox in win10x64), i.e. editing userscripts. Therefore I don't have a `~/` directory: every userscript is stored in it's own sub-directory in `%AppData%\Mozilla\Firefox\Profiles\profile_name.default\gm_scripts\script_title`. That's why I'd prefer not having to put a `.eslintrc` in every userscript directory. 

(I even tried copying `.eslintrc` to `C:\Users\Kostas\AppData\Roaming\npm` which is contained in %path%)

**Comment by ilyavolodin** [comment]
@darkred Sorry, I wasn't clear. I assumed that you updated package.json in the global installation of the ESLint based on the path you provided here: https://github.com/AtomLinter/linter-eslint/issues/257#issuecomment-155948764 That wouldn't do anything.
By `~/` I mean your user's home directory. In Windows it would be `c:\Users\<username>`, in OSX - `/Users/<username>`, in linux - `/home/<username>`. If you create an .eslintrc file in that directory, and if you don't have .eslintrc files anywhere else, ESLint will automatically fall back to that config file for any file linted on the machine by your user.

**Comment by darkred** [comment]
Alright. Thanks a lot!

**Comment by Arcanemagus** [comment]
If the default search for `.eslintrc` doesn't find your global one, @steelbrain has now implemented the ability to hard code a path as well in #288. That should sufficiently cover your needs I think :wink:.

**Comment by darkred** [comment]
Thank you for letting me know! :smile:
