### ISSUE TITLE
Error: channel closed

### ISSUE THREAD

**Issue by haydenbleasel** [AtomLinter/linter-eslint#260]
Hi, I keep getting this error every so often after upgrading to the latest version. A window reload fixes it temporarily.

<img width="451" alt="screenshot 2015-11-14 00 37 36" src="https://cloud.githubusercontent.com/assets/4142719/11162837/fbf9b120-8a67-11e5-8635-b76737201915.png">

**Comment by iilei** [comment]
same here

**Comment by anthony-dandrea** [comment]
+1 :cry:

**Comment by ivanlemeshev** [comment]
+ 1

**Comment by steelbrain** [comment]
Fixed by #264 
It will now show a nice notification when it crashes and will dump to console what actually went wrong
