### ISSUE TITLE
v5.0.0 "Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly"

### ISSUE THREAD

**Issue by scottbert** [AtomLinter/linter-eslint#261]
Everything was working OK, now it isn't! OSX, using both global and local ESLints and it's not picked up. /usr/local is my global Node path, nothing has changed in my set up and it was working but now isn't.

```
$ which eslint
/usr/local/bin/eslint
```
Everything looks to be correct.

**Comment by lijunle** [comment]
+1 on Linux

Revert back to 4.0.0, everything works good.

**Comment by stefan-hausmann** [comment]
+1 on Windows 8.1
option "global node path" is set to the value printed out by ```npm config get prefix``` and "Use global ESLint installation" is set to true

**Comment by albertosantini** [comment]
https://github.com/AtomLinter/linter-eslint/blob/master/lib/worker.js#L56

A few notes about that line for Windows 10 box.

Try the following with Node.js REPL:
- `require('child_process').spawnSync('npm', ['get', 'prefix']).output[1].toString().trim()`
- `require('child_process').spawnSync('npm.cmd', ['get', 'prefix']).output[1].toString().trim()`

Notice `npm.cmd`.

Then, in Windows 10, no `lib`, after `npm`, in that folder.
For instance, the path of `eslint` is the following one: 

`C:\\Users\\icebox\\AppData\\Roaming\\npm\\node_modules\\eslint\\lib\\cli.js`

However, modifying accordingly the code, I continue to get an exception:

```
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
    at C:\Users\icebox\.atom\packages\linter-eslint\lib\worker.js:63:13
    at C:\Users\icebox\.atom\packages\linter-eslint\node_modules\childprocess-promise\node_modules\sb-communication\node_modules\zm-event-kit\dist\Emitter.js:58:16
    at Array.forEach (native)
    at Communication.emit (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\childprocess-promise\node_modules\sb-communication\node_modules\zm-event-kit\dist\Emitter.js:57:43)
    at Communication.gotMessage (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\childprocess-promise\node_modules\sb-communication\dist\main.js:33:16)
    at process.<anonymous> (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\childprocess-promise\dist\main.js:29:27)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

It seems there is a race condition due to a dependency is not compatible with Windows, because adding a log in the try-catch block, no message is logged in the devtools console.

**Comment by tylerFowler** [comment]
+1 Though I've been using Node 5.0.0 for a while and haven't had problems, it just randomly started happening last night, though I suppose I did upgrade to eslint 1.9.0 around the same timeframe (from the directly previous version). Also worth mentioning eslint is indeed on my path correctly.

**Comment by escolhatecnologia** [comment]
+1

linter-eslint 5.0.0
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly

**Comment by albertosantini** [comment]
However there is another issue related to this one: sometimes the settings are not correctly loaded.

See https://github.com/atom/atom/issues/9600
That issue refers to `release-notes`, but it happens with any package, also with `linter-eslint`.

**Comment by steelbrain** [comment]
Can you guys post your configs? It'll help me debug this further

**Comment by steelbrain** [comment]
Just a side note that this sounds like an upgrade problem, here's what works most of the time
```
apm uninstall linter-eslint
apm install linter-eslint@latest
```

**Comment by scottbert** [comment]
```
$ apm install linter-eslint@latest
Installing linter-eslint@latest to /Users/<user>/.atom/packages ✗
Package version: latest not found
```

**Comment by albertosantini** [comment]
My config is the following one:
```
"linter-eslint":
    useGlobalEslint: true
```

Uninstalling and installing again, for instance `apm install linter-eslint@5.0.0`, doesn't resolve the issue on Windows due to the path problem reported above.

**Comment by scottbert** [comment]
```cson
"*":
  "exception-reporting":
    userId: “<id>”
  welcome:
    showOnStartup: false
  "linter-eslint":
    globalNodePath: "/usr/local/"
    disableWhenNoEslintrcFileInPath: false
    useGlobalEslint: true
  core:
    themes: [
      "one-dark-ui"
      "monokai"
    ]
    packagesWithKeymapsDisabled: [
      "one-dark-ui"
      "htmlhint"
    ]
  editor:
    invisibles: {}
    showInvisibles: true
    tabLength: 4
    tabType: "soft"
  minimap:
    plugins:
      linter: true
      selection: true
  "sync-settings":
    _analyticsUserId: “<id>”
    personalAccessToken: “<id>”
    gistId: “<id>”
    _lastBackupHash: “<id>”
  htmlhint:
    validateOnChange: true
    validateOnSave: false
    hideOnNoErrors: true
  linter:
    gutterPosition: "Left"
    showErrorTabLine: true
  "linter-scss-lint":
    executablePath: "/usr/local/bin/scss-lint"
  "open-recent": {}
  "tree-view":
    hideVcsIgnoredFiles: true
```

**Comment by Arcanemagus** [comment]
@scottbert Try 'apm install linter-eslint@5.0.0`

@steelbrain `apm` is still based on an older version of `npm` and probably doesn't know what `@latest` means.

**Comment by scottbert** [comment]
I did - 5.0.1 now - still the same issue.

**Comment by albertosantini** [comment]
Same issue with 5.0.1.

Recap on Windows box.

- Don't join ` npm get prefix` and `lib`, because that path doesn't exist.
- Also fixing that, I get an exception originated in `childprocess-promise` (see stacktrace above).

**Comment by dmitrage** [comment]
There are issues with child_process.spawn on Windows. I replaced ChildProcess.spawnSync with spawn.sync from [cross-spawn](https://www.npmjs.com/package/cross-spawn) package, and it helped (I also had to remove 'lib' from path join).

Details: https://github.com/nodejs/node-v0.x-archive/issues/2318

**Comment by steelbrain** [comment]
I'll test the features on windows one by one now and try to fix this

**Comment by andrelima** [comment]
This is not related only to Windows, I am on OS X, getting the same problem that @scottbert is reporting since I upgraded linter-eslint yesterday...

I know it's not ESLint itself, because I didn't upgrade it yesterday, I've been using v1.9.0 since it was released with no problems.

I'm using only global ESLint and didn't change any Atom settings yesterday.

$ which eslint
/usr/local/bin/eslint

Config is:
```
  "linter-eslint":
    useGlobalEslint: true
    globalNodePath: "/usr/local"
```

**Comment by andrelima** [comment]
Also, uninstalled and installed with `apm install linter-eslint@5.0.1` and restarted Atom twice after that ...always getting this error.

**Comment by steelbrain** [comment]
As a "workaround" you guys can just disable `Use Global ESLint` setting

**Comment by andrelima** [comment]
> As a "workaround" you guys can just disable Use Global ESLint setting

Ah, right — Thank you!

As I have no project-local ESLint installed, I guess linter-eslint is using its own... OK! :)

**Comment by steelbrain** [comment]
I have a fix up for the Windows support. Working on OSX global eslint support now

**Comment by steelbrain** [comment]
`v5.0.2` is supports eslint installations in current project as well as global eslint for Windows. Now if only somebody tell me where `npm` stores the dependencies on OSX, that would be very helpful.
```
# For OSX Peeps
echo $PWD
cd `npm get prefix`
cd lib && ls -lah
cd node_modules && ls -lah
```
^ If you can post results of those commands, it would be really helpful in supporting global ESLint on OSX

**Comment by andrelima** [comment]
Here's the whole thing:
```
andy@AL-Mac ~ $ echo $PWD
/Users/andy

andy@AL-Mac ~ $ cd `npm get prefix`

andy@AL-Mac /usr/local (master) $ cd lib && ls -lah
total 280
drwxrwxr-x  42 andy  admin   1.4K Nov  6 21:46 .
drwxr-xr-x  25 andy  admin   850B Nov 11 18:46 ..
drwxr-xr-x   3 andy  admin   102B Nov  6 21:41 dtrace
lrwxr-xr-x   1 andy  admin    48B Oct  2 04:27 libfreetype.6.dylib -> ../Cellar/freetype/2.6_1/lib/libfreetype.6.dylib
lrwxr-xr-x   1 andy  admin    42B Oct  2 04:27 libfreetype.a -> ../Cellar/freetype/2.6_1/lib/libfreetype.a
lrwxr-xr-x   1 andy  admin    46B Oct  2 04:27 libfreetype.dylib -> ../Cellar/freetype/2.6_1/lib/libfreetype.dylib
lrwxr-xr-x   1 andy  admin    37B Oct  2 04:28 libjpeg.8.dylib -> ../Cellar/jpeg/8d/lib/libjpeg.8.dylib
lrwxr-xr-x   1 andy  admin    31B Oct  2 04:28 libjpeg.a -> ../Cellar/jpeg/8d/lib/libjpeg.a
lrwxr-xr-x   1 andy  admin    35B Oct  2 04:28 libjpeg.dylib -> ../Cellar/jpeg/8d/lib/libjpeg.dylib
lrwxr-xr-x   1 andy  admin    38B Oct 15 00:43 liblzma.5.dylib -> ../Cellar/xz/5.2.2/lib/liblzma.5.dylib
lrwxr-xr-x   1 andy  admin    32B Oct 15 00:43 liblzma.a -> ../Cellar/xz/5.2.2/lib/liblzma.a
lrwxr-xr-x   1 andy  admin    36B Oct 15 00:43 liblzma.dylib -> ../Cellar/xz/5.2.2/lib/liblzma.dylib
lrwxr-xr-x   1 andy  admin    46B Oct  2 04:29 libodbc.2.dylib -> ../Cellar/unixodbc/2.3.2_1/lib/libodbc.2.dylib
lrwxr-xr-x   1 andy  admin    44B Oct  2 04:29 libodbc.dylib -> ../Cellar/unixodbc/2.3.2_1/lib/libodbc.dylib
lrwxr-xr-x   1 andy  admin    48B Oct  2 04:29 libodbccr.2.dylib -> ../Cellar/unixodbc/2.3.2_1/lib/libodbccr.2.dylib
lrwxr-xr-x   1 andy  admin    46B Oct  2 04:29 libodbccr.dylib -> ../Cellar/unixodbc/2.3.2_1/lib/libodbccr.dylib
lrwxr-xr-x   1 andy  admin    50B Oct  2 04:29 libodbcinst.2.dylib -> ../Cellar/unixodbc/2.3.2_1/lib/libodbcinst.2.dylib
lrwxr-xr-x   1 andy  admin    48B Oct  2 04:29 libodbcinst.dylib -> ../Cellar/unixodbc/2.3.2_1/lib/libodbcinst.dylib
lrwxr-xr-x   1 andy  admin    39B Oct  2 04:11 libpcre.1.dylib -> ../Cellar/pcre/8.37/lib/libpcre.1.dylib
lrwxr-xr-x   1 andy  admin    33B Oct  2 04:11 libpcre.a -> ../Cellar/pcre/8.37/lib/libpcre.a
lrwxr-xr-x   1 andy  admin    37B Oct  2 04:11 libpcre.dylib -> ../Cellar/pcre/8.37/lib/libpcre.dylib
lrwxr-xr-x   1 andy  admin    41B Oct  2 04:11 libpcre16.0.dylib -> ../Cellar/pcre/8.37/lib/libpcre16.0.dylib
lrwxr-xr-x   1 andy  admin    35B Oct  2 04:11 libpcre16.a -> ../Cellar/pcre/8.37/lib/libpcre16.a
lrwxr-xr-x   1 andy  admin    39B Oct  2 04:11 libpcre16.dylib -> ../Cellar/pcre/8.37/lib/libpcre16.dylib
lrwxr-xr-x   1 andy  admin    41B Oct  2 04:11 libpcre32.0.dylib -> ../Cellar/pcre/8.37/lib/libpcre32.0.dylib
lrwxr-xr-x   1 andy  admin    35B Oct  2 04:11 libpcre32.a -> ../Cellar/pcre/8.37/lib/libpcre32.a
lrwxr-xr-x   1 andy  admin    39B Oct  2 04:11 libpcre32.dylib -> ../Cellar/pcre/8.37/lib/libpcre32.dylib
lrwxr-xr-x   1 andy  admin    42B Oct  2 04:11 libpcrecpp.0.dylib -> ../Cellar/pcre/8.37/lib/libpcrecpp.0.dylib
lrwxr-xr-x   1 andy  admin    36B Oct  2 04:11 libpcrecpp.a -> ../Cellar/pcre/8.37/lib/libpcrecpp.a
lrwxr-xr-x   1 andy  admin    40B Oct  2 04:11 libpcrecpp.dylib -> ../Cellar/pcre/8.37/lib/libpcrecpp.dylib
lrwxr-xr-x   1 andy  admin    44B Oct  2 04:11 libpcreposix.0.dylib -> ../Cellar/pcre/8.37/lib/libpcreposix.0.dylib
lrwxr-xr-x   1 andy  admin    38B Oct  2 04:11 libpcreposix.a -> ../Cellar/pcre/8.37/lib/libpcreposix.a
lrwxr-xr-x   1 andy  admin    42B Oct  2 04:11 libpcreposix.dylib -> ../Cellar/pcre/8.37/lib/libpcreposix.dylib
lrwxr-xr-x   1 andy  admin    36B Oct  2 04:27 libpng.a -> ../Cellar/libpng/1.6.18/lib/libpng.a
lrwxr-xr-x   1 andy  admin    40B Oct  2 04:27 libpng.dylib -> ../Cellar/libpng/1.6.18/lib/libpng.dylib
lrwxr-xr-x   1 andy  admin    45B Oct  2 04:27 libpng16.16.dylib -> ../Cellar/libpng/1.6.18/lib/libpng16.16.dylib
lrwxr-xr-x   1 andy  admin    38B Oct  2 04:27 libpng16.a -> ../Cellar/libpng/1.6.18/lib/libpng16.a
lrwxr-xr-x   1 andy  admin    42B Oct  2 04:27 libpng16.dylib -> ../Cellar/libpng/1.6.18/lib/libpng16.dylib
drwxr-xr-x  10 andy  admin   340B Nov 11 18:50 node_modules
drwxr-xr-x   3 andy  admin   102B Nov  6 21:40 perl5
drwxr-xr-x   3 andy  admin   102B Nov  6 21:46 php
drwxr-xr-x  11 andy  admin   374B Oct 15 00:43 pkgconfig

andy@AL-Mac /usr/local/lib (master) $ cd node_modules && ls -lah
total 0
drwxr-xr-x  10 andy  admin   340B Nov 11 18:50 .
drwxrwxr-x  42 andy  admin   1.4K Nov  6 21:46 ..
drwxr-xr-x  10 andy  admin   340B Nov 11 18:50 babel-cli
drwxr-xr-x  12 andy  admin   408B Nov  6 21:55 browser-run
drwxr-xr-x  13 andy  admin   442B Oct 30 22:49 browserify
drwxr-xr-x   9 andy  admin   306B Nov  6 21:55 eslint
drwxr-xr-x   9 andy  admin   306B Nov  3 15:41 faucet
drwxr-xr-x  25 andy  admin   850B Nov 11 18:47 npm
drwxr-xr-x   8 andy  admin   272B Nov  6 20:30 onchange
drwxr-xr-x   9 andy  admin   306B Nov  2 15:55 uglify-js

andy@AL-Mac /usr/local/lib/node_modules (master) $
```

**Comment by steelbrain** [comment]
@andrelima That was very helpful! Thanks!

**Comment by obieq** [comment]
echo $PWD
  /usr/local/lib/node_modules

npm get prefix
  /usr/local

cd lib && ls -lah
  dtrace
  node_modules

cd node_modules && ls -lah
  bower
  ember-cli
  http-server
  npm
  phantomjs2

**Comment by steelbrain** [comment]
From what I see, the latest version should work on OSX too, Please try it out and let me know if you still see any error

**Comment by albertosantini** [comment]
Great job!

On Windows 10 it is ok.

**Comment by andrelima** [comment]
Getting this error:
error: Cannot read property '1' of null
---
typeerror: Cannot read property '1' of null    at /Users/andy/code/atom/atom-cfg/packages/linter-eslint/lib/worker.js:55:80    at /Users/andy/code/atom/atom-cfg/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:58:16    at Array.forEach (native)    at Communication.emit (/Users/andy/code/atom/atom-cfg/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:57:43)    at Communication.gotMessage (/Users/andy/code/atom/atom-cfg/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/dist/main.js:33:16)    at process.<anonymous> (/Users/andy/code/atom/atom-cfg/packages/linter-eslint/node_modules/childprocess-promise/dist/main.js:29:27)    at emitTwo (events.js:87:13)    at process.emit (events.js:172:7)    at handleMessage (internal/child_process.js:685:10)    at Pipe.channel.onread (internal/child_process.js:440:11)
---

**Comment by steelbrain** [comment]
@andrelima You are on OSX and you are not launching Atom from the Terminal. It's a limitation of OSX apps that they can not inherit `$PATH`, so you'll have to run it from the terminal to use global eslint I am afraid.

Anyways, I'm adding error handling for it now

**Comment by andrelima** [comment]
@steelbrain But it was working fine before... for several months...?

**Comment by steelbrain** [comment]
@andrelima Can you please confirm that it works if you launch it from terminal?

**Comment by andrelima** [comment]
@steelbrain It is indeed working now from the terminal. :)

But I don't understand how it could be working before?...

**Comment by steelbrain** [comment]
@andrelima It's a mystery to me. It's a known limitation of all OSX apps not just Atom :)
Anyways, in the upcoming version you'll be shown a nicer notification if `npm get prefix` fails, instead of that confusing trace you posted above

**Comment by steelbrain** [comment]
@andrelima Just so you would know, we have removed the `globalNodePath` config from the latest version. Maybe it was working because you had specified a hard-coded value

**Comment by scottbert** [comment]
It probably was, we OSXers were all using ```globalNodePath: “/usr/local/“```

**Comment by andrelima** [comment]
Ahhh... OK — Mystery solved. :)

Thank you @steelbrain for all your work in fixing this and maintaining this package. :)

**Comment by steelbrain** [comment]
I'm adding `globalNodePath` again to this linter, You can track the work here https://github.com/AtomLinter/linter-eslint/pull/274
You can expect a working version in less than an hour

**Comment by andrelima** [comment]
That's great! Appreciated.

**Comment by steelbrain** [comment]
`v5.1.0` is out everybody! Thank you for all of your feedback!

**Comment by andrelima** [comment]
Working well now without having to launch Atom from the terminal. :)

Thank you!

**Comment by RryLee** [comment]
@andylima Thank you man!!!

**Comment by rotexhawk** [comment]
I was having the same issue so I removed eslint that was added through yarn and used `npm install eslint -g` and it works.
