### ISSUE TITLE
Unable to use eslint-plugin-react

### ISSUE THREAD

**Issue by mhagmajer** [AtomLinter/linter-eslint#262]
My own .eslintrc uses the `react` plugin and I have both `eslint` and `eslint-plugin-react` in the dev dependencies of my project.

Unfortunately, Atom throws `Cannot find module 'eslint-plugin-react'` when it attepts to run `linter-eslint`. How can I add the `eslint-plugin-react` to Atom?

I didn't have this problem before f6a210b9f5e055a2fa781ce381a0b2ca0b643077 was committed.

**Comment by dominicbarnes** [comment]
As of v5.0.0, I can't seem to use any modules via `extends` or `plugins`, I suspect it's related to this problem. (I've downgraded to v4.0.0 for the time-being)

**Comment by magalhas** [comment]
I'm also facing this with `eslint-config-relax`.

**Comment by globexdesigns** [comment]
Same problem here. I've even tried installing the plugin globally (`npm install -g eslint-plugin-eslint`) and locally (`npm install eslint-plugin-react`). But neither of those helped the issue.

**Comment by Arcanemagus** [comment]
Duplicate of #259, please follow that for when a resolution is pushed out.
