### ISSUE TITLE
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly

### ISSUE THREAD

**Issue by kambing86** [AtomLinter/linter-eslint#267]
fix the issue

**Comment by steelbrain** [comment]
Have you installed `eslint` globally? If you have not, you can either install it or you can use the bundled one by disabling `Use Global ESLint` from your settings. If you want to use the eslint local to your project,  See #259

**Comment by kambing86** [comment]
i used 5.0.0 with global eslint without any issue, now just updated to 5.0.1 then got issue, definitely you didn't take note of the path correctly after putting code into worker.js

**Comment by steelbrain** [comment]
@kambing86 I'm about to push a release with several fixes. Please bear with us
