### ISSUE TITLE
linter-eslint 5.1.0  Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by escolhatecnologia** [AtomLinter/linter-eslint#275]
Error: Path must be a string. Received null

linter-eslint 5.1.0

**Comment by steelbrain** [comment]
That is very weird, would you mind posting your `~/.atom/config.cson`?

**Comment by Hendrik** [comment]
Had the same error after updating to 5.1.0, but restarting Atom fixed it and it didn't come up again so far.

**Comment by steelbrain** [comment]
Great! Closing based on comment above
