### ISSUE TITLE
Eslint rules dir location no longer working with 5.1.0

### ISSUE THREAD

**Issue by hatched** [AtomLinter/linter-eslint#281]
Before updating to 5.1.0 this morning it was respecting the dir name passed to the `Eslint Rules Dir` field `eslint-rules` . After updating, it no longer is loading our custom rules from that directory.

**Comment by steelbrain** [comment]
Thanks for the bug report @hatched. While rewriting this linter package, I didn't quite understand why somebody would need `eslintRulesDir`, Can you please specify a valid use case?

**Comment by hatched** [comment]
Definitely :) We have custom eslint rules stored in a directory in a project and then use those rules in the `.eslintrc`. Externally we then run our lint step as follows: 

```Makefile
.PHONY: lint-js
lint-js: $(NODE_MODULES)
	$(NODE_MODULES)/.bin/eslint --rulesdir eslint-rules/ $(SRC)
```

So when opening js files in atom the linter now throws a warning for the first line in every file saying that it cannot find the rules defined in the `.eslintrc`.

**Comment by globexdesigns** [comment]
Some problem here. We also have defined some custom rules for our projects and we keep those together with our custom configuration file. Defining custom rules is useful when you don't want to bother with creating an entire custom plugin package.

**Comment by steelbrain** [comment]
A fix is up in #286 
Can you please confirm that it works?

**Comment by hatched** [comment]
Thanks for the quick fix @steelbrain It works if I specify the full path to the directory. Previously I was able to specify a path relative to the directory atom was opened via which is also the path the .eslint was loaded from. 

How would you feel changing:
```JavaScript
argv.push('--rulesdir', params.rulesDir)
```
to:
```JavaScript
argv.push('--rulesdir', Path.join(eslintPath, params.rulesDir))
```

**Comment by steelbrain** [comment]
@hatched I would want you to get the credit for it, mind opening a PR? :)

**Comment by hatched** [comment]
That change of course assumes that people have their custom rules as a child of the project. A more robust solution might be to check for an absolute path first (prefixed with a `/`). 

Sure I can put together a PR tonight.

**Comment by hatched** [comment]
As requested: https://github.com/AtomLinter/linter-eslint/pull/292
