### ISSUE TITLE
EsLint of standalone JS not working after v3.1.1

### ISSUE THREAD

**Issue by JohnMurga** [AtomLinter/linter-eslint#291]
I open JS files in isolation sometimes, when there is no related project or .eslintrc file.

Under these conditions under 3.1.1 it does run EsLint with the default rules, which is nice for catching some issues when scanning code.

This hasn't been working for a while, despite the following in my config.cson.
```javascript
  "linter-eslint":
    disableWhenNoEslintrcFileInPath: false
```
Downgrading to 3.1.1 gives the desired behavior, any version after does not work.

I was thinking someone must have reported this, so have been manually downgrading to 3.1.1 on every update for a few weeks :scream:

**Comment by Arcanemagus** [comment]
`eslint` after version 1.0.0 have no default rules set, if you want a set of default configuration either place a `.eslintrc` file in your home directory (or whatever directory is a "parent" to your project folders), or hard code a configuration path in the very latest version.

**Comment by JohnMurga** [comment]
Thanks ...
Is it possible to get `.eslintrc` from `.atom` or a directory relative to that instead of `$HOME` or project ?
I maintain https://github.com/JohnMurga/atom-portable, and have not found a way of bundling a default `.eslintrc` file, which is why I have to roll back to 3.1.1 every time.

**Comment by steelbrain** [comment]
@JohnMurga We have a config where you can specify path to the eslintrc config and it'll be used when none is found in project

**Comment by JohnMurga** [comment]
@steelbrain yes, but the path is either absolute or relative to the project directory ...
For a portable setting I would need something relative to `$ATOM_HOME`

**Comment by steelbrain** [comment]
One "workaround" I can think of is by setting `.eslintrc` in `~/.atom/init.coffee`.

**Comment by JohnMurga** [comment]
@steelbrain that would be OK I guess ...
Please forgive me. but I am not quite sure  ...
Do you mean programatically setting the absolute `"linter-eslint".eslintrcPath` at startup ?

**Comment by steelbrain** [comment]
@JohnMurga Yep, that's what I mean, I think atom has services where you can wait until all packages have finished activation, and once they have, you can just set that config

**Comment by SpainTrain** [comment]
I think this https://github.com/AtomLinter/linter-eslint/pull/297 plus `$ATOM_HOME` would allow this use case?
