### ISSUE TITLE
error with extends local config having sublevels of node_modules folders 

### ISSUE THREAD

**Issue by tinchoz49** [AtomLinter/linter-eslint#294]
In v5.2.0 i have one case where i'm still getting the error using local plugin extends.

I'm working in a browserify project where i have the next folder structure:
```
node_modules/
src/
    components/
    styles/
    node_modules/
    index.js
.eslintrc
gulpfile.js
package.json
```
If i check the gulpfile.js with atom-eslint everthing works great. But if i check the src/index.js atom-eslint is trying to find the eslint config plugin in src/node_modules/ instead of the root node_modules, throwing the error: Cannot find module 'eslint-config-airbnb'

Note: in v4.0.0 is working fine.

**Comment by aruberto** [comment]
I ran into same issue. I was able to get it working again by modifying the find method in worker.js to return a string containing all found node_modules directories instead of returning the first found result. I've created pull request #313

**Comment by steelbrain** [comment]
@aruberto Thanks

**Comment by Arcanemagus** [comment]
Does `./node_modules/.bin/eslint` work while linting that file?

**Comment by Arcanemagus** [comment]
Well `npm` completely ignores a directory like that and just installs in the parent `node_modules`, which is really how this should be done, but if I manually create that folder and copy something in there then I can reproduce this.

**Comment by IanVS** [comment]
Where is eslint installed?

**Comment by lijunle** [comment]
Thanks @aruberto , your fix works good! :smiley_cat: 

@IanVS please look on #314 for eslint installation hierarchy.
