### ISSUE TITLE
Feature request: Use a default .eslintrc if one does not exist in the project

### ISSUE THREAD

**Issue by bjmiller** [AtomLinter/linter-eslint#31]
My use case is that I frequently open up JS files in different projects, or no project at all.  I'd like a set of my own defaults to be in use for these, rather than the packaged default.

Yes, I can turn eslint off entirely for such cases, but I'd rather still have linting and just not have the rules set that don't match my preferences or my shop's official gudelines.

I can submit a PR if the maintainers are OK with the feature, and don't have time to work on it themselves.

**Comment by jfaissolle** [comment]
The plugin (same behavior a eslint command line tool) uses all `.eslintrc` configs in the file hierarchy, that is, if you have a `.eslintrc` file in your home directory, it will server as defaults when there is no config in the project. Would putting your defaults in your home directory solve your problem ?

**Comment by bjmiller** [comment]
It looks like this is working.  Thanks for the tip.  Closing.
