### ISSUE TITLE
Support Configuration File Formats

### ISSUE THREAD

**Issue by ChristianMurphy** [AtomLinter/linter-eslint#317]
ESLint 1.10 deprecates `.eslintrc` and recommends using `.eslintrc.js`, `.eslint.yaml`, `eslint.yml`, or `.eslint.json`.

Reference http://eslint.org/blog/2015/11/eslint-v1.10.0-released/#configuration-file-formats

**Comment by steelbrain** [comment]
Just so you would know, those configurations should work fine with `linter-eslint`. Just disable `Disable when no .eslintrc in path` option while we support those

**Comment by ChristianMurphy** [comment]
Good to know, Thanks :smile:

**Comment by ChristianMurphy** [comment]
@steelbrain hmm it still doesn't seem to be picking up the config.

I'm running
`Atom` 1.3.0-beta5
`linter` 1.11.2
`linter-eslint` 5.2.1

`Disable when no .eslintrc is found` is off
`Global Node Installation Path` is set to my global Node 5.1.0 folder
`Use global ESLint installation` is true

`eslint -v` is v1.10.1
And the configuration file is `.eslint.yml`

Running ESLint from CLI picks up the file.
`linter-eslint` is currently not picking it up.
When I rename the file back to `.eslintrc` the file is picked up again.

**Comment by steelbrain** [comment]
@ChristianMurphy I am not sure what the problem is right now, but I'll investigate soon (unless someone beats me to it).

In the meanwhile, can you try the master branch to see if it fixes your problem?

```
apm uninstall linter-eslint
cd ~/.atom/packages
git clone --depth=1 https://github.com/AtomLinter/linter-eslint
cd linter-eslint
apm install
```

**Comment by ChristianMurphy** [comment]
I installed master version, same issue.

**Comment by ChristianMurphy** [comment]
When I modify [this line](https://github.com/AtomLinter/linter-eslint/blob/e0bc5aa96a8a154f7bc614e1856f3aa527dede45/lib/worker.js#L37) to `.eslintrc.yml` it picks up the file correctly.
A naive approach while I could open a PR for would be to do a for loop for each type.
But I'm not sure how that would affect the configuration file [precedence](http://eslint.org/docs/user-guide/configuring#configuration-file-formats).

**Comment by steelbrain** [comment]
A better approach would be to support an array of inputs in `findFile`, there is an implementation like that [here](https://github.com/AtomLinter/atom-linter/blob/master/lib/helpers.coffee)
