### ISSUE TITLE
Cannot pass in multiple rules dirs

### ISSUE THREAD

**Issue by christopherstott** [AtomLinter/linter-eslint#321]
It looks like eslintRulesDir only supports a single dir.

We have some rules supplied in an npm module, and some rules in our own repo, so need to pass in multiple rulesdirs.

For eslint on the command line it supports passing in --rulesdir multiple times

**Comment by IanVS** [comment]
I'm not saying this shouldn't be addressed, but in the meantime for the npm modules, can you use the `extends` syntax in your config?  http://eslint.org/docs/user-guide/configuring#extending-configuration-files
