### ISSUE TITLE
Can not find eslint-react-plugin

### ISSUE THREAD

**Issue by AJIh** [AtomLinter/linter-eslint#324]
Hi, I have just upgraded my linter-eslint to v5.2.2. But linter throws 'Can not find module eslint-react-plugin' when I edit my code. It worked well in v5.2.0.
My .eslintrc looks like this: 
```
{
    "parser": "babel-eslint",
    "rules": {
        "indent": [
            2,
            2
        ],
        "quotes": [
            2,
            "single"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ],
        "react/jsx-uses-react": 1,
        "react/react-in-jsx-scope": 1
    },
    "env": {
        "es6": true,
        "browser": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "ecmaFeatures": {
      "modules": true,
      "jsx": true
    },
    "plugins": [
        "react"
    ]
}

```

**Comment by steelbrain** [comment]
Are you using bundled eslint or global eslint? If you are using global, then have you installed `eslint-plugin-react` globally? for local eslint, it needs to be installed in your project root

**Comment by AJIh** [comment]
I am using local eslint. `eslint` and `eslint-plugin-react` are all in local node_modules. 
This is my linter-eslint config:
```
  "linter-eslint":
    disableWhenNoEslintrcFileInPath: false
```

**Comment by just-boris** [comment]
Got a similar issue: 
```
Cannot read config package: eslint-config-rackt
```
I am using local `eslint` installation and it passes fine when I run it from console. My `.eslintrc` is follows
```
{
  "extends": "rackt"
}
```

**Comment by NicholasGW** [comment]
Seeing this issue as well, tried both local and global install

**Comment by cryptoquick** [comment]
Local eslint is still broken as of 5.2.4.
