### ISSUE TITLE
.eslintrc.js

### ISSUE THREAD

**Issue by iamstarkov** [AtomLinter/linter-eslint#327]
eslint 1.10 [added new types of configuration](http://eslint.org/blog/2015/11/eslint-v1.10.0-released/#configuration-file-formats) files `.eslintrc.js`, `.eslintrc.yml` and `.eslintrc.json`. And `.eslintrc` will be deprecated in first major update.

I think linter-eslint should start support them too.

**Comment by steelbrain** [comment]
Dupe of #317

**Comment by iamstarkov** [comment]
sorry, was looking into open issues
