### ISSUE TITLE
Dead workers causing memory leak?

### ISSUE THREAD

**Issue by tylerFowler** [AtomLinter/linter-eslint#330]
I've been noticing for a little while now (read: ~1.5 weeks) that the linter worker will randomly crash with a message like: `Worker died unexpectedly. Check console for more info`. Then in the console I'll either get `stdout` & `stderr` properties that are just empty strings, or sometimes `stderr` will be a malloc error (will update with one of those when it happens, that case is more rare).

So I've been dealing with this for a while but got an update that restarted the worker every time it crashed so it hasn't been too disruptive, until today when it had been happening for a while OSX told me I was out of memory. So I pulled up ActivityMonitor and saw this:

![eslint-memory](https://cloud.githubusercontent.com/assets/5419372/11348611/13ad6a46-91ed-11e5-87e4-5f55035a7d7e.png)

So it looks like maybe workers that die are leaking, though I've gone through eslint worker die/respawn cycles for much longer than I did today without running into memory issues so it could have been introduced in the most recent update (5.2.3).

### System:
Atom: `1.2.3`
OSX: Capitan `10.11.1`
Node: `5.1.0`

It's worth noting that I'm also using the atom-ternjs (0.9.0), which is also crashing randomly a lot, could be related.

**Comment by steelbrain** [comment]
The numbers are actually quite scary. I've never seen a node app use that much amount of memory. It's not the module that's causing a memory leak, but a bug in the `electron` (Atom's runtime). This memory leaking issue has been fixed in the beta, it should be in the next stable.

Ref: https://github.com/AtomLinter/linter-eslint/issues/278#issuecomment-157892974

**Comment by steelbrain** [comment]
@tylerFowler Can you install the atom beta and see if it fixes this for you? The beta will install alongside your current installation and will not modify your stable installation in any way.

**Comment by tylerFowler** [comment]
Interesting I didn't know about that, and yeah I haven't seen a node app use that much memory either. That's bananas.

I'll try the beta tonight and let you know what I find.

**Comment by sheeley** [comment]
I encountered this last night - nearly the same memory usage, yowza. I haven't figured out how to reproduce, but I downloaded the beta and I don't see the issue with workers dying or memory leaking.

**Comment by Arcanemagus** [comment]
I hope you mean "workers **not** dying"? :stuck_out_tongue:
