### ISSUE TITLE
Info: Workers not initialized yet, please try again shortly.

### ISSUE THREAD

**Issue by jpdatalicious** [AtomLinter/linter-eslint#333]
Anyone else having error like this? Eslint won't run..

![image](https://cloud.githubusercontent.com/assets/13620831/11389264/911caeaa-9379-11e5-9f9b-077e5ae90513.png)

**Comment by darkred** [comment]
I have the same issue. 
`Atom 1.3.0 beta 6` in win10x64
`linter-eslint` v5.2.4, 
`eslint` v1.10.1

**Comment by steelbrain** [comment]
This is not an issue, it's just 5 seconds delay before worker is spawned. After atom is opened, wait five seconds, save a js file and you'll find that eslint lints it.

**Comment by jpdatalicious** [comment]
I'm waiting for hours already :-)

**Comment by steelbrain** [comment]
@jpdatalicious That is definately weird.

cc @Arcanemagus

**Comment by darkred** [comment]
> This is not an issue, it's just 5 seconds delay before worker is spawned. 
> After atom is opened, wait five seconds, save a js file and you'll find that eslint lints it.

You're talking about having Atom already open, wait 5 sec, then open a js file.
But, if you launch Atom via opening a .js file with rightclick|`Open with Atom` (in File Explorer),
then the opened file is never linted, unless you close and re-open it.

**Comment by IanVS** [comment]
All you need to do is save the file, or if you have continuous linting set up, start typing something.  I've noticed this same behavior if reloading (view -> reload) Atom while a JS file is open.

**Comment by Arcanemagus** [comment]
Sounds like more bugs with Atom not activating packages properly, although wasn't it supposed to respawn a worker if one wasn't found @steelbrain?

**Comment by steelbrain** [comment]
@Arcanemagus It respawns a worker when it crashes yes, but `not found` isn't even a scenario, it's supposed to spawn one, I can't see why it wouldn't.

**Comment by Arcanemagus** [comment]
Atom has issues with running the activate() command for a package occasionally, especially on session resume (Starting Atom and it re-opens the files that were already open last time).

**Comment by sheeley** [comment]
@steelbrain would you consider changing the wording? I was under the impression something was broken as well - it might be clearer if the message were something along the lines of "Worker start delayed - save or type to begin linting"?

**Comment by steelbrain** [comment]
I would be happy to accept a PR with a nicer message :)

**Comment by sheeley** [comment]
#336 :)

**Comment by OKNoah** [comment]
Linting is not working for me in Atom, and I see this message as well. Other times this error does not show and it just says "no issues". Atom often gives a "quit unexpectedly" when I close the app, not sure if that's related. It also lags for a few seconds at a time and removing focus and focusing back on the window _seems_ to help that.

**Comment by IanVS** [comment]
@steelbrain See any issues with taking out the delay?  I know you had that in your more major PR (https://github.com/AtomLinter/linter-eslint/pull/344), but it might be worth making this one simple fix apart from that one.

**Comment by Arcanemagus** [comment]
@OKNoah are you using the Atom beta or are you on stable? There is a pretty major bug in Atom related to sub-processes causing them to leak memory, eventually filling up the system's RAM. It sounds like you might be hitting that and updating to the v1.3.0 betas fixes that.

**Comment by OKNoah** [comment]
@Arcanemagus I'm not on any beta as far as I know. I have just reinstalled Atom.

**Comment by IanVS** [comment]
You can install atom-beta side-by-side with the normal Atom version.  That's what I've done, and the beta uses the same configuration and preferences as your existing Atom.

**Comment by darkred** [comment]
[**@IanVS**](https://github.com/IanVS) commented on [Dec 7, 2015, 8:50 PM GMT+2](https://github.com/AtomLinter/linter-eslint/issues/333#issuecomment-162622102 "2015-12-07T18:50:44Z - Replied by Github Comment Enhancer"):
> You can install atom-beta side-by-side with the normal Atom version.  That's what I've done, and the beta uses the same configuration and preferences as your existing Atom.

I had Atom 1.0.19 stable installed (in win10 x64). Installing beta 1.3.0 beta, **replaced** the stable installation (without asking any user confirmation)

**Comment by IanVS** [comment]
Hm, strange.  Maybe that only applies to Atom 1.2 and 1.3 beta.  I'm sorry. :-/

**Comment by IanVS** [comment]
Their page (https://atom.io/beta) specifically says:

> The Atom Beta runs side-by-side with the Atom stable release

So, maybe that was a bug that you experienced.

**Comment by nmn** [comment]
I have the same problem. I have not been able to make eslint work for weeks now. other linters, line linter-flow still seem to work fine most of the time.

**Comment by jpdatalicious** [comment]
@nmn What's your Atom config like? I got mine working back ...

**Comment by eaigner** [comment]
Doesn't work for me either. Worker is never initialised (not even after 5 seconds)

**Comment by steelbrain** [comment]
Everyone, this delay will be removed in the next release, expect it soon

**Comment by nmn** [comment]
@jpdatalicious I just got it to work again. Just changed somethings in my config.

**Comment by eaigner** [comment]
"some things"?

**Comment by nmn** [comment]
Now it looks like this:
```
"linter-eslint":
    disableWhenNoEslintrcFileInPath: false
    disableEslintIgnore: false
    globalNodePath: "/usr/local"
    useGlobalEslint: false
```

removed the custom rules key allotter. And all the trues changed to false.

**Comment by Zorgatone** [comment]
Same issue with me... Same message and waited hours but my JS code doesn't get linted. I'm on Windows 10 latest Atom version (no beta).

I just installed the eslint plugin and I already tried to close and reopen Atom
