### ISSUE TITLE
Version 5.2.3 breaks import/no-unresolved rule

### ISSUE THREAD

**Issue by IanVS** [AtomLinter/linter-eslint#335]
I haven't dug into what could be causing this, but when upgrading from `5.2.2` to `5.2.3` I begin to get failures from [import/no-unresolved](https://github.com/benmosher/eslint-plugin-import#no-unresolved) for all of my relative imports.

### 5.2.2

![screen shot 2015-11-25 at 9 05 56 am](https://cloud.githubusercontent.com/assets/4616705/11399382/00f5b21e-9355-11e5-9b80-19ce7cb1da6f.png)

### 5.2.3

![screen shot 2015-11-25 at 9 14 05 am](https://cloud.githubusercontent.com/assets/4616705/11399384/07cf8ab0-9355-11e5-8b29-aa289faa64a9.png)

**Comment by Arcanemagus** [comment]
Do you mean 5.2.4? 5.2.3 only fixes a small bug in 5.2.2.

**Comment by IanVS** [comment]
Yep, I'm sure.

```
apm install linter-eslint@5.2.2
```

![screen shot 2015-11-25 at 2 57 55 pm](https://cloud.githubusercontent.com/assets/4616705/11408122/2e0cdab8-9385-11e5-9bfa-103502f8a62b.png)

```
apm install linter-eslint@5.2.3
```

![screen shot 2015-11-25 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/4616705/11408132/365d05c6-9385-11e5-882e-7989f64038b7.png)

**Comment by IanVS** [comment]
Also, upgrading to 5.2.4 does not solve the issue.

**Comment by Arcanemagus** [comment]
It has to be https://github.com/AtomLinter/linter-eslint/pull/325 then as that was the only thing within that release.

**Comment by steelbrain** [comment]
@Arcanemagus that is actuall a fix, not a bug :wink:

**Comment by Arcanemagus** [comment]
I know, but it's the _only_ thing in v5.2.3, so it broke _something_ :P

**Comment by steelbrain** [comment]
:joy:

**Comment by IanVS** [comment]
Yep, reverting #325 solves my problem.  Now to figure out why...
