### ISSUE TITLE
Dealing with "Cannot find module 'eslint-plugin-react'" and "Unable to execute npm get prefix errors

### ISSUE THREAD

**Issue by cryptoquick** [AtomLinter/linter-eslint#338]
I'm getting the error: `Cannot find module 'eslint-plugin-react'`

I then tried installing eslint globally, along with eslint-plugin-react, but I then get:

`error: Unable to execute npm get prefix. Please make sure Atom is getting $PATH correctly`

I then tried setting the following in my `.bash_profile`:

`export PATH=$PATH:$(which eslint)`

I source it and I can verify that is present in my bash shell, but I still get that error.

**Comment by steelbrain** [comment]
For future visitors, dupe of #339

**Comment by Arcanemagus** [comment]
Future visitor thanks you :stuck_out_tongue:.
