### ISSUE TITLE
Dealing with "Cannot find module 'eslint-plugin-react'" and "Unable to execute npm get prefix" errors

### ISSUE THREAD

**Issue by cryptoquick** [AtomLinter/linter-eslint#339]
I'm getting the error: `Cannot find module 'eslint-plugin-react'`

I then tried installing eslint globally, along with eslint-plugin-react, but I then get:

`error: Unable to execute npm get prefix. Please make sure Atom is getting $PATH correctly`

I then tried setting the following in my `.bash_profile`:

`export PATH=$PATH:$(which eslint)`

I source it and I can verify that is present in my bash shell, but I still get that error.

Environment is:

OS X El Capitan 10.11.1
Atom 1.2.4
linter-eslint (tried 5.1.0, 5.2.0, and 5.2.4)

**Comment by steelbrain** [comment]
```
export PATH=$PATH:$(which eslint)
```
^ that is an incorrect `$PATH` value, it expects folders not files and `which eslint` returns the exact `eslint` file path

**Comment by cryptoquick** [comment]
Um, I changed it to this in my .bash_profile, and it's still providing the `npm get prefix` error, even after restarting Atom:
`export PATH=$PATH:/Users/hunter/.nvm/versions/node/v4.1.2/bin`

Also, pardon opening two tickets, it was by accident. I would prefer if you didn't close the ticket before I confirm the issue is resolved on my end, though.

**Comment by steelbrain** [comment]
Can you post the output of `which npm` from terminal and `process.env.PATH` from the atom dev tools?

**Comment by cryptoquick** [comment]
Output of `which npm`:
`/Users/hunter/.nvm/versions/node/v4.1.2/bin/npm`

Output of `process.env.PATH` from Atom dev tools:
`"/usr/bin:/bin:/usr/sbin:/sbin"`

Not sure what this means.

**Comment by steelbrain** [comment]
This means that you are on OSX and you are not launching Atom from Terminal

**Comment by cryptoquick** [comment]
I just tried installing node 5.1.0 from nodejs.org, to see if I'd get a different result. I then reinstalled eslint and eslint-plugin-react. I found it installed to a different place now.

```bash-3.2$ which eslint
/usr/local/bin/eslint```

So, I updated my .bash_profile:

`export PATH=$PATH:/usr/local/bin`

I think that was already there, though, seems like a pretty common place.

Still getting the `npm get prefix` error, though, even after restarting Atom.

Interesting, though. If I launch atom from terminal, as you suggested, I get a different error. 

`Cannot find module 'babel-eslint'`

This is a promising development, since that's from the linter drawer.

Not sure I want to ask my colleagues to start atom from the command line every time, though...

**Comment by cryptoquick** [comment]
Looks like starting from the terminal and installing `babel-eslint` will work for now.

I'm guessing atom has to be started from the terminal to use global eslint.

Is there a way I can use local eslint?

**Comment by steelbrain** [comment]
If you want Atom to act as a runtime and make `linter-eslint` use the bundled `eslint`. You should disable `Use Global ESLint` from package settings, but after you do that it will no longer pick global dependencies, you will have to install them in your project (maybe as dev dependencies?)

**Comment by cryptoquick** [comment]
Ah! Great idea. I guess the moral of the story is, always install your linter dependencies locally. Thank you so much for helping me get here so quickly.

**Comment by IanVS** [comment]
Yes, the ESLint team generally recommends against installing eslint globally at all.
