### ISSUE TITLE
Feature Request: Ignore whitespace while editing

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-eslint#34]
Atom automatically strips the trailing whitespace on save, so it would be nice for that to now show up while I'm editing. Not everyone on my team uses atom, so I'd prefer not to have to turn the rule off in my `.eslintrc`.

**Comment by jfaissolle** [comment]
I wonder if this should be a linter-eslint option (implemented by overriding the corresponding eslint option) or an AtomLinter option implemented by pre-trimming whitespaces before linting as this behavior would be useful for other linters too.

**Comment by iam4x** [comment]
Closed by https://github.com/AtomLinter/Linter/issues/700
