### ISSUE TITLE
5.2.5 - Fix File - Linting Errors Remain

### ISSUE THREAD

**Issue by albertosantini** [AtomLinter/linter-eslint#353]
On Windows 10, using `Fix File` command with `5.2.5` I get always the following message:
`Linter-ESLint: Fix Attempt Completed, Linting Errors Remain`

Settings:
```
 "linter-eslint":
    useGlobalEslint: true
```

Investigating it seems the config file is not correct, like `C:\my\project\path.eslintrc.yml`: notice missing backslash between path and the config file.

https://github.com/AtomLinter/linter-eslint/blob/master/lib/worker.js#L88

I cannot give more details because, at the moment, for every change I get the annoying spawn bug.

**Comment by IanVS** [comment]
@albertosantini, thanks for the report. 

ESLint cannot guarantee that all linting errors will be fixed, only some rules are "fixable".  So, that message is telling you that fixing was performed, but there is still at least one rule violation remaining in the file.  The message itself isn't something to normally be concerned about.

The missing backslash could indeed be a problem, how did you determine this path?  Are the linting error messages displayed in the editor not the kinds which you would expect given your configuration?  @steelbrain, maybe this is something you can investigate and test in `findFile` from `atom-linter`?  I don't have a Windows box handy.

As for the spawn bug, are you able to upgrade to atom-beta?  That would solve that particular issue.  It will give you both normal Atom and Atom Beta side-by-side, and they will share the same configuration.  I've been using the beta and have been quite happy with it so far.

**Comment by steelbrain** [comment]
This world sure is full of surprises, I'll test the `findFile` method on windows to see if it's a windows-specific bug

**Comment by albertosantini** [comment]
@IanVS Firstly I tried using the command line `eslint --fix`. 
If it fixes all the linter errors, I would expect `Fix File` command has the same result.
It seems no sort of `--fix` is executed.

About the path, I created a message string with the relevant variables (for instance `configFile`) and then `reject(myMesssage)` replacing `reject('Linter-ESLint: Fix Attempt Completed, Linting Errors Remain')`. Here `err` is null`. Primitive form of debugging, but effective. :)

(I didn't enjoy the beta - of course, eslint-linter is not guilty. Sigh)

**Comment by albertosantini** [comment]
(On Windows box) I verified `findFile` in `atom-linter` and it returns the correct path.
I printed again, just to be sure, `configFile` (from `determineConfigFile(params)`) and it is missing the last backshlash, between the path and the name of the config file.

Investigating...

**Comment by albertosantini** [comment]
Really I didn't get the problem with the config file. Very weirdly.

I followed another path: `on('JOB'...` and `on('FIX'...` are very similar.

So, with a very quick and dirty change, it works nice with the following approach:

```
Communication.on('FIX', function(fixJob) {
  const params = fixJob.Message
  const modulesPath = find(params.fileDir, 'node_modules')
  const eslintDir = findEslintDir(params)
  const configFile = determineConfigFile(params)
  const eslintBinPath = Path.normalize(Path.join(eslintDir, 'bin', 'eslint.js'))

  if (modulesPath) {
    process.env.NODE_PATH = modulesPath
  } else process.env.NODE_PATH = ''
  require('module').Module._initPaths()

  // Determine which eslint instance to use
  const eslintNewPath = findEslintDir(params)
  if (eslintNewPath !== eslintPath) {
    eslint = getEslintCli(eslintNewPath)
    eslintPath = eslintNewPath
  }

  const argv = [
    process.execPath,
    eslintPath,
    params.filePath,
    '--fix'
  ]

  if (configFile !== null) {
    argv.push('--config', resolveEnv(configFile))
  }

  fixJob.Response = new Promise(function(resolve, reject) {
    try {
      process.argv = argv
      eslint.execute(process.argv)
    } catch (err) {
      reject('Linter-ESLint: Fix Attempt Completed, Linting Errors Remain')
    }
    resolve('Linter-ESLint: Fix Complete')
  })
})
```

Suggestion.
Why not remove `.on('FIX'...` and using only `.on('JOB'...` passing, for instance, a `canFix` (true or false) param and conditionally pushing different arguments?
