### ISSUE TITLE
Specify file pattern for eslint rules file

### ISSUE THREAD

**Issue by vproman** [AtomLinter/linter-eslint#357]
I'd like to have a separate lint config for my unit test (.spec.js) files.  Our project structure has the .spec.js files in the same dir as the files they are testing.

**Comment by Arcanemagus** [comment]
The simplest solution is to just do what everybody else does and put your specs in a folder of their own (where you can put an `eslint` configuration in there).

Without doing that you are rather limited here and I'm not sure how this would ever work in a plugin scenario. To do this from the command line you would need to specify the configuration file you want to use for each run. You can do that already with this package with the "ESLint Rules Dir" setting, but you would need to edit that based on the file you have open at the time.

I don't think this is really a scenario that can be handled without heavily customizing the way the package works to your specific project, thoughts @AtomLinter/linter-eslint?

**Comment by steelbrain** [comment]
If we support this special use case in this package, we'd be diverging from the base `eslint`. I would highly recommend we raise this request in their repo and have it supported there so this feature would be available to a broader audience

**Comment by SpainTrain** [comment]
I need this feature also. Agree with @steelbrain and it's already an issue on the upstream - https://github.com/eslint/eslint/issues/3611

**Comment by steelbrain** [comment]
Closing based on comment above
