### ISSUE TITLE
Add Setting to Show Lint Error on Mouseover

### ISSUE THREAD

**Issue by targeter21** [AtomLinter/linter-eslint#36]
It would be really useful to show the lint error on mouseover instead of clicking the problem line. I'm used to it in other editors and IDE's that do that.

**Comment by jfaissolle** [comment]
Hello @targeter21. The display of errors is not performed by linter-eslint. This plugin only makes the bridge with elsint to retrieve errors.  The graphics/reporting part is done by the https://github.com/AtomLinter/Linter plugin. You should file an issue there if you want this functionality.

**Comment by targeter21** [comment]
@jfaissolle Ahh my mistake, I will log it to the appropriate project. Thanks!
