### ISSUE TITLE
debugging / running

### ISSUE THREAD

**Issue by dcsan** [AtomLinter/linter-eslint#360]
I'm having trouble getting started with this linter and wondering how to debug it / where to look.

- I've installed the package
- I'm working on a meteor project, so there is no local `node_modules` directory. I've configured the Global Node Installation path.

added a `.eslintrc` to the root of my project.

opening any .js or .jsx file, there is no "lint" command in the command palette.
there is a `linter/fix file`

![image](https://cloud.githubusercontent.com/assets/514002/11662756/3a910c84-9d8d-11e5-884a-6ef67f6eea05.png)

running that simply gives 
![image](https://cloud.githubusercontent.com/assets/514002/11662775/51db65b0-9d8d-11e5-8041-ecec75da7a95.png)

If I make obvious errors in the file, these are not found as errors. In short it looks like the linter is 'running' but not doing anything.

Is there a console window to see what's going on when the linter process runs (like sublime's console)

thanks!

**Comment by dcsan** [comment]
needs basic linter enabled.

**Comment by Arcanemagus** [comment]
That's odd, it should have installed that for you. Glad you got it figured out though!

**Comment by dcsan** [comment]
i had disabled it since i thought it might conflict. didn't realize it was required underpinnings. thanks!

**Comment by Arcanemagus** [comment]
Ah, yea `linter` is the actual package that handles running and displaying results. The `linter-*` packages are service providers for it. For example this one acts as an interface to `eslint` but there are dozens of other service providers for it.
