### ISSUE TITLE
Replace childprocess-promise with process-communication

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-eslint#364]
When installing dependencies the following message is printed:
```
npm WARN deprecated childprocess-promise@3.0.0: Use process-communication instead
```

@steelbrain I'm assigning this to you as it seems you are the author of both packages :wink:.

**Comment by steelbrain** [comment]
Yeah I did a complete rewrite and optimized a lot of things, will be replacing soon

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-eslint/pull/367
