### ISSUE TITLE
Getting eslint error when package eslint doesn't report it

### ISSUE THREAD

**Issue by devinus** [AtomLinter/linter-eslint#365]
I'm using the `babel-eslint` parser, however it doesn't seem to be using it in this plugin.

<img width="502" alt="screen shot 2015-12-10 at 8 36 54 pm" src="https://cloud.githubusercontent.com/assets/4836/11734535/c552bbe6-9f7d-11e5-9d4e-268c89f17a45.png">

<img width="855" alt="screen shot 2015-12-10 at 8 35 37 pm" src="https://cloud.githubusercontent.com/assets/4836/11734531/b8d7b830-9f7d-11e5-983c-d40fbcd4a4ed.png">

**Comment by SpainTrain** [comment]
In the screenshot, that error is coming from JSHint.

**Comment by devinus** [comment]
@SpainTrain I'm an idiot. Thanks!

**Comment by SpainTrain** [comment]
:+1:  Not the first time this mix up has happened, and will likely not be the last :smile_cat:

**Comment by steelbrain** [comment]
I guess adding linter names to messages was a good decision

**Comment by Arcanemagus** [comment]
I absolutely love knowing which linter a message is coming from :wink:.
