### ISSUE TITLE
Convert to ES6

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-eslint#366]
Okay guys, I am gonna do an iteration 2 of converting the package to es6. Here's how I am gonna do it:

1. I'm gonna create a branch named es6 based on master
2. I'm gonna send PRs TO es6
3. Eventually, gonna merge that es6 into master

I'm gonna do smaller, focused PRs to make review easier

__Note:__ APM uses the repo releases tags from github to download packages, so we can't `.gitignore` dist files, we'll have to include them in the repo

Here are some things that I would try to solve while doing this:

- [ ] A spec for everything
- [x] Unify both worker jobs in one to avoid code de-duping and getting out of sync
- [x] Unify both helper modules

cc @SpainTrain @Arcanemagus @IanVS @iam4x @Adezandee

**Comment by tinchoz49** [comment]
great idea @steelbrain !

**Comment by grabbou** [comment]
Any help needed? I've checked the source code and I can see some places where I could help with simplifications!

**Comment by steelbrain** [comment]
@grabbou I could use some reviews here https://github.com/AtomLinter/linter-eslint/pull/373
