### ISSUE TITLE
Linter cannot recognize ES7 Decorators.

### ISSUE THREAD

**Issue by yadhu-QB** [AtomLinter/linter-eslint#369]
![eslint](https://cloud.githubusercontent.com/assets/12905327/11738576/e099d51a-a009-11e5-8ece-b6ed37a9edd9.png)
I am using React with Radium which uses Babel and hence supports some of the proposed ES2016 standards. The Decorators cause the above error.

```
...
@Radium   //Error at this line.
class Hero extends Component {
...
```
Is there some way to turn this off?
I am using both linter and linter-eslint and have looked through the documentation for both of these packages with no luck. That's not to say it is not there. Am I missing something?

**Comment by steelbrain** [comment]
This package is just an [`eslint`](https://github.com/eslint/eslint) messenger for atom. You might wanna google on it's docs

**Comment by SpainTrain** [comment]
If you are using babel 6, decorators aren't supported as they were in 5 (https://phabricator.babeljs.io/T2645).  There is a plugin to bridge the gap until the standard is proposed (https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy).  Or just do what I did - stick with babel 5 for now =-)
