### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by openben** [AtomLinter/linter-eslint#37]
Hi there, 
I am experiencing an error when trying to run use the linter-eslint plugin. This occurs since the last update. Before that it always worked fine. 

1. Open atom.io
2. Open any .js file

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.4.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\user\.atom\packages\linter-eslint\lib\linter-eslint.coffee:54

TypeError: undefined is not a function
  at LinterESLint.lintFile (C:\Users\user\.atom\packages\linter-eslint\lib\linter-eslint.coffee:54:38)
  at C:\Users\user\.atom\packages\linter\lib\linter-view.coffee:158:18
  at Array.forEach (native)
  at C:\Users\user\.atom\packages\linter\lib\linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:18.7 application:open-folder (atom-text-editor.editor)
     -0:15.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:05.7 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "git-diff"
    ]
  },
  "linter-eslint": {
    "disableWhenNoEslintrcFileInPath": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.0
file-icons, v1.5.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-eslint, v0.4.1
linter-jsonlint, v0.1.2
linter-xmllint, v0.0.5
minimap, v4.3.1

# Dev
No dev packages
```

**Comment by jfaissolle** [comment]
Hello, I could not reproduce the problem. Version 0.4.0 introduces the use of the local version of eslint if found in the project node_modules. Perhaps you have an old eslint installed in your project ?

**Comment by openben** [comment]
Hi, sorry for the late reply and thanks for the advice. The outdated eslint version caused the problem.
