### ISSUE TITLE
Atom 1.4-beta0

### ISSUE THREAD

**Issue by dvdplm** [AtomLinter/linter-eslint#372]
Not sure what's going on, but as of this morning and the new Atom 1.4-beta0 the linter does not start. No error messages, so I'm not sure if it's the linter or linter-eslint having problems. Any debugging hints?

**Comment by Arcanemagus** [comment]
It's working fine for me on the latest version of everything, so that is definitely odd. Are you seeing anything in the console? You can also try deleting `~/.atom/compile-cache` to clear out any lingering old cache files.

**Comment by steelbrain** [comment]
Here's an entry from [`1.3.0-beta6`](https://github.com/atom/atom/releases/tag/v1.3.0-beta6) `Fixed a state serialization issue introduced in 1.3.0-beta5. Delete ~/.atom/storage if Atom fails to start after upgrading to this version after using 1.3.0-beta5.
`

**Comment by steelbrain** [comment]
If that didn't fix the problem for you, let us know
