### ISSUE TITLE
Cannot fix issues in HTML files.

### ISSUE THREAD

**Issue by liudangyi** [AtomLinter/linter-eslint#374]

**Comment by JamesMowery** [comment]
Same issues here. Here's a few images for context:

![Error](http://d.pr/i/1g090+)
![Error](http://d.pr/i/1esvu+)
![Settings](http://d.pr/i/17J3V+)

**Comment by liudangyi** [comment]
Seems you didn't install `eslint-plugin-html`. My problem is that linter-eslint cannot *fix* issues in HTML.

**Comment by Arcanemagus** [comment]
@JamesMowery your configuration is also in the wrong format, see [here](https://github.com/AtomLinter/linter-eslint/blob/v5.2.6/spec/fixtures/configs/js/.eslintrc.js) for an example of how JS configurations should look.

@liudangyi does `eslint` from the command line work for fixing issues within HTML?

**Comment by JamesMowery** [comment]
I just fixed it following the example.

![Example](http://d.pr/i/1dXIU+)

I did that, but it is still showing me the errors on the html file. Any suggestions?

**Comment by JamesMowery** [comment]
Actually, now I'm getting this error:

![Error](http://d.pr/i/1a5c7+)

**Comment by Arcanemagus** [comment]
You would need to list that package as a {dev}Dependency, along with `eslint`, then run `npm install` in your project.

**Comment by liudangyi** [comment]
@Arcanemagus `eslint` doesn't support fixing codes in HTML. http://eslint.org/docs/user-guide/command-line-interface#fix says "This option has no effect on code that uses processors". :disappointed:

**Comment by Arcanemagus** [comment]
Figured it was something like that but didn't have time to look it up when asking that. Glad to know the root issue at least, thanks!
