### ISSUE TITLE
Handle tilde expansion in .eslintrc path option

### ISSUE THREAD

**Issue by geakstr** [AtomLinter/linter-eslint#380]
Please fix this because when I write something like `~/Dropbox/Atom/.eslintrc` this transforms to `/~/Dropbox/Atom/.eslintrc`

**Comment by IanVS** [comment]
I don' think this is a matter of relative vs. absolute, it's that we are not handling the tilde expansion.  I would consider this a bug.

Relative paths don't really make sense (i.e. `'../../.eslintrc') in this scenario, because there's no reasonable expectation of what `cwd` should be.

**Comment by steelbrain** [comment]
We're already support ENV vars in config path, so instead of doing `~/Dropbox/Atom/.eslintrc`, you could do `$HOME/Dropbox/Atom/.eslintrc` and it would work

**Comment by geakstr** [comment]
Thank your, it's works
