### ISSUE TITLE
What to do with option which prevents linting when no config file is found

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-eslint#383]
Continuing discussion from https://github.com/AtomLinter/linter-eslint/issues/378:
[**@rugk**](https://github.com/rugk) commented on [20. Dez. 2015, 21:17 MEZ](https://github.com/AtomLinter/linter-eslint/issues/378#issue-123180840 "2015-12-20T20:17:06Z - Replied by Github Comment Enhancer"):
> In the settings I could find a setting which prevents execution when no ESLint config file is found and I disabled it and thought it would use some defaults, but there were still no linter errors.

[**@SpainTrain**](https://github.com/SpainTrain) commented on [20. Dez. 2015, 22:46 MEZ](https://github.com/AtomLinter/linter-eslint/issues/378#issuecomment-166156899 "2015-12-20T21:46:22Z - Replied by Github Comment Enhancer"):
>  The option you mention was added before this linter used 1.0, so it made more sense at the time.

> @AtomLinter/linter-eslint Thoughts on removing this option and instead issuing a warning or something when no .eslintrc file is found?

[...]

[**@Arcanemagus**](https://github.com/Arcanemagus) commented on [21. Dez. 2015, 06:29 MEZ](https://github.com/AtomLinter/linter-eslint/issues/378#issuecomment-166208431 "2015-12-21T05:29:57Z - Replied by Github Comment Enhancer"):
> I agree that option should probably be removed, if a configuration can't be found we should just put a Warning "message" on the first line about needing a configuration.

**Comment by steelbrain** [comment]
I am personally in favor of the current behavior as mentioned by @Arcanemagus. I believe that people use different configurations per project, they might use `JSHint` in one and `ESLint` in another. Adding a message saying `no .eslintrc was found` to every opened text editor is abuse IMO. We have already clarified the way it works in the README, we do not need to alter this behavior because it would spam the bottom panel

**Comment by rugk** [comment]
> Adding a message saying no .eslintrc was found to every opened text editor is abuse IMO.

I agree, but what to do with this option? Currently it does not really make a difference whether it is enabled or not.

**Comment by steelbrain** [comment]
@rugk It does, if you don't have a `.eslintrc` and that option is set to ignore non-existing config, `eslint` will give you syntax errors in your javascript code

**Comment by rugk** [comment]
> eslint will give you syntax errors in your javascript code

Ah okay. That's the only difference.

**Comment by IanVS** [comment]
@steelbrain Ah yes, I forgot about syntax errors.  Good point.

**Comment by SpainTrain** [comment]
Agree with everything here.
