### ISSUE TITLE
Support typing delay when performing linting

### ISSUE THREAD

**Issue by ajsharp** [AtomLinter/linter-eslint#385]
It would be great if there were a setting where the linter wouldn't be invoked until after a specified delay.

**Comment by SpainTrain** [comment]
Yes, [debouncing](https://lodash.com/docs#debounce) makes sense for this operation.

I think we really want this in the atom-linter helper function.  @steelbrain @Arcanemagus thoughts?

**Comment by Arcanemagus** [comment]
This setting is already present in `linter` as "Lint As You Type Interval". If this isn't working properly for you please file a bug on the [linter](https://github.com/atom-community/linter) package :wink:.
