### ISSUE TITLE
Doesn't lint unsaved file

### ISSUE THREAD

**Issue by darkred** [AtomLinter/linter-eslint#390]
Currently using Atom 1.3.2 stable with: `linter` 1.11.3, `linter-eslint` 5.2.7 
and `eslint` 1.10.3 _(with a `.eslintrc` file in `C:\Users\User`, in win 10 x64)_.

***

To reproduce just open a New File(Ctrl+N), select `JavaScript` in the bottom right corner, 
and type, e.g. 
```
a =;
```
The `Parsing error: unexpected token ;` won't be displayed unless you either:
- save the content to a new .js file, or 
- open an existing .js file with the above content  

_(In both cases, however, if then you further edit the opened files, any errors will be highlighted, as expected)_

**Comment by steelbrain** [comment]
It's actually the base linter who ignores unsaved files, and it's the wanted behavior.
