### ISSUE TITLE
Two rules from eslint-config-airbnb fail

### ISSUE THREAD

**Issue by silvenon** [AtomLinter/linter-eslint#394]
I have the following config:

```json
{
  "extends": "airbnb"
}
```

linter-eslint cannot find rules `react/no-deprecated` and `react/no-is-mounted` (it prints out a warning). It can find other `react/*` rules though. I checked if this happens just by running ESLint, but it doesn't, it seems to be some weird linter-eslint issue.

Any ideas?

**Comment by silvenon** [comment]
Forgot to refresh Atom after updating ESLint plugins.

**Comment by Arcanemagus** [comment]
Glad to hear you got it figured out, was a bit stumped myself :stuck_out_tongue:.
