### ISSUE TITLE
Set Preferred Line Length based on .eslintrc

### ISSUE THREAD

**Issue by arv** [AtomLinter/linter-eslint#395]
If .eslintrc has `max-len` set it would be nice if Atom used that as the preferred line length instead of the global option.

(My projects have different line lengths.)

**Comment by Arcanemagus** [comment]
Are you saying that you want this package to set the `Preferred Line Length` setting in Atom to what you have set in your `.eslintrc` file?

If so you probably want to look into a [`.editorconfig`](http://editorconfig.org/) file, as that is really beyond the scope of what this package is for. This is merely an interface between Linter and `eslint`.
