### ISSUE TITLE
Consider using mock-fs

### ISSUE THREAD

**Issue by grabbou** [AtomLinter/linter-eslint#397]
https://github.com/tschaub/mock-fs

So that we have better flexibility on testing file system and we don't have to keep full folders within the project fixtures.

It would also allow me to test #396 since it would be as simple as defining `virtual` multi-package folders and real eslint as well.

Some inspirations on how it can look like in real life:
https://github.com/rnpm/rnpm/blob/master/test/ios/getProjectConfig.spec.js#L10

An example structure of #396 would be:
```js
// Simple project definition
const simpleProject = {
   node_modules: {},
   'package.json': {}
};

mock({
  ...simpleProject,

  // top-level node_modules with eslint installed
  node_modules: {
     eslint: {}
  },

  // some sub-packages
  packages: {
      packageA: simpleProject,
      packageB: simpleProject
  }
});
```

I would be interested in submitting a PR to that & possibly adding more advanced test cases later on. Since it's `not-that-heavy` dev only dependency, I wouldn't consider it as an extra overheat when test suite is concerned.

What do you think? :)

**Comment by Arcanemagus** [comment]
Looks like a cool idea to me, anything to make testing easier is a good thing :wink:.

**Comment by steelbrain** [comment]
@grabbou Thanks! Using that now in the new specs I'm writing

**Comment by steelbrain** [comment]
`mock-fs` crashes Atom spec runner window :warning:

**Comment by grabbou** [comment]
Ha, really sorry that I forgot to update that issue! Had the same issue and generally it does not work since Atom is probably not using the same fs mock-fs is mocking. But thanks for investigating!
