### ISSUE TITLE
Better handling of worker crashes

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-eslint#402]
As suggested by @joefitzgerald we need a better strategy for dealing with the situation of a worker process that is continuously crashing. Currently we immediately restart the worker on a crash, which in some cases simply means an infinite loop until Atom is closed.

Ideas for throttling this:

* If the last crash was within __ seconds of the previous one pop up an alert to the user asking if they want to continue trying to start it
* Just use a backoff strategy on the timing, but have no limit on the time it is attempted
* A combination of the two
* Something else?

@AtomLinter/linter-eslint, thoughts?

**Comment by steelbrain** [comment]
I've probably said this a million times, but I'll say it again :stuck_out_tongue: 
Already done in https://github.com/AtomLinter/linter-eslint/pull/373

**Comment by steelbrain** [comment]
Done
