### ISSUE TITLE
Error: Unable to execute npm get prefix. Please make sure Atom is getting $PATH correctly

### ISSUE THREAD

**Issue by lmartins** [AtomLinter/linter-eslint#408]
Hi,

After today's update I've started getting this message every time I open a JS file:

```
Error: Unable to execute `npm get prefix`. Please make sure Atom is getting $PATH correctly
    at getNodePrefixPath (/Users/luismartins/.atom/packages/linter-eslint/lib/worker-helpers.js:43:13)
    at getESLintFromDirectory (/Users/luismartins/.atom/packages/linter-eslint/lib/worker-helpers.js:53:49)
    at Object.getESLintInstance (/Users/luismartins/.atom/packages/linter-eslint/lib/worker-helpers.js:83:10)
    at /Users/luismartins/.atom/packages/linter-eslint/lib/worker.js:56:26
    at /Users/luismartins/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:63:9
    at Array.forEach (native)
    at Emitter.emit (/Users/luismartins/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:59:30)
    at /Users/luismartins/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /Users/luismartins/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at /Users/luismartins/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:61:9
```

**Comment by steelbrain** [comment]
Open a terminal and do
```
npm get prefix
```
paste the value into settings

**Comment by steelbrain** [comment]
If you are not using global node and eslint, then uncheck the `Use Global ESLint` option

**Comment by lmartins** [comment]
Thank you @steelbrain, the `npm get prefix` did the trick.

**Comment by OKNoah** [comment]
This error popped up for me today too.

**Comment by Arcanemagus** [comment]
Did the comments earlier in the issue resolve it for you @OKNoah, or are you still running into problems?

**Comment by thearabbit** [comment]
I have the same problem.

![2016-02-16_21-00-25](https://cloud.githubusercontent.com/assets/4495160/13078261/77614030-d4f0-11e5-97ad-7f0b235f67eb.png)

**Comment by steelbrain** [comment]
@thearabbit You have selected `Use global ESLint installation` even though you didn't install it globally (presumably), either install it globally or uncheck the config

**Comment by thearabbit** [comment]
So I need install vai `npm or apm`.

**Comment by steelbrain** [comment]
By checking global eslint, you declare that you have eslint and therefore node installed globally, to get the prefix path of your node installation you should do `npm get prefix`

**Comment by thearabbit** [comment]
Thanks, Now it don't after I installed `node`, But show error with module:

![2016-02-16_22-08-38](https://cloud.githubusercontent.com/assets/4495160/13080414/17694fbe-d4fb-11e5-81cf-8141254ba2b9.png)

**Comment by thearabbit** [comment]
Sorry it have problem with `eslint or any...`.

**Comment by steelbrain** [comment]
That is not actually an error but a user misconfiguration, please configure eslint to allow es6+ syntax

**Comment by thearabbit** [comment]
Could you help me, how to solve?

**Comment by steelbrain** [comment]
I personally use babel-eslint as my parser, check it out here https://github.com/babel/babel-eslint#setup

**Comment by thearabbit** [comment]
Now I tried to install `babel-eslint`, but still problem.

**Comment by thearabbit** [comment]
```js
npm install -g eslint

apm install language-babel
```

**Comment by steelbrain** [comment]
@thearabbit This is a bug report for a completely different thing, I would love to help you but you're asking for help about something very basic of eslint (not related to this Atom package), I would recommend you google some `Getting started with ESLint` or ask for help in IRC

**Comment by thearabbit** [comment]
Very thanks for your helping, I will try the best.

**Comment by annacollins85** [comment]
@steelbrain if you are using global node, but local eslint how should you configure things?

**Comment by steelbrain** [comment]
@annacollins85 You shouldn't have to configure anything, it should run out of the box in that scenario :)

Also this is a pretty old issue, if you're still having this problem, please open a new issue instead
