### ISSUE TITLE
Linter broken ?

### ISSUE THREAD

**Issue by tomaskikutis** [AtomLinter/linter-eslint#41]
I install the plugin and it just doesn't work. Console prints out

```
activate linter-eslint
index.js:56 Window load time: 769ms
```

but the editor works as no linter is present. I have .eslintrc config file at the project root, so i think it's not the problem.

It's also on a fresh install of newest atom version.
How can I debug it and what to test ?

**Comment by jfaissolle** [comment]
Hello, did you also install the `linter` plugin ? It is needed for `linter-eslint` to work. The latter is only a plugin of the `linter` plugin...

**Comment by tomaskikutis** [comment]
@jfaissolle thank you, I didn't. I thought it was a stand-alone plugin, and not a plugin for plugin. At last got it working!
