### ISSUE TITLE
Fix on save

### ISSUE THREAD

**Issue by Segflow** [AtomLinter/linter-eslint#417]
It will be great if there was an option to fix the file onsave.

**Comment by steelbrain** [comment]
Sounds like a idea

**Comment by youzhonghui** [comment]
+1. like it

**Comment by dmodalek** [comment]
:+1: Would be awesome

**Comment by pvamshi** [comment]
there is this package esformatter , which fixes half of the errors related to spaces

**Comment by jamesdixon** [comment]
any update on this? really love this about the `linter-jscs` plugin

**Comment by Arcanemagus** [comment]
It looks like the `linter-eslint:fix-file` command was added way back in v5.2.0, it shouldn't be too difficult to add an option to enable fixing on save by calling the implementation of that.

**Comment by pvamshi** [comment]
I will try to work on this.

**Comment by pvamshi** [comment]
I got it fixed :sparkles: 
Trying to write tests for the code .

**Comment by pvamshi** [comment]
Created a pull request #508  . 
The functionality is working fine. 
Finding difficulty in writing the unit test. If someone can help me , it would be great . 
Thanks.
