### ISSUE TITLE
Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by JaxCavalera** [AtomLinter/linter-eslint#418]
This only started since I updated to the latest version of linter-eslint inside the Atom editor (any version of the editor).

The error only occurs when linter-eslint is enabled/installed (version 6.0.0).

**Full Error :**
> Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Console.log (console.js:36:16)
    at EventEmitter.Program (..MyProject\node_modules\eslint-plugin-react\lib\rules\jsx-quotes.js:52:15)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (..MyProject\node_modules\eslint\lib\util\node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (..MyProject\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (..MyProject\node_modules\eslint\lib\eslint.js:767:36)

It looks like there may be some problems with permissions.
**Running :**
- Windows 10 64bit
- Atom 1.4.1
- Node 5.x (probably not relevant)
- NPM 3.x (probably not relevant)

So far I've tried removing read-only from my project directory as a work-around fix but that didn't work.  The project is not located in a protected System directory and Atom is not installed in one either (I've seen some people install Atom under system32 etc.. but mine is installed to Appdata/local/atom)

I'll try running Atom with Admin perms but I think that shouldn't be necessary as it never was prior to updating linter-eslint to version 6.0.0.

**Comment by Arcanemagus** [comment]
After talking with @steelbrain we traced it down to [this line](https://github.com/yannickcr/eslint-plugin-react/blob/v3.16.1/lib/rules/jsx-quotes.js#L52), which is telling you that you should be using `eslint`'s `jsx-quotes` instead of `eslint-plugin-react`'s in the first place :stuck_out_tongue:.

FYI: The error you are seeing is due to a `console.log()` in the plugin attempting to write to a stream (`stdout`) that was closed when it tried to write to it, thus it got the permission denied error.

**Comment by JaxCavalera** [comment]
Yep changing the line in my *.eslintrc : "react/jsx-quotes": 1    FOR  "jsx-quotes": 1   fixed the error thank you.

**Comment by srahulprdxn** [comment]
I am still facing this issue. I have followed the instructions mentioned here and the issue didn't get resolved.

**Comment by Arcanemagus** [comment]
Are you seeing the exact same stack trace? If not please file a new issue... If so then update your eslint installation and fix the configuration.

**Comment by srahulprdxn** [comment]
The issue gets resolved when I update babel-eslint to 6.0.0 and eslint to 2.5.1. Thanks for the swift reply @Arcanemagus.

**Comment by Arcanemagus** [comment]
@srahulprdxn you should get one in the red error dialog box popping up (Expand it to see).

**Comment by srahulprdxn** [comment]
@Arcanemagus Great. Got it.

**Comment by danielstern** [comment]
I'm noticing this as well

**Comment by Arcanemagus** [comment]
Please follow https://github.com/atom/atom/issues/12504 for further updates on this being fixed, @sompylasar did a great job of tracing this down over in https://github.com/AtomLinter/linter-eslint/issues/579#issuecomment-241766886.

**Comment by sompylasar** [comment]
@Arcanemagus thanks :)

**Comment by Dinesh9909** [comment]
i am installing a new plugin and facing a problem message saying that Error 1 - Operation not Permitted.
i am using wordpress how to overcome this problem

**Comment by Arcanemagus** [comment]
@Dinesh9909 without more information it's impossible to say. Can you please file a new issue and provide the information requested in the template?
