### ISSUE TITLE
Error comming from .eslintrc Path even if .eslintrc Path is empty

### ISSUE THREAD

**Issue by Trudko** [AtomLinter/linter-eslint#426]
Hi everyone ;),

I've been playing around with package.
I created .eslintrc config using eslint --init.
I made some error in the config like misspelled standard in "extends": "standard".
Put the config outside of my project (like /home/trudko/dev/).
Set .eslintrc Path towards that file.
Use linter.

Of course I got an error saying that the file is invalid. Problem is that if I deleted .eslintrc Path value, I would expect invalid file being ignored, but I still got an error even though I had valid .eslintrc file inside of my project again. 

Removing the invalid file config file solved the issue.

**Comment by steelbrain** [comment]
Ah Trudko, long time no see. Haven't even seen you on IRC in the longest time!

Also the bug you're seeing is in ESLint, it caches javascript configs, they have fixed it in latest release if I recall correctly!

**Comment by IanVS** [comment]
I believe you are referring to https://github.com/eslint/eslint/issues/5067, @steelbrain?  That issue is for `.eslintrc.js` files.  It looks like @Trudko is using a legacy `.eslintrc` file (without extension), in which case it should not be cached.

@Trudko, can you confirm the exact filename of the config file (including extension)?

**Comment by Trudko** [comment]
Hi @steelbrain :) , I was actually glad, when I saw you as maintainer here :) . And yeah moved to other things. Right now I've been busy to full switching to javascript development, so right now I am mostly looking for some prof. project to work. 

@IanVS well I have .json file (/home/trudko/dev/.eslintrc.json)

**Comment by Arcanemagus** [comment]
I'm marking this as closed, it's highly likely the file was being cached in a similar manner. If you are still experiencing this with a current version of this package and ESLint please file a new issue.
