### ISSUE TITLE
Configure linter scope or file extensions

### ISSUE THREAD

**Issue by ninacfgarcia** [AtomLinter/linter-eslint#431]
I see the default scopes are 'source.js', 'source.jsx', 'source.js.jsx', 'source.babel', 'source.js-semantic'  ... would it be a common enough use case to override these scopes or specify how the linter works (or doesn't) for certain file extensions?

I have legacy js files with extension foo.js in my tree, alongside ES6-lintable files named bar.es6.js . I work in both kinds of files simultaneously within the project and don't want the linter distraction on the legacy files.

Would it be best to blacklist certain scopes and merge that setting with the default scopes? Or use a whitelist that overrides the scope setting entirely?

**Comment by steelbrain** [comment]
Instead of messing up with grammars and doing things like that, how about an `.eslintignore` file that ignores all of your legacy files?

**Comment by Arcanemagus** [comment]
I've also seen the `.es6` extension used for ES6 files, any reason you aren't just going with that?

**Comment by ninacfgarcia** [comment]
@steelbrain thanks, I had been dancing around that solution but was blocked by the need to ignore .js and not ignore .es6.js .  @Arcanemagus there was a reason for not using .es6 that I'm trying to dig up from past slack chats and whatnot (it'd be a shame if it was only an aversion to rewriting a gulp config or something).

Maybe this is the solution -- ignore js and unignore es6.js
```
*.js
!*.es6.js
```

**Comment by ninacfgarcia** [comment]
Solutions exist
