### ISSUE TITLE
Add Delay Option

### ISSUE THREAD

**Issue by tylerFowler** [AtomLinter/linter-eslint#434]
It would be nice to have a delay option after the last keyup before actually showing anything. For example it gets old (and more importantly interferes with autocomplete) to have eslint complain about my line not having a semicolon while I'm typing it out.

**Comment by steelbrain** [comment]
There's an option about lint on fly delay in the base `linter` package config

**Comment by tylerFowler** [comment]
Ah my bad, I looked for that but assumed it was a core package

**Comment by Arcanemagus** [comment]
@tylerFowler That's an eventual goal, but it isn't there yet :wink:.
