### ISSUE TITLE
Feature Request: Do not lint files ignored by VCS

### ISSUE THREAD

**Issue by dominicbarnes** [AtomLinter/linter-eslint#437]
Every so often, I find myself dropping into `node_modules` to debug something. In the meantime, ESLint throws errors and is very "loud".

In the `linter` package, I see a config for ignoring uncontrolled files. (ie: things in the `.gitignore`, such as the entire `node_modules` dir) Thus, I'm not sure if this is a bug in `linter-eslint`, or just a feature that hasn't been implemented.

Either way, it would be nice to turn `linter-eslint` off in this situation. (via config)

**Comment by Arcanemagus** [comment]
It's something that has been implemented for months, and should be working. Are you absolutely sure your `node_modules` folder is ignored properly by your VCS? (And Atom supports said VCS)

**Comment by steelbrain** [comment]
I wonder why the ignore CVS config is not being honored in the base linter, can you provide us some way to repro this?

**Comment by dominicbarnes** [comment]
Actually, I think I might have discovered something. It looks like the file isn't being linted, but `linter-eslint` is still trying to lookup any plugins used in `extends`. (and it is dying because it can't find them)

So, it looks like the issue is that `plugins` and `extends` are still being processed, despite the file not being linted. (which would put the scope of the problem in `linter-eslint`)

**Comment by Arcanemagus** [comment]
Nope, that's definitely still a `linter` issue, as it shouldn't even be calling this plugin's `lint()` function on a VCS ignored file.

**Comment by Arcanemagus** [comment]
@dominicbarnes Can you run the following in the Developer Tools when you have a file that is being ignored open?

```js
atom.project.getRepositories()[0].isPathIgnored(atom.workspace.getActiveTextEditor().getPath())
```

This will tell us whether Atom thinks the file should be being ignored according to the backing VCS.

**Comment by simon04** [comment]
The upcoming `linter` release will contain some changes in this respect, see steelbrain/linter#1109. However testing with steelbrain/linter@13728e7b5479910f7599aa3679a93dc32c1b1c53, `linter-eslint` still lints `.gitignore`d files.

**Comment by Arcanemagus** [comment]
@simon04 that PR had nothing to do with this, it just makes linter respect the core Atom setting that controls that preference.

**Comment by mxstbr** [comment]
I'm running into this problem.

A file is git ignored, and I've got "Do Not Lint Files Ignored by VCS" checked in the linter base config, but linter-eslint is showing errors. I've ran

```JS
atom.project.getRepositories()[0].isPathIgnored(atom.workspace.getActiveTextEditor().getPath())
```
in the console and it returned `true`.

Screenshot of all of those things:

<img width="1162" alt="screen shot 2016-05-29 at 16 29 46" src="https://cloud.githubusercontent.com/assets/7525670/15634028/ade4754e-25ba-11e6-91ca-63a3cf658760.png">

In the tree view and the tab you can see that Atom recognizes the file as VCS ignored (in this case git). You can also see eslint still linting it, and that the JS code above returns true.

**Comment by Arcanemagus** [comment]
@mxstbr Can you please file that on [linter](https://github.com/steelbrain/linter) with the above information?

Marking this as closed, as stated earlier `linter-eslint` has _no_ control over when it is ran.

**Comment by mxstbr** [comment]
Done, thanks for this great package @Arcanemagus!

Moved to steelbrain/linter#1167
