### ISSUE TITLE
linter-eslint breaks when using ~ in the rule path

### ISSUE THREAD

**Issue by EvHaus** [AtomLinter/linter-eslint#441]
When setting the "ESLint Rules Dir" in the settings for linter-eslint, if you specify your path with a "~" character, the linter will completely stop working. No errors messages will appear, no warnings will appears, it will simply behave as if it's not installed.

Example of broken path:

```
~/Git/myproject/rules
```

However, if you change that path to an absolute path:

```
/home/myuser/Git/myproject/rules
```

Everything will work correctly again.

If ~ isn't supported in the paths, the linter should at least give us an error message. But better yet -- it would be great to fix this bug.

**Comment by Arcanemagus** [comment]
Marking this as a duplicate of #985 because that is written in a more general fashion, even though it relates to the same thing this does 😉.

**Comment by Arcanemagus** [comment]
Duplicate of #985
