### ISSUE TITLE
Cannot find module 'atom-package-path'

### ISSUE THREAD

**Issue by anewmanBV** [AtomLinter/linter-eslint#442]
[Enter steps to reproduce below:]

1. Open a new Atom Window

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v6.0.0

### Stack Trace

Failed to activate the linter-eslint package

```
At Cannot find module 'atom-package-path'

Error: Cannot find module 'atom-package-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.install (/Users/alex.newman/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/main.js:27:12)
    at Object.module.exports.activate (/Users/alex.newman/.atom/packages/linter-eslint/lib/main.js:71:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter-eslint": {
    "eslintrcPath": "~/",
    "globalNodePath": "/usr/local"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-netsuite, v0.4.0
language-jade, v0.6.3
language-lua, v0.9.4
language-salesforce, v0.6.0
linter, v1.11.3
linter-eslint, v6.0.0
linter-lua, v1.0.1
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Can we have the output of `cd ~/.atom/packages/linter-eslint; npm ls` please?

**Comment by anewmanBV** [comment]
├─┬ atom-linter@4.4.0
│ ├─┬ consistent-path@1.1.1
│ │ └─┬ shell-path@1.0.8
│ │   └─┬ strip-ansi@3.0.0
│ │     └── ansi-regex@2.0.0
│ ├── named-js-regexp@1.3.1
│ └─┬ tmp@0.0.28
│   └── os-tmpdir@1.0.1
├─┬ atom-package-deps@3.0.8
│ └─┬ atom-package-path@1.0.1
│   └── sb-callsite@1.1.2
├── escape-html@1.0.3
├─┬ eslint@1.10.3
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├─┬ strip-ansi@3.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.5.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@2.0.5
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@0.0.1
│ │ │ ├── process-nextick-args@1.0.6
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ doctrine@0.7.2
│ │ ├── esutils@1.1.6
│ │ └── isarray@0.0.1
│ ├── escape-string-regexp@1.0.4
│ ├─┬ escope@3.4.0
│ │ ├─┬ es6-map@0.1.3
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.11
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.4
│ │ │ ├── es6-symbol@3.0.2
│ │ │ └── event-emitter@0.3.4
│ │ ├─┬ es6-weak-map@2.0.1
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.11
│ │ │ ├── es6-iterator@2.0.0
│ │ │ └── es6-symbol@3.0.2
│ │ └─┬ esrecurse@3.1.1
│ │   └── estraverse@3.1.0
│ ├── espree@2.2.5
│ ├── estraverse@4.1.1
│ ├── estraverse-fb@1.3.1
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.2.4
│ │ └─┬ flat-cache@1.0.10
│ │   ├─┬ del@2.2.0
│ │   │ ├─┬ globby@4.0.0
│ │   │ │ ├─┬ array-union@1.0.1
│ │   │ │ │ └── array-uniq@1.0.2
│ │   │ │ ├── arrify@1.0.1
│ │   │ │ └─┬ glob@6.0.4
│ │   │ │   ├─┬ inflight@1.0.4
│ │   │ │   │ └── wrappy@1.0.1
│ │   │ │   ├── inherits@2.0.1
│ │   │ │   └─┬ once@1.3.3
│ │   │ │     └── wrappy@1.0.1
│ │   │ ├── is-path-cwd@1.0.0
│ │   │ ├─┬ is-path-in-cwd@1.0.0
│ │   │ │ └── is-path-inside@1.0.0
│ │   │ ├── pify@2.3.0
│ │   │ ├─┬ pinkie-promise@2.0.0
│ │   │ │ └── pinkie@2.0.4
│ │   │ └─┬ rimraf@2.5.1
│ │   │   └─┬ glob@6.0.4
│ │   │     ├─┬ inflight@1.0.4
│ │   │     │ └── wrappy@1.0.1
│ │   │     ├── inherits@2.0.1
│ │   │     └─┬ once@1.3.3
│ │   │       └── wrappy@1.0.1
│ │   ├── graceful-fs@4.1.3
│ │   ├── read-json-sync@1.1.1
│ │   └── write@0.2.1
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ └─┬ once@1.3.3
│ │   └── wrappy@1.0.1
│ ├── globals@8.18.0
│ ├─┬ handlebars@4.0.5
│ │ ├── async@1.5.2
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├─┬ source-map@0.4.4
│ │ │ └── amdefine@1.0.0
│ │ └─┬ uglify-js@2.6.1
│ │   ├── async@0.2.10
│ │   ├── source-map@0.5.3
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.10.0
│ │     ├── camelcase@1.2.1
│ │     ├─┬ cliui@2.1.0
│ │     │ ├─┬ center-align@0.1.3
│ │     │ │ ├─┬ align-text@0.1.4
│ │     │ │ │ ├─┬ kind-of@3.0.2
│ │     │ │ │ │ └── is-buffer@1.1.2
│ │     │ │ │ ├── longest@1.0.1
│ │     │ │ │ └── repeat-string@1.5.2
│ │     │ │ └── lazy-cache@1.0.3
│ │     │ ├─┬ right-align@0.1.3
│ │     │ │ └─┬ align-text@0.1.4
│ │     │ │   ├─┬ kind-of@3.0.2
│ │     │ │   │ └── is-buffer@1.1.2
│ │     │ │   ├── longest@1.0.1
│ │     │ │   └── repeat-string@1.5.2
│ │     │ └── wordwrap@0.0.2
│ │     ├── decamelize@1.1.2
│ │     └── window-size@0.1.0
│ ├─┬ inquirer@0.11.4
│ │ ├── ansi-escapes@1.1.1
│ │ ├── ansi-regex@2.0.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.1.0
│ │ ├── cli-width@1.1.1
│ │ ├── figures@1.4.0
│ │ ├── lodash@3.10.1
│ │ ├─┬ readline2@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ └── mute-stream@0.0.5
│ │ ├─┬ run-async@0.1.0
│ │ │ └─┬ once@1.3.3
│ │ │   └── wrappy@1.0.1
│ │ ├── rx-lite@3.1.2
│ │ ├─┬ string-width@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │   └── number-is-nan@1.0.0
│ │ ├── strip-ansi@3.0.0
│ │ └── through@2.3.8
│ ├─┬ is-my-json-valid@2.12.4
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@2.0.0
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.2
│ ├─┬ js-yaml@3.4.5
│ │ ├─┬ argparse@1.0.6
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.2
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ lodash.clonedeep@3.0.2
│ │ ├─┬ lodash._baseclone@3.3.0
│ │ │ ├── lodash._arraycopy@3.0.0
│ │ │ ├── lodash._arrayeach@3.0.0
│ │ │ ├─┬ lodash._baseassign@3.2.0
│ │ │ │ └── lodash._basecopy@3.0.1
│ │ │ ├── lodash._basefor@3.0.3
│ │ │ ├── lodash.isarray@3.0.4
│ │ │ └─┬ lodash.keys@3.1.2
│ │ │   ├── lodash._getnative@3.9.1
│ │ │   └── lodash.isarguments@3.0.6
│ │ └── lodash._bindcallback@3.0.1
│ ├─┬ lodash.merge@3.3.2
│ │ ├── lodash._arraycopy@3.0.0
│ │ ├── lodash._arrayeach@3.0.0
│ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ ├── lodash._bindcallback@3.0.1
│ │ │ ├── lodash._isiterateecall@3.0.9
│ │ │ └── lodash.restparam@3.6.1
│ │ ├── lodash._getnative@3.9.1
│ │ ├── lodash.isarguments@3.0.6
│ │ ├── lodash.isarray@3.0.4
│ │ ├─┬ lodash.isplainobject@3.2.0
│ │ │ └── lodash._basefor@3.0.3
│ │ ├── lodash.istypedarray@3.0.4
│ │ ├── lodash.keys@3.1.2
│ │ ├── lodash.keysin@3.0.8
│ │ └─┬ lodash.toplainobject@3.0.0
│ │   └── lodash._basecopy@3.0.1
│ ├─┬ lodash.omit@3.1.0
│ │ ├── lodash._arraymap@3.0.0
│ │ ├─┬ lodash._basedifference@3.0.3
│ │ │ ├── lodash._baseindexof@3.1.0
│ │ │ ├── lodash._cacheindexof@3.0.2
│ │ │ └─┬ lodash._createcache@3.1.2
│ │ │   └── lodash._getnative@3.9.1
│ │ ├─┬ lodash._baseflatten@3.1.4
│ │ │ ├── lodash.isarguments@3.0.6
│ │ │ └── lodash.isarray@3.0.4
│ │ ├── lodash._bindcallback@3.0.1
│ │ ├── lodash._pickbyarray@3.0.2
│ │ ├─┬ lodash._pickbycallback@3.0.0
│ │ │ └── lodash._basefor@3.0.3
│ │ ├─┬ lodash.keysin@3.0.8
│ │ │ ├── lodash.isarguments@3.0.6
│ │ │ └── lodash.isarray@3.0.4
│ │ └── lodash.restparam@3.6.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.2
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── object-assign@4.0.1
│ ├─┬ optionator@0.6.0
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.0.7
│ │ ├── levn@0.2.5
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.2
│ │ └── wordwrap@0.0.3
│ ├── path-is-absolute@1.0.0
│ ├── path-is-inside@1.0.1
│ ├── shelljs@0.5.3
│ ├── strip-json-comments@1.0.4
│ ├── text-table@0.2.0
│ ├─┬ user-home@2.0.0
│ │ └── os-homedir@1.0.1
│ └── xml-escape@1.0.0
├─┬ process-communication@1.1.0
│ ├── sb-communication@4.0.1
│ └── sb-event-kit@1.0.3
└── resolve-env@1.0.0

**Comment by steelbrain** [comment]
You are experiencing a bug triggered between a 2 hour span due to a deployment issue, this should fix it for you
```
cd ~/.atom/packages/linter-eslint
npm install atom-package-path@latest
```

**Comment by anewmanBV** [comment]
Thanks that worked perfectly.
