### ISSUE TITLE
"Worker died unexpectedly" spam when running Atom in dev mode

### ISSUE THREAD

**Issue by 50Wliu** [AtomLinter/linter-eslint#446]
![worker-died-unexpectedly-spam](https://cloud.githubusercontent.com/assets/2766036/13165979/bb67e2d8-d690-11e5-8eaf-9977f2e1774f.png)

This **only** happens in dev mode, and I'm currently running Atom 1.7.0-dev-2bd6c54 on Windows 10 x64, though it's been happening for quite a while now.  There is not in fact any info in the console when this happens.  Potential lead: this *may* have started happening when I started working on a branch that was built on Electron 0.35+, so you might want to try that.

@Arcanemagus asked me to take a look at the `worker` object...neither of us knew what to look for though, and all I found was that `exitCode` was 1.

`apm list --installed` (the vast majority of these are `apm link`ed; I really only have ~12 packages installed):
```
├── file-icons@1.6.14
├── find-and-replace@0.197.1
├── fizzy@0.16.0
├── language-c@0.51.1
├── language-coffee-script@0.46.1
├── language-csharp@0.11.0
├── language-gfm@0.84.0
├── language-git@0.11.1
├── language-html@0.44.1
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-latex@0.6.1
├── language-make@0.21.0
├── language-objective-c@0.15.1
├── language-php@0.37.0
├── language-python@0.43.0
├── language-ruby@0.68.1
├── language-sass@0.42.1
├── language-shellscript@0.20.0
├── language-sourcepawn@0.6.0
├── language-sql@0.19.0
├── language-toml@0.17.0
├── language-xml@0.34.3
├── language-yaml@0.25.1
├── linter@1.11.3
├── linter-coffeelint@1.1.2
├── linter-csslint@1.3.1
├── linter-eslint@6.0.0
├── linter-javac@1.5.0
├── merge-conflicts@1.3.7
├── pdf-view@0.39.0
├── script@3.5.2
├── tabs@0.89.0
├── travis-ci-status@1.0.0
└── tree-view@0.201.2
```

/cc @steelbrain

**Comment by steelbrain** [comment]
@50Wliu Can you please post what you see in the dev console?

**Comment by Arcanemagus** [comment]
This may or may not be related, but @joefitzgerald has been hitting this error when running `atom --dev` on the master branch:
```
[Linter-ESLint] STDERR module.js:340
    throw err;
    ^

Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jfitzgerald/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.js:19:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by steelbrain** [comment]
I think I know the bug joe hit, investigating

**Comment by steelbrain** [comment]
Fix is in https://github.com/AtomLinter/atom-linter/pull/113

**Comment by Arcanemagus** [comment]
@50Wliu if you force an update to `atom-linter@4.5.1` does this issue go away?

**Comment by 50Wliu** [comment]
I can confirm that atom-linter@4.5.1 fixes the issue.  Your choice whether to keep this open or not until 4.5.1 is covered by package.json.

**Comment by Arcanemagus** [comment]
It's currently covered, just not listed as the minimum version (which Atom doesn't respect anyway...). Marking this as closed and thanks for the early report of the issue!
