### ISSUE TITLE
Problems with nested package.json

### ISSUE THREAD

**Issue by lemonmade** [AtomLinter/linter-eslint#447]
I have a repository that contains multiple node packages (https://github.com/Shopify/javascript). The root package has the dev dependencies on ESLint and our custom ESLint plugin/ config. Here's the basic summary of the project structure:

```
javascript
  package.json
  packages
    package-1
      package.json
      .eslintrc
    package-2
      package.json
      .eslintrc
    package-3
      package.json
      .eslintrc
```

Where the root `package.json` has:

```json
{
  "devDependencies": {
    "eslint": "^2.1.0",
    "eslint-plugin-shopify": "file:./packages/eslint-plugin-shopify"
  }
}
```

And each package does **not** have any dependency on ESLint or the config (since these are shared at the root) but **does** have a `.eslintrc` that changes which particular config/ env setup is needed for that project.

When I am working in files within one of the subprojects, I get errors from ESLint indicating that the config can't be found, like this one:

```
Error: Cannot read config package: eslint-config-plugin:shopify/esnext
Error: Cannot find module 'eslint-config-plugin:shopify/esnext'
Referenced from: /Users/chris/Projects/javascript/packages/generator-eslint-shopify/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadPackage (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:385:18)
    at /Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:309:28)
```

Would it be possible for `linter-eslint` to recursively check for the nearest folder that can provide the local ESLint instance, instead of giving up when not found in the current project?

**Comment by steelbrain** [comment]
Does this behavior differ from the `eslint` CLI? If it does not, you might wanna file a bug in `eslint` instead

**Comment by lemonmade** [comment]
Yes, this behaviour does differ from the CLI: when running `node_modules/.bin/eslint .` from the root of the project, it will correctly lint all subprojects.

**Comment by steelbrain** [comment]
@lemonmade Please note that this does not lint from the root of the project each time, it tries to find eslint from the file dir up and run from the nearest possible position

Can you try eslint from the child dirs and test it's behavior?

**Comment by lemonmade** [comment]
Sorry, I'm not sure I entirely understand. If I go down into a subproject and still want to use the local ESLint, I will just be running the same command (`cd packages/project-1 && ../../node_modules/.bin/eslint .`), which continues to work because it's running the same executable. I can't use the local ESLint in the subdirectory (like, `cd packages/project-1 && node_modules/.bin/eslint .`) because the subprojects do not include ESLint as a dependency.

**Comment by qimingweng** [comment]
I am seeing this too. What's even more confusing is it only happens... to some subdirectories. I've been trying a few hypothesis but haven't figured out what's different yet.

This may be anecdotal or unrelated but removing node_modules in one of the affected subdirectories can sometimes fix the problem. However, adding `**/node_modules/**` to eslintignore doesn't resolve the issue.

**Comment by Arcanemagus** [comment]
Can you try v6.1.0? It _should_ fix this.

**Comment by lemonmade** [comment]
I'm no longer having any issues, works fabulous. Thanks for getting to this so quickly!
