### ISSUE TITLE
.eslintignore file has no effect

### ISSUE THREAD

**Issue by onlywei** [AtomLinter/linter-eslint#448]
I'm on version `6.0.0`. I have a directory structure like this:

```
js/
- node_modules/
- lib/
  - gen/
- .eslintignore
- .eslintrc.json
- .gitignore
- package.json
```

My `.eslintignore` looks like this:
```
node_modules/
lib/gen/
```

And my `.gitignore` file looks like this:
```
lib/gen/
```

(I don't .gitignore my node_modules)

In Atom with `linter-eslint@6.0.0`, opening any `.js` files inside my `node_modules` directory will result in half of my screen being bombarded with lint errors. Opening any `.js` files inside the `lib/gen` directory will not. Furthermore, if I remove `lib/gen` from my `.eslintignore` file, the files inside that directory still do not get linted by the text editor. Only when I remove the path from my `.gitignore` does the linter actually activate for files in that directory.

With some investigation, I added a `console.log()` statements above line 149 of `linter-eslint/lib/main.js` and discovered that opening any files that are under `.gitignore` don't ever even trigger the worker job request.

**Comment by steelbrain** [comment]
It's a configuration in the base `linter` Atom package to ignore VCS ignored files, you can disable it if you want

**Comment by onlywei** [comment]
@steelbrain I just found and disabled the "Do Not Lint Files Ignored by VCS". That turned on linting for stuff under `.gitignore`. But now my `.eslintignore` file still has no control over anything the linter does.

**Comment by steelbrain** [comment]
@onlywei can you explain it a bit more?

**Comment by onlywei** [comment]
@steelbrain Here are all the details I can think of that may be relevant:

(global) Node v5.4.1
(global) npm v3.3.12

The local `eslint@2.1.0` package is installed as a transitive dependency of `gulp-eslint@2.0.0`. It is located at `node_modules/eslint/` (in the directory structure I wrote in my original message).

I want to ignore files in the `lib/gen` directory, but what I have typed in my `.eslintignore` file seems to be completely ignored.

I have multiple nested `.eslintrc.json` files throughout my different subdirectories, but only one `.eslintignore` file.

Does that help?

**Comment by steelbrain** [comment]
Thanks for the info, gonna try to repro soon

**Comment by onlywei** [comment]
@steelbrain I thought of another piece of information that may be relevant:

My directory structure is actually like this:
```
root/ (this is the dir I open with Atom)
- src/
  - js/ (although, it still doesn't work even if I open this dir with Atom directly)
    - node_modules
    - lib/gen
    - .eslintignore
    - package.json
```

**Comment by onlywei** [comment]
OK I don't know what happened, but suddenly it's working now after not working for as long as I can remember. I didn't update or change any code. All I did was:

1. Disable "Do Not Lint Files Ignored by VCS"
2. Close my Atom window.
3. File > Open > the `root/src/js` directory directly as explained in my previous comment.
4. Observe that it's still not working.
5. Close that window.
6. File > Open > the `root` directory again.

After those steps, suddenly it's working and I'm seeing:
"Warning Fatal File ignored because of a matching ignore pattern."

I have no idea how this came to pass.

**Comment by onlywei** [comment]
Hmm... now I just closed the window and re-opened it, and my `.eslintignore` file is no longer working once again.

**Comment by mistadikay** [comment]
I can confirm the same bug here. Atom 1.5.3, Node 5.6.0, npm 3.7.3, linter-eslint 6.0.0. .eslintignore does not affect whether files are being linted or not. Tried both with  disabled `Do Not Lint Files Ignored by VCS` in linter package and without it. `Disable using .eslintignore files` is also on.

**Comment by IanVS** [comment]
@mistadikay, that is the expected behaivor by setting `Disable using .eslintignore files`.

**Comment by mistadikay** [comment]
@IanVS you sure? Anyway, the same result is with setting disabled. When I run ESLint from the command line for the whole project folder, it ignores certain files correctly, `linter-eslint` doesn't

**Comment by onlywei** [comment]
@mistadikay I'm getting slightly confused by your use of double negatives. Do you mean to say that the `Disable using .eslintignore files.` seems to have no effect whatsoever?

**Comment by IanVS** [comment]
@onlywei You said that ESLint is a transitive dep of gulp-eslint.  Does that mean you are not able to run `node_modules/.bin/eslint .` ?

I'm wondering if maybe linter-eslint is falling back to its own packaged version of ESLint, which is older and does not support that format of `.eslintignore`.

**Comment by mistadikay** [comment]
@onlywei sorry, it's just this whole options naming is a bit confusing. So, I've tried both `Disable using .eslintignore files` on and off — and this option had no effects whatever I chose. However if I add file/folder to `.gitignore` — eslint disabling works. Looks like the same bug you have?

**Comment by onlywei** [comment]
@IanVS I am able to run `./node_modules/.bin/eslint .` and it is working correctly.

**Comment by IanVS** [comment]
There goes that theory...

**Comment by onlywei** [comment]
Where is the `current working directory` set to for the linter process? In ESLint 2.0 they changed it so that only the `.eslintignore` file inside the CWD would be read, and no other file.

**Comment by IanVS** [comment]
If an ignore file can be found, `cwd` is set to the directory containing that file: https://github.com/AtomLinter/linter-eslint/blob/master/src/worker-helpers.js#L100.

**Comment by onlywei** [comment]
@IanVS yeah, I just added a `console.log(process.cwd())` right before the `eslint` is called in `worker.js` and I got the correct result. There goes that theory...

**Comment by peregrinogris** [comment]
I'm experiencing the exact same behavior as @onlywei.

I have a file explicitly ignored in my `.eslintignore` file. When I run `eslint` on the console on that file I get a message saying the file is ignored. But then when I open the file with Atom, I see that somehow `linter-eslint` is running `eslint` on it and shows errors.

**Comment by peregrinogris** [comment]
Well, just came up with a test case for this. As you can see in the picture, foo.js shouldn't be linted as it's in the `.eslintignore` file. The files for the testcase can be found here: https://gist.github.com/peregrinogris/929293d7f37d9e42a75a
![linter-eslint error](http://i.imgur.com/yCdvpPW.png)
When I try to lint that file from the console, I get:
```
$ ./node_modules/.bin/eslint foo.js

/Users/hcolmeiro/test/eslint-error/foo.js
  0:0  warning  File ignored because of a matching ignore pattern. Use --no-ignore to override

✖ 1 problem (0 errors, 1 warning)
```

**Comment by huttotw** [comment]
I am experiencing these same symptoms. You can run `eslint` from the command line, and the `.eslintignore` works. It does not work inside of Atom and still displays errors on an ignored file.

**Comment by IanVS** [comment]
I have a feeling this is an issue with ESLint itself.  I'm working on a refactor/fix of the ESLint ignore logic right now, hopefully that will address these problems.  Thanks for the heads-up.

**Comment by thgaskell** [comment]
> I am experiencing these same symptoms. You can run eslint from the command line, and the .eslintignore works. It does not work inside of Atom and still displays errors on an ignored file.

I can confirm the same behavior running `eslint@2.2.0`.

Running from command line ignores files correctly using `.eslintignore`, but Atom seems to be linting ignored files.

**Comment by IanVS** [comment]
`gulp-eslint` is also having problems with ignores (https://github.com/eslint/eslint/issues/5314).  I believe it is due to the way these tools are passing files to ESLint (as text), and the changes ESLint made recently to our ignore system (it now is _supposed to_ match the behavior of .gitignore).  I haven't confirmed for sure that's what's going on here, but I have strong suspicions.  I've already found a few problems with how we are doing ignores in ESLint, and I should be able to resolve them within the next few days.

**Comment by artisologic** [comment]
I am also experiencing the same issue since I believe the update to linter-eslint 7.0.0.

Using eslint via command line does ignores files in `.eslintignore` but in atom, it still highlights errors.

**Comment by IanVS** [comment]
Are all of you using the `eslint` that comes bundled with `linter-eslint`?  Or if not, what version of ESLint are you using?

**Comment by peregrinogris** [comment]
I'm using eslint v2.2.0.

**Comment by huttotw** [comment]
v2.2.0

**Comment by artisologic** [comment]
In my `linter-eslint` settings: 

> Use global ESLint installation

 is unchecked, so I'm guessing I am using the `eslint` bundled with`linter-eslint`.

**Comment by aoberoi** [comment]
i'm experiencing this issue as well. i have `"eslint@2.3.0"` in the node project i am editing.

but if @artisologic is right (which i think he is) i'm also using the `eslint` bundled with `linter-eslint` (the `Use global ESLint installation` checkmark is off).

**Comment by aoberoi** [comment]
FYI: i tried manually going into the linter-eslint package directory and running `npm update eslint` to go from 2.2.0 -> 2.3.0, and that still didn't fix the issue. i'm not conviced this is an eslint issue because on the CLI it works fine. it must be something with the interface between linter-eslint and eslint.

**Comment by IanVS** [comment]
You would need to call eslint with the `--stdin` and `--stdin-filename` flags as linter-eslint does.

**Comment by IanVS** [comment]
It does seem that I was wrong after all.  Even with my fixes to ESLint, Atom was still having problems for no discernable reason.  I've submitted #481 which should force `.eslintignore` files to be applied.
