### ISSUE TITLE
linter-eslint doesn't seem to load plugins

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-eslint#45]
I setup https://github.com/yannickcr/eslint-plugin-react and now I get errors in Atom that don't show up when I run the eslint from the command line. I started looking at the source, I suspect the problem is that eslint expects to be run from `node` but when run from inside `atom` `require()` is a little different.

I'm looking into how to fix this, but wanted to open an issue for it first.

**Comment by davidagraf** [comment]
+1

**Comment by RickEyre** [comment]
+1, this is happening with `eslint-plugin-one-variable-per-var`

**Comment by AsaAyers** [comment]
I didn't notice when I opened it, but linter-eslint [explicitly disables plugins](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L59-L67) My PR #46 should fix this and turn plugins on.
