### ISSUE TITLE
Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by TitanNano** [AtomLinter/linter-eslint#462]
I get this error since the most recent update. is it possible there this is missing somewhere in the package?

**Comment by IanVS** [comment]
Are you using `import` or `export`?  If so, what is your config file?  And, how are you using ESLint (installed in your project, globally, or using the version packaged with `linter-eslint`), and what version of ESLint are you using?

My first guess is that you need to add

```json
{
    "parserOptions": {
        "sourceType": "module",
    }
}
```

to your config file.

**Comment by TitanNano** [comment]
yes thank you, that solved the issue! :+1: 

My eslint config is:
```JSON
{
    "ecmaFeatures": {
        "modules": true,
        "spread" : true,
        "restParams" : true
    },
    "env" : {
        "browser" : true,
        "node" : true,
        "es6" : true
    },
    "rules" : {
        "no-unused-vars" : 2,
        "no-undef" : 2
    },
    "parserOptions": {
        "sourceType": "module"
    }
}
```
and I'm using the packaged version.

**Comment by IanVS** [comment]
We recently upgraded the packaged version from ESLint `1.x` to `2.x`, which had some breaking changes in the way configurations should be written.  Check out ESLint's [migration docs](http://eslint.org/docs/user-guide/migrating-to-2.0.0#language-options).

**Comment by Big-Blue** [comment]
Thank you, my problem has been solved, too

**Comment by saahil0826** [comment]
HI just a question on es lint. what is the standard way of setting it up? just install the package from atom or setting up es lint locally for each and every project.

**Comment by cuiyongjian** [comment]
i come with the same problem.
i use eslint standard style and eslint-plugin-prettier.  But when i exec `npm run lint`, i get this problom.

my config:

```js
module.exports = {
  env: {
    browser: true,
    node: true,
    es6: true
  },
  extends: ['standard', 'plugin:prettier/recommended'],
  plugins: ['vue'],
  globals: {
    $: true
  },
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module'
  }
}

```

========
my solution: uninstall the vscode eslint extension, and reinstall it.   It worked for me.

**Comment by staghouse** [comment]
Is this issue possibly causing [this issue with vue-eslint-parser](https://github.com/mysticatea/vue-eslint-parser/issues/52)?

**Comment by CristianCuartas** [comment]
Solve with: 
https://github.com/standard/eslint-config-standard/blob/master/eslintrc.json#L12

**Comment by jtakalai** [comment]
Unrelated (thanks for the parserOptions tip!), adding `""plugin:@typescript-eslint/recommended"` under `"extends"` also seemed to solve a bunch of `Parsing error: Unexpected token :` for me (in very vanilla JS object notation), so that's also something you might want to have.
