### ISSUE TITLE
Cascading eslintrc files

### ISSUE THREAD

**Issue by werne2j** [AtomLinter/linter-eslint#463]
I have a project structure like:
```
root/
    .eslintrc
    public/
        .eslintrc
```
The eslint file in the public folder is being overwritten even when i have { root: true }.

When running eslint in the command line the eslintrc files work as expected but not in Atom. I am trying to use the airbnb/base in my root eslintrc and airbnb/legacy inside the public folder.

**Comment by themasch** [comment]
:+1: got the same problem. We are using different eslintrc files for front- & backend (browser vs node, es5 vs. es6, different styleguides etc).

**Comment by Arcanemagus** [comment]
I'm unable to reproduce this with this structure: [linter-eslint_GH463.zip](https://github.com/AtomLinter/linter-eslint/files/157609/linter-eslint_GH463.zip)

Are you seeing the same, or does that not capture some aspect of your setup?

Atom: 1.6.0-beta7
linter-eslint: 7.0.0

**Comment by werne2j** [comment]
Updating to 1.5.4 solved this issue!

**Comment by Arcanemagus** [comment]
Interesting, what version were you on before?

**Comment by werne2j** [comment]
I cannot confirm exactly which version but i know it was <= 1.5.2

**Comment by Arcanemagus** [comment]
Oh well :stuck_out_tongue:

@themasch Are you running an older version of Atom as well? Or is the above structure missing something to reproduce your issue?

**Comment by guzart** [comment]
I was having the same problem with the latest version of eslint, right after adding `root: true` to my eslintrc. I just needed to close atom completely and open it again.

"Have you tried turning it off and on again?"

**Comment by IanVS** [comment]
Sounds like this can be closed.

**Comment by benmvp** [comment]
I had the same issue to. Quitting Atom and re-opening it fixed it. Thanks! 👍
