### ISSUE TITLE
Cannot find module 'eslint-plugin-react-internal'

### ISSUE THREAD

**Issue by gmaggess** [AtomLinter/linter-eslint#464]
Hi there,

I'm using Atom 1.5.4 and I'm trying to use linter-eslint, but I get the following error:

Error: Failed to load plugin react-internal: Cannot find module 'eslint-plugin-react-internal'. I've tried to do a atom clean install, but no luck.

Any clue?

Cheers,
George

**Comment by steelbrain** [comment]
The error is pretty clear, you haven't installed that dependency in your project. Is the result you get from the command line `eslint` any different?

**Comment by gmaggess** [comment]
I tried this first.
```
$ npm install eslint-plugin-react-internal --save-dev
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "eslint-plugin-react-internal"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code E404
```
I've recreated my eslintrc file and it works now.

Thanks for the help.
