### ISSUE TITLE
Using `eslint-import-resolver-webpack` doesnt resolve based on alias settings in webpack

### ISSUE THREAD

**Issue by andykenward** [AtomLinter/linter-eslint#466]
Having issues when using b8b9165 of the package in atom `1.5.4`

I am using `"eslint-plugin-import": "1.0.3"` in my `.eslintrc` settings and it has been working fine.
But when I implemented the [webpack resolver](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) it doesnt work.

Running eslint in the command line works so it isnt my `.eslintrc` file or webpack setup causing the issue.

Tried adding `eslint-import-resolver-webpack` to the `devDependencies` of `linter-eslint` and install it but that didnt fix it for me.

**Comment by steelbrain** [comment]
That commit you referred to only updates `consistent-path` and even if it did screw something up we're only using it's value to execute `npm get prefix`. I think it may be a problem with the latest version of `eslint` that the error is quite misleading. Whenever it complains about something not existing, you actually need to install it in your project instead of your `~/.atom/packages/linter-eslint` directory.

Can you post a minimal repro of your error somewhere?

Also your error looks a lot like #457 #459

**Comment by andykenward** [comment]
Sorry I should have said that I just get a linting error in atom. When it shouldnt be. As it passes via eslint command line within the project. I have all the packages installed within my project folder so it isnt a case of not being installed in the correct folder etc. 

https://dl.dropboxusercontent.com/u/482925/Screen%20Shot%202016-03-05%20at%2022.33.25.png

**Comment by andykenward** [comment]
Sorry seems to be something else causing it.

**Comment by leoasis** [comment]
@andykenward were you able to solve this problem? I'm having it as well

**Comment by theideaofnorth2** [comment]
Should this issue have been closed? I am having the same problem

**Comment by andykenward** [comment]
I think it may have to do with the eslint settings file being cached by atom for me. Or the wrong directory defined for the alias. So it should still be closed.

**Comment by theideaofnorth2** [comment]
I am using eslint-loader as preLoader in my webpack config and it works fine. So the alias is properly configured (if I change its settings I do get an error).
As for the .eslintrc, it is well updated if I change other settings, so there are no cache issues.
I am using node 6.0.0.

**Comment by theideaofnorth2** [comment]
Oops I got it: my webpack.config.js file was written in es2015 using the "import" syntax for modules, which isn't supported natively by node 6.0.0.
Using "require" to import modules solves it.

**Comment by Wexcode** [comment]
Note that for a es6 webpack config to work you must also have `babel-core` installed (either locally or globally, depending on your editor). For vim + syntastic users it must be installed globally.

**Comment by marceloemanoel** [comment]
@theideaofnorth2 Thank you! This solved my problem!

**Comment by Tux1** [comment]
I have got the same issue and I cannot fix it.
I use `babel-core` and :    
   "eslint": "^3.7.0",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-import-resolver-webpack":f "^0.6.0",
    "eslint-plugin-import": "^2.0.0",

Any suggestion ?

**Comment by dickeylth** [comment]
Me too: https://github.com/benmosher/eslint-plugin-import/issues/692

**Comment by xuqinggang** [comment]
使用 [eslint-import-resolver-webpack](https://www.npmjs.com/package/eslint-import-resolver-webpack)，告诉eslint，使用webpack的resolver来检查package是否引用正确
`
module.exports = {
     // ...
    // eslint-import-resolver-webpack 让eslint，使用webpack的resolver来检查package是否引用正确
    settings: {
        "import/resolver": 'webpack',
    },
};

`
