### ISSUE TITLE
Add specs for showRuleIdInMessage

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-eslint#473]
We aren't currently testing the results of toggling `showRuleIdInMessage`.

**Comment by granteagon** [comment]
@Arcanemagus Happy to help implement this if help is wanted.

**Comment by steelbrain** [comment]
@granteagon We'd be happy to review a PR if you wanna help :)

**Comment by granteagon** [comment]
👍🏼It's on my todo list!

**Comment by Arcanemagus** [comment]
Turns out the reason they weren't showing as HTML currently was that the package wasn't getting activated, so the defaults weren't being set. This has been fixed now, but there should still be a spec testing the option controlling that if we are going to keep the option.
