### ISSUE TITLE
Errors crash the linter fatally

### ISSUE THREAD

**Issue by jontonsoup** [AtomLinter/linter-eslint#479]
I'm getting this error on a comma splice -- this crashes the linter until I restart it using toggle.

<img width="537" alt="screen shot 2016-03-10 at 6 21 50 pm" src="https://cloud.githubusercontent.com/assets/845636/13688025/fcea1656-e6ec-11e5-9639-288fb9e11873.png">

```
{
    "plugins": [
        "flowtype",
        "react"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
      "ecmaFeatures": {
        "jsx": true,
        "modules": true
      }
    },
    "env": {
      "browser": true,
      "node": true
      },
  "extends": ["eslint:recommended", "plugin:react/recommended"]
}
```

**Comment by Arcanemagus** [comment]
This _sounds_ like expected behavior... if your JS is invalid then `eslint` will throw a fatal error until it is fixed, at which point it will then run the rest of the rules.

Is this not what you are talking about?

**Comment by jontonsoup** [comment]
@Arcanemagus nope. eslint is broken after I fix the typo (it still underlines the line)

**Comment by jontonsoup** [comment]
Actually, let me correct myself -- the errors not going away are not specific to syntax errors. I'm getting the same behavior for no-unused-vars as well (probably all errors)

**Comment by Arcanemagus** [comment]
Can you provide a file in the state that causes this crash?

**Comment by jontonsoup** [comment]
```
'use strict'
/* @flow */

if (process.env.ENV !== 'test' && process.env.ENV !== 'development') {
  require('newrelic')
}

require('babel-core/register')
require('babel-polyfill')

let app = require('./server').app

app.listen(app.get('port'), () => {
  if (process.send) {
    process.send('online');
  } else {
    //empty block
  }
})
```

Filling in the empty block does not remove the empty block error.

**Comment by Arcanemagus** [comment]
I am unable to reproduce with this structure: [linter-eslint_GH479.zip](https://github.com/AtomLinter/linter-eslint/files/168249/linter-eslint_GH479.zip)

_Note: I moved the `//empty block` comment up a line so that the error is actually triggered_

I can move the comment around triggering and then not triggering the message, and it disappears and appears as it should.

What do you get from running the following?

```ShellSession
atom -v
apm -v
apm list --installed
```

**Comment by jontonsoup** [comment]
```
[jonathan]: atom -v                                                         [~]
1.5.4
[jonathan]: apm -v                                                          [~]
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.1
[jonathan]: apm list --installed                                            [~]
/Users/jonathan/.atom/packages (13)
├── bottom-dock@0.3.7
├── ex-mode@0.8.0
├── highlight-selected@0.11.2
├── language-javascript-jsx@0.3.7
├── linter@1.11.3
├── linter-eslint@7.1.0
├── linter-flow@4.1.0
├── linter-manager@0.2.9
├── linter-scss-lint@2.5.1
├── pigments@0.24.5
├── terminal-plus@0.14.5
├── tomorrow-night-eighties-syntax@0.12.0
└── vim-mode@0.65.0
```

**Comment by jontonsoup** [comment]
@Arcanemagus  also FYI:

[jonathan]: eslint -v                                                       [~]
v2.3.0

**Comment by Arcanemagus** [comment]
Wait, are you using a _global_ `eslint`? Can you try with the exact folder I uploaded above?

**Comment by jontonsoup** [comment]
oh woah -- works fine in your file. Is this a path issue? Yes, I am using a global eslint.

I turned on global eslint in the settings.

**Comment by jontonsoup** [comment]
I changed this to a devDep install and disabled flow checking and the issue went away. 

Thanks for the help!

**Comment by Arcanemagus** [comment]
The general practice is to have a local `eslint` configured in your `package.json`, as this means everyone is using the same setup.

In this case I'm betting this was a side effect of trying to make `eslint@2.3.0` and `babel-eslint@5.0.0` work together, as they are incompatible (see https://github.com/AtomLinter/linter-eslint/pull/465).

**Comment by jontonsoup** [comment]
Yea I had this setup but some incompatibilities forced me to change it. 

Best,

Jon

On Thu, Mar 10, 2016 at 8:01 PM Landon Abney

<
mailto:Landon Abney <notifications@github.com>
> wrote:

The general practice is to have a local

eslint

configured in your

package.json

, as this means everyone is using the same setup.

In this case I'm betting this was a side effect of trying to make

eslint@2.3.0

and

babel-eslint@5.0.0

work together, as they are incompatible (see
https://github.com/AtomLinter/linter-eslint/pull/465
).
