### ISSUE TITLE
Error: Unknown node type TypeAlias && ClassProperty

### ISSUE THREAD

**Issue by gregegan** [AtomLinter/linter-eslint#483]
Continually getting the following linting errors.
`Error: Unknown node type ClassProperty.`
`Error: Unknown node type TypeAlias.`

When turning on atom developer tools with pause on exceptions, here is the exception message.
```
`[ERROR] nuclide - Flow failed: flow get-def --json --path /Users/gregegan/gigwalk/apps/gigwalk_apps_platform/gigwalk_app/platform_fe/static/js/apps/projects/dev/components/BulkInviteForm.js 8 3. Error: {"exitCode":8,"stderr":".flowconfig:25 Wrong version of Flow. The config specifies version 0.22.1 but this is version 0.22.0\n","stdout":"","name":"Async Execution Error","message":"exitCode: 8, stderr: .flowconfig:25 Wrong version of Flow. The config specifies version 0.22.1 but this is version 0.22.0\n, stdout: ."}`
```

```
node -v
v5.8.0

npm ls flow-bin
├── flow-bin@0.22.1
└─┬ gulp-flowtype@0.4.9
  └── flow-bin@0.20.1

apm ls
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.15.6
├── language-ini@1.14.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.3
├── linter-eslint@7.1.1
├── linter-jscs@3.4.8
├── nuclide@0.124.0
├── sort-lines@0.14.0
└── tool-bar@0.3.0

```

![image](https://cloud.githubusercontent.com/assets/6665100/13713722/5e137868-e77f-11e5-8d98-e04d88ab3617.png)

![image](https://cloud.githubusercontent.com/assets/6665100/13713790/a9957854-e77f-11e5-855d-94e71337b891.png)

**Comment by Arcanemagus** [comment]
The flow message has nothing to do with this plugin. The error screenshots you point to are related to `estraverse`, which has some issues with `eslint@2.3.0`. Is that the version of `eslint` that you are using?

**Comment by gregegan** [comment]
![image](https://cloud.githubusercontent.com/assets/6665100/13716543/ae32059c-e790-11e5-9445-5c12cb597619.png)

**Comment by Arcanemagus** [comment]
It looks like from that screenshot you have `eslint@2.2.0` installed globally, and `eslint@2.3.0` installed locally to your project?

**Comment by gregegan** [comment]
Success! Thanks @Arcanemagus.

Changed my local project eslint to eslint@2.2.0

**Comment by Arcanemagus** [comment]
Glad to hear it. :wink:

**Comment by IanVS** [comment]
2.4.0 was just released which should fix the estraverse bug.
