### ISSUE TITLE
Error: Unable to execute `npm get prefix`

### ISSUE THREAD

**Issue by albertosantini** [AtomLinter/linter-eslint#484]
With `7.0.0` it was ok.

Adding the output of `npm get prefix` in `Global Node Installation Path` field fixes the issue.
I would expect not to insert that value.

- eslint 2.3.0
- linter-eslint 7.1.1
- Windows 10

```
  "linter-eslint":
    useGlobalEslint: true
```

```
Error: Unable to execute `npm get prefix`. Please make sure Atom is getting $PATH correctly
    at getNodePrefixPath (C:\Users\icebox\.atom\packages\linter-eslint\lib\worker-helpers.js:57:13)
    at getESLintFromDirectory (C:\Users\icebox\.atom\packages\linter-eslint\lib\worker-helpers.js:67:47)
    at Object.getESLintInstance (C:\Users\icebox\.atom\packages\linter-eslint\lib\worker-helpers.js:97:10)
    at C:\Users\icebox\.atom\packages\linter-eslint\lib\worker.js:59:24
    at Emitter.emit (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-event-kit\lib\emitter.js:70:19)
    at C:\Users\icebox\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-communication\lib\main.js:22:23
    at C:\Users\icebox\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-communication\lib\main.js:21:24
    at Emitter.emit (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-event-kit\lib\emitter.js:68:19)
    at Communication.parseMessage (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-communication\lib\main.js:63:18)
    at process.ProcessCommunication.messageCallback (C:\Users\icebox\.atom\packages\linter-eslint\node_modules\process-communication\lib\communication.js:35:27)
```

**Comment by Arcanemagus** [comment]
So the latest version shows this, but `apm install linter-eslint@7.0.0` doesn't?

**Comment by albertosantini** [comment]
Correct.

**Comment by albertosantini** [comment]
Debugging the following line https://github.com/AtomLinter/linter-eslint/blob/master/lib/worker-helpers.js#L54, I see PATH is null and not a string.

I thought it was due to
https://github.com/AtomLinter/linter-eslint/commit/3dae8fb0b9a534d4c911c9c57092dd84b6785cf1#diff-ba0b506b21d765d9a942022f3dbdd800

but reverting that it doesn't resolve the issue.

**Comment by Arcanemagus** [comment]
@albertosantini Do you have `eslint` installed globally? The only way you should be hitting this error is if you have the "Use global eslint instance" option enabled, but _don't_ have `npm` available on your system... which you would need to have available to install `eslint` globally.

**Comment by albertosantini** [comment]
Yes, I installed eslint globally, I have `Use global eslint instance` enabled and I have `npm` available in the PATH.

On my side, nothing is changed between `7.0.0` and `7.1.1`.

```
λ npm ls -g --depth=0
C:\Users\icebox\AppData\Roaming\npm
+-- eslint@2.3.0
...
```
```
  "linter-eslint":
    useGlobalEslint: true
```

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

11:46:49 [C:\Users\icebox]$ npm get prefix
C:\Users\icebox\AppData\Roaming\npm
```

(node 5.8.0, npm 3.7.3)

**Comment by albertosantini** [comment]
Well, weirdly, as I said, `getPath()` returns `null` in 
https://github.com/AtomLinter/linter-eslint/blob/master/src/worker-helpers.js#L29

So I removed it:
`ChildProcess.spawnSync(npmCommand, ['get', 'prefix']).output[1].toString().trim()`

In `lib` I have:
` Cache.NODE_PREFIX_PATH = _child_process2.default.spawnSync(npmCommand, ['get', 'prefix']).output[1].toString().trim();`

And it works ok.

Really I don't know, if it works  with all OSs.
I tested on Windows with global and local setup.

What do you think?

**Comment by steelbrain** [comment]
@albertosantini I think I know what's happening here, can you provide us your OS?

**Comment by albertosantini** [comment]
Windows 10 64bit

**Comment by steelbrain** [comment]
Aha! I'll have a fix up in a few minutes

**Comment by steelbrain** [comment]
#### The Problem

On all platforms but windows, the name of the `$PATH` variable is `PATH`. But on windows, it can be a lot of other things as well. Windows treats ENV keys as case insensitive IIRC so `Path` and `PATH` are both valid

#### The solution

Try to get both `PATH` and `Path` on windows. See https://github.com/steelbrain/consistent-path/pull/7

**Comment by steelbrain** [comment]
@albertosantini Here's how you can get that fix
```
# To reset your local changes
apm uninstall linter-eslint
apm install linter-eslint

# To upgrade consistent-path to latest version
cd ~/.atom/packages/consistent-path
npm install consistent-path@latest
```

@Arcanemagus Should we publish a release of this package bumping the dep version?

**Comment by albertosantini** [comment]
Well... thanks for the details to upgrade manually that dep.
I backported the changes directly in the dep.

It works ok.

Thanks for your efforts.
