### ISSUE TITLE
Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by TimonVS** [AtomLinter/linter-eslint#487]
I get an error when the linter kicks off.

```
Error: Cannot find module 'babel-eslint' from '/Users/timon/.atom/packages/linter-eslint/node_modules'
```

**Comment by TimonVS** [comment]
I'm sorry, it was my own mistake.

**Comment by sethbergman** [comment]
Try this setting:

![](https://cloud.githubusercontent.com/assets/427137/14826214/b85fabf8-0b91-11e6-9786-8a6ea0d1affe.png)

You don't need to add `babel-eslint` as a dependency. Just check this setting in Atom.

**Comment by IanVS** [comment]
@sethbergman, we recommend installing all of your project's dependencies as explicit dependencies, including eslint and any eslint plugins or parsers that you're using.  Yes, you can install everything globally, but that can cause problems if you work on different projects which all have different configurations.
