### ISSUE TITLE
404's on some rules

### ISSUE THREAD

**Issue by larryboymi** [AtomLinter/linter-eslint#490]
http://eslint.org/docs/rules/react/sort-comp
http://eslint.org/docs/rules/react/prop-types

maybe others..

Found content here... https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules

**Comment by Arcanemagus** [comment]
The rules don't provide a URL, it is just making a guess that they are base `eslint` rules. If you want this functionality to be implemented reliably you would need to file a feature request on `eslint` asking for a URL field to be added to rules. In this case you would also need `eslint-plugin-react` to support it once it was added to `eslint`.

For now the added benefit of being able to click on rules and get a definition for most of them outweighs the issue of a few dead links from plugin rules in my opinion.

**Comment by larryboymi** [comment]
Gotcha, thanks for your reply!
