### ISSUE TITLE
Is there a way to specifiy a relative path to .eslintrc ?

### ISSUE THREAD

**Issue by antoinerey** [AtomLinter/linter-eslint#491]
I set up a [package](https://www.npmjs.com/package/eslint-config-antoinerey) including configuration and dependencies needed for ESLint to work (eslint itself, babel-eslint ...). So I can `npm install eslint-config-antoinerey` and start linting my files out of the box.

Calling `eslint` from the CLI works like expected.

But, `linter-eslint` cannot find the local `.eslintrc` - it does not exist. So, I'd like to set a relative path to `<project-path>/node_modules/eslint-config-antoinerey/.eslintrc`. Is that even possible ?

**Comment by Arcanemagus** [comment]
That package isn't how `eslint` configuration packages work. A proper `eslint-config-____` package exports a set of rules, then in your project you include that package as a dependency, and in the project's `.eslintrc.__` file you use the `extends` key to tell `eslint` to check your module for additional rules to load.

It seems that the blog post mentioned in your "config" repo was based on `eslint@^1.0.0`, and relies on several implementation quirks to work at all. I would highly recommend against doing things in that manner as you will run into all sorts of issues.

All that being said, you _might_ be able to hack this together using the `.eslintrc Path` configuration option, but it's highly likely you will run into issues with plugin detection.

**Comment by antoinerey** [comment]
Indeed, that package is not a standart `eslint` configuration used with the `extends` keyword. It contains the rules and the presets (the `airbnb` one), but also, all the dependencies like `eslint`, `babel-eslint`, `eslint-plugin-react` ...  This way, I can just install my package and all its dependencies will be set up for me. 

Unlike the original package, mine includes `eslint 2.x.x`. It does work by calling the `eslint` command from the CLI.

That said, is there a special keyword to use to setup a relative path from the linter configuration ?

**Comment by antoinerey** [comment]
I just forced myself to use a common eslint-config package. Thanks for your time ;)
