### ISSUE TITLE
Error: Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by antoinerey** [AtomLinter/linter-eslint#492]
As explained in #491, I set up a package to speed up the ESLint configuration when starting a project.

For now, I set the path to `.eslintrc` absolutely `/Users/antoinerey/Sites/project/node_modules/eslint-config-antoinerey/.eslintrc` and try to get `linter-eslint` woking.

It does find the `.eslintrc` file but cannot find 'babel-eslint'. It is however installed locally (`nodes_modules/babel-eslint`)

It that because my `package.json` does not have it as `dependency` ?

**Comment by IanVS** [comment]
How are you using `eslint`?  Is it installed locally, globally, or are you relying on the version packaged with `linter-eslint`?

**Comment by antoinerey** [comment]
I set up a package containing my configuration `.eslintrc` and my dependencies. (ESLint itself, Airbnb's preset, additional plugin...) This package also expose a curtom `eslint` command to get it working from the CLI.

```
- - - - - -          - - - - - - - - - - - -        - - - - - - - - - - - -
| PACKAGE |  ---->  | CUSTOM ESLINT COMMAND | ----> | REAL ESLINT COMMAND |
- - - - - -          - - - - - - - - - - - -        - - - - - - - - - - - -
```

So the only package required directly at the project level is the configuration package. Eslint, Airbnb's preset and all plugins are dependencies of the package.

**Comment by antoinerey** [comment]
I just forced myself to use a common eslint-config package. Thanks for your time ;)

**Comment by leny** [comment]
Hi @antoinerey, can you document how you resolved this issue? I'm having the same problem when using `babel-eslint` as parser for a project.

Thanks in advance,

**Comment by Arcanemagus** [comment]
@leny can you please file a new issue? @antoinerey was attempting to use a very unique setup and it's highly unlikely you are running into issues for the same reasons.

In your new issue please include the relevant sections of your `package.json`, your `eslint` configuration file(s), and the directory structure leading to the file you are trying to lint.

**Comment by sethbergman** [comment]
Try this setting:

![](https://cloud.githubusercontent.com/assets/427137/14826214/b85fabf8-0b91-11e6-9786-8a6ea0d1affe.png)

You don't need to add `babel-eslint` as a dependency. Just check this setting in Atom.
