### ISSUE TITLE
Dot files are not linted.

### ISSUE THREAD

**Issue by AaronFriel** [AtomLinter/linter-eslint#493]
Suppose I have a few files:

`test.js`
```
var test = [
  foo,
  bar.
  test;
]
```

And 

`.test.js` (note that the filename begins with a dot)
```
var test = [
  foo,
  bar.
  test;
]
```

And 

`test.test.js`
```
var test = [
  foo,
  bar.
  test;
]
```

All three are correctly picked up as having the JavaScript grammar (in my case Babel ES6 JavaScript), however the file beginning with a dot does not get linted.

This occurs even with this `.eslintrc`:
```
{
}
```

And with an empty `.eslintignore`.

This issue is fixed if I select the option "Disable using .eslintignore files". But why are dot files ignored by default? 

The negative path `!**/.*.js` does not seem to work either, if I add that to my `.eslintignore` the dot file is still ignored.

**Comment by IanVS** [comment]
This is the default behavior of ESLint itself, and has nothing to do with linter-eslint.  I'm in the process of reworking how ESLint handles default ignore patterns.  If you'd like to file an issue in the ESLint repo, it would help to track this.

**Comment by IanVS** [comment]
Incidentally, this _should_ be fixed in recent versions of ESLint, I believe.
