### ISSUE TITLE
Add option: Update errors on file save

### ISSUE THREAD

**Issue by vjancik** [AtomLinter/linter-eslint#497]
Currently my ESLint Errors and Warnings get updated with every character I write in Atom. It's a total distracting light show. Is there a way to change it to update only on file save?

If not could we implement it as an option? I would be happy to send in a pull request.

**Comment by IanVS** [comment]
Hm, this used to be a setting, but it seems to have been removed.  @Arcanemagus @steelbrain was this intentional?

**Comment by steelbrain** [comment]
@IanVS It still is, the user just needs to disable `lintOnFly` in base linter config

**Comment by IanVS** [comment]
Oh right, I forgot to check the base linter options.  :facepalm:

**Comment by vjancik** [comment]
I found the setting. Thanks!
