### ISSUE TITLE
Request for package information failed: getaddrinfo ENOTFOUND (ENOTFOUND)

### ISSUE THREAD

**Issue by ericntd** [AtomLinter/linter-eslint#499]
I have `eslint` 2.4.0 installed both globally and locally and an .eslintrc.js file as follows:
```
module.exports = {
    "extends": "airbnb",
    "plugins": [
        "react"
    ],
    "rules": {
        "indent": [2, 4]
    }
};
```
My Atom version is 1.6.0

**Comment by Arcanemagus** [comment]
That's an error from `apm`, not this package.

From a quick Google search this looks to be connectivity issues, have you tried installing it again?
