### ISSUE TITLE
Worker died unexpectedly

### ISSUE THREAD

**Issue by birra05** [AtomLinter/linter-eslint#503]
Hello!
I'm getting the same mistake each time I try to launch Linter-Eslint in Atom settings: 

[Linter-ESLint] Worker died unexpectedly
Check your console for more info. A new worker will be spawned instantly.

I use Atom version 1.6.0.

**Comment by Arcanemagus** [comment]
What messages are being printed in your Developer Tools console?

**Comment by birra05** [comment]
It's weird, but now I don't get this alert and Eslint is working :)
Many thanks!
