### ISSUE TITLE
Semi "never" rule not working from package.json

### ISSUE THREAD

**Issue by scottmartin** [AtomLinter/linter-eslint#504]
I'm using the below eslint configuration in my package.json file. When I run `./node_modules/.bin/eslint src/client.js` it works just fine and gives me no errors. However, when I pull up the same file in Atom I get errors saying I'm missing my semicolons. I've also realized that if I move the same config to a .eslintrc file then the errors in Atom go away. Something about having them defined in my package.json is causing my `"semi": [2, "never"]` rule to be ignored.

```json
"eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 6,
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "env": {
      "browser": true,
      "node": true
    },
    "plugins": [
      "react"
    ],
    "extends": ["eslint:recommended", "plugin:react/recommended"],
    "rules": {
      "strict": [2, "global"],
      "no-undef": 2,
      "no-unused-vars": 2,
      "semi": [2, "never"],
      "semi-spacing": 2,
      "no-extra-semi": 2,
      "no-unexpected-multiline": 2,
      "quotes": [2, "single", "avoid-escape"],
      "indent": [2, 2, { "SwitchCase": 1 }]
    }
  }
```

**Comment by IanVS** [comment]
Are _any_ rules being applied from your `package.json`?  Do you also have `.eslintrc` files in your project?

**Comment by scottmartin** [comment]
I did see changes when I changed other rules. I have also tried .eslintrc but not at the same time. It's odd. The semi rule is the only one that I can see being effected.

**Comment by scottmartin** [comment]
I just created a blank project called test on my desktop. I used the following package.json file and I'm having the same problem.

package.json
```json
{
  "name": "test",
  "private": true,
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "eslint": "^2.5.1",
    "eslint-plugin-react": "^4.2.3"
  },
  "eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 6,
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "env": {
      "browser": true,
      "node": true
    },
    "plugins": [
      "react"
    ],
    "extends": ["eslint:recommended", "plugin:react/recommended"],
    "rules": {
      "strict": [2, "global"],
      "no-undef": 2,
      "no-unused-vars": 2,
      "semi": [2, "never"],
      "semi-spacing": 2,
      "no-extra-semi": 2,
      "no-unexpected-multiline": 2,
      "quotes": [2, "single", "avoid-escape"],
      "indent": [2, 2, { "SwitchCase": 1 }]
    }
  }
}
```

index.js
```javascript
'use strict'
const express = require('express')
```

```shell
npm install
```

When I open index.js in Atom all of my rules seem to work except the semicolon one.

**Comment by IanVS** [comment]
I'm not able to test it myself at the moment, but is it possible that you
have an eslint config file in an ancestor directory or in your home
directory?

**Comment by scottmartin** [comment]
I just checked and indeed I did have a .eslintrc.json file in my home directory. I must have played around with eslint once before. Removing that file fixed the issue. So sorry for wasting your time.

**Comment by IanVS** [comment]
No trouble at all. Glad it's working. Not sure why it behaves differently from the CLI, though. We should only be looking in home directory if no other configs are found. I'll need to investigate a bit, so keeping the issue open for now.
