### ISSUE TITLE
Issues with module.exports = {...somethingElse, ...module.exports}

### ISSUE THREAD

**Issue by artursgirons** [AtomLinter/linter-eslint#505]
When module with content bellow gets imported into other file, eslint is highlighting methods as not found in that file:

```javascript
const somethingElse = getSomethingElse()
export function somethings() {}
module.exports = {...somethingElse, ...module.exports}
```

**Comment by IanVS** [comment]
Sorry, I'm having a hard time following.  Do you believe this to be an issue only in Atom, or does ESLint report the error when you run it manually on the command line as well?  Also, it would be very helpful if you can provide the actual error message you are seeing.

**Comment by artursgirons** [comment]
When i run it manually, all is good! Issue happens, when this module (as described abow) is being imported somewhere else.

```javascript
import mixedExports from 'mixedExports.js'

mixedExports.somethings() // all fine, no eslint errors
mixedExports.functionFromSomethingElse() // eslint in Atom reports that module does not have such function!
```

Sorry, I don't remember exact message (I restructure my code already to avoid this error, but I would like not to do that :) ), but it was about methods or something not being found in exported module

**Comment by IanVS** [comment]
I'm afraid this really isn't enough information to go off of in order to troubleshoot this.  If you can provide the exact message and the rule name that is giving the error, we can try to help.  But for now unfortunately there's not much we can do.
