### ISSUE TITLE
Upgrade eslint to 2.5.0 

### ISSUE THREAD

**Issue by pvamshi** [AtomLinter/linter-eslint#510]
I am getting the following error in my project. The reason being eslint now supports `off`, `warn`, `error` along with 0,1,2 . This change happened in 2.3.0 it seems. 
The eslint shipped with linter-eslint is 2.2.0 and causing this issue. 
When I upgraded the eslint version to 2.5.0 ( latest) the error stopped appearing. 

eslint change issue : https://github.com/eslint/eslint/issues/3626
tl;dr: 
Need to upgrade eslint shipped along with `linter-eslint`
```
Error: /home/vamshi/projects/eslint/packages/eslint-config-eslint/default.yml:
    Configuration for rule "array-callback-return" is invalid:
    Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "error").
Referenced from: /home/vamshi/projects/eslint/.eslintrc.yml
    at validateRuleOptions (/home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-validator.js:111:15)
    at /home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-validator.js:157:13
    at Array.forEach (native)
    at Object.validate (/home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-validator.js:156:35)
    at load (/home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-file.js:459:19)
    at /home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-file.js:338:28)
    at Object.load (/home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config/config-file.js:464:22)
    at loadConfig (/home/vamshi/projects/linter-eslint/node_modules/eslint/lib/config.js:67:33)
```

**Comment by kaicataldo** [comment]
Can confirm this locally with a freshly installed `linter-eslint` package. Looks like it installs ESlint v2.2.0 despite the `package.json` version being `^2.4.0`. Maybe has something to do with the release process and how the package is being bundled?

**Comment by pvamshi** [comment]
I believe there was a recent commit to upgrade from 2.2.0 , I did not take that update. @kaicataldo  Can you please delete eslint in node_modules, and try again with latest version . If its still 2.2.0 we can check further.

**Comment by kaicataldo** [comment]
@pvamshi I did a fresh install from within Atom's settings panel. Do you mean then going into the hidden atom packages directory and manually deleting the node_modules folder? For what it's worth, cloning this repo, `npm install`ing, and then `apm link`ing makes it work just fine, as it pulls the latest version of ESLint on install.

Seems to me like the ESLint version packaged with `apm` might not be up to date, but I'm not sure how that all works.

**Comment by pvamshi** [comment]
ok. I will try the same steps and report.

**Comment by Arcanemagus** [comment]
I've seen many issues with `apm` not fully installing things, or installing the wrong version. My guess is that it has cached `eslint@2.2.2` and for some reason decided that that was good enough :confused:.

In any case you should _not_ be using the bundled version of `eslint`. If the `eslint` repo itself for some reason prevents installing `eslint` to it's `node_modules` I guess you could install it globally? The bundled version is intended to be a last case fallback if everything else failed to be found.

**Comment by Arcanemagus** [comment]
Also note for everyone in this thread: The bundled version of `eslint` is an absolute last resort fallback if no other version can be found. You should be using one installed locally in your project, or it that isn't possible for some reason then you should install it globally. The bundled version is only to provide _very_ basic linting support if no better version can be found.
