### ISSUE TITLE
gitter/slack integration

### ISSUE THREAD

**Issue by pvamshi** [AtomLinter/linter-eslint#512]
I've been trying to understand the project and got lots of doubts but not sure how to communicate . Is there a way we can communicate better.

**Comment by Arcanemagus** [comment]
There is a #linter-plugin-dev channel on [Atom's Slack Instance](http://atom-slack.herokuapp.com/).

**Comment by pvamshi** [comment]
Can we put a link in the description ? 
or is it pretty obvious ?

**Comment by IanVS** [comment]
Seems like a good idea to me.  Want to submit a PR to put it in CONTRIBUTING.md?

**Comment by pvamshi** [comment]
yeah will do . Thanks
