### ISSUE TITLE
i use eslint in atom but happend this problem

### ISSUE THREAD

**Issue by zhiqiang21** [AtomLinter/linter-eslint#517]
![image](https://cloud.githubusercontent.com/assets/3990411/14131908/5918fe1c-f672-11e5-8331-d9c4b5f7fdaf.png)

.eslintrc.js use ourself 

![image](https://cloud.githubusercontent.com/assets/3990411/14131932/9ba53408-f672-11e5-82d3-6116ef3134e0.png)

**Comment by IanVS** [comment]
It looks like you don't have ESLint installed locally in your project, and you don't have the `Use global ESLint` option checked, so linter-eslint is falling back to the bundled version of ESLint which does not support the newer string style of rule severity.

So, you have a few options of how to solve this.  My recommendation would be to install eslint into your project with `npm install --save-dev eslint`.  Or if you don't want to do that for some reason, you can tell linter-eslint to use your global installation.

Also, out of curiosity, what version of linter-eslint are you using?

**Comment by zhiqiang21** [comment]
`npm install --save-dev eslint`  solve my question! thanks
