### ISSUE TITLE
Automatically add linting for HTML-embedded JS when eslint-plugin-html is installed

### ISSUE THREAD

**Issue by chrisvfritz** [AtomLinter/linter-eslint#519]
Right now, it's necessary to check the option to lint HTML files in the settings, but would it be possible to just check whether `eslint-plugin-html` is installed instead? If it's installed, people probably always want to lint HTML, right?

**Comment by Arcanemagus** [comment]
Marking this as a duplicate of #254.

I don't want to start maintaining a list of what plugins add what support, and as getting that support working properly requires extra configuration anyway, this isn't something that should be handled automatically.
