### ISSUE TITLE
ESLint not found, Please install or make sure Atom is getting $PATH correctly

### ISSUE THREAD

**Issue by alexmngn** [AtomLinter/linter-eslint#521]
Hi,
My linter-eslint was working fine using my local `.eslintrc` file, until I had the bad idea to change the value of the empty field in the config: `.eslintrc Path`
I changed it, reverted my change to have it back to empty, and now eslint complains about the $PATH not found. 
I tried to uninstall eslint, linter-eslint, to run atom from the terminal, nothing changes, it still complains:

```
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
    at getESLintFromDirectory (/Users/alex/.atom/packages/linter-eslint/lib/worker-helpers.js:80:13)
    at Object.getESLintInstance (/Users/alex/.atom/packages/linter-eslint/lib/worker-helpers.js:97:10)
    at /Users/alex/.atom/packages/linter-eslint/lib/worker.js:59:24
```

How can I get rid of this error?
Thanks!!

**Comment by IanVS** [comment]
I think you have the `Use global ESLint installation` option checked.  Try turning that off.

**Comment by jgrosso** [comment]
Try `npm install -g eslint`

**Comment by IanVS** [comment]
>Try `npm install -g eslint`

That is generally not recommended.  It is better to install all your dependencies in your projects.
