### ISSUE TITLE
Local ESLint not found

### ISSUE THREAD

**Issue by ChrisC** [AtomLinter/linter-eslint#522]
Locally installed `eslint` v2.5.3 and `eslint-plugin-react` v4.2.3 into project are not being recognized by `linter-eslint` v7.1.3. Neither packages are installed globally and `use global eslint installation` is not checked. Tried `npm cache clear` and re-installing but that does not resolve the problem. 

Here’s the error message I’m seeing in the editor:
```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.load (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:134:21)
    at Object.load (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:443:21)
    at loadConfig (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/chris/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:192:38)
```

cc @1beb @IanVS

**Comment by Arcanemagus** [comment]
What is the directory structure of the file you are editing?

I'm looking for something like this so I can attempt to replicate your setup:
```text
project\
  node_modules\
  foo\
    bar.js
  package.json
```

**Comment by ChrisC** [comment]
@Arcanemagus yup exactly

**Comment by Arcanemagus** [comment]
Okay..... are you able to share a zip of the folder (without `node_modules`, of course)?

The above structure works perfectly fine...

**Comment by ChrisC** [comment]
Interesting… I just tried opening my project in a new Atom window and I’m not seeing the errors. Could be that the Atom project may have been corrupted somehow when `linter-eslint` last upgraded!

**Comment by 1beb** [comment]
I found something similar. It seemed to work not after restarting, but after Ctrl + Alt + R

On Thu, Mar 31, 2016 at 5:31 PM, Chris Cuellar < notifications@github.com [notifications@github.com] > wrote:
Interesting… I just tried opening my project in a new Atom window and I’m not seeing the errors. Could be that the Atom project may have been corrupted somehow when linter-eslint last upgraded!

**Comment by Arcanemagus** [comment]
Ah, if you haven't restarted Atom since updating things can get... wonky. Atom has a bad habit of not killing the worker threads on updates. You need to fully close the window and open a new window to spawn a new worker process.

**Comment by ChrisC** [comment]
Ouch! After leaving the project open for a few hours I’m starting to see the errors again :confounded: @1beb’s solution not working either...

**Comment by derakhshanfar** [comment]
i have same problem...please fix this bug..

**Comment by IanVS** [comment]
We're not going to be able to troubleshoot without a solid reproducible case.  It would help us a lot if you could share enough info to reproduce it (zip file as @Arcanemagus requested).

**Comment by shodanuk** [comment]
I've added quite a bit of detail to the following (very similar) issue: https://github.com/AtomLinter/linter-eslint/issues/489#issuecomment-200003188

**Comment by derakhshanfar** [comment]
i only uninstall global eslint and use it in local project by npm install eslint --save-dev and its fix for me...

**Comment by deathgaze** [comment]
@derakhshanfar 's solution works great. Removing global `eslint` and `eslint-plugin-react` and `npm install`ing locally into project worked great. 

For reference, to use it like this requires something like this: 
```(master %) ~/project/ $ npm install eslint --save
(master %) ~/project/ $ /node_modules/.bin/eslint --init
// Answer questions
// IF NESCESSARY -- these weren't installed automatically for me...
(master %) ~/project/ $ npm install eslint-plugin-react eslint-plugin-airbnb --save
```

**Comment by jagged3dge** [comment]
Just a thought, might want to use `--save-dev` (or `-D`) for eslint and its plugins, so that they're not installed when the project is deployed to a `NODE_ENV=production` environment.
```
$ npm install eslint eslint-plugin-react eslint-plugin-airbnb --save-dev
```

**Comment by IanVS** [comment]
@ChrisC Is this issue resolved for you now?

**Comment by ChrisC** [comment]
@IanVS yes haven't seen this issue in a while 👍
