### ISSUE TITLE
Can't find rule definitions for plugins

### ISSUE THREAD

**Issue by MidnightLightning** [AtomLinter/linter-eslint#523]
In attempting to use `linter-eslint` inside Atom with the `eslint-plugin-react` plugin, I get an error inside Atom on the first line of the file that "Definition for rule 'jsx-closing-bracket-location' was not found.

Attempted with ESLint and the plugin installed locally:
```
{
  "devDependencies": {
    "eslint": "^2.5",
    "eslint-plugin-react": "^4.2.3"
  },
  "eslintConfig": {
    "extends": "eslint:recommended",
    "parserOptions": {
      "ecmaVersion": 5,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "plugins": ["react"],
    "env": {
      "browser": true,
      "amd": true,
      "node": true
    },
    "rules": {
      "jsx-closing-bracket-location": 2
    }
  }
}
```

And tried with ESLint and the plugin installed globally: `npm install --global eslint eslint-plugin-react`

Both resulted in the same error.

From the command line inside my project, running `eslint src/js` (global ESLint) and `./node_modules/.bin/eslint src/js` (local ESLint) both run without issue, so ESLint itself seems to be working, just the connection inside Atom isn't picking up the additional plugin rule definitions.

**Comment by MidnightLightning** [comment]
Never mind, I was wrong; running from the command line is also not able to see the plugin, so this is an ESLint configuration issue, not an Atom `linter-eslint` issue.

**Comment by Arcanemagus** [comment]
Thanks for reporting back @MidnightLightning :wink:.
