### ISSUE TITLE
[Linter-ESLint] Worker died unexpectedly

### ISSUE THREAD

**Issue by silvaemota** [AtomLinter/linter-eslint#524]
[Linter-ESLint] Worker died unexpectedly
Check your console for more info. A new worker will be spawned instantly.

**Comment by Arcanemagus** [comment]
Do you have any further information posted in the console?

**Comment by nelson6e65** [comment]
I'm having the same issue... Infinite loop with this message.

From console:
```js
[Linter-ESLint] STDERR /home/jeahm/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:17
class ProcessCommunication {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/jeahm/.atom/packages/linter-eslint/node_modules/process-communication/lib/main.js:21:22)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)

```

**Comment by nelson6e65** [comment]
`class` is valid in JavaScript? :confused:

**Comment by Arcanemagus** [comment]
It is in ES6, but that should be ES5 code there. @steelbrain it looks like your transpile into the `lib` folder isn't working properly?

**Comment by justinsthomas** [comment]
I'm seeing the same issue. Has there been any progress made on this, or is this something that's being worked on?

**Comment by Arcanemagus** [comment]
As you can see from the error trace, this is a bug in the `process-communication` module by @steelbrain.

**Comment by steelbrain** [comment]
I don't think this is a bug in `process-communication`, it's working fine, it's just that your Atom is too old to allow `const` syntax

**Comment by Arcanemagus** [comment]
Marking as closed based on the above comment.

**Comment by bronson** [comment]
Just got this with 1.11.2.  Upgrading to 1.12.0 fixed it.

![bug3](https://cloud.githubusercontent.com/assets/1776/20191147/31c6765a-a739-11e6-8c35-3a5cf0f02984.gif)
