### ISSUE TITLE
"Disable when no ESLint config is found" is not honored

### ISSUE THREAD

**Issue by cdaringe** [AtomLinter/linter-eslint#529]
# problem statement
- linter-eslint is enforcing rules in a project where I have no ESLint config
- _I previously used ESLint & ESLint plugins directly_ in this project, but do no longer
  - this project does use standard (which uses eslint under the hood)

demonstration of the issue: https://www.youtube.com/watch?v=0hYH13VNdDE

**Comment by Arcanemagus** [comment]
Do you still have an `eslint` section in your `package.json` file? Do you have an `.eslintrc` file in any format in a parent directory that this project is under?

**Comment by IanVS** [comment]
. . . or in your home directory?

**Comment by cdaringe** [comment]
mother of pete.  ya, it's in a parent dir.  hmm.  is that correct behavior?  i expected that it didnt traverse beyond the scope of the open folder root.

**Comment by Arcanemagus** [comment]
That's the behavior that `eslint` itself should be using, unless it was changed :wink:.

**Comment by cdaringe** [comment]
Ah, I c! In retrospect that makes perfect sense. Thanks all :)

**Comment by IanVS** [comment]
As a side note, configs will cascade all the way back up to root.  If you want to prevent that and treat a particular config file as the "root", thus breaking further cascade upwards, you can add `root: true` to the config file.  ESLint will then not look any higher in the folder structure.
