### ISSUE TITLE
It underlines not only the part of the line that causes the warning/error, but the rest of the line as well

### ISSUE THREAD

**Issue by darkred** [AtomLinter/linter-eslint#530]
_Using Atom 1.6.2 in win10 x64 with ESLint 2.7.0, linter 1.11.4 and linter-eslint 7.1.3._

For example this simple code:
```
var foo = 1;   // test
var obj = { foo: 1 };   // test
obj++;
```
ESlint shows this:
```
 1:5   warning  'foo' is defined but never used      no-unused-vars
  2:11  warning  There should be no space after '{'   object-curly-spacing
  2:20  warning  There should be no space before '}'  object-curly-spacing
```
Well, the problem is that linter-eslint underlines not only the part that causes the warning/error, but the rest of the line as well, even including any inline comment in the end.
That is, instead of only underlining `foo` in line 1 and `{` and `}` in line 2. 
it underlines:
![2016-04-11_164733](https://cloud.githubusercontent.com/assets/723651/14429221/34921e7e-0005-11e6-9098-900211518c79.png)

That's especially confusing when there are multiple warning/errors in the same line, like in line 2.

----

For reference, linting the same file in SublimeText 3, using sublimelinter-eslint:
![2016-04-11_164504](https://cloud.githubusercontent.com/assets/723651/14429233/3d0cad44-0005-11e6-94e2-20ae50e109b9.png)

**Comment by Arcanemagus** [comment]
It looks like something broke your screenshots, but what you are describing is a purposeful design choice.

`eslint` itself only gives a line and column for errors that it reports... note how that does _not_ include a range that the error encompases. This means that we can either have a _single character_ highlighted, or highlight the remainder of the line, starting where `eslint` tells us something is wrong.

As it stands I'm marking this as won't fix and closing, if you have a suggestion as to a better method though please feel free to comment further :wink:.

**Comment by Arcanemagus** [comment]
The crazy thing is... `sublimelinter-eslint` is doing [nothing special](https://github.com/roadhump/SublimeLinter-eslint/blob/1.10.0/linter.py#L46-L62) to pull out that variable name, so I'm not sure how it's even highlighting just that. Maybe the `sublimelinter` runner itself is automatically highlighting tokens when plugins pass it only a single column?

**Comment by darkred** [comment]
> `eslint` itself only gives a line and column for errors that it reports... note how that does _not_ include a range that the error encompases. This means that we can either have a _single character_ highlighted, or highlight the remainder of the line, starting where `eslint` tells us something is wrong.

Apart from the line and column, ESLint also gives the relevant character/string/variable name in the descriptions of the errors that it reports. 
In my examples above these are `foo`, `{`, and `}`.

**So I'd suggest, to underline only the given character/string/variable name.**

---

In cases where there's no character/string/variable name given in the description,
such as for `quotes` errors, for example:  

```
/*eslint quotes: ["error", "double"]*/

var single = 'single';
```
where the error is:
`quotes ---> Strings must use doublequote.at line 3 col 14` 
to only underline the **character** in the given position, i.e. the first/left `'` character

---

Especially in case of `sort-vars` errors, to underline **each variable name** in the line.

---

Especially in case of `key-spacing` errors: 
for example 
```
var bar = { baz :52 };
```
when the error description is about the **key itself** to underline the **key**,
i.e. to underline `52`  i.e.`baz ` because --> there is `Extra space after key 'baz'`  

but when the error description is about the **value of the key** to underline the **value of the key**,
i.e. to underline `52` because --> it's `Missing space before value for key 'baz'`

---
---

Hopefully the above cover most cases. (in all other cases, my suggestions 1 and 2 should be applied )

**Comment by Arcanemagus** [comment]
Parsing the message for the relevant names is highly dependent on the rules having a formatting that stays consistent, and writing parsers for the output of each individual rule that could need one, and handling special cases such as odd characters.

That's something that is highly version dependent, and very "fragile" for maintainability. I personally don't want to maintain extremely special cases like that.

You might want to bring this up as an enhancement request on `eslint` itself to see what they think about giving back proper ranges for messages instead of just a column. Some of the things you are talking about `eslint` already provides suggested fixes for, which `linter-eslint` is sending back to `linter`, it just has no support for handling that (currently, next major(?) release should support it).

**Comment by IanVS** [comment]
There is an [existing issue](https://github.com/eslint/eslint/issues/3307) at ESLint for this, that is accepted and on the backlog, meaning it's not on the top of our priority on the core team, but would be willing to accept a PR if someone wants to take the effort to submit one.

**Comment by darkred** [comment]
> There is an existing issue at ESLint for this, that is accepted and on the backlog. It looks like mysticatea might be working on it, but perhaps he can use some help if you're willing to step in.

I just checked that issue and unfortunately I don't think I can contribute there programmatically (my knowledge is limited).
So, I don't know how I could be of help there (apart from commenting and/or making suggestions).

**Comment by mysticatea** [comment]
I'm sorry, yeah, I'm working on that. I will be back to active soon.
