### ISSUE TITLE
Error on HTML files

### ISSUE THREAD

**Issue by e-domnenko** [AtomLinter/linter-eslint#537]
Error on HTML files lint

```text
Error: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at /Users/evgendomnenko/dev/eslint-test/node_modules/eslint-plugin-html/src/index.js:61:37
    at Array.forEach (native)
    at Object.htmlProcessor.postprocess (/Users/evgendomnenko/dev/eslint-test/node_modules/eslint-plugin-html/src/index.js:60:17)
    at processText (/Users/evgendomnenko/dev/eslint-test/node_modules/eslint/lib/cli-engine.js:178:30)
    at CLIEngine.executeOnText (/Users/evgendomnenko/dev/eslint-test/node_modules/eslint/lib/cli-engine.js:666:26)
    at Object.cli.execute (/Users/evgendomnenko/dev/eslint-test/node_modules/eslint/lib/cli.js:180:36)
    at lintJob (/Users/evgendomnenko/.atom/packages/linter-eslint/lib/worker.js:30:10)
    at /Users/evgendomnenko/.atom/packages/linter-eslint/lib/worker.js:66:20
    at Emitter.emit (/Users/evgendomnenko/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/evgendomnenko/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
```

Using locally installed eslint and eslint-html-plugin

linter-eslint 7.2.0
eslint 2.8.0
eslint-plugin-html 1.4.0

**Comment by Arcanemagus** [comment]
This error looks to be happening within the `eslint-plugin-html` code, do you see the same thing when running `eslint` from the command line?

**Comment by e-domnenko** [comment]
No errors when running `eslint` from command line.
I use `node_modules/.bin/eslint app/**/*.html` command to run locally installed `eslint`

**Comment by Arcanemagus** [comment]
Hmmm, can you provide your `eslint` configuration, the relevant sections of your `package.json` specifying the versions of `eslint` and any plugins, as well as the file that triggers this (or a minimal test case if you can create one)?

**Comment by e-domnenko** [comment]
https://drive.google.com/file/d/0Bxg0C4VmKADBTlp1b2tuU3BLaUE/view?usp=sharing
Here is package on which lint of HTML fails
`npm test` will run `eslint` tool - it runs OK

**Comment by e-domnenko** [comment]
When I set disableFSCache: true - everything works perfect

Think I will go on with disabled cache for this moment

**Comment by jamesmgg** [comment]
@e-domnenko you rock!! that works for me too.

**Comment by belisarh** [comment]
@e-domnenko thank you! I was about to start banging my head at the wall. Disaster averted!

**Comment by maxjiang23326** [comment]
@e-domnenko Could you please tell me where should `disableFSCach: true` configured? I encountered exactly the same issue.

**Comment by Arcanemagus** [comment]
@maxjiang23326 That should be an option in the `linter-eslint` package settings.
