### ISSUE TITLE
"Fix Errors on Save" breaks undo

### ISSUE THREAD

**Issue by gpbl** [AtomLinter/linter-eslint#542]
Hi, I really love this new option, thanks for adding it!

There's a small bug: when I save the file and then I undo more than one time, one of the "undo" steps removes the whole content of the file.

**Comment by Arcanemagus** [comment]
If you run `eslint foo.js --fix` manually does the same thing show up?

All that the option does is when the TextEditor `save()` is finished it runs the command above on the file... nothing from this package is actually touching the text in the editor so my only guess is that some other package (or Atom itself?) is doing this when it detects that the file contents on disk have changed.

**Comment by gpbl** [comment]
I tried, it happens randomly. Maybe you are right saying it's not related to eslint. I'll check it better out, thanks for the fast reply!

**Comment by Arcanemagus** [comment]
If you have `linter-jscs` installed and _also_ have it's fix on save enabled the way that one works _could_ end up with that state in the undo buffer, as it _does_ directly modify the contents of the TextEditor.
