### ISSUE TITLE
disableEslintIgnore doesn't seem to be respected

### ISSUE THREAD

**Issue by bojand** [AtomLinter/linter-eslint#548]
What is exactly `Disable using .eslintignore files` checkbox / setting suppose to to? Disable the plugin just if I have `.eslintignore` file present? If so it doesn't seem to be working. My config:

```
"linter-eslint":
    disableEslintIgnore: true
    disableWhenNoEslintConfig: false
    useGlobalEslint: true
```

I have `.eslintignore` present in the root of my project, yet I am still getting an error:

![image](https://cloud.githubusercontent.com/assets/2081100/14712256/c290e55c-07b2-11e6-8216-72ff46b07b53.png)

I've tried having an empty `.eslintignore` or one that has just a valid random folder, ie. `node_modules`.
Am I doing something wrong?

Thanks,

**Comment by IanVS** [comment]
If you check that setting (`disableEslintIgnore`), we won't look at the `.eslintignore` file at all.  Can you explain what you're trying to do?

**Comment by bojand** [comment]
Hello, thanks. I must have a misunderstanding what that setting / checkbox is for and it's suppose to do at all? My assumption was that if you have `.eslintignore` present, it would turn off `atom-eslinter` plugin? Is this correct? What is the meaning of this setting?

What I am trying to do is the following...

In some of my projects I use [xo](https://github.com/sindresorhus/xo) and its [Atom plugin](https://github.com/sindresorhus/atom-linter-xo). I have `eslint` and `xo` globally installed. `xo` uses `eslint`. In the cases where I have `xo` setup I would like linting through `atom-eslinter` package to be turned off _somehow_. So I had assumed that just putting `.eslintignore` would turn off the plugin?

In cases where I do not have `xo` setup in the project, I would like linting using (my global) `eslint` and `atom-eslinter` plugin to be done, regardless if I have `.eslintrc` or ESLint config in `package.json`.

It seems I am assuming what that setting / checkbox _actually means_?

Thanks,

**Comment by IanVS** [comment]
An `.eslintignore` file is used by ESLint to disable linting for particular files.  For more information on how they work, check out http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

Do the projects which use xo have `.eslintrc` files in them?  It seems like you wouldn't since the top of the xo readme says:

> No decision-making. No `.eslintrc` or `.jshintrc` to manage. It just works!

If that's the case, you can use `disableWhenNoEslintConfig` to accomplish what you want.  

Also, I would suggest putting eslint and xo in devDependencies of your projects, rather than installing them globally.  That will ensure that everyone using your projects use the same versions, and you don't force others to have global installations.

**Comment by bojand** [comment]
Thanks. I understand how `.eslintignore` and the effect of it on eslint behaviour. I guess I am confused what the meaning of the checkbox `Disable using .eslintignore files` actually is? What is the effect if checkbox is checked? What is the effect if it is not checked? I assumed it meant to disable the whole plugin? Which isn't the case. 

Basically my workflow is use `xo` if i have it setup, otherwise fallback to eslint for _all_ JS projects even if the project itself does not have eslint setup in any way at all (nor xo setup)... Was trying to get that working but can't really find a way to disable atom-eslinter for projects that I have `xo` setup for, and still it work for all other projects. Without the use `disableWhenNoEslintConfig` which I would constantly have to switch on and off?

**Comment by IanVS** [comment]
As I mentioned above, the setting essentially disables the `.eslintignore` file.  As in, it's as if it doesn't exist.

Unless you put `.eslintrc` files in the projects you want to lint and enable `disableWhenNoEslintConfig`, I don't see a way to accomplish what you're trying to do.  You're probably going to need to just manually enable and disable the linter based on what you're working on.

**Comment by bojand** [comment]
Ok I see. Thanks for the explanation.
