### ISSUE TITLE
linting markdown files

### ISSUE THREAD

**Issue by iamstarkov** [AtomLinter/linter-eslint#550]
i believe it's not expected behavior
![screen shot 2016-04-23 at 00 14 15](https://cloud.githubusercontent.com/assets/559321/14756275/584494be-08e8-11e6-90ac-324555f16c00.png)

**Comment by Arcanemagus** [comment]
What version of Atom are you using? That's a bug in `language-gfm` that has been fixed for a while (v1.5.0 or v1.6.0).

**Comment by iamstarkov** [comment]
it was `v1.3.1`, after update on `v1.7.2` there is no problem now. thanks

**Comment by Arcanemagus** [comment]
Glad to hear it :wink:.
