### ISSUE TITLE
Error: Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by sunorry** [AtomLinter/linter-eslint#552]
I'm already install `babel-eslint` in global. 

`eslint` and `babel-eslint` in  `/usr/local/lib/node_modules/`.

> Error: Cannot find module 'babel-eslint'
>     at Object.ModuleResolver.resolve (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/eslint/lib/util/module-resolver.js:77:19)
>     at Object.load (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:515:42)
>     at loadConfig (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:67:33)
>     at new Config (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:200:38)
>     at CLIEngine.executeOnText (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:655:28)
>     at Object.cli.execute (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/eslint/lib/cli.js:180:36)
>     at lintJob (/Users/sunwangxing/.atom/packages/linter-eslint/lib/worker.js:30:10)
>     at /Users/sunwangxing/.atom/packages/linter-eslint/lib/worker.js:66:20
>     at Emitter.emit (/Users/sunwangxing/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
>     at /Users/sunwangxing/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23

**Comment by sunorry** [comment]
It's a strange 'bug', I tracked `module-resolver.js`, then install `babel-eslint` in 'Users/sunwangxing/.atom/packages/linter-eslint'. fixed this problem.

**Comment by Arcanemagus** [comment]
That's not a fix, but a bad workaround to your real issue. As it looks like you are trying to use a global installation instead of the recommended installation in the project, did you enable the option in the settings to allow use of a global installation?

**Comment by sunorry** [comment]
@Arcanemagus Yes, ESLint Rules Dir is '/usr/local/lib/node_modules/babel-eslint'.

**Comment by Arcanemagus** [comment]
I'm talking about this setting:
![image](https://cloud.githubusercontent.com/assets/427137/14826214/b85fabf8-0b91-11e6-9786-8a6ea0d1affe.png)

Without that enabled you can't use the global installation like you are trying to do.

**Comment by sunorry** [comment]
@Arcanemagus ops, i forgot to enabled that.

**Comment by sunorry** [comment]
@Arcanemagus thx, i'll buy a new rmbp tomorrow, i can try this next time。 thank you again.
