### ISSUE TITLE
import/no-unresolved Unable to resolve path to module

### ISSUE THREAD

**Issue by tleunen** [AtomLinter/linter-eslint#554]
I have the eslint import plugin with the webpack resolver, and for some reasons, the linter in Atom gives me an error on all the paths but if I execute the linter outside of Atom, I don't have any errors.

**Comment by tleunen** [comment]
Looks like it was an issue with my webpack configuration instead.
If anyone has the same issue, I changed my root path from `path.resolve('./src')` to `path.resolve(__dirname, './src')`.

The issue was that when the webpack resolver get the root path from the webpack config, it wasn't correct since it tries to resolve `./src` from the directory where the file is linted, instead of the project root. Not sure if it's an error with the webpack resolver or if we should always resolve from the project root.

**Comment by IanVS** [comment]
Great, thanks for posting the solution!

**Comment by Alewis103** [comment]
where can I find path.resolve() ?

**Comment by Arcanemagus** [comment]
That's a core Node.js module, it looks like the file in question is your "webpack configuration".

**Comment by kosychike** [comment]
i changed it to path.resolve(__dirname, './src') but still didnt work

**Comment by Arcanemagus** [comment]
@kosychike You'll need to adjust that for your own project structure.

**Comment by closingin** [comment]
I have the same problem as @kosychike. My `webpack.config.js` contains this alias :
```
alias: {
    '@': path.resolve(__dirname, './src')
}
```

And I have an import like this :
```js
import Header from '@/components/Navigation/Header';
```

The linter tells me that it "cannot find module ...". The weird thing is that it didn't complain about this a day ago. It just occured right now. The only thing I did in between is that I installed `atom-ide-ui`.

**Comment by skylize** [comment]
@closingin 

Original issue was solved by including `__dirname` in the path, which you have already done. So looks like you have a different problem. 

**Please open a new, separate Issue**  and, if at all possible, try to create a minimum case project to reproduce the error, so we have a reasonable chance of tracking down where things are going wrong.
