### ISSUE TITLE
On startup or via a command, run eslint on all files

### ISSUE THREAD

**Issue by lukeapage** [AtomLinter/linter-eslint#558]
If I find I have errors in 10 files (frequently when switching rules on for instance) I have to open those files by hand before I can see the list of "project errors".

It would be great if either via a command or an option, linter-eslint would run on all files in the project and show all failures where I can click-navigate to fix the issues.

**Comment by lukeapage** [comment]
Please let me know if accepted and if I have time I may try and put together a PR

**Comment by Arcanemagus** [comment]
This should be filed on [linter](https://github.com/steelbrain/linter), this is simply a provider that runs lints on files when requested. Nothing about this plugin controls its running on a file.

I _think_ there are already issues filed over there for similar ideas, so try searching first.

**Comment by IanVS** [comment]
@lukeapage In cases like that I like to run ESLint on the command line in a terminal, then with iTerm2 I can click the filenames and they will open in Atom.

**Comment by lukeapage** [comment]
@IanVS I'm on windows :(

@Arcanemagus it seems different from what you state in this comment - https://github.com/steelbrain/linter/issues/1117#issuecomment-203752066
but raised new issue since I cannot find any previous mention other than that.

**Comment by Arcanemagus** [comment]
@lukeapage You can still install `eslint` globally on Windows :stuck_out_tongue:, or run the one installed in `.\node_modules\.bin\eslint` in your project.

That comment _might_ have actually been due to a bug in the `editorconfig` package that I have installed that caused a "buffer modified" event, which `linter` caught and triggered `lintOnFly` linters on.

**Comment by lukeapage** [comment]
Im well aware of that, but manually copying each filename then searching in atom for that file is the chore im trying to avoid. iTerm may allow clicking a file to open in atom, but bash/cygwin on windows do not.

**Comment by tonyxiao** [comment]
@IanVS nice workaround. Thanks!
