### ISSUE TITLE
Getting into state where it is showing child process error: Error: Channel Closed

### ISSUE THREAD

**Issue by lukeapage** [AtomLinter/linter-eslint#559]
Quite often as I am editing files Atom gets into a state where every time I save a file I get this

![image](https://cloud.githubusercontent.com/assets/309321/14861950/b2978348-0caf-11e6-8426-c773b16218dc.png)

It seems to happen now in 7.2.1 as I was happy til then, but it could of course be something else that is causing it.

Can I get a log or something to see a stacktrace?

**Comment by lukeapage** [comment]
I'm not convinced any longer it is this plugin - sorry I disabled it and stopped seeing issues, but it may have been a fluke - I am now thinking it is atom-ternjs

**Comment by Arcanemagus** [comment]
This is the only linter that I know of that currently uses a child worker thread, but I'm not sure how you could get into that state :confused:.

What OS are you on?

**Comment by IanVS** [comment]
`atom-ternjs` is not a linter, and it does use child workers.  I had a lot of problems with it when I tried to use it as well, and ended up disabling it.  I wouldn't be surprised if it were the cause.

**Comment by aysark** [comment]
Agreed with @IanVS.  I've been getting spammed with that notification... `atom-ternjs` was the culprit.

**Comment by candu** [comment]
It looks like this *might* have been addressed in latest `atom-ternjs` (0.17.0), according to [the changelog](https://github.com/tststs/atom-ternjs/blob/master/CHANGELOG.md).
