### ISSUE TITLE
one-var rule works incorrectly

### ISSUE THREAD

**Issue by Hurtak** [AtomLinter/linter-eslint#56]
When using "one-var": [1, "never"] it acts just as if it was set to "one-var": [1, "always"]

When using eslint from CLI it works as expected.

**Comment by jfaissolle** [comment]
If there is a difference between CLI and plugin, it comes from different eslint versions. The plugin uses first the project version. If there is none, the plugin version. It does not use the globally installed version.
The just released version (0.5.1) uses eslint 0.18. If you want to use a specific eslint version, deploy it locally in your project.

**Comment by iam4x** [comment]
Fixed with newer versions.
