### ISSUE TITLE
Definition for rule 'react/jsx-first-prop-new-line' was not found

### ISSUE THREAD

**Issue by codetony25** [AtomLinter/linter-eslint#561]
I've been getting this eslint error. I have tried to also add it as one of my rules, but even doing so it would still say it wasn't found. Here is the result:

![screen shot 2016-04-30 at 6 20 41 pm](https://cloud.githubusercontent.com/assets/10192761/14939573/31c57f50-0f01-11e6-830c-735a638a916f.png)

Here's my .eslintrc

```
 {
   "parser"  : "babel-eslint",
   "extends" : [
     "airbnb"
   ],
   "ecmaFeatures": {
     "jsx": true
   },
   "plugins" : [
     "react"
   ],
   "env"     : {
     "browser" : true
   },
   "globals" : {
     "__DEVELOPMENT__"    : false,
     "__PRODUCTION__"     : false
   },
   "rules" : {
     "semi": ["error", "never"],
     "arrow-body-style": ["error", "always"],
     "new-cap": 0,
     "key-spacing": [2, {
     "singleLine": {
         "beforeColon": false,
         "afterColon": true
     },
     "multiLine": {
       "beforeColon": false,
       "afterColon": true,
       "align": "colon"
       }
     }]
   }
 }

```
In my package.json

>     "eslint": "^2.9.0",
>     "eslint-config-airbnb": "^8.0.0",
>     "eslint-config-standard": "^5.1.0",
>     "eslint-config-standard-jsx": "^1.2.0",
>     "eslint-config-standard-react": "^2.3.0",
>     "eslint-loader": "^1.3.0",
>     "eslint-plugin-import": "^1.6.1",
>     "eslint-plugin-jsx-a11y": "^1.0.4",
>     "eslint-plugin-promise": "^1.1.0",
>     "eslint-plugin-react": "^4.3.0",
>     "eslint-plugin-standard": "^1.3.2",

Current linter-eslint version installed:

> 7.2.1

**Comment by IanVS** [comment]
That rule was added in eslint-plugin-react version 5.

**Comment by codetony25** [comment]
Thank you!

Fixed this by turning all my package.json packages to wildcards and did 'npm update --save -u' and 'npm update --save-dev -u' and it worked.
