### ISSUE TITLE
404's when linking to react linting docs

### ISSUE THREAD

**Issue by mildfuzz** [AtomLinter/linter-eslint#565]
The links assigned to errors generated by ```eslint-plugin-react``` result in 404's

http://eslint.org/docs/rules/react/prefer-stateless-function

Could the correct docs repo be linked?

https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules

**Comment by Arcanemagus** [comment]
There are two different PR's up that fix this, one of which is ready to merge as I see it, just waiting on confirmation from the other maintainers :wink:.

**Comment by IanVS** [comment]
Closed by https://github.com/AtomLinter/linter-eslint/pull/562

**Comment by Arcanemagus** [comment]
v7.2.2 should include links for 10 plugins, enjoy!

**Comment by mildfuzz** [comment]
Sweet :)
