### ISSUE TITLE
Windows: Errors when viewing PHP files.

### ISSUE THREAD

**Issue by phoenixenero** [AtomLinter/linter-eslint#567]
```
Error: 'F:\Users\Design' is not recognized as an internal or external command, operable program or batch file.
Error: 'F:\Users\Design' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.<anonymous> (F:\Users\Design Studio\.atom\packages\linter-eslint\node_modules\atom-linter\node_modules\sb-exec\lib\index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Funny thing is it works for other files which are located in the same directory I'm on, but with a different extension.

**Comment by Arcanemagus** [comment]
Looks like this is only here due to Atom grabbing `atom-linter` from `linter-eslint`'s folder, can you open this issue on whichever of the linters that you have installed that run on PHP files? (`linter-php`, `linter-phpcs`, `linter-phpmd`)

**Comment by Arcanemagus** [comment]
I actually _just_ ran into this myself... not sure what changed but I'm looking into a fix.

**Comment by Arcanemagus** [comment]
This will be fixed through https://github.com/steelbrain/exec/issues/16.

**Comment by Arcanemagus** [comment]
Until that is fixed if you have Node.js installed you can workaround this by going into the `~/.atom/packages/linter-phpcs` (and/or `linter-phpmd`) folder and running this:
```shell
npm install atom-linter@4.6.1
```
