### ISSUE TITLE
How to disable eslint/linter when there is no `eslint` installed?

### ISSUE THREAD

**Issue by skyuplam** [AtomLinter/linter-eslint#568]
I like to download the source code and read it locally but the error of `Error: Failed to load plugin xxx` is always shown when I open any `js` file if there is `.eslintrc` in it. It's really annoying when you only want to read to source. Is there any way to disable linting when there no any node module installed? or any better solution for getting rid of the error message?

**Comment by Arcanemagus** [comment]
Hmmmm, personally I feel this should be a wontfix, if you have a configuration, have the linter enabled, and call for a lint on the file how are we supposed to know whether you simply haven't installed all the proper dependencies in your project, or are just opening up the project for a quick look? :confused:

Thoughts @AtomLinter/linter-eslint?

**Comment by IanVS** [comment]
I agree with @Arcanemagus.  I think your best bet is to disable linting @skyuplam when you're just popping it open for a quick look.

**Comment by Arcanemagus** [comment]
FYI @skyuplam: Linter has a `Linter: Toggle Active Editor` command to temporarily disable linting for the currently open file.

**Comment by skyuplam** [comment]
@Arcanemagus @IanVS thanks a lot. I didn't know I can temporarily disable linting. It helps a lot! ;)
