### ISSUE TITLE
Path type check fails with Node 6

### ISSUE THREAD

**Issue by tensor5** [AtomLinter/linter-eslint#580]
Node 6 (which is included in Electron 1.1.0) became more strict about the input type of `path` methods (https://github.com/nodejs/node/commit/08085c49b6e49ecfffd638c6cd46f4de639ae4f4).

As a result, the following error pops up when running Atom with the latest Electron and linter-eslint:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.getESLintInstance (/home/nicola/.atom/packages/linter-eslint/lib/worker-helpers.js:87:35)
    at /home/nicola/.atom/packages/linter-eslint/lib/worker.js:59:24
    at Emitter.emit (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```

**Comment by Algram** [comment]
I don't quite understand how this hasn't gotten more attention since it affects everyone that updates to the latest atom. This package is unusable in newer versions.

**Comment by Arcanemagus** [comment]
@Algram Atom v1.9.0-beta0 is based on Electron 0.37.8 and Node 5.10.0... even Atom's master branch is still on that version of Electron.

This hasn't hit me, and isn't anywhere even remotely close to hitting anyone not building from source so I haven't put any time into fixing it. If you want to look into why a `null` is ever getting to that function in the first place and submit a fix that would be awesome!

**Comment by Algram** [comment]
@Arcanemagus I'll look into it. My error has a different origin then.

**Comment by devm-ru** [comment]
@IanVS 
![2016-08-24_17 30 53](https://cloud.githubusercontent.com/assets/4389555/17934423/91c166ec-6a20-11e6-8d80-2a0a86e51abf.png)

**Comment by IanVS** [comment]
@devm-ru  you have npm installed within `.node_modules`?  Inside that directory, is there another subdirectory of `node_modules`?

**Comment by devm-ru** [comment]
@IanVS 
```

**Comment by devm-ru** [comment]
```

**Comment by devm-ru** [comment]
Fixed 
```
cd ~/.atom/packages/linter-eslint/
npm install
```

**Comment by jolyonruss** [comment]
`apm update linter-eslint` fixed this for me

Package Updates Available (1)
└── linter-eslint 7.2.2 -> 8.0.0

**Comment by krasimir** [comment]
In my case I can't update linter-eslint so I had to manually solve my issue. Just for the protocol.
1. Open `~/.atom/packages/linter-eslint/lib/worker-helpers.js`
2. Replace 
```js
function getESLintInstance(fileDir, config) {
  var modulesDir = _path2.default.dirname((0, _atomLinter.findCached)(fileDir, 'node_modules/eslint'));
  refreshModulesPath(modulesDir);
  return getESLintFromDirectory(modulesDir, config);
}
```
with
```js
function getESLintInstance(fileDir, config) {
  var filePath = (0, _atomLinter.findCached)(fileDir, 'node_modules/eslint');
  var modulesDir = _path2.default.dirname(filePath || 'node_modules/eslint');
  refreshModulesPath(modulesDir);
  return getESLintFromDirectory(modulesDir, config);
}
```
