### ISSUE TITLE
Async and unexpected token function

### ISSUE THREAD

**Issue by Bosek** [AtomLinter/linter-eslint#582]
![linter-eslint](https://cloud.githubusercontent.com/assets/6001235/15269627/3c0d48b2-1a05-11e6-82cd-5400a6200bbc.png)

`eslint fetchCorpKills.js` **is working**. I've tried to update everything: eslint, babel-eslint, linter and linter-eslint.

Is there anything I can try to make it work? It drives me crazy. I've been trying to solve this for about 4 hours by now.

eslint v2.10.1
babel-eslint v6.0.4
linter v1.11.4
linter-eslint v7.2.2

**Comment by Bosek** [comment]
I've found "fix":

1. Go to `.atom>packages>linter-eslint>node_modules` 

2. Copy babel-eslint folder from your project's node_modules folder into this one

3. Open `.atom>packages>linter-eslint>node_modules>.bin` folder and edit **eslint.cmd**: [eslint.txt](https://github.com/AtomLinter/linter-eslint/files/264619/eslint.txt)

Voila!

**Comment by IanVS** [comment]
I'm not sure, but it looks like you're mixing global and local (project) installations of ESLint.  Can you tell us where you have ESLint and babel-eslint installed?  Also, how is `linter-eslint` configured?  Is it using the global installation?

**Comment by IanVS** [comment]
Actually, this seems to be an upstream bug in ESLint: https://github.com/eslint/eslint/issues/6182.

**Comment by Arcanemagus** [comment]
Marking this as closed, it wasn't an issue with `linter-eslint` in the first place, and can be solved by updating to ESLint v2.10.2 or higher.

**Comment by mLuby** [comment]
Finding this is still an issue with ESLint v4.0.0 and linter-eslint 8.4.1
```shell
node_modules/.bin/eslint --version
# v4.0.0

atom --version
# Atom    : 1.24.0
# Electron: 1.6.16
# Chrome  : 56.0.2924.87
# Node    : 7.4.0

# atom packages: linter 2.2.0, linter-eslint 8.4.1
```

**Comment by Arcanemagus** [comment]
Please file a _new_ issue and fill out the information requested in the template @mLuby. You should also update your version of ESLint as it is almost a year old by now.
