### ISSUE TITLE
Reconsider current behaviour of only linting active tab

### ISSUE THREAD

**Issue by jesucarr** [AtomLinter/linter-eslint#588]
Imagine I open 12 tabs, and edit them. If I "Save All" and didn't have any lint errors in the active tab, but I had error in the other 11, I won't get any sort of notification. 

I would need to open each tab one by one and save individually. 

I think at least the 12 tabs that I have open should be linted.

And ideally add an option or a button to scan the entire opened project.

**Comment by Arcanemagus** [comment]
You should file this on [linter](https://github.com/steelbrain/linter), this project has no control over when it is triggered, or what it is triggered on.
