### ISSUE TITLE
Issue with Content Security Policy

### ISSUE THREAD

**Issue by ALF-er** [AtomLinter/linter-eslint#59]
Hello, I'm using eslint with https://github.com/babel/babel-eslint as parser (specified via .eslintrc). But in any js file I get

```
node_modules\babel-core\lib\acorn\src\identifier.js:63 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

I've tried a variety of options but all my attempts failed. Maybe you can help me =)

**Comment by jfaissolle** [comment]
Sorry, I did not encounter this problem. Can you try to upgrade babel-eslint and babel to the last versions ? Note that babel-eslint is moving really fast and problems can appear or disappear pretty often...
Can you give me your exact config (package.json, .eslintrc) ?

**Comment by ALF-er** [comment]
Interesting. I had installed eslint v0.19.0 and babel-eslint v2.0.2 globally (it caused the original error). But when I installed them locally in project it caused error from already reported issue: https://github.com/AtomLinter/linter-eslint/issues/37 But I have latest versions of packages. Here my settings https://gist.github.com/ALF-er/14f838afead2a94c3747 Thank you in advance

**Comment by iam4x** [comment]
@ALF-er I see you use `eslint-plugin-react` but it's not defined in your `.eslintrc`, you should add the line: `"plugins": ["react"]` into.

I don't know if this is related to the issue.

**Comment by ALF-er** [comment]
@iam4x 7th line of .eslintrc =)

**Comment by iam4x** [comment]
Wouah, how I missed that? My bad sorry

**Comment by iam4x** [comment]
I'm getting this with the latest babel and babel-eslint, I will inspect this.

**Comment by iam4x** [comment]
Fixed with the new release ;)

**Comment by ALF-er** [comment]
@iam4x Didn't work for me =( 

If I install packages globally I receive:
> Cannot find module 'babel-eslint'
`npm install eslint` in your project to enable plugins: react (linter-eslint)

If I install packages locally I receive this error: https://github.com/AtomLinter/linter-eslint/issues/37

Version of Atom: 0.190.0
Version of AtomLinter: 0.12.0
Version of linter-eslint: 0.5.2
Versions of related packages:
├── babel-eslint@3.0.1
├── eslint@0.19.0
├── eslint-plugin-react@2.1.0

**Comment by iam4x** [comment]
In your project where you run atom you should do:
`npm install --save-dev eslint@0.19.0 babel-eslint@3.0.1 eslint-plugin-react@2.1.0`
