### ISSUE TITLE
Parsing error: The keyword 'const' is reserved

### ISSUE THREAD

**Issue by ethans** [AtomLinter/linter-eslint#592]
I'm using the latest build of atom for Windows and the latest linter-eslint (7.2.2) with my NodeJS project.

I am getting a parsing error every time I use the keyword **const**.

Example:
`const a = 5;`

I get:
> Parsing error: The keyword 'const' is reserved at line XX col YY

How come? What am I doing wrong?

Thanks,
Ethan

**Comment by ethans** [comment]
I'm closing this as I finally found that the default is still EcmaScript 5. After adding a .eslintrc file to my project and setting to ecmaVersion 6 - all's good.

**Comment by nikulkarni** [comment]
For those who came here figuring it out how to do this, in .eslintrc file add below

 ```
"parserOptions": {
    "ecmaVersion": 6
  }
 ```

**Comment by slonak79** [comment]
Thanks @nikulkarni this worked for me!

**Comment by MAPESO** [comment]
@nikulkarni @ethans Should not it be like this?

`"parserOptions": {
   "ecmaVersion": 2015
}`

ES2015 === ES6

**Comment by Arcanemagus** [comment]
@MAPESO Either way works, as specified in [the documentation](https://eslint.org/docs/user-guide/configuring#specifying-parser-options).

Locking this as the original question has been resolved and several ways of configuring this have been posted 😉.

**Comment by PatelAshish11** [comment]
ESLint defaults to ES5 syntax-checking. You’ll want to override to the latest well-supported version of JavaScript.

Try adding a .eslintrc file to your project. Inside it:

{
"parserOptions": {
"ecmaVersion": 2017
},

"env": {
"es6": true
}
}
Hopefully this helps.

Source Code [Here](https://icetutor.com/question/eslint-error-parsing-error-the-keyword-const-is-reserved/)

**Comment by AkashGalani** [comment]
ESLint defaults to ES5 syntax-checking. You’ll want to override to the latest well-supported version of JavaScript.

Try adding a .eslintrc file to your project. Inside it:

{
"parserOptions": {
"ecmaVersion": 2017
},

"env": {
"es6": true
}
}

Example [Here](https://icetutor.com/question/eslint-error-parsing-error-the-keyword-const-is-reserved/)
