### ISSUE TITLE
`Error: ENOENT: no such file or directory, uv_chdir` when using with nuclide and remote server

### ISSUE THREAD

**Issue by aaronabramov** [AtomLinter/linter-eslint#594]
It gets thrown on every save

```
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.getRelativePath (/Users/111/.atom/packages/linter-eslint/lib/worker-helpers.js:113:11)
    at /Users/111/.atom/packages/linter-eslint/lib/worker.js:61:34
    at Emitter.emit (/Users/111/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/111/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /Users/111/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/Users/111/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/Users/111/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (/Users/111/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
    at emitTwo (events.js:87:13)
```

**Comment by Arcanemagus** [comment]
Do you see this for all remote file systems? What about local files?

For some reason it's trying to set the cwd to a directory that doesn't exist, from reading other bug reports on other projects it looks like people were renaming folders after things had already loaded and grabbed paths to use, is that possibly the case here?

**Comment by dmitriiabramov** [comment]
I haven't tried it with other remote file systems.
i have two projects that i work on every day. One is local and another is remote.
I use `eslint` for the local project and it works great, but whenever i connect to the remote project it throws this.
I usually just disable `linter-eslint` whenever i switch to remote, but it's kind of annoying :)
is there an easy temp fix i can do on my end?

**Comment by Arcanemagus** [comment]
Can you put the following above [this line](https://github.com/AtomLinter/linter-eslint/blob/v7.2.2/lib/worker-helpers.js#L106):

```js
console.log(fileDir, filePath, config);
```

Somehow either `ignoreDir` is wrong on line 110, or `fileDir` is wrong on line 113 😕.

**Comment by dmitriiabramov** [comment]
```
nuclide://my.devserver.url.com/my_dir 
nuclide://my.devserver.url.com/my_dir/my_file.js

{ lintHtmlFiles: false,
  useGlobalEslint: false,
  showRuleIdInMessage: true,
  disableWhenNoEslintConfig: true,
  eslintrcPath: '',
  globalNodePath: '',
  eslintRulesDir: '',
  disableEslintIgnore: false,
  disableFSCache: false,
  fixOnSave: false
}
```

**Comment by Arcanemagus** [comment]
What in the world... it looks like they have some custom protocol and have set that as the "path" to the file.

We can try falling back to somewhere guaranteed to exist when that is hit I guess, but the results will _not_ be as correct as they could be, if it works at all.

**Comment by jgable** [comment]
I messed around with trying to parse the filePath and fileDir out of the weird nuclide protocol but am hitting a wall because of the remote project. 

```
// lib/worker-helpers.js in `getRelativePath`
console.log('eslint:getRelativePath', {fileDir, filePath, config})
  var urlParsed = _url.parse(filePath);
  if (urlParsed && urlParsed.protocol) {
    fileDir = _path.dirname(urlParsed.path);
    filePath = urlParsed.path;
    console.log('eslint:urlParsed', {fileDir, filePath, config})
  }
```

I still get the error and I assume it's because there is no directory to change to locally that matches the path I pull from the url.  Is this just a dead end because it's a remote project and you can't get a relative path? I'm not that familiar with how remote projects work together with other packages.

**Comment by dmitriiabramov** [comment]
@jgable yeah, i'm not sure either. I usually just disable this plugin when i work on fb remote projects (as they have their own nuclide integration) and re-enable when i work on oss project. I think the best solution here would be to just not throw an error :) this way it'll be enabled but no op

**Comment by Arcanemagus** [comment]
There is no way to fix this correctly, the best solution I've came up with is as posted above: When a directory is impossible to get from the file, use something guaranteed to exist as the `cwd` (`os.tmpdir()`?).
