### ISSUE TITLE
Disable verbose error display for  trailing whitespace rule violation on current line

### ISSUE THREAD

**Issue by ddumontatibm** [AtomLinter/linter-eslint#596]
![image](https://cloud.githubusercontent.com/assets/648319/15873969/062dd298-2ccf-11e6-80dd-4dc2b9c8e0ce.png)

I like the linter... but it kinda gets in the way in this case.   I don't mind the red lines... but the popup should perhaps be suppressed in this specific case.

**Comment by Arcanemagus** [comment]
We don't actually have anything to do with the UI, this package just provides a translation between ESLint and Linter. You might want to increase the delay in the Linter settings so it doesn't lint right away, I personally use 1500 ms for the delay.

**Comment by Arcanemagus** [comment]
You should follow #666, as it will allow you to hide that rule when editing the file (but still show it for on-save lints).
