### ISSUE TITLE
Linter suddenly not linting jsx files

### ISSUE THREAD

**Issue by EMCP** [AtomLinter/linter-eslint#597]
Disclaimer : I've posted this to Nuclide, but figured this may have to do with my `linter-eslint` as well?
### Issue and Steps to Reproduce
this is a strange thing, and not sure what's up.. but suddenly noticed that Nuclide is no longer linting my `.jsx` files.  I've just been updating packages and not fiddling with any of my linter setup.

### Expected Behavior
if jsx linting is working, it should continue working in a project.. even when updating packages

### Actual Behavior
seems suddenly it's silently stopped working

### Versions
* Atom: 1.8.0
* Nuclide: 0.141.0
* Client OS: OSX 10.11.x
* Server OS (optional):

### Additional Details

```
Community Packages (17) ~/.atom/packages
├── Stylus@3.0.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.26.3
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── lint@0.0.1
├── linter@1.11.4
├── linter-eslint@7.2.2
├── linter-htmlhint@1.1.4
├── linter-jsonlint@1.2.5
├── linter-stylint@2.1.2
├── nuclide@0.141.0
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
└── tool-bar@0.4.0

└── (empty)
```

**Comment by Arcanemagus** [comment]
What do you get if you run `Editor: Log Cursor Scopes` from the command palette when editing a file? I notice that you have `language-babel` installed, which may not be specifying the right scope for the file to be recognized as one this package is compatible with.

**Comment by EMCP** [comment]
```
Scopes at Cursor

  source.js.jsx
  meta.class.body.js
  meta.function-call.method.with-arguments.js
  meta.brace.round.js
```

**Comment by Arcanemagus** [comment]
Hmmm, `source.js.jsx` is one of the scopes listed as being compatible. If you open Developer Tools and put a breakpoint [here](https://github.com/AtomLinter/linter-eslint/blob/v7.2.2/lib/main.js#L161), then try to lint a file is it ever triggered?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If you are still having issues feel free to re-open the issue and continue the discussion.
