### ISSUE TITLE
Add keybind instructions to docs

### ISSUE THREAD

**Issue by samsch** [AtomLinter/linter-eslint#600]
Currently, there is an option to have eslint attempt to fix problems when saving. Could this functionality also be applied with a keybinding? Sometimes I'd like to see that what I'm working on is fixed, but I don't want to save at that moment.

**Comment by Arcanemagus** [comment]
See https://github.com/AtomLinter/linter-eslint/issues/575 for how to accomplish this yourself. With how simple it is to add your own key binding, and the difficulty of determining one that won't conflict with other things I don't see us adding one by default.

**Comment by samsch** [comment]
Oh, thanks! Looks like I made the silly mistake of not searching closed issues.

Would it be possible to have something added to the docs for this?

**Comment by Arcanemagus** [comment]
Sure, makes sense to me.

**Comment by Arcanemagus** [comment]
Wrote up https://github.com/AtomLinter/linter-eslint/wiki/Keybind-Creation 😉.

**Comment by jjerome00** [comment]
You can also fix the current file by opening the Command Palette and typing `eslint fix`
