### ISSUE TITLE
After updating linter to version 7.2.2 throws error

### ISSUE THREAD

**Issue by maxpolski** [AtomLinter/linter-eslint#601]
[Linter-ESLint] STDERR Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at monkeypatch

**Comment by Arcanemagus** [comment]
That error is being forwarded on from `eslint`, it looks like you have a _very_ old version of `babel-eslint` in your project combined with an incompatible version of `eslint`. Try updating your project to the current versions of those plugins, or limiting your `eslint` version in your project to one that is compatible with the old `babel-eslint` you are using.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response, if you are still experiencing issues feel free to re-open the issue with more information.
