### ISSUE TITLE
Can't find global eslint if node is installed via nvm

### ISSUE THREAD

**Issue by Algram** [AtomLinter/linter-eslint#603]
The package can't find my global eslint package even though I have it installed.
It is looking in `/lib/node_modules/eslint` but actually I am managing my node versions via nvm.

This means that global modules are actually installed in `/home/<username>/.nvm/versions/node/v6.2.1`.

`npm get prefix` also returns this correct directory.

The error seems to be in `lib/worker-helpers.js` in `Line 41`:

``` node
function getNodePrefixPath() {
  if (Cache.NODE_PREFIX_PATH === null) {
    var npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';
    try {
      Cache.NODE_PREFIX_PATH = _child_process2.default.spawnSync(npmCommand, ['get', 'prefix'], {
        env: Object.assign(Object.assign({}, process.env), { PATH: (0, _consistentPath2.default)() })
      }).output[1].toString().trim();
    } catch (e) {
      throw new Error('Unable to execute `npm get prefix`. Please make sure Atom is getting $PATH correctly');
    }
  }
  return Cache.NODE_PREFIX_PATH;
}
```

This method is returning an incorrect prefix of `/` whereas the correct string would (in my case) be `/home/<username>/.nvm/versions/node/v6.2.1`.
Since it just spawns `npm get prefix` I am not sure where this is coming from.

Help requested :)

**Comment by IanVS** [comment]
Have you tried setting the `Global Node Installation Path` setting for linter-eslint?

**Comment by Algram** [comment]
I have.

**Comment by Arcanemagus** [comment]
That function is [completely ignored](https://github.com/AtomLinter/linter-eslint/blob/v7.2.2/src/worker-helpers.js#L36) if you have set anything in the `Global Node Installation Path`, are you sure you don't still have anything in there?

**Comment by udipl** [comment]
Thanks @Arcanemagus ! that was the cause for this issue for me.

**Comment by SOSANA** [comment]
Hey all,

Had similar issue, not sure why but I uninstalled, reopened atom, than reinstalled, reopened atom and it started working. Had to do this on my desktop and laptop as both locations were having same issue.

I also choose to use local rather than global and unchecked marked global option.

**Comment by zaaack** [comment]
I got same issue when using nvm, and has `global node install path` correctly set,
```
$ npm get prefix
/Users/z/.nvm/versions/node/v6.3.1
```
 but eslint won't work when enable  `use global eslint installation`

**Comment by zaaack** [comment]
@lanVS the lint message won't update after I change my code and reopen it, until I disabled `use global eslint installation` option and reopen the file, than it would update again.

here is my linter-eslint settings:
![image](https://cloud.githubusercontent.com/assets/5233940/17646747/d64ed962-6209-11e6-9c2e-5729e523c7d5.png)

I have to disable the last option to make it work.

**Comment by IanVS** [comment]
Sorry if these are obvious, but:

1. Are you certain eslint is installed globally? (`eslint` shows the cli options help)
1. Did you restart atom after enabling the Use global option?
1. "the lint message won't update" Do you mean that it tells you there are no problems, even when you make a change you know should throw an error?
1. Have you tried removing the path from `Global Node Installation Path` (and restarting atom)?

**Comment by zaaack** [comment]
@lanVS Thanks for you fast reply.

1. At the beginning the error in my .eslintrc troubled my for a while after I checked it using the cli, so the first question is yes. Would it be better to throw a error message for better experience？
![image](https://cloud.githubusercontent.com/assets/5233940/17646806/56ac4a0c-620c-11e6-94c4-457755af4a41.png)

2. yes, but after restart atom, there are no lint message any more.

3. yes, and the lint message won't move after I insert a new line.

4. yes, just the same, no lint message any more.

**Comment by IanVS** [comment]
Ah, so is your issue that you _are_ getting a lint error (the underline), but that editing the file does not change the lint error location?  Do you have the "Lint as you type" setting from the base `linter` project enabled?  

Regardless, unless I'm misunderstanding, it seems like there's some other error here, not that the global ESLint isn't being found at all.  I'd suggest opening another issue.

**Comment by zaaack** [comment]
@IanVS  sorry for my pool english,  the screen capture is after I disabled the `Use Global ESLint Installation`, so the lint errors would show. And `editing the file does not change the lint error location?` only shows when I not restart atom(may be cache or some thing).  My main issue is still:

"After I use nvm and check `Use Global ESLint Installation`  (whether or not setting `Global Node Installation Path`), the ESLint-linter won't work and show any lint error."

**Comment by DanPurdy** [comment]
@Arcanemagus @IanVS  this may be related to the issue I was seeing in linter-sass-lint with regards to `consistent-env` not reading a bash_profile or bashrc file (i can't remember which it was!) But basically it would fail to pull your npm prefix through after being set by nvm and would therefore be unable to use a globally installed package.

@zaaack It might be worth trying again after reinstalling linter-eslint and see if the issue still occurs

**Comment by vdisawar** [comment]
npm config set prefix /usr/local

That fixed it for me on a Mac

**Comment by theSuiGenerisAakash** [comment]
I just edited my $PATH and appended `/home/<username>/.nvm/versions/node/<version>/node_modules/eslint/`. Pay attention to the `/` after `../eslint`. This made sense with the last option of `Global node` being checked.

I too was trying to have a global default `.eslintrc` file to be pointed to by Atom. With the above changes and the path accordingly set in Atom to my `.eslintrc` file in the home directory made it work.

**Comment by Arcanemagus** [comment]
@theSuiGenerisAakash That's exactly what this setting is for:
https://github.com/AtomLinter/linter-eslint/blob/fbefec607cbd706c082ed6fbacc26546b8bf2e96/package.json#L34-L39

You don't need a global ESLint installation to use that.

**Comment by skylize** [comment]
This Issue is very old, and the source code referenced in the original Issue no longer matches the existing source. 

@Algram, Please let us know if this is still a problem for you.

If anyone else is still experiencing similar issues, please open a _new_ case.
