### ISSUE TITLE
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by trusktr** [AtomLinter/linter-eslint#604]
![screen shot 2016-06-12 at 4 06 40 am](https://cloud.githubusercontent.com/assets/297678/15990778/1a2a7b0c-3053-11e6-878a-cb939d75a22f.png)

**Comment by trusktr** [comment]
I've installed the `linter-eslint` package. Do I have to install something else too?

**Comment by trusktr** [comment]
Ah, it works with "Use global" option.

**Comment by yanandcoffee** [comment]
Should resolvable with `npm install` in local project without the "Use global" option?

**Comment by trusktr** [comment]
Oh, gotcha! I want to avoid the extra dependencies in my project, so the global option works. Thanks!

**Comment by yanandcoffee** [comment]
No problem, Joseph. I ran into the same issue myself! Maybe it would be a good feature request as an option to not error continuously when there's no local node_modules installed for purposes of looking through code.

**Comment by trusktr** [comment]
True! Maybe the error can also say something like "make sure eslint is installed in your project. Alternatively enable the 'Use global ...' option you prefer using globally installed version of eslint."

**Comment by Arcanemagus** [comment]
The current plan is actually to just entirely remove the `eslint` that is bundled with this package as it causes nothing but confusion for people unfamiliar with how `eslint` works... and anyone that does know how it should be working knows better than to have a setup that is falling back on the bundled version.

Nobody has had time to look into how much of a pain actually implementing that is going to be yet though 😛.
