### ISSUE TITLE
Settings doesn't show up in Atom

### ISSUE THREAD

**Issue by nonameolsson** [AtomLinter/linter-eslint#607]
I'm trying to add Eslint to lint my .jsx-files. After a lot of time dedicated to configuring it I think the problem is with the atom plugin. 

When I open the settings for the plugin I only see this.

![eslint-error](https://cloud.githubusercontent.com/assets/1493018/16008340/d40a0bb2-3177-11e6-858f-6009f0d9f3de.png)

**Comment by IanVS** [comment]
It looks like it didn't finish installing correctly, perhaps.  There's no version number shown, which is odd.  Have you tried restarting Atom?

**Comment by nonameolsson** [comment]
Yeah, I did restart it. I just managed to solve it. Don't know exaclyt what the problem was. But I did uninstall jshint and the eslint plugin, restarted Atom and reinstalled eslint. Then after restarting Atom again it worked. 

Thanks for your answer, and sorry to open up an issue so fast.

**Comment by IanVS** [comment]
No problem, glad you got it working.
