### ISSUE TITLE
Silence all errors because it's very, very annoying

### ISSUE THREAD

**Issue by eranimo** [AtomLinter/linter-eslint#608]
I don't particularly care when eslint can't lint my file. It's much more intrusive to have the giant red box appear.

**Comment by Arcanemagus** [comment]
What do you mean by "can't lint my file"? Or for that matter "giant red box"?

Are you getting an error of some sort?

**Comment by Arcanemagus** [comment]
Marking as closed due to lack of response, if you can provide any more information feel free to re-open this.
