### ISSUE TITLE
Feature request: auto generate eslint ignore directives inline comments

### ISSUE THREAD

**Issue by chalda** [AtomLinter/linter-eslint#611]
so when it shows there is an error/warning add a button in the tool tip to auto generate the comment to ignore that rule

**Comment by Arcanemagus** [comment]
Sorry, this isn't really possible with how this linter works.

The only way it could potentially be done would be to specify a `fix` back up to Linter... but in the first place that isn't actually fixing anything, and secondly `eslint` already specifies fixes for things it knows how to fix, which that would break.
