### ISSUE TITLE
.eslintignore not working correctly

### ISSUE THREAD

**Issue by tanertopal** [AtomLinter/linter-eslint#613]
I already checked the issues and apparently #481 fixed the issue that the .eslintignore file wasn't used.
Now I got the issue of getting a lot of warnings which say

> [FATAL] File ignored because of a matching ignore pattern. Use "--no-ignore" to override

Not sure how to fix this. Any recommendations?

**Comment by Arcanemagus** [comment]
Whoops, looks like the fix for `eslint@2.11.1` wasn't released yet.

**Comment by Arcanemagus** [comment]
Should be fixed in v7.2.3.

**Comment by tanertopal** [comment]
Very nice! Now it works thanks!
