### ISSUE TITLE
Error: Column start (26) greater than line length (25)

### ISSUE THREAD

**Issue by dawnwish** [AtomLinter/linter-eslint#616]
the stylelintrc file:
http://cl.ly/gUau

the style file:
http://cl.ly/gUV0

**Comment by Arcanemagus** [comment]
Can you please file this on [linter-stylelint](https://github.com/AtomLinter/linter-stylelint)?

**Comment by Arcanemagus** [comment]
I actually went through and found a minimal reproduction case and filed it on the `stylelint` repo, there is no need to file another issue. 😉

**Comment by dawnwish** [comment]
thank you very much :)
