### ISSUE TITLE
autofix randomly replaces whole buffer

### ISSUE THREAD

**Issue by dwelle** [AtomLinter/linter-eslint#620]
Autofix at random times (usually for new files, or after a tab is left inactive for a while; but not exclusively to these occasions) replaces whole buffer, and position is lost (reset to first line).

Sometimes accompanied by following error:

```
Error: Line number (1412) greater than maximum line (0)
Error: Line number (1412) greater than maximum line (0)
    at Object.rangeFromLineNumber (\.atom\packages\linter-eslint\node_modules\atom-linter\lib\index.js:165:11)
    at \.atom\packages\linter-eslint\lib\main.js:191:33
    at Array.map (native)
    at \.atom\packages\linter-eslint\lib\main.js:17
```

`linter 1.11.14`, `linter-eslint 7.2.4`, Win 7

**Comment by Arcanemagus** [comment]
This package doesn't actually modify the buffer at all for a fix job... it calls out to `eslint` to run `eslint --fix` on the saved file on disk.

Are you possibly saving the file and then trying to type more and `eslint` is possibly updating the file underneath you? Do you have some other package that does things when the file you are editing changes on disk? I have the `file-watcher` package installed to catch that scenario and ask what to do.

**Comment by dwelle** [comment]
Nope, I just save and do nothing afterwards. I have `file-watcher` too (tried even disabling it). I'll try to disable every package but `linter/eslint` to ensure no other package is interfering.

**Comment by Arcanemagus** [comment]
@repsac-by Do you have any more information on how to trigger this since you 👍'd the issue?

**Comment by repsac-by** [comment]
@Arcanemagus Yes, I get this. I have autosave when losing focus, maybe it had something to do, unfortunately I did not conduct an investigation and can't give more information at the moment.

**Comment by dwelle** [comment]
I can confirm this happens with just `linter`, `linter-eslint`, and core packages enabled. Happened to me right after atom boot:

1. open atom
2. remove a semicolon
3. save
4. semicolon fixed, buffer replaced in full, cursor reset to 1st line.

Config:

```
{
    "parser": "babel-eslint",
    "env": {
        "es6": true
    },
    ...
```

I'll probably open an issue in `eslint`, instead.

**Comment by dwelle** [comment]
Ok, after ridiculous debugging, I was able to nearly 100% reproduce the bug when doing this:

config:

```
{
    "parser": "babel-eslint",
    "env": {
        "es6": true
    },
    "rules": {
        "semi": [ 1, "always" ]
    }
}
```

Steps:

1. save & open [this file](http://pastebin.com/raw/Yk6K1w5k)
2. remove the last semicolon in file
3. save

It usually even throws the error in my OP. If it doesn't work, try to repeat steps `2` & `3` a few times.

**Comment by pgherveou** [comment]
I can confirm I have the same bug on some large files. whole buffer is replaced, and position is lost

**Comment by Arcanemagus** [comment]
Took some time to look into this, and I can reproduce what you are seeing in `atom --safe`... meaning no packages at all. This is a bug (behavior?) in Atom, and should be filed over there.

To reproduce create a file with the following contents:

```raw
1
2
3
4
6

```

Open it in both Atom and an external editor. In the external editor add the missing "5" so it will look like this, and then save the file in the external editor:

```raw
1
2
3
4
5
6

```

If you then check the Undo history in Atom you will see a step in the history where the file is completely blank. It seems this is only reproducible if the file is 6 lines at the start, however it doesn't seem to be related to the _file_ size, as `CRLF` vs. `LF` doesn't make a difference in whether this can be reproduced.

Again, this package makes _no_ changes to the file directly for the autofix, `eslint` is doing that externally to the Atom process, and apparently triggering this behavior.

**Comment by dwelle** [comment]
can't reproduce using those steps on latest stable Atom :/

**Comment by Arcanemagus** [comment]
I was testing on Atom v1.10.0-beta5, maybe the content needs to be different on stable? In either case, it's an Atom issue. I'm not sure the issue you linked is the root cause, but it does sound related.

**Comment by adamreisnz** [comment]
@Arcanemagus has there been an issue raised in one of the Atom repo's to track this external bug? If not, what package do you think is suitable to file this under (core?)

I'm using Atom 1.14 and it's still an issue that's occasionally driving me crazy.

**Comment by gabrielkunkel** [comment]
@adamreisnz And it's so sweet, except for it popping me back up to the top of the file! (I'm a compulsive saver.)

@Arcanemagus ...Edge of my seat... Whatever you can recommend about going to resolve this issue. Much appreciated!

**Comment by Arcanemagus** [comment]
I would file it on `atom/atom`, if that isn't the proper repo they can redirect you further.

**Comment by adamreisnz** [comment]
Found a possibly related issue here which was closed: https://github.com/atom/atom/issues/11483

**Comment by vvo** [comment]
Small note that this never happens with prettier-atom, maybe we could ask if they tackled this specifically? cc @robwise and @darahak

**Comment by dwelle** [comment]
@vvo not sure since they lately made a [PR that _minimizes_](https://github.com/prettier/prettier-atom/pull/113) probably the same problem we have

**Comment by darahak** [comment]
There is the PR @dwelle mentioned and the fact that we always end up using [`editor.setTextInBufferRange`](https://github.com/prettier/prettier-atom/blob/7ba80853a95162cd3b36b068ee4a527e54ad5b4d/src/executePrettier/executePrettierOnBufferRange.js#L33) to insert the formatted code.

I couldn't find how `linter-eslint` does it, but other than that, I don't see what we could do differently.
We still have issues with text replacement like disappearing bookmarks (https://github.com/prettier/prettier-atom/issues/105).

I'm relatively new on this project, maybe Rob will have more insight.

**Comment by dwelle** [comment]
:laughing: in the https://github.com/prettier/prettier-atom/issues/105 issue you guys were interested what _we_ were doing over here that our bookmarks stayed in place (which was later debunked). It seems we have a catch 22 here.

Probably the best course of action is to take this over to atom/atom. The `setTextInBufferRange` is a way to improve behavior, too, but it seems it's not a silver bullet.

**Comment by Arcanemagus** [comment]
https://github.com/atom/atom/issues/14189 is the root cause of the issue here, hopefully this can get some more detailed investigation soon over there. I'm still happy I managed to find a case that reproduces most of the time.
