### ISSUE TITLE
Allow rules overriding

### ISSUE THREAD

**Issue by ngryman** [AtomLinter/linter-eslint#621]
Hi,

In my use case I report the `no-multiple-spaces` as an error. But for obvious reasons, I don't want this rule to be reported while I'm coding. Still, I want to keep the default cascading behavior and my project `eslintrc`.

Being able to specify a config path that would take precedence on any other rules would be perfect. That would allow to tweak the config for a live coding environment.

Thanks!

![eslint](https://cloud.githubusercontent.com/assets/892048/16360004/87ba7648-3b4a-11e6-97ab-338d43f10c1b.gif)

**Comment by Arcanemagus** [comment]
Is this even possible @IanVS? As far as I know `eslint` doesn't support anything like this.

**Comment by ngryman** [comment]
@Arcanemagus I suppose there are several ways of forcing a set of rules.

One would be to use the `--rule` command line switch of `eslint` as it has a higher precedence (http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).
But it would be cumbersome I guess.

An other would be to extend the found project configuration with the global one and pass the result to `eslint`.

There are probably other ways of achieving this but I'm not aware of them.

---

On a side note, I think this should be an important feature. Linting a *live* code and a codebase should be treated differently as the context is different.
*Live* code evolves and while you are typing you are certainly violating some rules that only make sense when the code is in its final version.

Another *simpler* way to solve this problem, would be to allow the user to lint only on save, in order to review the code when he wants.

**Comment by Arcanemagus** [comment]
Interesting idea, I can see allowing an array of `--rule` specifications to pass in only for on the fly lints, while letting it use the unaltered project configuration for a "on save" lint, that would require an almost complete re-write of the linter though as it would need to move to the Indie API to be able to provide different functionality based on the type of lint call...

**Comment by sradevski** [comment]
What I was thinking of is quite simple: Have an option that will only lint on save. Like this you can code without the annoying linting messages, and once saved, the whole file will be linted and it will show the linting errors.

**Comment by ngryman** [comment]
@sradevski This option already exist in the `linter` package as `Lint As You Type`.

**Comment by sradevski** [comment]
@ngryman I wasn't aware of it, thanks!

**Comment by IanVS** [comment]
@ngryman would https://github.com/AtomLinter/linter-eslint/pull/666 meet your needs?

**Comment by ngryman** [comment]
@IanVS It seems perfect! I guess we can close this one then.

**Comment by jakedeichert** [comment]
@Arcanemagus I think eslint supports overriding but I can't seem to get it to work with linter-eslint.

Check out the docs here: http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

> The configuration cascade works by using the closest .eslintrc file to the file being linted as the highest priority, then any configuration files in the parent directory, and so on.
> ...
> When ESLint traverses into the tests/ directory, it will then use your-project/tests/.eslintrc in addition to your-project/.eslintrc. So your-project/tests/test.js is linted based on the combination of the two .eslintrc files in its directory hierarchy, with the closest one taking priority. In this way, you can have project-level ESLint settings and also have directory-specific overrides.

I have a `test` directory with a `.eslintrc.js` and 1 rule override. linter-eslint seems to only obey the top-level `.eslintrc.js` file.

Maybe I'm missing something? But so far it seems like linter-eslint doesn't combine `.eslintrc.js` files and therefore doesn't support overriding at the moment.

**Comment by IanVS** [comment]
@jakedeichert, that's a separate issue.  Would you mind opening another issue with a reproducible test case?

**Comment by jakedeichert** [comment]
@IanVS sure, I'll do this today!

**Comment by jakedeichert** [comment]
@IanVS @Arcanemagus ahhhh I apologize...

After restarting Atom, I can no longer reproduce this. Might have been my Atom update from yesterday.

Sorry for the confusion!

**Comment by IanVS** [comment]
👍   It's best to always try restarting Atom when funky things are happening.  Not sure why that is, but it seems to solve a lot of weird problems.  Glad it's working for you now!
