### ISSUE TITLE
Error thrown in project without eslint installed

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-eslint#623]
I have to frequently work on projects from other develops, and they do not have eslint installed nor any of its plugins like standard or semi-standard (which is what I use).

Whenever I open one of their js files, I get  continuous errors as shown below.  How can I prevent this, and have Atom simply ignore the fact that the plugin(s) are not in the given project?

![screen shot 2016-06-28 at 10 25 52 am](https://cloud.githubusercontent.com/assets/835148/16419380/76fd0e06-3d1b-11e6-80b2-8bbb20fa43ea.png)

**Comment by Arcanemagus** [comment]
Where is the configuration telling `linter-eslint` to even look for `eslint-plugin-standard` coming from in the first place?

**Comment by smlombardi** [comment]
apparently i had copied the eslintrc.json file from one of my projects to my home directory.  that was causing it.  still which it would fail more gracefully, though.

**Comment by IanVS** [comment]
Yes, if you have a config in your home, it will apply to all of your projects.  

What would a graceful failure look like in this case, do you think?
