### ISSUE TITLE
Display rule name with errors

### ISSUE THREAD

**Issue by adambuczynski** [AtomLinter/linter-eslint#624]
When I was using jscs or jshint linter, it would display the rule name of the error un the error console at the bottom, e.g.:

![image](https://cloud.githubusercontent.com/assets/490562/16436738/7a89ffa0-3df4-11e6-900b-47f0f02b9817.png)

Could we enable this for eslint as well? It was really useful.

If this is something that the eslint package needs to do let me know and I'll raise it there.

**Comment by adambuczynski** [comment]
Actually they do appear, it seems this was just a fatal eslint error, not related to a rule. Will close issue.

**Comment by Arcanemagus** [comment]
The rule names are also clickable here, leading to the documentation of the rule 😉.
