### ISSUE TITLE
A way to provide environment variables when running eslint?

### ISSUE THREAD

**Issue by tleunen** [AtomLinter/linter-eslint#625]
I can't see a way in the settings of the plugin to setup environment variables when running eslint inside Atom.

Is there something I'm missing?
If there's currently no way to do that, do you see any value adding this setting?

**Comment by IanVS** [comment]
What would you want to do with an environment variable? What would be the
benefit for you?

**Comment by tleunen** [comment]
This is actually related to this issue https://github.com/benmosher/eslint-plugin-import/issues/398

I'm using a webpack resolver to check the imports, and inside my webpack, I'm using an environment variable. Because it's never set when running eslint inside atom, the plugin fails to load the configuration file.

For sure I can resolve the issue by adding a check in the file like `if (typeof process.env.X === 'undefined') ...`, but I wonder if there's a better way to resolve the initial issue.

**Comment by IanVS** [comment]
Have you tried launching atom with `SOME_ENV_VAR=whatever atom .`?

**Comment by tleunen** [comment]
Yes it works.

Hmm... I'll close this ticket since there are multiple ways to resolve it.

**Comment by IanVS** [comment]
Cool, glad it worked out for you.

**Comment by robwierzbowski** [comment]
For anyone with the same issue, I found the easiest way to fix missing `env` arguments is to provide an ES6+ default argument. Works on newer versions of node.

```js
// webpack.config.js
const defaultEnv = { NODE_ENV: 'development' };

module.exports = (env = defaultEnv) => {
  // ...configuration
}
```

Easy peasy.

**Comment by douglasmamilor** [comment]
@robwierzbowski Wish I could give you two thumbs ups for that little trick. Saved me some head banging
