### ISSUE TITLE
"undefined is not a function!" with JSX/Import/React/I don't know v0.5.2

### ISSUE THREAD

**Issue by framerate** [AtomLinter/linter-eslint#63]
Works great in 0.5.1 though... here is an example:

```
v0.5.1
```
![v0.5.1](http://i.imgur.com/qTxwXsa.png)

```
v0.5.2
```
![v0.5.2](http://i.imgur.com/ykvRuvI.png)

**Comment by framerate** [comment]
As an update, this happens on a normal ES5 file

```
var express = require('express');
```

kicks it too

**Comment by quazzie** [comment]
same here

**Comment by iam4x** [comment]
Open the developer tools `CMD+ALT+I` and paste the callstack here

**Comment by framerate** [comment]
What callstack do you want? The console only prints:

```
activate linter-eslint
init.coffee:8activate linter-jsonlint
index.js:59 Window load time: 1214ms
```

**Comment by iam4x** [comment]
You don't have any errors about the `undefined is not function` ?

**Comment by framerate** [comment]
Nope. The “undefined is not a function!” doesn’t appear to be an error (note the ! in the text), it is showing up as an “eslint failure". See my screenshots and this one:

![v0.5.1](http://i.imgur.com/R9SREKB.png)

**Comment by iam4x** [comment]
Can you paste your `package.json` of the folder your project && your `.eslintrc`, thank's.

**Comment by framerate** [comment]
package:
```
"dependencies": {
    "flux": "^2.0.1",
    "jquery": "^2.1.3",
    "react": "^0.13.1",
    "react-router": "^0.13.2"
  },
  "devDependencies": {
    "babel-core": "^4.7.16",
    "babel-eslint": "^2.0.2",
    "babel-loader": "^4.2.0",
    "babelify": "^5.0.4",
    "body-parser": "^1.12.2",
    "browserify": "~9.0.3",
    "colors": "^1.0.3",
    "eslint": "^0.19.0",
    "eslint-plugin-react": "^1.6.1",
    "express": "^4.12.3",
    "gulp": "^3.8.11",
    "gulp-html-replace": "^1.4.4",
    "gulp-nodemon": "^2.0.2",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-streamify": "0.0.5",
    "gulp-uglify": "=1.1.0",
    "gulp-util": "^3.0.4",
    "livereactload": "^0.2.2",
    "load-grunt-tasks": "^3.1.0",
    "react-hot-loader": "^1.2.4",
    "serve-static": "^1.9.2",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^2.6.2"
  }
```

eslintrc:
```
{
    "parser": "babel-eslint",
    "env": {
        "node": true,
        "es6": true
    },

    "plugins": [
        "react"
    ],

    "settings": {
        "ecmascript": 6
    },

    "ecmaFeatures": {
        "jsx": true
    },

    "rules": {
        "comma-dangle": "never",
        "no-extra-semi": 2,
        "camelCase": true,
        "brace-style": [2, "1tbs", { "allowSingleLine": true }],
        "no-underscore-dangle": 0,
        "strict": 0,
        "no-trailing-spaces": 0,
        "no-undef": 1,
        "react/jsx-no-undef": 2,
        "no-unused-vars": 2,
        "react/jsx-uses-vars": 1,
        "no-console": 1,
        "eqeqeq": [2, "smart"],
        "quotes": [2, "single"]
    },

    "globals": {
        "document": true,
        "window": true,
        "karma": true,
        "chrome": true
    }
}
```

**Comment by framerate** [comment]
I did some work today and redid my package.json to latest versions and the problem seems to have gone away. Here is the NEW package.json if it helps you figure out the problem:

```
  "dependencies": {
    "flux": "^2.0.1",
    "jquery": "^2.1.3",
    "react": "^0.13.1",
    "react-router": "^0.13.2"
  },
  "devDependencies": {
    "babel-core": "^5.1.9",
    "babel-eslint": "^3.0.1",
    "babel-loader": "^5.0.0",
    "babelify": "^6.0.2",
    "body-parser": "^1.12.2",
    "browserify": "~9.0.8",
    "colors": "^1.0.3",
    "eslint": "^0.19.0",
    "eslint-plugin-react": "^2.1.0",
    "express": "^4.12.3",
    "gulp": "^3.8.11",
    "gulp-html-replace": "^1.4.5",
    "gulp-nodemon": "^2.0.2",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-streamify": "0.0.5",
    "gulp-uglify": "=1.2.0",
    "gulp-util": "^3.0.4",
    "livereactload": "^0.4.0",
    "load-grunt-tasks": "^3.1.0",
    "react-hot-loader": "^1.2.5",
    "serve-static": "^1.9.2",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.1.1"
  }
```

**Comment by iam4x** [comment]
Great :+1:

**Comment by asan** [comment]
I have issued same problem, it caused by exception in core-js(from babel 4.x), so easiest workaround to upgrade babel to 5.x

**Comment by marudor** [comment]
This Problem still exists. I traced it to a line in the babel-core package. The Problem is this line:
> static globals = flatten([globals.builtin, globals.browser, globals.node].map(Object.keys));
Object.keys is overridden it seems. It uses arguments to and wants to use the 2nd argument as a function.
The fix is to not pass Object.keys directly but to wrap it as anonymous function.

**Comment by marudor** [comment]
Addition: This is actually due to another package overriding the native Method.
For me it was autocomplete-bibtex.
If you have this problem please open the developer tools of atom and check where your Object.keys method is coming from. If it is not the native Method you should disable the package that changed your Object.keys method and check if it works after that.

It is not a linter-eslint, eslint or babel problem.

**Comment by iam4x** [comment]
Is this still happening with newer versions of the package?

**Comment by iam4x** [comment]
Version 2.0 has been released now using CLI, please open a new issue if something is wrong.
