### ISSUE TITLE
How hide the linter inline overlay message ?

### ISSUE THREAD

**Issue by noyobo** [AtomLinter/linter-eslint#639]
I can't find the option to shut down 💤

<img width="289" alt="2016-07-16 11 21 17" src="https://cloud.githubusercontent.com/assets/1292082/16892515/b44dcca2-4b47-11e6-8c4b-7aa8b65584ae.png">

**Comment by KooBiGitHub** [comment]
Von meinem iPhone gesendet

**Comment by Arcanemagus** [comment]
This package has nothing to do with the UI, it is only a provider for `eslint` messages. You should disable the 'Show Inline Error Tooltips' option in the Linter package if you don't want those to show.
