### ISSUE TITLE
Error expected indentation of 1 tab character but found 0.

### ISSUE THREAD

**Issue by PolGuixe** [AtomLinter/linter-eslint#642]
I am getting this error when I do actually have indented the line properly. See gif below: 

http://g.recordit.co/q22bCoA66T.gif

Any idea why?

**Comment by IanVS** [comment]
Those could be spaces (Atom can be "smart" about cursoring around indentation even if they're groups of spaces). Could you try enabling the "Show Invisibles" setting in the main Atom settings page?  

![image](https://cloud.githubusercontent.com/assets/4616705/16917680/a4b6ccbe-4cd0-11e6-80e8-c01ea44aade5.png)

**Comment by PolGuixe** [comment]
Nice. It did work. ;)

**Comment by IanVS** [comment]
Great!

**Comment by benjaminviaud** [comment]
You can convert spaces into tabs in Atom :
https://stackoverflow.com/questions/41848002/how-to-replace-tabs-with-spaces-in-atom
