### ISSUE TITLE
ReactDom is not defined

### ISSUE THREAD

**Issue by jjdp** [AtomLinter/linter-eslint#651]
I got this error:

> ReactDom is not defined

using [atom-react](https://github.com/orktes/atom-react) or [language-babel](https://github.com/gandm/language-babel) eitherway still generates it

I am on windows 10 64-bit
Node 4.4.7
Atom 1.8.0
linter-eslint 7.2.4

**Comment by IanVS** [comment]
That error is not a problem in this package.  It just means you are using a variable in your code (`ReactDom`) that is not defined (there should be a `var reactDom = require('react-dom');` or similar.)

**Comment by jjdp** [comment]
thank you. I missed that one.
