### ISSUE TITLE
eslint standard not installing eslint-plugin-promise dependency

### ISSUE THREAD

**Issue by marcosfede** [AtomLinter/linter-eslint#659]
When I `eslint --init` on my project and select the standard style guide, I get an error because the eslint-plugin-promise dependency is not installed by the init script. running `npm install eslint-plugin-promise --save-dev` fixes the issue

**Comment by IanVS** [comment]
Thanks, but would you mind filing this issue over at https://github.com/eslint/eslint?  This repo is just the atom-linter plugin.
