### ISSUE TITLE
Support .eslintrc files in subdirectories

### ISSUE THREAD

**Issue by emiln** [AtomLinter/linter-eslint#660]
I often find that I need to change the ESLint rules slightly for testing with `chai`. Typically I have a structure like the following:

```
.
├── .eslintrc
├── app.js
├── lib
├── middlewares
├── package.json
└── test
    ├── .eslintrc
    ├── lib
    └── middlewares
```

I define the general rules in `./.eslintrc` and disable a few of them for testing (mostly `no-unused-expressions` to use features like `expect(error).to.exist`).

This works well when running my tests with ESLint through my automated testing setup, but `linter-eslint` does not seem to pick up these additional rules from `./test/.eslintrc`. It still displays errors about `no-unused-expressions` when editing files under the `./test`dir, which I think is wrong.

Currently I just have to ignore the types of errors I know I've asked to have ignored in .eslintrc files in subdirectories, but this is not very satisfying when editing.

**Comment by IanVS** [comment]
That's strange, and definitely should be working (it works fine for me).  Have you tried restarting atom lately?  I know it sounds crazy, but these kinds of weird issues are many times solved by a simple "turn it off and back on again".   ¯\\_(ツ)_/¯

**Comment by emiln** [comment]
You know what? That actually did the trick. Thanks for the quick reply and simple solution.
