### ISSUE TITLE
// eslint-disable-next-line prefer-stateless-function doesn't apply

### ISSUE THREAD

**Issue by kevinSuttle** [AtomLinter/linter-eslint#661]
Both of the following work
`// eslint-disable-next-line`
`// eslint-disable-line`

However, if I try `// eslint-disable-next-line prefer-stateless-function`, that doesn't work. 

<img width="1065" alt="screen shot 2016-08-05 at 3 38 31 pm" src="https://cloud.githubusercontent.com/assets/95672/17448524/d4c46f50-5b22-11e6-8924-16dd5a614060.png">

**Comment by IanVS** [comment]
You need to include the `react/` part of the rule name.  So try, `// eslint-disable-line react/prefer-stateless-function`.

**Comment by Arcanemagus** [comment]
Also, marking this as closed since this has nothing to do with `linter-eslint`, and is a general `eslint` question 😉.

**Comment by kevinSuttle** [comment]
Gah, that always gets me. Thanks!
