### ISSUE TITLE
Still processing despite "disabled" in Prefs

### ISSUE THREAD

**Issue by mikeerickson** [AtomLinter/linter-eslint#662]
I have linter-eslint to be disabled if there is no local `.eslintrc.yml` file, but as displayed in the screenshots, seems to still be running (and there is no config info in the `package.json` file either)

<img width="883" alt="lint-config" src="https://cloud.githubusercontent.com/assets/183153/17465438/ccc7b58e-5cab-11e6-863a-9b100f3c7cac.png">
<img width="1079" alt="lint-error" src="https://cloud.githubusercontent.com/assets/183153/17465439/cccd9de6-5cab-11e6-9a29-ad8da634c9c8.png">

**Comment by IanVS** [comment]
Is it possible you might have an `.eslintrc` in an ancestor directory or your home directory?

**Comment by mikeerickson** [comment]
@IanVS Well, as luck would have it, the answer is indeed yes.  But, I *thought* that was defined to use `esprima` when in fact it was set to `babel-eslint` hence the unexpected error report.

Sorry I didn't think to check that first.

**Comment by IanVS** [comment]
:+1:
