### ISSUE TITLE
Better experience for `create-react-app` projects

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-eslint#664]
![selection_002](https://cloud.githubusercontent.com/assets/324999/17562775/2685bc92-5ee1-11e6-88fa-e40e4bc93434.png)

When you create a project with `create-react-app` it comes with eslint preconfigured in a way that doesn't work with editors. `package.json` contains `"eslintConfig": { "extends": "./node_modules/react-scripts/config/eslint.js"  }` and because of how eslint resolves modules, this configuration only works if it's run from the instance of eslint installed at `./node_modules/react-scripts/node_modules/eslint`

My attempt at fixing this in eslint [has been rejected](https://github.com/eslint/eslint/pull/6865#issuecomment-238923390), so now I'm here just trying to find a way to still use Atom on these projects. So far my ideas are:

1. If these errors can be suppressed then Atom is usable but missing any linting errors.
2. [WARNING: hack] If [getESLintInstance](https://github.com/AtomLinter/linter-eslint/blob/dd11d264d2424fa357d7f08d7687e41a7461661a/src/worker-helpers.js#L65-L69) also checks `
node_modules/react-scripts/node_modules/eslint` it prevents the error, but that's only going to work in this one scenario.

**Comment by IanVS** [comment]
Have you tried the steps in https://github.com/facebookincubator/create-react-app/blob/master/template/README.md#displaying-lint-output-in-the-editor? (essentially, use a global linter installation).

Granted, it's not ideal, but the problem really needs to be addressed upstream in ESLint.  I don't think we want to add hacks to `linter-eslint`, but maybe it's worth it in this one case.  What do you think, @Arcanemagus?

**Comment by AsaAyers** [comment]
No, I didn't see that when I last look at that page. I installed a local eslint into my project, I locally installed every plugin, I globally installed eslint and the plugins. The step I didn't know I needed to was to go make linter-eslint use the global eslint.

I think linter-eslint could provide a better experience by attempting to detect this situation and either switching to a global eslint or guiding the user on how to fix it.

I rarely use a global modules because they are just undocumented dependencies. It makes sense for commands to be global, but modules should never be global. If you have a project that is configured to use `eslint` it belongs in `devDependency`. I have run into small projects before where the only developer doesn't bother to add dependencies because he already has them globally installed and everything works on his machine.

**Comment by IanVS** [comment]
Yes, we recommend not using global ESLint whenever possible for _exactly_ the reasons you point out.  But it's there as a fallback for cases like this.

**Comment by Arcanemagus** [comment]
Since `npm` can't even find the `eslint` install with something like this:

```json
  "scripts": {
    "eslint": "eslint ."
  }
```

I'm not really inclined to work on an incredibly hacky "solution" to the mess FB has created there by trying to hide all the details of how it works 😒.

It looks like you can localize their global hack by just running this:

```shell
npm install --save eslint babel-eslint eslint-plugin-react eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-flowtype
```

You have to maintain the versions to be compatible with their hidden ones... but you would have to be doing that anyway with the global workaround.

**Comment by gaearon** [comment]
Author of CRA checking in. I’d like to say I *hate* to tell people to install ESLint globally. I’m not a fan of the workaround we tell people to use.

We do it because hiding dependencies is the main feature of the project, but I’d much rather see it solved in ESLint.

**Comment by AsaAyers** [comment]
Was this fixed somewhere and not closed?

I just started a new `create-react-app` to discover there's a new dependency to install globally. Since the workaround broke after less than a month I decided I was going to find another solution (probably running a fork of linter-eslint). I have uninstalled all of the global packages, turned off 'use global ESlint` and somehow eslint is running successfully!

**Comment by AsaAyers** [comment]
:( I found it. In trying to get the new version of `create-react-app` working I accidentally left the `-g` off my `npm install`. linter-eslint was just using `node_modules/{eslint,babel-eslint,eslint-plugin-react,etc}`. But that might be a better hack than the global installs.

I have several different projects I work on with Atom and some use `create-react-app` and need a global install and others don't. it's a real pain having to flip that setting back and forth. I have the `project-manager` addon, but it doesn't always handle having multiple projects open at the same time  (maybe Atom's fault here?).

**Comment by Arcanemagus** [comment]
Yea, installing the dependencies locally was the workaround I proposed instead of the global install 😛.

I'm going to mark this as closed as an external issue.

**Comment by chrisbolin** [comment]
For reference, this *is* fixed in `create-react-app` now (by making the eslint config a separate package). Just add this to your `package.json` and Atom's linter will pick it up:

```json
  "eslintConfig": {
    "extends": "./node_modules/eslint-config-react-app/index.js"
  },
```

**Comment by gaearon** [comment]
Won’t `"extends": "react-app"` also work?

**Comment by chrisbolin** [comment]
@gaearon yup! you're right. my eslint foo is not strong. updated my comment to reflect that

**Comment by Arcanemagus** [comment]
Glad to hear it!
