### ISSUE TITLE
Editing .eslintrc throws an annoying warning

### ISSUE THREAD

**Issue by broberson** [AtomLinter/linter-eslint#669]
eslint ignores .eslintrc, so when Atom tries to run it on that file, it complains that the file is ignored by default and offers a no-so-helpful suggestion about how to un-ignore it.

`File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern \'!<relative/path/to/filename>\'") to override.`

**Comment by IanVS** [comment]
Closed by #670.  Will go out in the next release (which will likely be soon).
