### ISSUE TITLE
Make it possible to link inside <script> element of HTML file

### ISSUE THREAD

**Issue by brentonstrine** [AtomLinter/linter-eslint#674]
We use HTML templates that have Javascript in them, and they're currently unlintable without manually creating a new temporary file with the .js extension and pasting the contents of the <script> element into it.

**Comment by Arcanemagus** [comment]
This is _exactly_ why the scopes that trigger running `linter-eslint` is configurable 😉.

When you have the cursor in a block of that embedded JS and run `Editor: Log Cursor Scopes` from the command palette. Then go into your settings and add the most specific `source.___` scope in the list you just grabbed into the "List of scopes..." setting.

**Comment by nopnop** [comment]
Hello @Arcanemagus: This configuration option seems to be unreleased (7.2.4 does not provide Scope configuration). Do you confirm (else I missed something) ?

**Comment by Arcanemagus** [comment]
Sorry, it actually wasn't released, but it is released in v7.3.0!

**Comment by nopnop** [comment]
Awesome, thks @Arcanemagus!
