### ISSUE TITLE
 Unable to resolve path to module

### ISSUE THREAD

**Issue by MonsieurWave** [AtomLinter/linter-eslint#677]
Hi everyone,

I keep getting errors for all my modules :  Unable to resolve path to module
although they have been locally installed. 
I am using babel-require and Atom 1.9.9 on windows 10. 
Any idea why that might be ?

Best regards.

**Comment by IanVS** [comment]
Hi @MonsieurWave, can you give a little more details?  Do you get the same error if you run eslint from the command line?  If so, it's a problem with your configuration and not a bug in this package, and you're likely to find the best help at the eslint gitter: https://gitter.im/eslint/eslint.

**Comment by MonsieurWave** [comment]
Yes I do get the same errors on the commandline.
Thanks for the advice.
