### ISSUE TITLE
 Definition for rule 'no-global-assign' was not found

### ISSUE THREAD

**Issue by MonsieurWave** [AtomLinter/linter-eslint#678]
Hi everyone,

I keep getting the error : Definition for rule 'no-global-assign' was not found
I am using babel-require and atom 1.9.9 on windows 10.

Best regards.

**Comment by IanVS** [comment]
Hi @MonsieurWave, what version of ESLint are you using?

**Comment by IanVS** [comment]
This is an error when you try to use a core ESLint rule which does not exist in your version of ESLint.  `no-global-assign` was just added to ESLint `3.3.0`, and you are likely using an older version.

**Comment by MonsieurWave** [comment]
I am using ESlint V. 3.3.1, so that can't be the origin of the problem.

**Comment by IanVS** [comment]
Are you using global or local eslint?  What is the result of linting with eslint on the command line?

**Comment by MonsieurWave** [comment]
I am using a local eslint and launching it from command line gives me the same error.

**Comment by chabbrik** [comment]
I have the same error on eslint 3.4.0

**Comment by IanVS** [comment]
If you have the same error when running ESLint on the command line, then it is not a problem with this particular package.  It could be a problem with ESLint itself, or with your configuration.  I'd recommend jumping into the ESLint gitter chat to get some live help.

I'm going to close the issue, since this is not directly related to linter-eslint, but feel free to continue the discussion here if you're stuck.

**Comment by MrSnappingTurtle** [comment]
Hey,

I seem to be having the same issue along with a few other rules. I do not get the errors in the CLI. My linter-eslint version is 7.3.2. I believe that is the latest version. CLI is 3.7.0.

Thanks!

![issue](https://cloud.githubusercontent.com/assets/8148243/19019049/b4bd5ef6-882c-11e6-9168-fa21557463b5.PNG)

**Comment by Arcanemagus** [comment]
From your terminal @MrSnappingTurtle it appears you are using a global ESLint installation. Have you enabled that option in the settings?

As a note that setup, although _supported_, is not recommended.

**Comment by MrSnappingTurtle** [comment]
@Arcanemagus I uninstalled it globally and installed a local version. This fixed the problem. Thanks! :)
