### ISSUE TITLE
Error message is totally misleading - Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly

### ISSUE THREAD

**Issue by sjmcdowall** [AtomLinter/linter-eslint#680]
I spent 4 hours tracking this down -- only to find out the error message is totally wrong and mis-leading.

linter-eslint doesn't even't TRY to use $PATH to find eslint -- instead it does a lot of dancing around nodePrefixPaths() etc. which can be totally wrong depending on the situation. 

For example I use "nvm" but also load common -g type modules in the "standard" /usr/local area.  From my shell I can "which eslint" and run it just fine.  I then launch atom .. but get this error message if it's set to Use Global because my nvm get prefix isn't point to the global prefix area of /usr/local but rather some nvm/v6.3.1 path thing ..

It would be awesome of complex environments to ALSO check to see if eslint DOES exist in the path and to use that if it does.  Certainly though the error message needs to change because it's just wrong and frustrating going down a blind alley. 
## 

``` js
function getESLintFromDirectory(modulesDir, config) {
  var ESLintDirectory = null;

  if (config.useGlobalEslint) {
    var prefixPath = config.globalNodePath || getNodePrefixPath();
    if (process.platform === 'win32') {
      ESLintDirectory = _path2.default.join(prefixPath, 'node_modules', 'eslint');
    } else {
      ESLintDirectory = _path2.default.join(prefixPath, 'lib', 'node_modules', 'eslint');
    }
  } else {
    ESLintDirectory = _path2.default.join(modulesDir || '', 'eslint');
  }
  try {
    return require(_path2.default.join(ESLintDirectory, 'lib', 'cli.js'));
  } catch (e) {
    if (config.useGlobalEslint && e.code === 'MODULE_NOT_FOUND') {
      throw new Error('ESLint not found, Please install or make sure Atom is getting $PATH correctly');
    }
    return require(_path2.default.join(Cache.ESLINT_LOCAL_PATH, 'lib', 'cli.js'));
  }
}
```

**Comment by Arcanemagus** [comment]
Sorry, but this is a wontfix for what you _want_. We need the actual eslint JS files, not what you get from `which eslint`.

Leaving this open though as the error message could be improved.

**Comment by sjmcdowall** [comment]
You then missed what _wanted_ .  What I want is an appropriate and not misleading error message, nothing else.

**Comment by soredake** [comment]
Any progress on this?

**Comment by IanVS** [comment]
@soredake we'd be very happy to accept a PR for this.  You can check out https://github.com/AtomLinter/linter-eslint/pull/725#discussion_r82236519 for an idea of where to address this.
