### ISSUE TITLE
Different results between command line eslint and within Atom linter-eslint

### ISSUE THREAD

**Issue by sjmcdowall** [AtomLinter/linter-eslint#681]
Ok -- I know I am going to seem like a nut, and I'm maybe just totally forgetting something -- but this is driving me nuts.  

If I have linter-eslint installed with "local" copy of eslint, the linter works fine within Atom.  However, if I tell it to use the global version l -- and try to use that -- I get a nasty error (see down below).  

From EVERYTHING I can tell, my global version is the same version # as the project local. Here is the package.json snippet:

    "prelint": "which eslint || npm install -g eslint",
    "lint": "eslint ./src/.",

    "eslint": "^3.3.1",
    "eslint-config-airbnb": "^10.0.1",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.1.0",
    "eslint-plugin-react": "^6.1.2",

Here is the command line which etc. 

~/work/galaxy/next-gen/gs-service   develop±  which eslint
/usr/local/bin/eslint
 ✝  ~/work/galaxy/next-gen/gs-service   develop±  eslint -v
v3.3.1

-- Running lint on cli ---

 ✝  ~/work/galaxy/next-gen/gs-service   develop±  npm run lint

> @galaxysemi/gs-service@1.0.1 prelint /Users/sjm/work/galaxy/next-gen/gs-service
> which eslint || npm install -g eslint

/Users/sjm/work/galaxy/next-gen/gs-service/node_modules/.bin/eslint

> @galaxysemi/gs-service@1.0.1 lint /Users/sjm/work/galaxy/next-gen/gs-service
> eslint ./src/.

The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.

/Users/sjm/work/galaxy/next-gen/gs-service/src/gs-service.js
    1:1   error  'use strict' is unnecessary inside of modules           strict
   12:2   error  Expected indentation of 0 space characters but found 1  indent
   14:2   error  Expected indentation of 0 space characters but found 1  indent
   19:1   error  Import in body of module; reorder to top                import/imports-first

...

--- Error from Atom ---

Error: /Users/sjm/work/galaxy/next-gen/gs-service/node_modules/eslint-config-airbnb/rules/react.js: Configuration for rule "react/jsx-sort-props" is invalid: Value "data["0"].shorthandLast" has additional properties.

Referenced from: airbnb Referenced from: /Users/sjm/work/galaxy/next-gen/gs-service/.eslintrc
Error: /Users/sjm/work/galaxy/next-gen/gs-service/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
Referenced from: airbnb
Referenced from: /Users/sjm/work/galaxy/next-gen/gs-service/.eslintrc
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:522:19)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36

---

I'm quite going mad -- I am sure it probably is something really insane I have setup wrong but  can't figure it out !

**Comment by IanVS** [comment]
@sjmcdowall, do you have the same versions of all of the plugins and config also installed globally?

**Comment by sjmcdowall** [comment]
Ah ha!  You're a genius!  Sure enough I had an outdated eslint-react package in globals .. removed that and viola!!  Woot! Thanks!  Sanity returned (ha!) :)

**Comment by IanVS** [comment]
Yeah the whole global vs. local installation of ESLint is the most confusing part and creates more issues in this repo than anything else it seems.  You're not alone.
