### ISSUE TITLE
TypeError: Cannot set property '1' of undefined after update

### ISSUE THREAD

**Issue by AntonDnepr** [AtomLinter/linter-eslint#688]
After update to 7.3.0 got this error

```
TypeError: Cannot set property '1' of undefined
    at /home/anton/.atom/packages/linter-eslint/lib/main.js:193:27
    at Array.map (native)
    at /home/anton/.atom/packages/linter-eslint/lib/main.js:174:27
```

ubuntu: 14.04
Atom: 1.9.9
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
eslint: v3.3.1

Error happen when i write new code in any js file

**Comment by Arcanemagus** [comment]
Are you able to provide a JS file and ESLint configuration that shows this error? The only thing I am seeing is #687.

**Comment by AntonDnepr** [comment]
@Arcanemagus 
really weird but after system reboot I can't reproduce this one as well. This happened to me in *.js file with react jsx syntax. 

![2](https://cloud.githubusercontent.com/assets/7930813/18409223/e653b8e0-774a-11e6-83f9-934b25a6cb8f.png)

and eslint config file

{
    "plugins": [
        "react"
    ],
    "parser": "babel-eslint",
    "extends": ["eslint:recommended", "plugin:react/recommended"],
    "env": {
        "browser": true,
        "node": true
    },
    "rules": {
        "semi": [1, "always"],
        "react/display-name": 0
    },
}

**Comment by IanVS** [comment]
Closing for now, let us know if it comes back.  Thanks!
