### ISSUE TITLE
Unable to disable line?

### ISSUE THREAD

**Issue by mikeerickson** [AtomLinter/linter-eslint#693]
Hey Gang

I am having an issue with `linter-eslint` and I am not sure if it is this project or `estlint` in general

var COLOR_ORANGE          = '\033[38;5;214m';   // eslint-disable-line strict

Please see this screen shot for error.  I have tried everything I can find about disabling this line

http://d.pr/i/LWo0

I have also tried to disable via block

```
/*eslint-disable */
if(! isStrictMode() ) {
  COLOR_ORANGE          = '\033[38;5;214m';
  COLOR_RESET           = '\033[m';
}
/*eslint-enable */
```

**Comment by IanVS** [comment]
That is a parsing error, ESLint is just telling you what you would find out if you tried to run the code in the browser or node.  You'll need to define your color with something other than an octal literal if you are using strict mode (meaning `"use strict"` or ES6 modules i.e. `import`).  This is not an error you can disable.

**Comment by IanVS** [comment]
I closed the issue because this is not a bug in this package, but feel free to keep discussing here if you have other questions.
