### ISSUE TITLE
Installing “linter-eslint@7.3.1” failed.

### ISSUE THREAD

**Issue by s7dhansh** [AtomLinter/linter-eslint#704]
Error Message:
npm ERR! cb() never called!

I tried cleaning the npm cache and fixing my /tmp permissions so far, without any success. Any help would be great.

I had this package installed and working, but it stopped working after the last update (7.3.1), so I was trying to reinstall the package.

**Comment by s7dhansh** [comment]
I fixed it by spawning a brand new atom profile, installing linter-eslint, and then copying that folder to my old atom profile.

```
cd ~
rm -rf .atom/packages/linter-eslint   # to ensure the removal of any residual files
mv .atom .atom.1
apm install linter-eslint
cp -r .atom/packages/* .atom.bak/packages/
mv .atom .atom.2
mv .atom.1 .atom
```

Since I haven't been able to figure out the problem, I will leave this issue open for a few days, in case someone stumbles on the same issue.

**Comment by Arcanemagus** [comment]
I've never seen that particular error, so that's a new one... for future reference you should be able to just close all Atom instances, run `rm -Rf ~/.atom/packages/linter-eslint`, then `apm install linter-eslint`, and it should be working again. The settings aren't tied to the package installation.

**Comment by s7dhansh** [comment]
@Arcanemagus  I had already tried this approach, but finally sorted it out only through the solution that I wrote above.
The problem arose on  the 7.3.2 as well. Diagnosed it to be arising from .apm folder. Had to delete it and then everything started working.
