### ISSUE TITLE
eslint runs in command line but files are not linted in atom

### ISSUE THREAD

**Issue by barbalex** [AtomLinter/linter-eslint#707]
I can run `eslint src queries test --fix` on the command line and all linting errors are nicely listed.

When I open one of the files with linting errors in atom, I get a green "No issues" on the bottom left.

I can add very stupid js errors without any linting messages showing up.

What am I doing wrong?

In atom I am using:

- linter 1.11.6
- linter-eslint (undefined)
- jsonlint 1.1.4

Here is my project: https://github.com/FNSKtZH/apflora_api

**Comment by IanVS** [comment]
`linter-eslint (undefined)` That doesn't seem right.  Try re-installing linter-eslint, then restarting Atom.

**Comment by barbalex** [comment]
Yeah, that worked. Thanks so much for saving my day!
