### ISSUE TITLE
Error: Cannot mark location in editor

### ISSUE THREAD

**Issue by onlywei** [AtomLinter/linter-eslint#708]
Just started happening to me today. Upgraded to 7.3.2.

Linter errors sometimes throw this Atom error. This one was specifically for (no-multiple-empty-lines) - at line (215) column (2).

**Comment by Arcanemagus** [comment]
`no-multiple-empty-lines` had a bug in it and was reporting the wrong column since `eslint@1.8.0`, it is fixed in `eslint@3.5.0` so you just need to update to that version (or newer).
