### ISSUE TITLE
Cannot mark location in editor for (undefined) 

### ISSUE THREAD

**Issue by MikeyBurkman** [AtomLinter/linter-eslint#711]
I just updated to 7.3.2 yesterday, and now I'm getting a ton of errors that look like this:

```
Error: Cannot mark location in editor for (undefined) - (Parsing error: Unexpected token ILLEGAL) at line (570) column (15)
    at /Users/mburkman/.atom/packages/linter-eslint/lib/main.js:155:21
    at Array.map (native)
    at /Users/mburkman/.atom/packages/linter-eslint/lib/main.js:134:27
```

I can trigger the error just by typing a malformed line of JS. For instance, `parseInt('` will immediately throw the error, even though I'm in the middle of typing.

**Comment by IanVS** [comment]
Hm, as a first step have you tried restarting Atom?

**Comment by Arcanemagus** [comment]
I can't reproduce this myself 😕. Are you able to get a file to a state where it shows an error like that when you open it? Or do you only see this when you are in the middle of typing?

**Comment by MikeyBurkman** [comment]
I'm trying to do some more debugging on this thing. I created a new project, copied over the entire .eslintrc file, and tried to recreate it, but with no luck recreating the issue. I restarted Atom (and made sure the process was dead). I'm running OSX, if that changes anything.

I now have two concurrent instances of Atom running, one with the new test project that doesn't recreate the bug, and one running my (work) project where the bug is consistently showing up. So there's something in my project that the plugin doesn't like, but no idea what. I copied and pasted an entire file from my work project into my test project, as well as some other random .rc files (who knows), and still can't reproduce.

I'll plug away at it some more after work hours to see if I can find the trigger. But for now I have to disable the plugin altogether to avoid the barrage of errors :(

**Comment by Arcanemagus** [comment]
Oh, just to be clear, it _should_ be showing you the error... but as a regular lint message:

![image](https://cloud.githubusercontent.com/assets/427137/18761401/9e8ec1bc-80b9-11e6-8c80-66f573fffc9e.png)

The bizarre part is that the format of the error you are reporting can only come from where it is trying to get the position to show the error at, and failing 😕.

**Comment by dlmanning** [comment]
Am also seeing this with Atom 1.10.2 on OS X

**Comment by johanalkstal** [comment]
I'm getting a similar error after updating to 7.3.2.
`Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 2 blank lines not allowed.) at line (306) column (2)`

**Comment by IanVS** [comment]
@JohnMurga Please upgrade ESLint to version `3.5.0` or above in order to fix that particular issue.

**Comment by johanbrook** [comment]
No worries :)

**Comment by Arcanemagus** [comment]
@MikeyBurkman Are you still seeing this? If so what version of Atom are you running?

**Comment by Domeee** [comment]
Atom: 1.10.2
linter-eslint: 8.0.0
OS: Linux Mint 18, 64-bit

> Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 1 blank line not allowed.) at line (21) column (2)
    at /home/dome/.atom/packages/linter-eslint/lib/main.js:227:21
    at Array.map (native)
    at /home/dome/.atom/packages/linter-eslint/lib/main.js:192:27

![error](https://cloud.githubusercontent.com/assets/8982209/19427239/f713b15c-9442-11e6-97c1-23b3211041a6.png)

**Comment by Arcanemagus** [comment]
@Domeee You need to update to ESLint v3.5.0 or greater.

**Comment by Arcanemagus** [comment]
I'm marking this issue as closed since we have been unable to reproduce this and @MikeyBurkman hasn't responded with further information.

**Comment by Cohedrin** [comment]
I'm having this happen at the moment, on atom version 1.11.2, with eslinter version 8.0.0. 

However, unlike @MikeyBurkman, this seems to be happening on all my javascript projects.

I'm currently unable to cause this to _not_ to happen, even removing everything from the eslint file other than the top level `rules` key causes this to happen.

Eslint version:
```
➜  Documents eslint -v
v1.10.3
```

Here's my settings page:

![screen shot 2016-11-01 at 6 01 51 pm](https://cloud.githubusercontent.com/assets/8690766/19913159/4e410f8a-a05d-11e6-8cdd-3be31c0e26d5.png)


Is there any other information I can provide to help debug this? @Arcanemagus

**Comment by Cohedrin** [comment]
@IanVS Some projects I contribute to have eslint files that are quite old (1.0), so unfortunately upgrading is not a great option for me right now.

I've restarted atom multiple times (along with my computer), still seeing same issue.

Error message:

![screen shot 2016-11-01 at 7 42 30 pm](https://cloud.githubusercontent.com/assets/8690766/19914859/630844b6-a06b-11e6-9349-ef6b5496ab3b.png)


debug: 
```
atom version: 1.11.2
linter-eslint version: 8.0.0
eslint version: 1.10.3
hours since last atom restart: 0
platform: darwin
Using global eslint from /usr/local/lib/node_modules/eslint
linter-eslint configuration: {
  "disableEslintIgnore": true,
  "disableWhenNoEslintConfig": false,
  "eslintRulesDir": "/Users/Jonathon/Documents/",
  "eslintrcPath": "/Users/Jonathon/Documents/.eslintrc",
  "globalNodePath": "/usr/local",
  "rulesToSilenceWhileTyping": [
    ""
  ],
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "advancedLocalNodeModules": "",
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ]
}
```

**Comment by IanVS** [comment]
Are you able to provide the code on line 5 which is throwing the error?  If you fix the parse error, do those Atom error boxes go away?

**Comment by Cohedrin** [comment]
Sure:

![screen shot 2016-11-01 at 7 53 48 pm](https://cloud.githubusercontent.com/assets/8690766/19915066/ee2be088-a06c-11e6-94fc-4ecf7921f8a3.png)


Obviously thats invalid javascript, but I'm in the middle of typing. This happens seconds after typing the word function, heres a gif:

https://gyazo.com/49c568bf576ebdd67203d47bc925b521
@IanVS

**Comment by CJBrew** [comment]
Also seeing that here. #subscribe

**Comment by ShockiTV** [comment]
What was the safe version where this was not happening?
`apm install linter-eslint@what ?`
Also in package readme there is info about v1.0.0 eslint and above.
So please update it if the info is not valid anymore.
