### ISSUE TITLE
Error: Column start (n) greater than line length

### ISSUE THREAD

**Issue by danielabar** [AtomLinter/linter-eslint#712]
I have read similar issues reporting this error, but none of the solutions have helped. Whenever I start a new file, or simply hitting the Enter key in an existing file, this error is popping up in Atom:

```
Error: Column start (2) greater than line length (1)
    at Object.rangeFromLineNumber (/Users/dbaron/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:179:11)
    at /Users/dbaron/.atom/packages/linter-eslint/lib/main.js:142:33
    at Array.map (native)
    at /Users/dbaron/.atom/packages/linter-eslint/lib/main.js:125:27
```

There are no mixed spaces and tabs in js, .editorconfig:

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
charset = utf-8
end_of_line = lf
indent_style = space
insert_final_newline = true

# 2 space indentation
[{*.js,*.css,*.scss,*.html}]
indent_size = 2

# 4 space indentation
[*.go]
indent_style = tab
indent_size = 4
```

OSX 10.11.6
Atom 1.10.2
linter-eslint 7.3.2
eslint 1.10.3
node 5.4.1
npm 3.3.12

**Comment by IanVS** [comment]
Can you please try updating to the latest version of eslint?  You are very far behind.  There was a bugfix in version `3.5.0` which should fix the error you're seeing.

Also, I think you may need to restart Atom.

**Comment by danielabar** [comment]
Updating eslint to 3.5.0 and restarting atom solved the problem. 
Thanks for your help and quick reply!
