### ISSUE TITLE
ESlint fix errors on save

### ISSUE THREAD

**Issue by manasmishra** [AtomLinter/linter-eslint#717]
I have applied the check box in settings that fix errors on save. Though it is showing basic errors as sting quoted not properly(i.e use single quote instead of double quote). This version is not able to fix these errors it would be great if this can be fixed.

**Comment by IanVS** [comment]
Hi @manasmishra, this plugin does not do the actual fixing, it is ESLint which does that.  The latest version of ESLint _does_ fix the quotes rule (http://eslint.org/docs/rules/quotes), so if you upgrade the version of ESLint in your project you should be good-to-go.  But, keep in mind that not all rules are fixable.  You can see on the [eslint docs](http://eslint.org/docs/rules/) which rules are fixable.
