### ISSUE TITLE
Does not work with v1.10.2

### ISSUE THREAD

**Issue by onury** [AtomLinter/linter-eslint#719]
Does not work with Atom v1.10.2

OS X 10.11.6
Node v4.4.7

**Comment by IanVS** [comment]
Thanks for the report. Can you give some more details?  In what way is it not working? What versions of this package and eslint are you using? Have you restarted atom lately? We need these details to start troubleshooting.

**Comment by onury** [comment]
I always update all my Atom packages.
I generally have my .eslintrc.json file in root of my projects.
Normally it would detect errors as I type. But it doesn't.
I'm using the latest current version of eslint v3.6.1 (global and local both installed).
I've restarted Atom before I post here. Didn't help.

**Comment by onury** [comment]
I think it's an Atom issue. Realized that version was showing `undefined` in package view. Re-installing the package solved the problem.
