### ISSUE TITLE
.eslintrc file in user home directory overrides package.json specific configuration

### ISSUE THREAD

**Issue by joonaspessi** [AtomLinter/linter-eslint#720]
Seems that existence of ~/.eslintrc will override configuration that is specified in package.json eslintConfig property. 

In my case linter-eslint tried to use ~/.eslintrc even though package.json existed within that directory including eslintConfig.extends with .eslintrc.js file

**Comment by ierhyna** [comment]
I've faced the same issue on Windows 10 today.

I have .eslintrc in C:\Users\<my_user> directory. It causes an error `Cannot find module 'eslint-plugin-react'` if there is no .eslintrc file in the project's directory. The checkbox "Disable when no ESLint config is found" is checked.

Removing the .eslintrc from user's fixed the issue.

**Comment by IanVS** [comment]
Are you finding these issues are unique to linting in atom, or does the eslint cli work the same way?  I suspect this is standard ESLint configuration cascade behavior.  Read http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy for more details.  

Please let us know if the behavior in `linter-eslint` is different from that when running eslint manually from the command line.

**Comment by ierhyna** [comment]
Hi @IanVS, I had no globally installed eslint package when found the issue. I've installed it and checked its behavior from cli, it's the same as linter-eslint. Got the same error.

**Comment by IanVS** [comment]
@ierhyna yep that's standard ESLint behavior.  From the link I posted:

>Note: If you have a personal configuration file in your home directory (~/.eslintrc), it will only be used if no other configuration files are found.

**Comment by ierhyna** [comment]
Ok thanks :) The only question I still have is why checking on the setting to "Disable when no ESLint config is found" without eslint installed globally causes the overriding.

**Comment by IanVS** [comment]
I'm not sure exactly what you mean.  Maybe you could open a new issue if you think this is a bug?

**Comment by ierhyna** [comment]
Oh, sorry, I get it now. linter-eslint uses .eslintrc from the user's folder, so there _is_ a config and the checkbox doesn't disables the linter. Thanks again.

**Comment by Arcanemagus** [comment]
Marking this as closed based on the discussion above, thanks for taking the time to report this though!
