### ISSUE TITLE
Configuration for rule "valid-typeof" is invalid

### ISSUE THREAD

**Issue by yamsellem** [AtomLinter/linter-eslint#726]
I'm getting the same error [as in](https://github.com/sindresorhus/eslint-config-xo/issues/33).
Maybe updating eslint dependency to 3.7.x will help?

ps. when using `eslint-config-google` 0.6.0

![error](https://cloud.githubusercontent.com/assets/606754/19154074/4c5835d8-8bd9-11e6-9f10-b8885a4cabeb.png)
![details](https://cloud.githubusercontent.com/assets/606754/19154077/503bb5e4-8bd9-11e6-92c0-c47256dcc2c3.png)

**Comment by Arcanemagus** [comment]
Are you sure that isn't from [`atom-linter-xo`](https://github.com/sindresorhus/atom-linter-xo)? This package doesn't generate messages like that.

**Comment by Arcanemagus** [comment]
Also, the embedded ESLint should virtually _never_ be used, it is only as a last resort fallback and is planned for removal at some point in the future. You can easily update the ESLint being used by installing ESLint 3.7.x locally in your project.

**Comment by CJBrew** [comment]
I seem to be getting this from gulp-eslint.

**Comment by Arcanemagus** [comment]
@CJBrew Please file a new issue and fill in the questions in the template. Please note that if you are seeing the _exact_ same message though then it has nothing to do with this package.

**Comment by CJBrew** [comment]
@Arcanemagus  I'm just adding a bit of information for anyone else that comes across this issue. The error I was seeing was unrelated, particularly since it wasn't occurring under Atom!

Although the error may be caused by the same dependency package, I fixed the problem by upgrading gulp-eslint  from 2.x to 3.x.
