### ISSUE TITLE
How to close top left alert Balloon？

### ISSUE THREAD

**Issue by EasonWang01** [AtomLinter/linter-eslint#728]
<img width="1280" alt="2016-10-07 1 15 53" src="https://cloud.githubusercontent.com/assets/11001914/19179551/3bbd39ea-8c91-11e6-924e-51bc841b8afb.png">

How to make it  not appear on screen even if Error?

thanks for reply.

**Comment by IanVS** [comment]
Update to eslint 3.5.0 or above.

**Comment by EasonWang01** [comment]
Don't works

**Comment by IanVS** [comment]
Hello @EasonWang01, can you please give some more details?  What version of eslint did you install?  Is it installed globally or locally?  What version of linter-eslint are you using?  Have you restarted atom?  Are you getting the _exact_ same errors, or slightly different ones?

Thanks!

**Comment by EasonWang01** [comment]
thanks it works
