### ISSUE TITLE
Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by backspaces** [AtomLinter/linter-eslint#749]
## Issue Type

Bug, dup of #580? As suggested there, I ran:
> cd ~/.atom/packages/linter-eslint/
> npm install

.. which worked fine, no errors.

## Issue Description

When opening files, either from sidebar or ^p for .js files I get:
Error: Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.getESLintInstance (/Users/owen/Dropbox/Atom/packages/linter-eslint/lib/worker-helpers.js:87:35)
    at /Users/owen/Dropbox/Atom/packages/linter-eslint/lib/worker.js:62:24
    at Emitter.emit (/Users/owen/Dropbox/Atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/owen/Dropbox/Atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /Users/owen/Dropbox/Atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/Users/owen/Dropbox/Atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/Users/owen/Dropbox/Atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.messageCallback (/Users/owen/Dropbox/Atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)

## Bug Checklist
- Restart Atom.
Yup. Also installed newest atom. I'm running latest Atom (1.12.2) using Sierra. I believe the update to Sierra is when the problem started.

Note: I'm using dropbox in this way: .atom points to dropbox for several files/dirs:
drwxr-xr-x@  5 owen  staff   170B Nov 11 16:52 blob-store/
drwxr-xr-x@ 40 owen  staff   1.3K Jun  6 15:44 compile-cache/
lrwxr-xr-x   1 owen  staff    36B Feb 25  2016 config.cson@ -> /Users/owen/Dropbox/Atom/config.cson
lrwxr-xr-x   1 owen  staff    36B Feb 25  2016 init.coffee@ -> /Users/owen/Dropbox/Atom/init.coffee
lrwxr-xr-x   1 owen  staff    36B Feb 25  2016 keymap.cson@ -> /Users/owen/Dropbox/Atom/keymap.cson
lrwxr-xr-x   1 owen  staff    33B Feb 25  2016 packages@ -> /Users/owen/Dropbox/Atom/packages
drwxr-xr-x   2 owen  staff    68B Nov  8 17:20 recovery/
lrwxr-xr-x   1 owen  staff    38B Feb 25  2016 snippets.cson@ -> /Users/owen/Dropbox/Atom/snippets.cson
drwxr-xr-x@ 23 owen  staff   782B Apr 11  2016 storage/
lrwxr-xr-x   1 owen  staff    36B Feb 25  2016 styles.less@ -> /Users/owen/Dropbox/Atom/styles.less

- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
If I understand correctly: 
cd to ~/.atom/packages/linter-eslint then run eslint:
gives the help output. 
Running linter-eslint: -bash: linter-eslint: command not found

- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below
```
Linter Eslint: Debug output here
```
Using shift-cmd-p and typing Linter, I do not see a Debug option.

**Comment by backspaces** [comment]
Damn! Didn't notice linter/eslint needed update. Fixed. Problem doesn't seem to exist now.

**Comment by hex13** [comment]
But still it is not good behavior to just crash instead of notifying user about need for update.

**Comment by Arcanemagus** [comment]
@hex13 Atom is the one displaying the error, not us. Also if the user ignores Atom's notifications of updates to packages, what more are we supposed to do that they aren't also going to ignore...? 😛

@backspaces glad you got it figured out!

**Comment by hex13** [comment]
I think If package throws error then it's package responsibility to handle it.

Atom displays red window because of exception in package, right?

For example this:
![image](https://cloud.githubusercontent.com/assets/3883359/20392845/e4670716-acd9-11e6-83e2-49e559b30cb4.png)

I don't think red window messages w/ exception should be normal interaction between package and user.

**Comment by backspaces** [comment]
Sublime must have the same issues. Any idea how they handle it?

**Comment by Arcanemagus** [comment]
@hex13, you are hitting an _entirely_ different issue: You have an ESLint configuration in your project, but don't have `eslint` installed in the project, so it is falling back to the bundled version (which obviously doesn't have `eslint-plugin-react`).

That is a fatal error, preventing things from working properly, why _shouldn't_ it be thrown as a fatal error? 😕

In any case, simply running `npm install` in the project you are working on should fix things, if not please file a new issue, especially including the output of the debug command as the issue template requests.
