### ISSUE TITLE
eslint error: Cannot mark location in editor causes annoying red error popup

### ISSUE THREAD

**Issue by backspaces** [AtomLinter/linter-eslint#750]
## Issue Type

Bug

## Issue Description

Atom: 1:12:2
linter: 1.11.18
linter-eslint: 8.0.0

Using linter-eslint, adding a newline at the end of an empty line (thus correctly noticing a style problem in Standard) causes a popup with:
```
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 1 blank line not allowed.) at line (17) column (2)
Error: Cannot mark location in editor for (no-multiple-empty-lines) - (More than 1 blank line not allowed.) at line (17) column (2)
    at /Users/owen/Dropbox/Atom/packages/linter-eslint/lib/main.js:227:21
    at Array.map (native)
    at /Users/owen/Dropbox/Atom/packages/linter-eslint/lib/main.js:192:27
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
The line number is correct but there is no column 2 .. it's a new empty line.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

Running in the project master, eslint gives the help messages, and linter-eslint is not found:
: linter-eslint
-bash: linter-eslint: command not found

```
Linter Eslint: Debug output here
```
Uncaught TypeError: Cannot read property 'getPath' of undefined
/Users/owen/Dropbox/Atom/packages/linter-eslint/lib/main.js:77
Hide Stack Trace
TypeError: Cannot read property 'getPath' of undefined
    at atom-text-editor.linterEslintDebug (/Users/owen/Dropbox/Atom/packages/linter-eslint/lib/main.js:77:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
The error was thrown from the linter-eslint package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the linter-eslint package

**Comment by IanVS** [comment]
Update your eslint to version 3.5.0 or above.

**Comment by backspaces** [comment]
https://atom.io/packages/linter-eslint sez that, apparently, eslint will be chosen this way:

> linter-eslint will look for a version of eslint local to your project and use it if it's available. If none is found it will fall back to the version it ships with.
Lets say you depend on a specific version of eslint, maybe it has unreleased features, maybe it's just newer than what linter-eslint ships with. If your-project/node_modules/eslint exists linter-eslint will be used. This package requires an eslint of at least v1.0.0.

I've got two atom eslint's I think:
ls ~/.atom/.apm/eslint
2.13.1	2.2.0
So apparently eslint itself is *not* up-to-date?

If I just do a global npm install, will it be used? Or do I have to install it in every repo I have? God I hope not!  How about using apm to install the latest npm eslint, is that possible?
https://www.npmjs.com/package/eslint

Sorry to be so noob but I thought Atom had finally gotten so things "just work". But I appreciate the difficulties of version management.

**Comment by IanVS** [comment]
ESLint is something you're probably going to want to add as a development dependency in each of the projects you work on.  There are a lot of benefits to this, mostly making sure that everyone who works on the project with you is using the same version.  So, that's ideal.

But, if for whatever reason you want to just keep ESLint installed globally, you can. `npm install -g eslint` is what you'll want.  There is a setting for linter-eslint to then use the global eslint.

Linter-eslint comes bundled with a version of ESLint, but it's best not to rely on it.

I'm going to close the issue, but if you're still having problems, please run `Linter Eslint: debug` from the command palette and paste the output here.

**Comment by backspaces** [comment]
Fine to close but I hope we get the more recent eslint into atom soon so this won't be necessary. 

Thanks a *lot* for the help!

**Comment by IanVS** [comment]
Actually if you were to remove `linter-eslint` and re-install it, you would get the latest version of ESLint, but again we don't recommend that you rely on that version.
