### ISSUE TITLE
Error: /Users/halln/git/real/comps/mweb-serp/package.json: Configuration for rule "comma-dangle" is invalid: Value "[object Object]" must be an enum value.

### ISSUE THREAD

**Issue by noahehall** [AtomLinter/linter-eslint#754]
![screen shot 2016-11-17 at 9 03 52 am](https://cloud.githubusercontent.com/assets/10324554/20399163/d5a943fe-aca4-11e6-9c3e-3e6adc56f0b5.png)

![screen shot 2016-11-17 at 9 04 50 am](https://cloud.githubusercontent.com/assets/10324554/20399195/ed487db8-aca4-11e6-8b66-d7e84acf8303.png)

**Comment by IanVS** [comment]
Can you please provide the output of `Linter Eslint: Debug`, as requested in the issue template?

**Comment by noahehall** [comment]
Here it is

<img width="475" alt="screen shot 2016-11-18 at 5 51 33 am" src="https://cloud.githubusercontent.com/assets/10324554/20432256/1d7db21a-ad53-11e6-96c1-bc7a9109932f.png">

**Comment by IanVS** [comment]
The style of configuration you are using for `comma-dangle` was introduced in eslint version `3.8.0`(http://eslint.org/blog/2016/10/eslint-v3.8.0-released), but you are using an older version `3.6.0`.  Upgrading eslint should solve this error for you.
