### ISSUE TITLE
resolve error: can't match module version or module paths

### ISSUE THREAD

**Issue by tiodan81** [AtomLinter/linter-eslint#758]
## Issue Type
Bug

## Issue Description
Atom reports `module version mismatch` at line 1 (which contains `// @flow`), cannot resolve paths to node modules or project modules except those in the project root directory, and reports `missing file extension` for project modules. Files in the project root report no errors. Eslint CLI reports no errors for any files. 
I also described this [here](https://github.com/AtomLinter/linter-eslint/issues/610#issuecomment-262310957)

Linter Eslint: Debug output:
```
Error: Path must be a string. Received undefined
```

**Comment by IanVS** [comment]
What version of atom are you using?

**Comment by tiodan81** [comment]
Using Atom 1.12.5
eslint 3.9.1
eslint-import-resolver-webpack 0.6.0
webpack 2.1.0
linter-eslint 8.0.0

**Comment by Arcanemagus** [comment]
Are you seeing any errors printed in Atom's developer console? Without the information the debug command provides it can be _very_ tricky to try to figure out what is going on here.

**Comment by tiodan81** [comment]
There are no errors in the atom dev console. `Error: Path must be a string. Received undefined` is the only output I get from linter-eslint debug

**Comment by IanVS** [comment]
Is your problem solved if you add an empty `.eslintignore` file at your project root, as suggested in https://github.com/AtomLinter/linter-eslint/issues/610 ?

**Comment by tiodan81** [comment]
nope. I already had a (non-empty) `.eslintignore` in the project root, but nothing changed when I tried removing it and replacing it with an empty file

**Comment by Arcanemagus** [comment]
Are you still hitting this problem @tiodan81? If so, can you provide an example project for us to reproduce and track this down with?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
