### ISSUE TITLE
linting of html files not working

### ISSUE THREAD

**Issue by haasDev** [AtomLinter/linter-eslint#760]
## Issue Type
Bug

## Issue Description
When I turn on linting in html files it says it cannot find module "eslint-plugin-html" here is my list of global installs

```
$ npm -g list --depth=0
C:\Program Files\nodejs
+-- babel-eslint@7.1.1
+-- bower@1.8.0
+-- eslint@3.11.1
+-- eslint-plugin-chai-expect@1.1.1
+-- eslint-plugin-html@1.7.0
+-- grunt-cli@1.2.0
+-- gulp@4.0.0-alpha.2 (git+https://github.com/gulpjs/gulp.git#e9e5ab7e70080e1bfb5650a4fdc4c8849e70b3e0)
+-- npm@3.10.8
+-- polymer-cli@0.17.0
+-- snyk@1.21.2
`-- yo@1.8.5
```

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

Do not have any option for Linter Eslint: Debug in command Palette

**Comment by Arcanemagus** [comment]
Can you please update your `linter-eslint` install? The debug command was added in v8.0.0.

**Comment by AlbertoFdzM** [comment]
Related: https://github.com/eslint/eslint/issues/1238

**Comment by AlbertoFdzM** [comment]
I fix this on my machine by check "Use global ESLint installation" and "Lint HTML Files" and then installing the needed npm packages globaly (`eslint` and `eslint-plugin-html`)

**Comment by IanVS** [comment]
Closing as per @AlbertoFdzM's comments.  Please let us know if you're still having problems, @haasDev.
