### ISSUE TITLE
no information in editor

### ISSUE THREAD

**Issue by brigand** [AtomLinter/linter-eslint#763]
I can run `./node_modules/.bin/eslint src` and it gives me the lint errors, but atom-eslint isn't showing anything in the editor.

Is there some other plugin I need to install? `apm install atom-lint` fails.

```
$ cat .eslintrc.yml
extends: airbnb
parser: babel-eslint
plugins:
  - import
  - jasmine

env:
  browser: true
  node: true
  jest: true
  jasmine: true

settings:
  import/parser: 'babel-eslint'
  ecmaFeatures:
    - classes
    - jsx

rules:
  object-curly-spacing: 0
  quotes: 0
  arrow-body-style: 0
  react/forbid-prop-types: 0
  react/jsx-filename-extension: 0

globals:
  React: true
  ReactDOM: true
  __DEV__: true
  __PROD__: true
  __USE_MOCKS__: true
  __API_BASE_MACRO__: true
  __IMAGES_URL_BASE__: true
```

**Comment by Arcanemagus** [comment]
Can you provide the results of running the `Linter Eslint: Debug` command as was requested in the issue template? Without that information this will be rather hard to diagnose.

_Note: This is the `linter-eslint` package, if you actually have `atom-eslint` installed I would highly recommend uninstalling it and installing `linter-eslint` instead as `atom-eslint` hasn't been touched in 3 years and is extremely unlikely to work with a current Atom + Linter install._

**Comment by brigand** [comment]
I don't see that command in cmd-shift-p.

```
$ apm ls | grep lint
├── linter@1.11.16
├── linter-eslint@8.0.0
```

Sorry about the issue template.

**Comment by Arcanemagus** [comment]
The list in the Command Palette is searchable, when you type "debug" it _should_ be showing:
![image](https://cloud.githubusercontent.com/assets/427137/20981538/fd12a492-bc69-11e6-9534-182955d5b0dd.png)

**Comment by brigand** [comment]
For some reason linter was disabled in my plugins. Sorry for wasting your time

**Comment by Arcanemagus** [comment]
No worries, glad it was something as simple as that!

**Comment by CharlesMangwa** [comment]
Hi guys! I do face the same issue, and I don't know where it comes from. Here is my debug output:

```
atom version: 1.12.6
linter-eslint version: 8.0.0
eslint version: 3.11.1
hours since last atom restart: 0.2
platform: darwin
Using local project eslint from /Users/Charles_MANGWA/Desktop/Rapsodie/node_modules/eslint
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by Arcanemagus** [comment]
@CharlesMangwa Can you file a new issue so we don't spam @brigand diagnosing this? Please include the code/repository you are working on if at all possible.

**Comment by CharlesMangwa** [comment]
Yeah my bad, I'm on it.
