### ISSUE TITLE
Per project eslint config path

### ISSUE THREAD

**Issue by evcohen** [AtomLinter/linter-eslint#764]
## Issue Type
Feature request

## Issue Description
Multiple projects I work in don't have the .eslintrc file at the top level (it's brought in by other packages). Think that you should be able to specify an config path per project instead of just one .eslintrc path that persists throughout all of your atom projects. would be happy to help!

**Comment by Arcanemagus** [comment]
We should be detecting _any_ form of valid configuration for ESLint, including ones in the `package.jscon` for your project, this package itself pulls in a configuration that is brought in by an `extends`. Can you describe the directory structure where this isn't working properly? Or even better a repository?

**Comment by IanVS** [comment]
@evcohen were you able to solve your problem?  If not, we will need the information that @Arcanemagus asked for before we can help any further.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems please provide the requested information!
