### ISSUE TITLE
Constant error notifications poping up in dev mode

### ISSUE THREAD

**Issue by abe33** [AtomLinter/linter-eslint#765]
## Issue Type
Bug

## Issue Description
When running Atom in dev mode in a package project, while there's no eslint config and the config to disable the linter in projects without config, it keeps raising exception while attempting to lint the ES6 code from Atom itself...

![Annoying!!](https://cloud.githubusercontent.com/assets/247140/21016063/8d9b1792-bd64-11e6-94f1-c2cdefdca9e1.jpg)

**Comment by Arcanemagus** [comment]
Does the Debug command run?

**Comment by joefitzgerald** [comment]
I am also experiencing this issue. The`debug` command doesn't seem to run.

```
[Linter-ESLint] STDERR /Users/joe/github/atom/exports/atom.js:3
import TextBuffer, {Point, Range} from 'text-buffer'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joe/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:133:13)
    at Module._compile (module.js:556:32)
```

**Comment by Arcanemagus** [comment]
From private chats:

- Both @abe33 and @joefitzgerald are on builds of Atom from its `master` branch
- Attempting to reproduce this on the released stable and beta builds yields no results on my machine

**Comment by abe33** [comment]
I've tried to investigate the issue this morning and I think the issues comes from the way you're forking the process to initiate your worker. 

In dev mode, when Atom is built from sources, atom will loads its own sources and compile them on the fly in `require` as with other packages so that we can work with the current sources without having to rebuild Atom. 

As you're forking the Atom process without relying on the `Task` class, the `require` method in the worker isn't patched to transpile files on the fly, resulting in these errors. 

This might get quickly critical as the Atom core team is moving to eslint from standard and most will want to have a working linter even when running atom in dev mode.

**Comment by Arcanemagus** [comment]
Ah, that makes a lot of sense. Fixing that is going to require splitting the `atom-linter` module up into the parts that actually require Atom, and the parts that are just plain Node code.

**Comment by abe33** [comment]
Hmm, can't you use a `Task` instead? It looks like it does pretty much the same thing as you're doing, forking the current process and then running a specific file (see https://atom.io/docs/api/v1.12.8/Task).

**Comment by Arcanemagus** [comment]
Actually, this should stay open till a version is published that includes it.

**Comment by Arcanemagus** [comment]
v8.1.2 should work just fine in this enironment!
