### ISSUE TITLE
ESLint isn't working in Atom workspace

### ISSUE THREAD

**Issue by CharlesMangwa** [AtomLinter/linter-eslint#766]
## Issue Type
**Bug**

## Issue Description

Linter-ESLint is installed and does display all the errors if I run `eslint .` in the terminal. However, it doesn't show anything in Atom's workspace. Here is [the code](https://github.com/CharlesMangwa/rapsodie) I'm working on. Thanks in advance!

## Linter Eslint: Debug

```
atom version: 1.12.6
linter-eslint version: 8.0.0
eslint version: 3.11.1
hours since last atom restart: 0.2
platform: darwin
Using local project eslint from /Users/Charles_MANGWA/Desktop/Rapsodie/node_modules/eslint
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by Arcanemagus** [comment]
The `master` branch should have been giving you an error popup in Atom saying it couldn't run ESLint, checking the console should have told you that it couldn't find the `eslint-plugin-flowtype` module. Running `npm install --save-dev eslint-plugin-flowtype` and restarting Atom has everything working properly for me!

Btw, please be careful which `eslint` you are running, `eslint .` from your CLI will use a _globally_ installed `eslint`, to properly run the one from your project you would need to run `./node_modules/.bin/eslint .`.

**Comment by CharlesMangwa** [comment]
Hi @Arcanemagus! Sorry for not being clear enough. I installed `eslint-plugin-flowtype`, run with the eslint installed in my node modules and it worked in the terminal. However, nothing in Atom itself 😕…

**Comment by Arcanemagus** [comment]
Did you restart Atom after installing the missing module? The worker process that runs ESLint only changes on a project change so restarting Atom is the simplest method of restarting that.

**Comment by CharlesMangwa** [comment]
I quit and re-open several times to be sure yeah.

**Comment by Arcanemagus** [comment]
Are you seeing any errors in the Developer Tools?

Is the `linter` package enabled?

**Comment by CharlesMangwa** [comment]
Ooh! `linter` wasn't enabled, I was so focused on `linter-eslint`I didn't even pay attention, I'm so sorry!…

**Comment by Arcanemagus** [comment]
Ah, that would do it, glad it was something so simple 😉.
