### ISSUE TITLE
Allow disabling of notifications

### ISSUE THREAD

**Issue by amandaporto** [AtomLinter/linter-eslint#772]
Feature Request: option to disable the popup messages that can greatly interrupt workflow for a user.

There are some errors that display inline, in the linter status bar, and as a huge red notification in Atom. I'd imagine that for most users (hint hint.. ), the notifications can become extremely distracting and bothersome, especially considering we already have red dots, red underlines, and errors in the status bar for that same issue. There should be a way to disable notifications altogether.

**Comment by IanVS** [comment]
Those notifications are for critical errors that are causing the linter to not work correctly or at all, not for linting problems.  If you hide those boxes, you won't know if linting is successful or the plugin is broken.

If you are seeing red boxes, please search the issues to see if it has been reported before, and if not, it would help us a lot if you submit a new issue.

**Comment by Arcanemagus** [comment]
I'm guessing that a lot of the source of this are the messages about invalid points from broken rules and/or old ESLint versions, which should be handled by #761. This is now released in v8.1.0.

The rest of the messages are critical issues, with the possible exception of the message type being discussed in #739.

I'm going to close this issue, but if you have an example other than the types handled above that you think should be hidden/handled better please let us know!
