### ISSUE TITLE
Doesn't seem to detect multiple .eslintrc.js files in subdirectories

### ISSUE THREAD

**Issue by jorions** [AtomLinter/linter-eslint#776]
## Issue Type
Bug

## Issue Description
I have an .eslintrc.js file in my root directory, and one in my /test directory with less strict rules. The rules listed in the /test folder are not being applied - the rules from the root file are being applied instead. The CLI finds no errors while this package does.

```
atom version: 1.12.7
linter-eslint version: 8.0.0
eslint version: 3.12.2
hours since last atom restart: 19.7
platform: darwin
Using local project eslint from /Users/jared/Desktop/Moove-it/Apprenticeship/kaigi/kaigi-api/node_modules/eslint
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by IanVS** [comment]
Odd.  Could you verify that restarting Atom does not solve the problem, and if not, is there any chance you can share an example repo or set of files which exhibits the behavior?

**Comment by jorions** [comment]
That did it! I probably should have tried that first given that it is in your troubleshooting instructions... Thanks so much.
