### ISSUE TITLE
[Help]Can not find global eslint installed with yarn

### ISSUE THREAD

**Issue by linkdesu** [AtomLinter/linter-eslint#780]
Yarn install eslint in `~/.config/yarn/global/node_modules/.bin/eslint` and create a soft link at `/usr/local/Cellar/node/7.2.1/bin/eslint`. My $PATH contains `/usr/local/Cellar/node/7.2.1/bin`, so I'm sure can execute eslint from anywhere and I've checked the config `Use global ESLint installation`. 

But unfortunately, linter-eslint keep alert `Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly`.

Did I still miss something important?

**Comment by IanVS** [comment]
Can you please provide the output of the debug command as requested in the
issue template?

On Tue, Jan 10, 2017, 23:26 Aolin Xie <notifications@github.com> wrote:

Yarn install eslint in ~/.config/yarn/global/node_modules/.bin/eslint and
create a soft link at /usr/local/Cellar/node/7.2.1/bin/eslint. My $PATH
contains /usr/local/Cellar/node/7.2.1/bin, so I'm sure can execute eslint
from anywhere and I've checked the config Use global ESLint installation.

But unfortunately, linter-eslint keep alert Error: ESLint not found, Please
install or make sure Atom is getting $PATH correctly.

Did I still miss something important?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AtomLinter/linter-eslint/issues/780>, or mute the thread

**Comment by linkdesu** [comment]
Which debug command? Do you mean this:

```
Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
    at findESLintDirectory (/Users/linkdesu/.atom/packages/linter-eslint/lib/worker-helpers.js:90:13)
    at getESLintFromDirectory (/Users/linkdesu/.atom/packages/linter-eslint/lib/worker-helpers.js:100:30)
    at Object.getESLintInstance (/Users/linkdesu/.atom/packages/linter-eslint/lib/worker-helpers.js:127:10)
    at /Users/linkdesu/.atom/packages/linter-eslint/lib/worker.js:68:24
    at Emitter.emit (/Users/linkdesu/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/linkdesu/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:22:23
    at /Users/linkdesu/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/Users/linkdesu/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/Users/linkdesu/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:63:18)
    at process.messageCallback (/Users/linkdesu/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```

**Comment by linkdesu** [comment]
Well, I can not find a way to take breakpoint in linter-eslint package, so I add some `console.log` temporarily:

```
...
function findESLintDirectory(modulesDir, config, projectPath) {
  console.log(arguments)
  var eslintDir = null;
  var locationType = null;
  if (config.useGlobalEslint) {
    locationType = 'global';
    var prefixPath = config.globalNodePath || getNodePrefixPath();
    if (process.platform === 'win32') {
      eslintDir = _path2.default.join(prefixPath, 'node_modules', 'eslint');
    } else {
      eslintDir = _path2.default.join(prefixPath, 'lib', 'node_modules', 'eslint');
    }
  } else if (!config.advancedLocalNodeModules) {
    locationType = 'local project';
    eslintDir = _path2.default.join(modulesDir || '', 'eslint');
  } else if (_path2.default.isAbsolute(config.advancedLocalNodeModules)) {
    locationType = 'advanced specified';
    eslintDir = _path2.default.join(config.advancedLocalNodeModules || '', 'eslint');
  } else {
    locationType = 'advanced specified';
    eslintDir = _path2.default.join(projectPath, config.advancedLocalNodeModules, 'eslint');
  }
  console.log(eslintDir, locationType)
...
```

Then I get this output:
```
helpers.js:38 [Linter-ESLint] STDOUT { '0': '/Users/linkdesu/www/yf_learnx_teacher_web/node_modules',
  '1': 
   { useGlobalEslint: true,
     lintHtmlFiles: false,
     showRuleIdInMessage: true,
     disableWhenNoEslintConfig: true,
     eslintrcPath: '',
     globalNodePath: '',
     advancedLocalNodeModules: '',
     eslintRulesDir: '',
     disableEslintIgnore: false,
     disableFSCache: false,
     fixOnSave: false,
     scopes: 
      [ 'source.js',
        'source.jsx',
        'source.js.jsx',
        'source.babel',
        'source.js-semantic' ],
     rulesToSilenceWhileTyping: [] },
  '2': '/Users/linkdesu/www/yf_learnx_teacher_web' }

helpers.js:38 [Linter-ESLint] STDOUT /usr/local/lib/node_modules/eslint global
```

I think the answer is clear, we need a config option to specific the exact path to eslint, for example: `/Users/linkdesu/.config/yarn/global/node_modules/.bin/eslint`

**Comment by IanVS** [comment]
Have you tried adding `/usr/local/Cellar/node/7.2.1` to your `Global Node Installation Path` setting?

**Comment by linkdesu** [comment]
I have tried, but it not works.

I think the problem comes from this line: `eslintDir = _path2.default.join(prefixPath, 'lib', 'node_modules', 'eslint');`. If I config `/usr/local/Cellar/node/7.2.1` as `Global Node Installation Path`, the `eslintDir` will be `/usr/local/Cellar/node/7.2.1/lib/node_modules`, but yarn install eslint in `~/.config/yarn/global/node_modules/.bin/eslint` globally.

**Comment by metakermit** [comment]
Yeah, affects me too. I tried [this](https://github.com/atom/atom/issues/1614) `env open` suggestion, but it didn't help.

A temporary solution is to disable the use global eslint option as mentioned in https://github.com/AtomLinter/linter-eslint/issues/261 , but this is contrary to the create-react-app suggestion (I assume the warnings/errors wouldn't be in sync with their in-browser warnings/errors).

**Comment by IanVS** [comment]
I confirmed it's a bug.  I don't know when we'll have time to work on it, so PRs will gladly be accepted in the meantime.

**Comment by linkdesu** [comment]
THX, I will give a try!

**Comment by publicarray** [comment]
@linkdesu Any progress?

**Comment by tkallioras** [comment]
I am facing the same issue here with eslint

**Comment by Shyam-Chen** [comment]
```js
Error running ESLint Error: Cannot read config file
```

**Comment by Arcanemagus** [comment]
@linkdesu You would need to find where `yarn` is installing the actual code for ESLint, not the CLI binary. Setting the path to that in the settings should work, assuming `yarn` hasn't screwed up yet another aspect of package installation.

For example on my system `yarn global add eslint` installs the "binary" to `C:\Users\Landon Abney\AppData\Local\Yarn\bin\eslint.cmd`, but the actual code for ESLint is stored in `C:\Users\Landon Abney\AppData\Local\Yarn\config\global\node_modules\eslint`. So if I were to use Yarn for package management, and wanted to use a global ESLint installation, I would need to set the "Global Node Installation Path" setting to `C:\Users\Landon Abney\AppData\Local\Yarn\config\global` and then the package would work as is.

To find where Yarn is actually installing the code on your system you'll need to check the contents of `which eslint` to see what script it is calling, then find where _that_ script is calling the actual code from.

I'm removing `bug` and putting `Question` on here as there are no changes required in this package to get this working.

_Note: If you were using older versions of Yarn it seems they had decided to prefix all package paths with `npm_`, meaning the code lived in a `npm_eslint` instead of an `eslint` folder. Luckily it seems in later versions they have abandoned that terrible idea, **but** if you had things configured in one of those older versions they didn't migrate the old setup over and instead keep using it. To fix this it seems you need to delete your entire Yarn folder and start over._

**Comment by bennypowers** [comment]
```bash
which eslint
/Users/bennyp/.config/yarn/global/node_modules/.bin/eslint
```
Global Node Installation Path: /Users/bennyp/.config/yarn/global/

```
[Linter] Error running ESLint Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly
```

Maybe I missed something?

**Comment by Arcanemagus** [comment]
The result of `which eslint` has almost nothing to do with the path you need to enter there.

The script located at `/Users/bennyp/.config/yarn/global/node_modules/.bin/eslint` is most likely a script that simply calls the `eslint` script created by the `eslint` package, you need to find where _this_ script is located, and find the proper `node_modules` folder from there.

**Comment by bennypowers** [comment]
cat (which eslint) outputs the contents of https://github.com/eslint/eslint/blob/master/bin/eslint.js

logging `__dirname` inside `eslint/lib/cli.js` while running eslint from cli prints
```
/Users/bennyp/.config/yarn/global/node_modules/eslint/lib/cli.js
```
Haven't figured out yet which other eslint bin is getting run.

**Comment by bennypowers** [comment]
hacky solution:
Users/bennyp/.config/yarn/global/node_modules/.bin

**Comment by Arcanemagus** [comment]
Hmmm, if that's the case then `/Users/bennyp/.config/yarn/global/` _should_ be working just fine if you set that in the settings properly, but you reported earlier that it wasn't.

Can you post the output of the `Linter Eslint: Debug` command?

_Note: Interestingly, apparently `yarn` works a lot saner on your platform, on Windows for some reason it creates it's own wrapper script that calls the wrapper script included with the package (which then calls the actual code)._

**Comment by bennypowers** [comment]
hacky solution:
```js
//~/.atom/packages/linter-eslint/lib/worker-helpers.js:69

      eslintDir = _path2.default.join(prefixPath, 'node_modules', '.bin', '..', 'eslint');

```

**Comment by Arcanemagus** [comment]
Ah ha, sorry, I was mistaken above: It looks like Yarn is breaking with the standard set with NPM and doesn't include the `lib` folder in the path on non-Windows platforms.

@bennypowers your "hacky solution" is the exact same as the `process.platform === 'win32'` code path.

**Comment by Arcanemagus** [comment]
Fix released in v8.2.0 🎉.

**Comment by esd100** [comment]
@Arcanemagus Really, because I'm still having errors saying it can't find eslint.

**Comment by aarongeorge** [comment]
@esd100 actually Atom doesn't respect the $HOME variable, I had to manually set the path to /Users/myusername/.config/yarn/global

**Comment by mickyginger** [comment]
I have this error with v8.2.1 on a fresh install of Atom on macOS Sierra 10.12.6

```
[Linter] Error running ESLint Error: ESLint not found, please ensure the global Node path is set correctly.
```

eslint is installed globally with yarn

```
ls -l ~/.config/yarn/global/node_modules | grep eslint
drwxr-xr-x   11 mickyginger  staff    374 12 Aug 20:25 eslint
drwxr-xr-x    9 mickyginger  staff    306 12 Aug 21:11 eslint-plugin-react
drwxr-xr-x    7 mickyginger  staff    238 12 Aug 20:25 eslint-scope
```

Global Node Installation Path is set to:

```
~/.config/yarn/global
```

I have Use global Eslint installation checked

I also see this in Atom's console:

```
Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined
    at Object.<anonymous> (/Users/mickyginger/.atom/packages/linter-eslint/helpers.js:138:22)
    at Generator.next (<anonymous>)
    at step (/Users/mickyginger/.atom/packages/linter-eslint/helpers.js:9:1)
    at /Users/mickyginger/.atom/packages/linter-eslint/helpers.js:9:1
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Atom v1.19.0
Yarn v0.27.5
Eslint v4.4.1
Linter-Eslint v8.2.1

Any ideas?

**Comment by mickyginger** [comment]
Ok, finally got to the bottom of it

```
~/.config/yarn/global
```

Needs to be 

```
/Users/yourusername/.config/yarn/global
```

Which is a little odd since the eslintrc location can be `~/.eslintrc`
