### ISSUE TITLE
Defer lint on current line

### ISSUE THREAD

**Issue by kevinnguy** [AtomLinter/linter-eslint#782]
## Issue Type
Feature Request

## Issue Description
I was wondering if it's possible to implement an option to defer linting on the current line. From https://github.com/steelbrain/linter/issues/749

**Comment by Arcanemagus** [comment]
I'm going to close this as `WONTFIX` here.

While you are typing in a document `linter-ui-default` no longer shows a tooltip while you are in the middle of typing, the only indication there is anything wrong on the current line would be the underlines.
