### ISSUE TITLE
Config from package.json not works properly

### ISSUE THREAD

**Issue by tunnckoCore** [AtomLinter/linter-eslint#786]
## Issue Type

Bug / Question

## Issue Description

Notice that it not works and even not shows any errors. So, maybe, it should be implemented to get config from `eslintConfig` property in local package.json.

***

edit: Hm. It seems it has such thing, it not works correctly?
Or I should write something in `.eslintrc Path` option? which says:

> It will only be used when there's no config file in project

so... hm, don't know, i don't want to set full filepath to some global config. (just setting it to `package.json` doesn't work )

**Comment by IanVS** [comment]
By default, `linter-eslint` should already be locating the `eslintConfig` section of your `package.json`.  Can you please provide the output of `Linter Eslint: Debug` as requested in the issue template?

**Comment by tunnckoCore** [comment]
Sorry, didn't see need because it is with defaults.

````
atom version: 1.12.9
linter-eslint version: 8.0.0
eslint version: 3.13.1
hours since last atom restart: 4.8
platform: linux
Using bundled fallback eslint from /home/charlike/.atom/packages/linter-eslint/node_modules/eslint
linter-eslint configuration: {
  "fixOnSave": true,
  "globalNodePath": "/home/charlike/.nvm/versions/node/v7.3.0",
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic",
    "source.md",
    "source.markdown"
  ],
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "rulesToSilenceWhileTyping": []
}
```

**Comment by tunnckoCore** [comment]
Sorry, it seems it works today. ;/
