### ISSUE TITLE
extends feature doesn't resolve module in local node_modules

### ISSUE THREAD

**Issue by LaurentGoderre** [AtomLinter/linter-eslint#787]
## Issue Type
Bug

## Issue Description
`extends` feature doesn't seem to look in local node_modules. I have 

```json
{ "extends": "jquery", ...}
```

eslint-config-jquery is in my node_modules but it doesn't get loaded by the module. This is similar to https://github.com/eslint/eslint/issues/3782

```
Error: Cannot find module 'eslint-config-jquery' Referenced from: /home/laurentgoderre/git/wet-boew/wet-boew/.eslintrc.json
Error: Cannot find module 'eslint-config-jquery'
Referenced from: /home/laurentgoderre/git/wet-boew/wet-boew/.eslintrc.json
    at Object.resolve (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:478:33)
    at load (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:495:26)
    at /home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:63:33)
    at new Config (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:226:38)
    at CLIEngine.executeOnText (/home/laurentgoderre/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:743:28)
```

**Comment by IanVS** [comment]
Can you please share the output of running the `Linter Eslint: Debug` command?

**Comment by LaurentGoderre** [comment]
I get  `Error: Path must be a string. Received undefined` so this might be related to #784

**Comment by IanVS** [comment]
Hm, yeah could be.

Could you try removing that  `extends` from your config, and if you stop getting the errors, try the debug command again? (You may need to restart atom)

**Comment by LaurentGoderre** [comment]
I don't get the first error but I get the second one again

**Comment by IanVS** [comment]
OK, well I'll have to look into that, but I have a suspicion that the eslint binary that `linter-eslint` is using is not the one that's installed locally in your node_modules.  Do you have the `use global` setting checked?  Have you confirmed that `eslint` is also currently installed locally in your project?

(the debug command tells us exactly which eslint the plugin is trying to use, which is why I was asking for its output).

**Comment by LaurentGoderre** [comment]
I am using docker for all my node stuff so I don't have node or eslint installed globally. The eslint in my project is the one used by `grunt-eslint`

**Comment by LaurentGoderre** [comment]
Though I am wondering if the different install behavior in node 4 vs node 6 could account for that since in node 4, eslint would be nested in grunt-eslint but in node 6 everything is flat

**Comment by IanVS** [comment]
Ah, so it sounds like you don't have `eslint` in your dev dependencies?  What version of npm are you using?

Try adding `eslint` as a direct dev dependency.

**Comment by LaurentGoderre** [comment]
Yeah, when they are installed side by side it work but if they are not sibling folders it doesn't. It's really unfortunate but maybe it isn't worth fixing this since 6 is in LTS and by default fixes it. It's too bad we are stuck on node 4 for now.

**Comment by IanVS** [comment]
It's actually not due to node, it's due to `npm`.  As long as you install a version of npm that's >= 3, you _could_ avoid adding ESLint as a direct dependency, and rely on npm to flatten it out.

**Comment by LaurentGoderre** [comment]
aaah yes! Ok, i'll close
