### ISSUE TITLE
Cant see errors in editor only fix my file

### ISSUE THREAD

**Issue by billybonks** [AtomLinter/linter-eslint#789]
## Issue Type
Question

## Issue Description
Errors are not displayed in editor ?

## Bug Checklist
```
/Users/billybonks/project/client/app/routes/repo.js
   1:8   error  'Ember' is defined but never used  no-unused-vars
  10:64  error  Missing semicolon                  semi
  13:69  error  Missing semicolon                  semi

```

this is all i see 
![image](https://cloud.githubusercontent.com/assets/1640136/22182884/5d498416-e0eb-11e6-99c0-d51c697a156a.png)

an error should be displayed. i guess i am missing a base package ? tried to find it but couldn't
![image](https://cloud.githubusercontent.com/assets/1640136/22182889/6d7e673e-e0eb-11e6-83b1-901cecbcb360.png)

**Comment by IanVS** [comment]
Have you installed https://github.com/steelbrain/linter? Did you follow the questions in the template?

**Comment by billybonks** [comment]
it was disabled thanks 👍
