### ISSUE TITLE
request: apply the findFile algorithm to eslint itself

### ISSUE THREAD

**Issue by ide** [AtomLinter/linter-eslint#79]
I have a repo that contains multiple projects and want to configure eslint the same way for all of them. The simplest way I've found is to create .eslintrc and .eslintignore in my repo root, which linter-eslint discovers, but it doesn't seem to find find node_modules/eslint itself when I open a project subdir in Atom instead of the repo root.
```
.
├── project1          # open "atom repo_root/project1"
│   └── node_modules  # no eslint
├── .eslintrc
├── .eslintignore
└── node_modules
    └── eslint
```

Keeping the .eslintrc file and eslint package together also helps avoids version mismatches between the two.

Does this make sense? Is there perhaps a technical limitation where linter-eslint can load only one copy of eslint so it has to use only the directory that was opened in Atom (cwd)?

**Comment by iam4x** [comment]
Please install `eslint` globally with `npm i -g eslint` and use `Use Global Eslint` package option.
