### ISSUE TITLE
[Enhancement] Specify rules not to fix on save

### ISSUE THREAD

**Issue by IanVS** [AtomLinter/linter-eslint#791]
## Issue Type
Feature Request 

## Issue Description
I have a project which enforces the rule [`capitalized-comments`](http://eslint.org/docs/rules/capitalized-comments).  ESLint can auto-fix this rule, which is great…sometimes.  When I am working, I will occationally comment out a block of code, but since I use the `Fix on save` option, eslint capitalizes the code, which of course I don't want.

I propose a setting similar to the `rulesToSilenceWhileTyping` option, which will disable specified rules during `fix` jobs.

**Comment by Arcanemagus** [comment]
Is this even possible currently? Right now we are simply calling `eslint /path/to/file --fix` and have no control over the process.

**Comment by IanVS** [comment]
I _think_ we can pass a [`--rule`](http://eslint.org/docs/user-guide/command-line-interface#rule) like `--rule capitalized-comments: 0`

**Comment by wKich** [comment]
Yeah, it would be cool.

**Comment by not-an-aardvark** [comment]
:+1:

Related: https://github.com/eslint/eslint/issues/7955
