### ISSUE TITLE
How to install and enable airbnb eslint config?

### ISSUE THREAD

**Issue by maasha** [AtomLinter/linter-eslint#792]
The title says it all. There is patchy information on the internet, but I would appreciate a step-by-step guide.

**Comment by IanVS** [comment]
Sorry, but this has nothing to do with linter-eslint.  Your best bet is to follow the instructions at https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb.  You can also ask on the ESLint [gitter chat](https://gitter.im/eslint/eslint) if you get stuck.
