### ISSUE TITLE
Add include/exclude globs for format on save

### ISSUE THREAD

**Issue by kentcdodds** [AtomLinter/linter-eslint#805]
## Issue Type

Feature Request

## Issue Description

I have some projects where I'd like to make sure formatting on save happens and others where I don't (because I use a different formatter on those other projects). I'd like to have the option to specify a comma separated list of globs to specify whether the formatting should happen.

If the `include` array of globs is empty, then assume `**`. If there's a conflict between include and exclude, I think that `exclude` should win.

This would be really nice.

**Comment by IanVS** [comment]
Hmm, for project-specific settings, have you tried using [project-manager](https://atom.io/packages/project-manager)?  I think that would be a much more flexible and robust solution (if it meets your needs).

**Comment by kentcdodds** [comment]
That'll probably work, thanks!
