### ISSUE TITLE
Linter not Linting

### ISSUE THREAD

**Issue by patrickml** [AtomLinter/linter-eslint#806]
## Issue Type
Bug

## Issue Description
The other day atom completely broke down on my computer and wouldn't open. So i wiped the atom cson file which seemed to fix it. After that I noticed that the linter wasn't working. I went on for a few days not caring too much and decided to fix it when i could. Well... i've spent countless hours trying to fix it. I've wiped the entire atom folder and re-install atom only some basic plugins lint the linter and eslint.

I am still having the same issue as before. I've tried coping working cson files from other machines for the linter and eslint, but nothing has worked. What is odd is the "autofix" seems to still fix things, but no errors ever show.

eslint from the cli works just fine

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.13.1
linter-eslint version: 8.1.0
ESLint version: 3.5.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from /Users/patricklewis/Documents/sites/uTu/console/node_modules/eslint
linter-eslint configuration: {
  "fixOnSave": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by patrickml** [comment]
I seem to be getting an error in the developer console https://cl.ly/1m2S0u1T031H

**Comment by Arcanemagus** [comment]
Are you using `eslint-import-resolver-webpack`? Your error makes this look like a duplicate of #796.

**Comment by patrickml** [comment]
Issue was caused by web pack config containing a `const` same issue as https://github.com/AtomLinter/linter-eslint/issues/796#issuecomment-277797863

**Comment by nelson6e65** [comment]
After update to Atom 1.28.0 it was not working for *.js files. So, I had to add `'javascript`' to the `scopes` config. Now is working.

**Comment by skylize** [comment]
Thanks for letting us know @nelson.

But please try to avoid spamming unrelated topics. Instead,  if you cannot find your problem being discussed already, just open a new Issue.

The need to add `javascript` to the scopes if using the new Tree Sitter parser was documented in #1076, among other places. It has already been fixed in `master` branch, waiting for a release.

The suggested workaround for now is to add it yourself to the list as you have done. Alternatively, you can disable Tree Sitter, and use the older grammar parser.
