### ISSUE TITLE
Does not support autofixing markdown files?

### ISSUE THREAD

**Issue by tunnckoCore** [AtomLinter/linter-eslint#815]
## Issue Type

Bug / Question

## Issue Description

ref https://github.com/AtomLinter/linter-eslint/issues/779#issuecomment-279207475

Using `standard` and its needed peer deps

```
% ❯ npm ls | grep eslint                                                                               February 12, 12:34:53
├── eslint@3.15.0
├── eslint-config-standard@6.2.1
├── eslint-plugin-markdown@1.0.0-beta.3
├── eslint-plugin-promise@3.4.1
├── eslint-plugin-standard@2.0.1
```

Configured that Linter ESLint to accept `source.gfm`. Everything is okey, it alarms me the errors, but it seems that can't autofix them?

Is that a bug, or it is impossible?

## Bug Checklist

`atom --version`

```
% ❯ atom-beta --version                                                                            February 12, 12:46:58
Atom    : 1.14.0-beta2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

```

- Restart Atom - yes

eslintConfig in package.json

```json
  "eslintConfig": {
    "extends": ["standard"],
    "plugins": ["markdown"],
    "rules": {
      "semi": [
        2,
        "always"
      ],
      "no-extra-semi": 2
    }
  }
```

debug output 

```
Atom version: 1.14.0-beta2
linter-eslint version: 8.1.0
ESLint version: 3.15.0
Hours since last Atom restart: 0
Platform: linux
Using local project ESLint from /home/charlike/hub/randomorg-js/node_modules/eslint
linter-eslint configuration: {
  "fixOnSave": true,
  "globalNodePath": "/home/charlike/.nvm/versions/node/v7.3.0",
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic",
    "source.gfm",
    "source.md",
    "source.markdown"
  ],
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
Please update to `linter-eslint@8.1.1`, this _should_ be fixed by #811 which was included in that release.

**Comment by tunnckoCore** [comment]
Cool, I seen that i had some updates available, but didn't tried to do that first. :)

**Comment by tunnckoCore** [comment]
Nope. Seems to not work. Updated everything.

**Comment by IanVS** [comment]
Are you sure that your cursor is within the JavaScript tags when you try to save/fix?

**Comment by tunnckoCore** [comment]
Yep? What you mean with `Javascript tags`?

![2017-02-12-23 18 30_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/22866104/3eafb31a-f179-11e6-8370-281808dc7ad0.png)

the config is such, that i expect to insert semicolons on save, it is working on `.js` files.

![2017-02-12-23 21 14_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/22866123/8d58567a-f179-11e6-886a-4afa67d32c31.png)

**Comment by IanVS** [comment]
Yes, I meant within the JS fences.  

Does this work on the CLI, by the way?  (running `eslint <yourfile> --fix`)

**Comment by tunnckoCore** [comment]
@IanVS nope, still fails. Seems to not work

```
eslint --fix --ext md README.md
eslint --fix --ext md .
eslint --fix -c .eslintrc --ext md README.md
```

eslint `v3.15.0`

**Comment by IanVS** [comment]
OK, seems like it's not a `linter-eslint` issue then, and instead is a limitation of eslint-plugin-markdown.  I'd suggest opening an issue there to explore if it's possible to do.
