### ISSUE TITLE
Set custom node_modules directory on a per project basis

### ISSUE THREAD

**Issue by joerodrig** [AtomLinter/linter-eslint#816]
## Issue Type
Question

## Issue Description
I currently have a Rails/Node app structured in such a way that my `eslintrc.js` file is in the root directory, but my `node_modules` folder isn't in the same directory.

Example:
```
/app
  /assets
    /javascript
/vendor
  /node_modules
.eslintrc.js
```

To be able to read my eslint plugins correctly(ie React), I have to use the [advancedLocalNodeModules](https://github.com/AtomLinter/linter-eslint/blob/60b181bdb44d82129471f702c56424d26bd2e1a6/package.json#L46) setting for ESLint.

I'm able to get it working by setting the field to `./vendor/node_modules`. Unfortunately, I work on several other projects in Node that have a different folder structure, so I have to manually change that setting back when I work on those projects.

Is there a way to set that configuration in a file on a per project basis? Or would that have to be set manually depending on the type of project I'm working on?

**Comment by IanVS** [comment]
Have you tried https://atom.io/packages/project-manager?

**Comment by joerodrig** [comment]
@IanVS Thank you for that! :) I didn't know that package existed.

For anyone else having this issue, I was able to get this working by using the project-manager package referenced above

Here are the steps I took for anyone having a similar issue:
- Install  https://atom.io/packages/project-manager
- Open your project in atom and hit `CMD + SHIFT + P` and type `save project`. An item called `Project Manager: Save Project` should come up
- Save your project
- Open your projects.cson at `~/.atom/projects.cson` and you should see your saved project.
- Update the settings so it contains the custom node modules directory:
```coffeescript
[
  {
    title: "example-project"
    paths: [
      "/Users/joe/Documents/example-project"
    ]
    settings:
      "linter-eslint.advancedLocalNodeModules": "./vendor/node_modules"
    devMode: true
  }
]
```
