### ISSUE TITLE
Support for Vue plugin

### ISSUE THREAD

**Issue by dhershman1** [AtomLinter/linter-eslint#820]
## Issue Type
Feature Request

## Issue Description

The linter doesn't seem to support the vue plugin for eslint, I don't get any notifications about linting errors/warnings in my editor but when I run my build process I do seem to get back linter issues as expected.

## Bug Checklist
- Tried adding `source.vue` to the list of scopes to run ESLint on.

Verified that CLI does pick up the issue while linter does not:
![CLI Working](http://i.imgur.com/VOPbM7z.png)
![Atom Linter Not Working](http://i.imgur.com/Qt1tra7.png)

## Debug

```
Atom version: 1.14.2
linter-eslint version: 8.1.2
ESLint version: 3.15.0
Hours since last Atom restart: 0
Platform: win32
Using local project ESLint from C:\Users\dhers\Desktop\Development\Work\rtfrontline\node_modules\eslint
linter-eslint configuration: {
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic",
    "source.vue"
  ],
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
Can you please post the output of the `Linter Eslint: Debug` command as requested in the template?

**Comment by dhershman1** [comment]
Attached.

**Comment by Arcanemagus** [comment]
Hmmm, it's definitely using the ESLint installation from your project, so I'm not entirely sure what is going on here. Are you able to create a minimal reproduction and upload it? (zip file directly here, gist, ...)

**Comment by dhershman1** [comment]
[sample.zip](https://github.com/AtomLinter/linter-eslint/files/779940/sample.zip)

Here is a simple reproduction, unzip the file run `npm i` inside sample. and then run `npm run lint` you should see the eslint error and then npm will throw an error (Since eslint errored)

**Comment by Arcanemagus** [comment]
Looks like this is actually an incredibly easy fix: Just enable the "Lint HTML Files" option 😛

It turns out that `language-vue` marks embedded JS with the scope `source.js.embedded.html`, which we already have an option available that adds that to the list of allowed scopes. You can ignore the part in the description of the option about `eslint-plugin-html` as that's just the most common use of that setting.

**Comment by dhershman1** [comment]
Awesome thank you so much I guess I just never thought to try that setting.

**Comment by jpickwell** [comment]
I had "Lint HTML Files" enabled, but `*.vue` files were not being linted. I had to add `text.html.vue` to the list of scopes in the "linter-eslint" settings, and restart Atom. `text.html.vue` is the scope of the entire file, not just the `<script>` element.
