### ISSUE TITLE
Configuration file path is not relative to project root directory

### ISSUE THREAD

**Issue by Deseteral** [AtomLinter/linter-eslint#822]
The `.eslintrc path` setting is relative to the path of the file open in current text buffer - which seems like a weird feature to have (and use).

Wouldn't it be better for `.eslintrc path` to be relative to project root?
Is there a way to set this path relatively to project root directory?

Not everyone has their `.eslintrc` file in root directory, often times it's somewhere in tests directory for example. Users should be able to use this config no matter where this file is located in project directory structure.

**Comment by Arcanemagus** [comment]
As far as I can tell that is the behaviour [documented](http://eslint.org/docs/user-guide/configuring#using-a-configuration-file) for ESLint itself. Are you seeing _different_ behaviour between `eslint` on the CLI, and `linter-eslint` in Atom?

**Comment by Deseteral** [comment]
No I don't see any different behaviour between `eslint` CLI and `linter-eslint`. After reading through that documentation I understand why it works that way.

The way I dealt with the problem of using one `.eslintrc` in my project was to specify the path to config in the `package.json`:

```json
"eslintConfig": {
  "extends": "./path/to/.eslintrc/relative/to/packagejson"
},
```

Although, while I don't see _different_ behaviour I think I can see _missing_ behaviour between linter and CLI. [In this section of documentation](http://eslint.org/docs/user-guide/configuring#using-configuration-files) there are two ways of using config files:

1. Using `-c` option with path to the config file
2. Via `.eslintrc.*` and `package.json` files

The first option is the one that I need in `linter-eslint`, is it missing?

Thanks for your help 😄

**Comment by IanVS** [comment]
@Deseteral Unfortunately, there is no way for us to reliably determine what your project root is.  If you want to override the default ESLint config file resolution and specify a config file directly, I would suggest setting the `.eslintrc path` with an absolute pathname, and then using https://atom.io/packages/project-manager to change this setting for your various projects.

Hopefully that will work for you.
