### ISSUE TITLE
Invalid position given by 'react/jsx-indent'

### ISSUE THREAD

**Issue by nmynarcik** [AtomLinter/linter-eslint#825]
Atom told me to report this...

ESLint returned a point that did not exist in the document being edited.
Rule: `react/jsx-indent`
Requested range: 19:18

Debug information:
```json
{
  "atomVersion": "1.14.2",
  "linterEslintVersion": "8.1.0",
  "linterEslintConfig": {
    "showRuleIdInMessage": true,
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "2.13.1",
  "hoursSinceRestart": 38.1,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "...node_modules/eslint"
}
```

**Comment by Arcanemagus** [comment]
Are you able to provide a file and ESLint configuration to reproduce this? Since this is a non-standard configuration more information will definitely be needed to track this down and get it reported to the proper location.

**Comment by nmynarcik** [comment]
Oops! Sorry, this error was not form `react/jsx-indent` but instead a result of having a hidden character ([line separator](http://www.fileformat.info/info/unicode/char/2028/index.htm)) in code.
