### ISSUE TITLE
Support ESlint v3.16.0

### ISSUE THREAD

**Issue by piotr-cz** [AtomLinter/linter-eslint#829]
## Issue Type
Bug

## Issue Description
After local update of eslint from v3.15.0 to v3.16.0 I'm receiving an error popup in Atom editor:
```
Error: Cannot read config file: xxx\node_modules\eslint\conf\eslint.json Error: ENOENT: no such file or directory, open 'xxx\node_modules\eslint\conf\eslint.json' Referenced from: xxx.eslintrc.json
```
So it seems that linter cannot find file `node_modules\eslint\conf\eslint.json` which has been renamed to `eslint-recommended.json` in https://github.com/eslint/eslint/pull/8106, change available since _v3.16.0_ release.

**Comment by IanVS** [comment]
Thanks for the report. Did you try restarting Atom?  Can you please post the output of the `Linter Eslint: Debug` command?

**Comment by piotr-cz** [comment]
btw, in my root .eslintrc.json file I'm extending recommended rules by
```json
"extends": [
  "eslint:recommended"
]
```

When I readded the file from eslint [v3.15.0 relase](https://github.com/eslint/eslint/blob/v3.15.0/conf/eslint.json) error popup went away

**Comment by piotr-cz** [comment]
Linter Eslint :Debug output is

```
Atom version: 1.14.3
linter-eslint version: 8.1.2
ESLint version: 3.16.0
Hours since last Atom restart: 2
Platform: win32
Using local project ESLint from xxx\node_modules\eslint
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by IanVS** [comment]
Thanks, it looks like you haven't restarted in 2 hours.  Can you try restarting Atom, please?

**Comment by piotr-cz** [comment]
Okay. restarting Atom fixed the issue.
So the problem was that  updated eslint while Atom was opened?

**Comment by IanVS** [comment]
Yes, atom was still using a version of `eslint` which no longer matched the `eslint` installed on disk.  It's a fairly common issue, which is why we suggest restarting Atom in the issue template.  ;)

**Comment by piotr-cz** [comment]
I suggest rephrasing to _Restart Atom (especially when updated eslint via command line)_ or adding such pic. I don't know why I didn't restart when it's in the Bug Checklist.

![99problemsrestart](https://cloud.githubusercontent.com/assets/612953/23212846/ce940f08-f908-11e6-85b0-5daa1817cc3c.jpg)
