### ISSUE TITLE
Getting "Illegal import declaration" even with "modules" feature set to true.

### ISSUE THREAD

**Issue by richardkabiling** [AtomLinter/linter-eslint#83]
This is my .eslintrc

    {
      "ecmaFeatures": {
        "modules": true,
        "jsx": true
      },
      "parser": "babel-eslint",
      "environment": {
        "browser": true,
        "es6": true
      }
    }

I'm still getting the error in the following line.

    import React from 'react'

If it matters, I just edited my .eslintrc to include ``"modules": true``. I have tried reopening the file and restarting Atom to no avail.

I am using Atom 0.201.0 with linter-eslint 0.5.8 and linter 0.12.6

**Comment by iam4x** [comment]
Have you installed `eslint` locally to your project?

**Comment by blainsmith** [comment]
Same issue too and using this setup https://github.com/airbnb/javascript/tree/master/linters

**Atom Package Versions**
```
linter: 0.12.7
linter-eslint: 0.5.10
```

**Local package.json**
```json
"devDependencies": {
    "babel-eslint": "^3.1.17",
    "eslint": "^0.23.0"
}
```

**Comment by fa7ad** [comment]
same problem here as well

**Comment by JoeStanton** [comment]
Same issue here too.

**Comment by fa7ad** [comment]
its workin fine for me now

**Comment by blainsmith** [comment]
Seems like most of the updates fixed this for me.

**Comment by fa7ad** [comment]
I think this can be closed now

**Comment by yairEO** [comment]
I still get it... on `1.7.2`

**Comment by gnestor** [comment]
Me too. I'm on version 3.2.0.

**Comment by callmewhy** [comment]
same error...
> eslint -v
v1.8.0

**Comment by ugogo** [comment]
Same in `v1.9.0`

**Comment by Arcanemagus** [comment]
Are you saying that the local installation of `eslint` shows this error, or you _only_ see this from within Atom?

**Comment by ugogo** [comment]
Of course not, it's just a CLI temporary alternative

**Comment by IanVS** [comment]
@ugogo can you share your `.eslintrc`?  Also, where do you have eslint installed (in your project?  globally?)

**Comment by ugogo** [comment]
Sure

```js
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0,
    "indent": [2, 2, { "SwitchCase": 1 }],
    "quotes": [2, "single"],
    "linebreak-style": [2, "unix"],
    "semi": [2, "always"]
  },
  "env": {
    "es6": true,
    "browser": true
  },
  "extends": "eslint:recommended",
  "ecmaFeatures": {
    "jsx": true,
    "experimentalObjectRestSpread": true
  },
  "plugins": [
    "react"
  ]
}
```

**Comment by IanVS** [comment]
You need to add `"modules": true ` to your ecmaFeatures. See if that works.

**Comment by rguanghui** [comment]
@IanVS yes，as you say

**Comment by ryanburgess** [comment]
Thanks @IanVS that's exactly what I was missing too :+1:

**Comment by shashankKeshava** [comment]
@IanVS your fix did not work for me. This is my eslint config
`{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "modules": true,
            "experimentalObjectRestSpread": true
        }
    },
    "env": {
        "browser": true,
        "node": true,
        "jquery": true
    },
    "rules": {
        "quotes": 0,
        "no-trailing-spaces": 0,
        "eol-last": 0,
        "no-unused-vars": 0,
        "no-underscore-dangle": 0,
        "no-alert": 0,
        "no-lone-blocks": 1,
        "camelcase": 0
    },
    "globals": {
        "jQuery": true,
        "$": true
    }
}
`

**Comment by Arcanemagus** [comment]
@shashankKeshava Please file a new issue, preferably with a zip attached (or gist/example repo) demonstrating your issue. When you file this please make sure you fill out the template completely.

There's no sense spamming the other 12 participants in this thread troubleshooting your problem 😛.
