### ISSUE TITLE
linter-eslint isn't reading eslintConfig from my project's package.json

### ISSUE THREAD

**Issue by joeflynn** [AtomLinter/linter-eslint#832]
## Issue Type
Bug

## Issue Description
linter-eslint isn't reading `eslintConfig` from my project's `package.json`. I've taken a couple steps to try and isolate what could be causing the issue:

1. When "Disable when no ESLint config is found (in package.json or .eslintrc)" is checked, no linting happens at all. 
2. When it's unchecked and I specify an `.eslintrc` fallback in my home directory, it uses that instead of what's in `package.json`.
2. If I copy my `package.json`'s `eslintConfig` to an `.eslintrc` file at the root of my project, it behaves as expected.

I'm running Atom on macOS Sierra, and this project is based off https://github.com/react-boilerplate/react-boilerplate, if that helps track things down.

```
Atom version: 1.14.4
linter-eslint version: 8.1.2
ESLint version: 3.9.1
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from /Users/joe/dev/project_name/node_modules/eslint
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
As that's the method of configuration used in this package itself, I know that it does work, so we need to find what's unique about your project that is breaking things.

Does ESLint work in the CLI for this project?

**Comment by joeflynn** [comment]
Yes, it works in the CLI. One thing I should note is that it looks like this project is using `cross-env` to load some additional plugins when running eslint, and if ran without them it throws a lot of `import/no-unresolved` and `import/extension` errors. Specifically, it's loading transform-es2015-modules-commonjs, dynamic-import-node, and istanbul. Only istanbul isn't included in the react-boilerplate linked above.

It doesn't seem like linter-eslint has any issue resolving those paths when reading straight from `.eslintrc` in the project root, however, so I didn't think it was the issue.

Here's my eslintConfig/.eslintrc, if it helps:
```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "browser": true,
    "node": true,
    "mocha": true,
    "es6": true
  },
  "plugins": [
    "redux-saga",
    "react",
    "jsx-a11y"
  ],
  "globals": {
    "google": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "import/no-duplicates": 1,
    "no-duplicate-imports": 1,
    "no-underscore-dangle": [
      0,
      {
        "allow": [
          "__Rewire__"
        ]
      }
    ],
    "camelcase": 0,
    "import/no-unresolved": 2,
    "comma-dangle": [
      2,
      "always-multiline"
    ],
    "indent": [
      2,
      2,
      {
        "SwitchCase": 1
      }
    ],
    "jsx-a11y/aria-props": 2,
    "jsx-a11y/heading-has-content": 0,
    "jsx-a11y/href-no-hash": 2,
    "jsx-a11y/label-has-for": 2,
    "jsx-a11y/mouse-events-have-key-events": 2,
    "jsx-a11y/role-has-required-aria-props": 2,
    "jsx-a11y/role-supports-aria-props": 2,
    "max-len": 0,
    "newline-per-chained-call": 0,
    "no-console": 1,
    "no-use-before-define": 0,
    "prefer-template": 2,
    "class-methods-use-this": 0,
    "react/no-unused-prop-types": [
      1,
      {
        "skipShapeProps": true
      }
    ],
    "react/forbid-prop-types": 0,
    "react/jsx-first-prop-new-line": [
      2,
      "multiline"
    ],
    "react/jsx-filename-extension": 0,
    "react/jsx-no-target-blank": 0,
    "react/require-extension": 0,
    "react/self-closing-comp": 0,
    "redux-saga/no-yield-in-race": 2,
    "redux-saga/yield-effects": 2,
    "require-yield": 0,
    "arrow-parens": 0,
    "import/no-extraneous-dependencies": 1,
    "import/imports-first": 1,
    "object-shorthand": 1,
    "react/prefer-stateless-function": 1
  },
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "./internals/webpack/webpack.test.babel.js"
      }
    }
  }
}
```

**Comment by Arcanemagus** [comment]
> It looks like this project is using cross-env to load some additional plugins when running eslint

If you close _all_ instances of Atom, then launch it from a terminal where that environment is setup (`atom .`), does it work?

**Comment by joeflynn** [comment]
Sorry, that didn't work either. On a lark I tried `./node_modules/cross-env/bin/cross-env.js NODE_ENV=test atom .` but that had the same result.

**Comment by Arcanemagus** [comment]
Okay, took the time to try to reproduce this and unfortunately couldn't.

1. `git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git linter-eslint_GH823`
2. `npm run setup`
3. `./node_modules/.bin/eslint app/app.js`, note no errors
4. `atom .`, open `app/app.js`, note no errors
5. Remove a semi-colon and see both CLI and Atom show this as a problem
6. Paste in your configuration, watch CLI and Atom blow up with errors, both the same output.

Can you try that in a temp directory and see if you see the same thing?

**Comment by joeflynn** [comment]
I'm with you till step 4. When I do that, I see this in the linter output. Apologies for the screenshot, Atom won't let me copy & paste this for some reason.

<img width="925" alt="screen shot 2017-03-10 at 4 56 52 pm" src="https://cloud.githubusercontent.com/assets/309461/23814737/a774165a-05b2-11e7-814a-8397de6b5985.png">

**Comment by IanVS** [comment]
>when it's unchecked and I specify an .eslintrc fallback in my home directory, it uses that instead of what's in package.json.

I think I know what's going on.  We seem to prioritize the standard eslint config files (`.eslintrc.*`) over `package.json` config here: https://github.com/AtomLinter/linter-eslint/blob/fe0551bac59ff8775df377f83ce58ff74f53478e/src/worker-helpers.js#L110.  When you have a config in your home, we find and use that instead of the project's `package.json` config.  

If nobody else wants to jump in, I should be able to work on a PR within the next few days.

**Comment by joseph-teb** [comment]
FIX. add to eslintrc rule:
"jsx-a11y/href-no-hash": "off"
