### ISSUE TITLE
linter-eslint not showing errors (or even working ?)

### ISSUE THREAD

**Issue by pitrackster** [AtomLinter/linter-eslint#834]
## Issue Type

Question / Bug ?

## Issue Description

I recently installed Atom 1.14.4 ... I really don't know if it's related but since then I can not get linter-eslint to work... No eslint error are shown in Atom as they were before... 

This plugin : https://atom.io/packages/jslint is working... But it is not as good as your ;-)

## Bug Checklist
- Restart Atom
  - done (restart computer also)
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not

`node_modules/eslint/bin/eslint.js vendor/claroline/distribution/plugin/exo/Resources/modules/items/ordering/editor.js` worked as expected :

```
/var/www/html/Claroline/vendor/claroline/distribution/plugin/exo/Resources/modules/items/ordering/editor.js
    6:9   error  'SCORE_FIXED' is defined but never used  no-unused-vars
    8:9   error  'tex' is defined but never used          no-unused-vars
    9:9   error  'notBlank' is defined but never used     no-unused-vars
  115:19  error  'item' is defined but never used         no-unused-vars
```

- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

 `Linter Eslint: Debug` command worked *once* and gave this result 

```
Atom version: 1.14.4
linter-eslint version: 8.1.2
ESLint version: 2.13.1
Hours since last Atom restart: 0
Platform: linux
Using local project ESLint from /home/pitrackster/dev/www/Claroline/node_modules/eslint
linter-eslint configuration: {
  "disableFSCache": true,
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

I tried today to relaunch this command. It result in this line in the dev tools console :
```
.../.atom/packages/linter-eslint/lib/helpers.js:12  (in promise) TypeError: Cannot read property 'getPath' of undefined(…)
```

**Comment by IanVS** [comment]
That's really strange.  Have you tried uninstalling and re-installing `linter-eslint`?

**Comment by pitrackster** [comment]
> Have you tried uninstalling and re-installing linter-eslint?

Yes several times ;-)

**Comment by IanVS** [comment]
I figured you had, but it was worth a shot.  It's worth noting, you'll need to have a javascript file open for the `debug` command to work.  But the error message you're getting makes it seem like it's not getting a valid reference to the atom texteditor variable.  @Arcanemagus have you seen anything like this before?  It's a new one for me.

@pitrackster, one thing you could do (that probably won't help), is upgrade your version of ESLint.  You're quite a few versions behind the current.

**Comment by pitrackster** [comment]
> you'll need to have a javascript file open for the debug command to work. 

That's good to know !

> one thing you could do (that probably won't help), is upgrade your version of ESLint. You're quite a few versions behind the current.

I did... unfortunatley you where right that does not help. But now we know for sure that it does not come from my eslint version...

```
Atom version: 1.14.4
linter-eslint version: 8.1.2
ESLint version: 3.16.1
Hours since last Atom restart: 0
Platform: linux
Using local project ESLint from /home/pitrackster/dev/www/Claroline/node_modules/eslint
linter-eslint configuration: {
  "disableFSCache": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
I have no idea how you triggered that error as you can only run that command from an open text editor... and you can only get that error if there is no open text editor 😕.

Anyway, can you run `Editor: Log Cursor Scopes` when you have a JS file open?

**Comment by Arcanemagus** [comment]
Put up a PR guarding against that invalid `TextEditor` you somehow managed to trigger.

**Comment by pitrackster** [comment]
Hi,

Sorry for this strange behaviour... :-/

Below the result of `Editor: Log Cursor Scope` command

```
Scopes at Cursor

source.js
meta.switch-statement.js
meta.function-call.js
meta.arguments.js
punctuation.definition.arguments.end.bracket.round.js
```

**Comment by novym** [comment]
I am experiencing the same issue. 

Things I have tried
- uninstalling and re-installing linter-eslint.
- running eslint on its own which does report errors as expected.
- downgrading to a previous version of linter-eslint
- switching between local and global eslint

However, linter-eslint does not seem to report any issues at all.


```
Scopes at Cursor

source.js.mongodb
meta.method-call.js
meta.arguments.js
punctuation.terminator.statement.js
```
linter-eslint debugging information
```json
Atom version: 1.14.4
linter-eslint version: 8.1.2
ESLint version: 3.17.0
Hours since last Atom restart: 3
Platform: darwin
Using local project ESLint from /Users/me/repos/mine/project/node_modules/eslint
linter-eslint configuration: {
  "disableEslintIgnore": true,
  "disableFSCache": true,
  "disableWhenNoEslintConfig": false,
  "globalNodePath": "/Users/me/.nvm/versions/node/v6.3.0",
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by IanVS** [comment]
@novym it looks like a mongodb plugin is overriding the scope for JS files `source.js.mongodb` instead of `source.js`.  You should be able to add `source.js.mongodb` to your `linter-eslint` options ("List of scopes to run ESLint on").

**Comment by novym** [comment]
@IanVS that fixed my issue, thank you.

**Comment by sixfeetover** [comment]
I am having this same issue, and have tried the same debug steps as @pitrackster. ESLint on the command line and in VS Code work fine. Just updated to linter v2, atom 1.15, and linter-eslint 8.1.3 and am still having these issues. There are no errors in the console, and eslint _appears_ to run, but does not report anything back. The file I'm looking at has 138 problems (94 errors, 44 warnings) when running eslint manually (I know, yikes).

```json
Atom version: 1.15.0
linter-eslint version: 8.1.3
ESLint version: 3.16.1
Hours since last Atom restart: 0
Platform: darwin
Using global ESLint from: /usr/local/lib/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.method-call.with-arguments.js",
  "meta.function.json.js",
  "meta.method-call.with-arguments.js",
  "meta.method-call.with-arguments.js",
  "meta.method-call.with-arguments.js",
  "string.quoted.single.js"
]
linter-eslint configuration: {
  "eslintrcPath": "~/.eslintrc",
  "globalNodePath": "/usr/local",
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

```
Scopes at Cursor 
source.js.jsx
meta.method-call.with-arguments.js
meta.function.json.js
meta.method-call.with-arguments.js
meta.method-call.with-arguments.js
meta.method-call.with-arguments.js
string.quoted.single.js
```

What other information can I provide to be helpful?

**Comment by MidnightLightning** [comment]
Also hitting this issue: Atom 1.15.0 on OSX; updated to linter 2.1.0 and linter-eslint 8.1.3 and now no errors are reported in Atom, though there are warnings and errors reported from ESlint from the command line. Cursor scope shows `source.js.jsx`, so not the MongoDB plugin issue in my case.

**Comment by IanVS** [comment]
@MidnightLightning @sixfeetover are either of you able to share a reproducible example so we can look into this further?  That would be very helpful.

**Comment by Arcanemagus** [comment]
@sixfeetover By the way, the new debugging output includes the same information as running the "Scopes at cursor" command, so there is no longer a need to include that extra bit 😉.

@MidnightLightning Can you post the debug output as well? It has several bits of useful information in it to help us get an idea as to what is going on.

**Comment by MidnightLightning** [comment]
@Arcanemagus example and debug output in this Gist: https://gist.github.com/MidnightLightning/38ae806cea92d06296dfd2c6c62b8e5d

**Comment by IanVS** [comment]
@MidnightLightning can you try updating to `8.1.4`?  There's a _small_ chance it may have fixed your problems.

**Comment by pitrackster** [comment]
Hi !
After updating to `8.1.4` and `linter 2.1.0` the dev console tells me that no configuration file was found

```
/home/pitrackster/.atom/packages/linter/lib/linter-registry.js:177 [Linter] Error running ESLint Error: No ESLint configuration found.(…)(anonymous function) @ /home/pitrackster/.atom/packages/linter/lib/linter-registry.js:177
```

Giving the path to my `.eslintrc.json` file in `linter-eslint` settings seems to make it work again !

Great !

**Comment by sixfeetover** [comment]
So after playing with this some more, I've discovered that if I un-check "Disable when no ESLint config is found", eslint starts working again, _and_ it's using the eslint file I've specified in the `linter-eslint` settings (`/Users/jfraser/.eslintrc.json`).  I verified this by playing with the rules in my `.eslintrc.json` file and seeing those changes reflected in Atom.

So: The file is there, and `linter-eslint` is using it, but ONLY when I un-check that setting. Additionally, when that setting is still on, "Fix errors on save" and "Linter ESlint: Fix File" still work.

There are still no errors in my console showing up under any circumstances I've tested.

**Comment by IanVS** [comment]
Thanks @sixfeetover. Which version of linter-eslint are you using? If you're not on 8.1.4 already, can you try upgrading? Also, do you have an eslint config at the root of your home directory (~/.eslintrc)?

**Comment by IanVS** [comment]
Ah, I noticed from what you posted earlier: `"eslintrcPath": "~/.eslintrc"`. This is probably the culprit. A config at your home root is treated by eslint as a fallback, so it doesn't count as a project config by the option "Disable when no ESLint config is found".  

Can you explain your use case for having these settings the way they are?

**Comment by MidnightLightning** [comment]
@IanVS Updated, but no change:

```
Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.17.1
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/brooks.boyd/Development/eslint-test/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta",
  "punctuation.definition.function.end.es"
]
linter-eslint configuration: {
  "disableFSCache": true,
  "disableWhenNoEslintConfig": false,
  "globalNodePath": "/opt/local",
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by abe312** [comment]
ok, looks like eslint is un-initialised. open this command and follow the instructions.. `~/.atom/packages/linter-eslint/node_modules/.bin/eslint --init`

**Comment by MidnightLightning** [comment]
@abe312 Initializing ESLint like that creates a `.eslintrc.js` file in that project's folder. But I have my configuration settings in my `package.json` file. Copying the exact same config that I have in my `package.json` file, I can still run ESLint from the command line successfully for that project, but from within Atom for that project, the linter does not run and does not find any warnings/errors.

**Comment by abe312** [comment]
where did you save the package.json file. looks like it requires one in root project folder..
also,  uncheck this disable box..
![screen shot 2017-03-30 at 1 26 20 am](https://cloud.githubusercontent.com/assets/7970296/24473755/fef2a4e8-14e7-11e7-8c40-219967245b3b.png)

**Comment by abe312** [comment]
ok I have an idea, make a separate directory and store package.json in it, and add that to the ESLint Rules Dir in settings. and tell me whether it starts working properly..

**Comment by MidnightLightning** [comment]
@abe312 As I indicated earlier, I'm using this project as a minimal project to reproduce the issue: https://gist.github.com/MidnightLightning/38ae806cea92d06296dfd2c6c62b8e5d

`package.json` is in the same folder as an `app.js` file. On the command line, running `./node_modules/.bin/eslint app.js` shows the appropriate 1 error, 1 warning. Opening app.js in Atom does not show any errors or warnings.

**Comment by abe312** [comment]
Well I have a .eslintrc.js file 
![screen shot 2017-03-30 at 1 47 25 am](https://cloud.githubusercontent.com/assets/7970296/24474674/fd2eb0ae-14ea-11e7-8915-e8628787db25.png)

and package.json stores that file like this:
![screen shot 2017-03-30 at 1 47 36 am](https://cloud.githubusercontent.com/assets/7970296/24474657/efb8bcf8-14ea-11e7-885f-7924765e6371.png)

Try modularising your code? and add a .eslintrc.js by using atom's local eslint?

**Comment by MidnightLightning** [comment]
@abe312 No dice; it doesn't matter if the configuration is in an `.eslintrc.js` file or if it's part of the `package.json` file. The ESLint executable can find it either way, but Atom cannot.

Here's the absolute minimum setup:

<img width="581" alt="eslint-test2" src="https://cloud.githubusercontent.com/assets/250250/24474959/faec8d7c-1493-11e7-8c91-cb0f9e159fd2.png">

Note in the footer of Atom, there's zero warnings, zero errors found. From the CLI:

<img width="624" alt="eslint-test-cli" src="https://cloud.githubusercontent.com/assets/250250/24474982/1454e732-1494-11e7-9e47-b10efc6c33e7.png">

**Comment by abe312** [comment]
it's working fine in mine..

![screen shot 2017-03-30 at 2 06 28 am](https://cloud.githubusercontent.com/assets/7970296/24475530/c38d0348-14ed-11e7-8aef-6f68f6e3bb43.png)

how many versions of ESLint have you installed? I'm noticing in your directory that you have one in node_modules folder. Is is an alias of atom's .bin or a separate version?
try removing the global version. 
or if you're using global eslint, enable this in settings..

![screen shot 2017-03-30 at 2 10 57 am](https://cloud.githubusercontent.com/assets/7970296/24475655/3afd0eaa-14ee-11e7-9565-c63aecf26da3.png)

**Comment by MidnightLightning** [comment]
I do not have a global ESLint executable installed. The `node_modules` folder in the project is due to running `npm install eslint` in that project directory. Removing the `node_modules` folder from that project workspace does not cause Atom to start detecting things.

**Comment by abe312** [comment]
ok.. use `apm install linter-eslint`  and  remove that npm one.
if you was to use `--init` use from `/Users/abe/.atom/packages/linter-eslint/node_modules/.bin/eslint --init` 
if you have a global one, versions should match...

**Comment by abe312** [comment]
also did you enabled "Use global ESLint installation" in settings?

**Comment by MidnightLightning** [comment]
Okay, I did
```
rm -r node_modules
apm install linter-eslint
~/.atom/packages/linter-eslint/node_modules/.bin/eslint app.js
```
And it still shows the one error and one warning properly from the command line. In Atom, settings are set to not use Global ESLint installation, but Atom does not show any warnings or errors for that file.

**Comment by darahak** [comment]
My situation is a bit similar to @sixfeetover's: config in home directory and global install.
The thing is it works for the first file I see when I re-open Atom, but it disappears as soon as I make a change or save, and it never works again.

Here's the debug info I get for `linter-eslint`:

```
Atom version: 1.15.0
linter-eslint version: 8.1.0
ESLint version: 3.18.0
Hours since last Atom restart: 0
Platform: win32
Using global ESLint from C:\Users\D6K\AppData\Roaming\npm\node_modules\eslint
linter-eslint configuration: {
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by IanVS** [comment]
@MidnightLightning, I also tried your reproduction case and it seemed to work fine for me.  

Out of curiosity, do you have an eslint config file at your home directory's root (`~/.eslintrc`)?  That shouldn't cause trouble anymore with `8.1.4`, but I thought I'd ask.

**Comment by IanVS** [comment]
This is a very vague issue ("Not working") and it seems to be gathering a lot of different issues.  It sounds like in most cases the problem has been solved with a thorough uninstall / reinstall.  I'm going to leave this open for one more day, and then close & lock the thread to avoid notification spam of everyone subscribed.  If you're still having problems or come to this thread in the future, please open a new issue with as much detail about your configuration as possible, _including_ the output of the `Linter Eslint: Debug` command.

**Comment by MidnightLightning** [comment]
@IanVS I do not have an ESLint config file in my home directory. I tried uninstalling `linter`, `linter-ui-default`, and `linter-eslint`, quit Atom, started Atom again, and reinstalled `linter-eslint` (which prompted for the other two as dependencies. Quit Atom again and re-launched it, and still no linting results.

I am running Atom on a Mac with 10.11.6 (El Capitan), running as a non-admin user (which has sometimes messed up Atom's self-updating capabilities), with the Atom executable in my _user's_ Applications folder (not the system Applications folder, in order to get around the self-updating issues).

```
Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.19.0
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/brooks.boyd/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.brace.round.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "globalNodePath": "/opt/local",
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by JochenFromm** [comment]
One possible reason is that the file is not recognized as Javascript. If `Linter Eslint: Debug` says 

```
Current file's scopes: [
  "text.plain.null-grammar"
]
```

then the automatic detection of the Atom editor has classified it as a normal text file, and the Linter thinks it does not have to be checked. If you set the type of the file to JavaScript (at the bottom right corner), then the file type or "scope" is recognized correctly, and the Linter works as expected

```
Current file's scopes: [
  "source.js",
  "meta.method-call.js",
  "meta.arguments.js"
]
```

**Comment by MidnightLightning** [comment]
@JochenFromm Good thought! Though mine was properly detecting it as `source.js.jsx`, so that wasn't my specific problem.

However, I just upgraded to the latest package, and now it's working!

```
Atom version: 1.16.0
linter-eslint version: 8.1.6
ESLint version: 3.19.0
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/brooks.boyd/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta",
  "meta.function.body",
  "punctuation.terminator.statement.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "globalNodePath": "/opt/local",
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```
So, bumping up to Atom 1.16.0 and 8.1.6 of this plugin seems to have fixed the issue for me!

**Comment by IanVS** [comment]
Thanks everyone.  It seems like the issue is usually solved by upgrading atom/linter-eslint or from a re-install.  If you're still having problems with `linter-eslint`, please open a new issues with as much detail as possible.
