### ISSUE TITLE
Plugin rules detection (globally installed eslint)

### ISSUE THREAD

**Issue by nemoxps** [AtomLinter/linter-eslint#840]
## Issue Type

Bug

## Issue Description

- Enabled ```Use global ESLint installation``` in linter-eslint settings
- Globally installed eslint
- Globally installed plugin

#### The plugin:
eslint-plugin-nemoxps/

index.js
```js
module.exports = {
    rules: {
        'nemoxps-brace-style': require('./brace-style')
    }
};
```

brace-style.js contains the unmodified source code of the [brace-style](https://github.com/eslint/eslint/tree/master/lib/rules/brace-style.js) rule.

#### The project:
.eslintrc.js
```js
module.exports = {
    root: true,
    plugins: ['nemoxps'],
    parserOptions: {
        ecmaVersion: 8,
    },
    rules: {
        'nemoxps/nemoxps-brace-style': [2, 'allman', { allowSingleLine: true }]
    }
};
```

test.js
```js
if (true)
{
  '';
}

let a = {
    a: 'a'
};

let b = function () {
    return '';
};

let c = class {
    constructor()
    {
      
    }
};
```

linter-eslint shows ```ESLint Error Definition for rule 'nemoxps/nemoxps-brace-style' was not found (nemoxps/nemoxps-brace-style)at line 1 col 1```
eslint CLI works as expected.

---

- Disable ```Use global ESLint installation``` in linter-eslint settings
- Locally installed eslint
- Locally installed plugin

linter-eslint works as expected.
eslint CLI works as expected.

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.14.3
linter-eslint version: 8.1.2
ESLint version: 3.17.1
Hours since last Atom restart: 5.5
Platform: win32
Using global ESLint from C:\Node\node_modules\eslint
linter-eslint configuration: {
  "globalNodePath": "C:\\Node",
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by nemoxps** [comment]
I just noticed, that this is working now, so I played around with it a bit:
I suppose that this is a cache issue. If a rule's name gets changed in the plugin, the changed name cannot be found in the cached plugin. This is surely useful for performance reasons (as plugins usually don't change), but it means trouble for plugin authors at writing time.
So, this is probably less a bug than a feature request: Add a button in the package settings to delete the plugin cache.

**Comment by Arcanemagus** [comment]
If this is a bug anywhere, it would _maybe_ be a bug in `eslint` for not reloading a rule source? If you are changing the code for a plugin you need to close the Atom window that is using that plugin and reopen it to restart the worker process that handles the linting.
