### ISSUE TITLE
linter-eslint + eslint-plugin-flowtype[-errors]

### ISSUE THREAD

**Issue by krainboltgreene** [AtomLinter/linter-eslint#846]
## Issue Type
Bug

## Issue Description
I instealled eslint-plugin-flowtype-errors and I'm not seeing the linter errors in the editor.

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
tom version: 1.15.0
linter-eslint version: 8.1.3
ESLint version: 3.17.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/krainboltgreene/code/krainboltgreene/hsdk.js/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.function.js",
  "meta.function.arrow.js",
  "meta.function-call.without-arguments.js",
  "variable.other.object.js",
  "variable.other.object.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```
<img width="1114" alt="screen shot 2017-03-11 at 1 14 14 am" src="https://cloud.githubusercontent.com/assets/334809/23822020/1e9fa880-05f8-11e7-9315-048b611af92a.png">

<img width="1205" alt="screen shot 2017-03-11 at 1 12 47 am" src="https://cloud.githubusercontent.com/assets/334809/23822015/de6ce854-05f7-11e7-8afd-2b14b0d7b56c.png">

**Comment by Arcanemagus** [comment]
Hmmm, I see that there is a Project level message, can you see if that is the missing message? It's possible that `eslint-plugin-flowtype-errors` is messing up the file path so it isn't being properly associated with the file.

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response. If you are still having issues please provide a `.zip` file containing files to reproduce this, or link to a repository of the same. Thanks!
