### ISSUE TITLE
Multiline error messages with linter 2.0 are broken

### ISSUE THREAD

**Issue by caesarsol** [AtomLinter/linter-eslint#849]
(From https://github.com/steelbrain/linter/issues/1352)

## Issue Type
Bug

## Issue Description

Multiline error messages, such as Parser errors, are displayed in a single line and made unreadable.

<img width="1053" alt="screen shot 2017-03-14 at 12 48 37 pm" src="https://cloud.githubusercontent.com/assets/1799710/23899423/5ab9a45a-08b5-11e7-9c20-70c888d8712e.png">

### Manual eslint run

```bash
$ node node_modules/eslint/bin/eslint.js --cache --cache-location=/tmp/ src/

/Users/caesarsol/dev/project/file.js
  102:32  error  Parsing error: Unexpected token

  100 |     },
  101 |
> 102 |     get eventGroupsVisible() {;:;
      |                                ^
  103 |       const fromTs = this.eventsTimeExtent.max - (config.intervalToShow + config.intervalToFetch * 2)
  104 |       const toTs = this.eventsTimeExtent.max - 1
  105 |       const eventsGrouped = this.getEventsFromTo(fromTs, toTs)

✖ 1 problem (1 error, 0 warnings)
```

## Linter debug (stripped)

Platform: darwin
Atom Version: 1.15.0
Linter Version: 2.0.0
All Linter Providers: 
  - ESLint
Matching Linter Providers: 
  - ESLint
Disabled Linter Providers; 

### Other useful info

linter-eslint version: 8.1.3
Hours since last Atom restart: 0.1
Using local project ESLint from: /Users/caesarsol/dev/project/node_modules/eslint

Hope these info were useful.
Thanks for your work on this project!

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

**Comment by tommai78101** [comment]
Chiming in to offer a suggestion on how to improve the design for this bug:

1. Given that when using the linter in Atom, the linter already highlights where the errors are in the codes, there is no point in using ASCII text to point out where or what line of code is causing the error.
2. It may be possible to not parse the error message after the imporant message has been stated.For example, the error message is: `Parsing error: Unexpected token, expected , 21 | 22 | var foo = { > 23 | var bar = { | ^ 24 | var baz = { 25 | 26 | }; (Fatal)`

The linter can just stop at `Parsing error: Unexpected token, expected ,`. Reason is, this message only appears when the mouse cursor is hovering over the underlined erroneous code, and the description at the bottom can be more compact. It is therefore more fitting to have a compact error message when the mouse is hovering over the error, as well as remove the weird message shown down at the bottom.

**Comment by Arcanemagus** [comment]
Fixed in https://github.com/AtomLinter/linter-eslint/pull/911 for when ESLint was still reporting messages like this, but it seems that current versions of ESLint are back to the original form of reporting _just_ `Parsing error: Unexpected token :`.
