### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by jerome724** [AtomLinter/linter-eslint#850]
Hey!

I installed the plugin ``async-await``, so i did ``npm install eslint-plugin-async-await``, and added it to my ``package.json``:

```json
    "eslintConfig": {
        "plugins": [
            "async-await"
        ]
    }
```

Now atom tells me that it can't find the plugin, 
```
C:\Users\jerom\.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running ESLint Error: Failed to load plugin async-await: Cannot find module 'eslint-plugin-async-await'(…)(anonymous function) @ C:\Users\jerom\.atom\packages\linter\lib\linter-registry.js:177
```

i tried then installing it in the same directory as the ``package.json``, but that didn't worked either. Then i tried to edit the Global Node Installtion Path in the settings of the package, so i added ``C:\Users\jerom\AppData\Roaming\nvm\v7.7.3`` but atom still can't find the plugin.

where do i need to install eslint plugins so atom can find them?

https://www.npmjs.com/package/eslint-plugin-async-await

**Comment by Arcanemagus** [comment]
Can you provide the debug information with a file from this project open as requested in the template?

**Comment by jerome724** [comment]
Weird, after i restarted my laptop it worked fine.
