### ISSUE TITLE
Index is assigned but never used.

### ISSUE THREAD

**Issue by sidzan** [AtomLinter/linter-eslint#852]
## Issue Type

Question

## Issue Description

I am using react. I have configured to use default settings during eslint installation.

```
/*eslint-env node */
const ReactDOM = require ("react-dom");
const Index = require ("./components/index");
ReactDOM.render(
  <Index/>,
  document.getElementById("content")
);
```

I receive the error as :

```
file: 'file:///home/sijan/personal/express/index.js'
severity: 'Error'
message: ''Index' is assigned a value but never used. (no-unused-vars)'
at: '3,7'
source: 'eslint'
```

I assume the es-lint doesn't recognize Index wrapped inside a <> . Is there a way to solve this ?
I will be needing to add providers stores and other features and if this is going to be red throughout it might affect visibility to others . Any suggestion to fix ?

**Comment by Arcanemagus** [comment]
You'll need to configure ESLint for your project, it sounds like for starters you will need to install and configure [`eslint-plugin-react`](https://www.npmjs.com/package/eslint-plugin-react). You might also look into a preset configuration such as [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb), which configures many of the rules for you as well.
