### ISSUE TITLE
[Linter] Error running ESLint 

### ISSUE THREAD

**Issue by Irnis18** [AtomLinter/linter-eslint#856]
## Issue Description

Bug

version : linter-eslint: 8.1.4
<img width="466" alt="screen shot 2017-03-22 at 14 53 43" src="https://cloud.githubusercontent.com/assets/21169278/24203414/ee04f442-0f15-11e7-9de2-8e9012ef7923.png">
So this error appears when i try to do changes on .js files, i don't know if this appears on any other files. This happend after i updated Atom, i also deleted some packages, but they don't have anything to do with Linter, linter-eslint.  

## DEBUG OUTPUT 
```
Linter Eslint: Debug output here
```

``` Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.18.0
Hours since last Atom restart: 0
Platform: darwin
Using global ESLint from: /usr/local/lib/node_modules/eslint
Current file's scopes: [
  "unknown"
]
linter-eslint configuration: {
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
} ```

**Comment by xiaomuzhu** [comment]
+1

**Comment by r0dneyP3** [comment]
Same error, console gives
```
linter-registry.js [sm]:144 [Linter] Error running ESLint Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.<anonymous> (/Users/.../.atom/packages/linter-eslint/node_modules/eslint/lib/ignored-paths.js:38:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/.../.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:23:20)(anonymous function) @ linter-registry.js [sm]:144```

**Comment by Arcanemagus** [comment]
@r0dneyP3 What version of ESLint are you trying to use?

**Comment by sidharthchugh** [comment]
I am getting the same issue.

**Comment by Arcanemagus** [comment]
@sidharthchugh As has been asked of everyone else in the thread: Can you post debug info? What is it showing in the console? Are you able to share some code + ESLint config to reproduce this?

**Comment by r0dneyP3** [comment]
Somehow the error disappeared after I deleted my node_modules and reinstalled all the dependencies again.

**Comment by Naoto-Ida** [comment]
I'm getting the same error on Mac Atom.

**Comment by xzysun** [comment]
atom 1.15.0   
linter@2.1.2
linter-eslint@8.1.4

works fine on Windows, but get errors on Mac. Errors in console:

```
/Users/xzysun/.atom/packages/linter/lib/linter-registry.js:177 [Linter] Error running ESLint Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/Users/xzysun/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/Users/xzysun/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:151:21)
    at Object.load (/Users/xzysun/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:541:21)
    at loadConfig (/Users/xzysun/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:63:33)
    at new Config (/Users/xzysun/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:229:42)(anonymous function) @ /Users/xzysun/.atom/packages/linter/lib/linter-registry.js:177_tickCallback @ internal/process/next_tick.js:103
```

**Comment by xzysun** [comment]
I try to maually install `eslint-plugin-react`, `eslint-plugin-flow-vars`, `babel-eslint` to the project in `~/.atom/packages/linter-eslint` and it seems to work again.

**Comment by Irnis18** [comment]
This happend after i updated atom. i am running ios and i posted my debug output. when i started typing some javaScript code this happend.

Here are the console output.
<img width="514" alt="screen shot 2017-03-27 at 08 39 31" src="https://cloud.githubusercontent.com/assets/21169278/24343871/fb887ba0-12c8-11e7-8f1a-fb120f9ac032.png">

Sorry for late answer @Arcanemagus.

**Comment by Georgiy-G** [comment]
I had same problem, Dont forget made npm for your project

**Comment by Irnis18** [comment]
Okay, so i have this issue on only some projects for some reason. I think it has something to do with the setup of your projects.

**Comment by cjimenez113** [comment]
Make sure your in your right directory. I was having an issue right now and I came across the page then after looking again I noticed I was not installing in the right file. Hope that works

**Comment by Naoto-Ida** [comment]
I wiped my modules and now it's working.

**Comment by JuniorBoaventura** [comment]
For myself I just had an error on my .eslintrc file

**Comment by Princeraul** [comment]
I'm getting the same error

**Comment by blandine** [comment]
I had the same issue and solved it by upgrading the npm package eslint to 3.18.

**Comment by Maftalion** [comment]
same issue, tried a fresh npm install and reinstalled packages through atom but still getting this error

**Comment by shaharnakash** [comment]
for me the error was because  i had an error in the .eslintrc file, so make sure the syntax is correct there

**Comment by TomYeoman** [comment]
I'm getting this error also

Error stack:

linter-registry.js:144 [Linter] Error running ESLint Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.getRelativePath (C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\lib\worker-helpers.js:157:11)
    at global.onRequest (C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\lib\worker.js:70:36)
    at Emitter.emit (C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\node_modules\sb-event-kit\lib\emitter.js:70:19)
    at C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\node_modules\sb-communication\lib\main.js:22:23
    at C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\node_modules\sb-communication\lib\main.js:21:24
    at Emitter.emit (C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\node_modules\sb-event-kit\lib\emitter.js:68:19)
    at Communication.parseMessage (C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\node_modules\sb-communication\lib\main.js:63:18)
    at process.messageCallback (C:\Users\Thomas Yeoman\.atom\packages\linter-eslint\node_modules\process-communication\lib\communication.js:35:27)
    at emitTwo (events.js:106:13)

**Comment by oppodeldoc** [comment]
I was also getting this error on an older project, I suspect it's a problem with one of the packages that @TomYeoman listed. I fixed it by upping the version of `eslint-plugin-react` to `6.10.3` (All my other packages are the same version as @TomYeoman's list above), then restarted Atom completely, now Linter works fine.

**Comment by gmuc** [comment]
after npm install in my project dir the error disapear

**Comment by gregorskii** [comment]
Seeing the same issue after the past couple days, was working fine before.

I can run lint manually using ESLint, just not in atom. Likely my config is correct and the yml is correct as ESLint runs.

No usable error information is shown in Atom UI.

I do see an error in the Atom Dev Tools:

```
async-to-generator.js:14 Uncaught (in promise) Error: /react-graphql-udemy-courses/gql-users/node_modules/eslint-config-airbnb-base/rules/best-practices.js:(…)
```

I am using Nuclide, but have been for months and its been fine :/ it crashes with Nuclide disabled too.

Atom: 1.15.0 x64 Mac OS

```
"babel-eslint": "^7.2.0",
"eslint": "^3.18.0",
"eslint-config-airbnb-base": "^11.1.1",
"eslint-friendly-formatter": "^2.0.7",
"eslint-plugin-import": "^2.2.0",
```

eslintrc.yml:

```
env:
  node: true
  es6: true,
  mocha: true
parser: babel-eslint
parserOptions:
  sourceType: module
extends:
  - 'airbnb-base'
globals:
  expect: true
  assert: true
rules:
  comma-dangle: 0
  arrow-body-style: 0
  no-console: 1
  no-alert: 1
  no-debugger: 1
  no-unused-vars: 1
  spaced-comment: 1
  class-methods-use-this: 1
  space-before-function-paren: 0
  semi: 1
  import/extensions: 0
  import/no-unresolved: 0
  import/imports-first: 0
  import/newline-after-import: 1
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 1
```

**Comment by Bhavdip** [comment]
I am getting the same error message **console for more information'**  Point is that older project has not issue with Linter its working fine but when I create a new project and config the project it is not working.

**Comment by githubSathishkumar** [comment]
I'm too faced the same problem. The problem occured becasue of eslint node packages missed. I installed node_modules (npm install). After npm install the error pop-up was stopped.

**Comment by gsheppard** [comment]
The solution @gregorskii suggested works.

- Quit Atom
- `nvm use`
-- Maybe wipe node_modules?
- Re-open Atom

**Comment by Bhavdip** [comment]
@githubSathishkumar Nop not working for me. I already have installed npm_modules.

**Comment by weremax** [comment]
Check to make sure you actually have the package installed i have all the packages installed in atom created a new project once i added .eslintrc I had the same error when i got the error i checked my package.json and realized i hadn't installed eslint-config-rallycoding for devDependencies in my new project. Once I installed did not receive the error any more so did a search to see if anyone else had this particular problem to save them sometime.

**Comment by gregorskii** [comment]
@gsheppard It works but you must *always* open Atom from the terminal when using nvm.

**Comment by joeyfigaro** [comment]
Getting same issue here when I don't have an `.eslintrc` in a project. Plugin is configured to disable if there is not configuration found.

**Comment by Bhavdip** [comment]
I have updated the AtomLinter yet not fix. Still getting the same problem.

**Comment by austinkelleher** [comment]
I am also getting this error!

**Comment by M00staff** [comment]
also had this error just now - issue was a typo in the .eslintrc file

**Comment by bigwhiteshark** [comment]
I also met the same problem.

**Comment by hedleysmith** [comment]
Yep I'm also seeing this, can't see anything obvious which could be causing it

In the dev console of Atom I'm seeing:

`
/Users/hedley/.atom/packages/linter/lib/linter-registry.js:177 [Linter]
linter-registry.js [sm]:144 [Linter] Error running ESLint Error: Cannot find module '/Users/hedley/www/projects/package.json'`

The file I'm working on is in /Users/hedley/www/projects/my-project/file.js

**Comment by IanVS** [comment]
That's helpful, @hedleysmith.  Is there any chance you can share the relevant parts of your project?  Specifically, anything related to eslint.

**Comment by hedleysmith** [comment]
@IanVS sure, here are the packages I'm using:

```
{
    "eslint": "^3.4.0",
    "eslint-config-airbnb": "^10.0.1",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.1",
    "eslint-plugin-react": "^6.2.0"
}
```

I can no longer reproduce this issue though now, I disabled and re-enabled linter-eslint and it has seemed to all clear up.

**Comment by straley** [comment]
I had this happen, when I inadvertently did something like:
```
type Blah = {
    name: string,
    child: Blah,
}
```
It didn't like the recursion and produced the same vague error.

**Comment by AgtLucas** [comment]
Same problem here.

```
/Users/agtlucas/.atom/packages/linter/lib/linter-registry.js:177 [Linter] Error running ESLint Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'(…)
```

I'm not using `eslint-plugin-import`, I've tried to install it but didn't solve the problem...

**Comment by IanVS** [comment]
Unfortunately this issue has turned into a dumping-grounds of sorts for all kinds of different, seemingly unrelated issues.  It seems the main causes have been:

- `Cannot find module 'eslint-plugin-x'`: This means that you are using an eslint config which extends a plugin, but you don't have that plugin installed in the same place as your ESLint.  ESLint can be used from three different places:
  1. Your local project, as a `devDependency` in your `package.json`.  This is the preferred method.
  2. Globally, meaning you installed ESLint with `npm i -g eslint` and you have the `Use global ESLint installation` option of `linter-eslint` checked.  If this is your setup, you will then also need to install your plugins globally as well.
  3. A bundled fallback that comes with `linter-eslint`.  This is a last resort, and may be removed in a future major version of `linter-eslint` because of the confusion it causes when people try to use eslint plugins.  Install eslint in your project instead.

(You can determine which eslint is being used by running the `Linter Eslint: Debug` command from the Atom command palette.)

- A bad `.eslintrc` configuration.  Starting in ESLint version 4 (currently in alpha), config files will be [validated](http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0#-unrecognized-properties-in-config-files-now-cause-a-fatal-error).  Until that is released and being used, please try running `eslint` manually from the command line to determine whether you are having a problem with `eslint` itself or with `linter-eslint`.  

- Broken sub-dependencies.  A number of users in this thread have resolved their issue by removing their `node_modules` and reinstalling them (presumably without shrinkwrap or `yarn.lock`).  This is always a good thing to try if you can.

- A stale version of eslint being used by Atom.  Sometimes when upgrading `linter-eslint`, the worker process it is using can become stale.  A restart of Atom typically will fix this problem, and is always a good thing to try when troubleshooting.

This issue has seen a lot of "I'm having this problem too" comments, which don't help us get any closer to a solution and cause a notification for the nearly 30 people subscribed to this issue.  For that reason I'm locking this thread.

If none of what I wrote above fixes your issue and you are still having problems, please create a new issue with _all_ of the information requested in the issue template.  It is very hard for us to help unless you give us as much detail as possible.  

Thanks everyone for participating!
