### ISSUE TITLE
package isn't available?

### ISSUE THREAD

**Issue by dcsan** [AtomLinter/linter-eslint#860]
## Issue Type

bug

## Issue Description

I've installed this plugin using apm
eslint is available on the command line
created an .eslintrc.json
made sure i have a package.json

but nothing happens. 
I assume files would get linted on the fly.

also I can't see any commands specific to eslint on the commands palette
just the `debug` and `fix file`
Is this expected behavior or should there be some visible interface to run this tool?

I would have expected a "lint file" to force linting:

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

confirmed

I also confirmed I can lint with both global and local installed versions of eslint from the command line.

`node ./node_modules/eslint/bin/eslint.js lib`  # works OK

```
Linter Eslint: Debug output here

pages/list/list.js15:21
LFUTF-8JavaScriptmastergit+4 updates
linter-eslint debugging information
Atom version: 1.15.0
linter-eslint version: 8.1.4
ESLint version: 3.18.0
Hours since last Atom restart: 0.1
Platform: darwin
Using global ESLint from: /usr/local/lib/node_modules/eslint
Current file's scopes: [
  "source.js",
  "meta.function-call.js",
  "meta.arguments.js",
  "meta.method-call.js",
  "meta.arguments.js",
  "meta.brace.curly.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "globalNodePath": "/usr/local",
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}

```

**Comment by dcsan** [comment]
running debug gives output above.

running "fix file" gives `Linter-ESLint: Fix attempt complete, but linting errors remain.`

other than that, this package doesn't appear to exist or do anything.

**Comment by IanVS** [comment]
@dcsan can you confirm that you have also installed the `linter` package as well?

**Comment by dcsan** [comment]
hi - I was not running with the linter package. I thought this was a standalone. Now it works and has a nice front-end, thanks!
