### ISSUE TITLE
Extends doesn't work

### ISSUE THREAD

**Issue by AdriVanHoudt** [AtomLinter/linter-eslint#87]
The 'new' extends function doesn't work properly with plugins. If a plugin is defined in the extended config, the linter can't seem to find it

**Comment by maxbeatty** [comment]
I also came across this trying to extend [airbnb's config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

```
{
  "env": {
    "es6": true,
    "node": true
  },
  "extends": "airbnb"
}
```

I traced it down to [eslint requiring the extension](https://github.com/eslint/eslint/blob/master/lib/config.js#L96). Solutions that didn't work:

1. installing `eslint-config-airbnb` in `~/.atom/packages/linter-eslint` (got an error similar to #128)
2. installing `eslint-config-airbnb` globally
3. trying to `require` before getting the config file [here](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L81)

Hopefully someone has a more creative solution

**Comment by iam4x** [comment]
I use extends with https://github.com/ericclemmons/eslint-config-future and it's working great all I have is:

* `$ npm install --save-dev eslint eslint-config-future`

In my `.eslintrc` 

```
{
  "extends": "future/react"
}
```

What's different from me?

**Comment by maxbeatty** [comment]
I reproduced your setup in [this gist](https://gist.github.com/maxbeatty/4458a8ee1859c15c052a) and it worked great. The only differences were using a more stable version of `node` and `npm` (0.10.38 and 2.7.3 respectively). I was using 2.3.1 (iojs) and the new 3.0.0 of npm. Clearing `node_modules`, downgrading to npm 2.12.0, and reinstalling made everything work.

**Comment by AdriVanHoudt** [comment]
I'm not using a eslint config module but just extending a config file like 
`"extends": "./node_modules/lab/lib/linters/eslint/.eslintrc"` but I will try again with the 1.0 version this week

**Comment by iam4x** [comment]
@AdriVanHoudt Working?

**Comment by AdriVanHoudt** [comment]
not used Atom recently but I thought my last try of 1.0 did work yes, will test soon

**Comment by iam4x** [comment]
I'll close this so, just confirm me :+1:

**Comment by AdriVanHoudt** [comment]
so quick test and it can't find all the rules (of a plugin), I know this is something difficult since I have debugged the same issue with the author of the eslint linter of brackets, would be really nice if eslint could provide debug info of where it is looking for the plugins/rules

**Comment by iam4x** [comment]
@AdriVanHoudt Could you provide me an easy repro case?

**Comment by AdriVanHoudt** [comment]
Basic node server with [lab](https://github.com/hapijs/lab) testing lib of which I extend the eslint config and the server has a basic  eslint config:
```js
{
    "env": {
        "node": true
    },
    "extends": "./node_modules/lab/lib/linters/eslint/.eslintrc",
    "rules": {
        "no-undef": 2
    }
}
```

**Comment by iam4x** [comment]
Version 2.0 has been released now using CLI, please open a new issue if something is wrong.

**Comment by AdriVanHoudt** [comment]
I have eslint installed both globally and locally in project and I get 
![](http://puu.sh/iTOUe/1db65c67c4.png)
