### ISSUE TITLE
Package activation time causes significant slowdown for new Atom windows

### ISSUE THREAD

**Issue by joefitzgerald** [AtomLinter/linter-eslint#871]
## Issue Type
Bug

## Issue Description
`linter-eslint` is doing too much synchronously during package activation:
* Requires should be switched to lazy requires
* Use of atom-package-deps should be put behind a debounce
* The worker should be spawned after activation
* Observation of text editor (and other) events should be moved out of activate and ideally behind a debounce

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] ~Paste the output of the `Linter Eslint: Debug` command from the Command Palette below~

![screen shot 2017-04-03 at 11 16 08 am](https://cloud.githubusercontent.com/assets/744740/24621758/dd847d42-185f-11e7-85b0-e542f3b5a54b.png)

**Comment by Arcanemagus** [comment]
To clarify a little bit here, "debounce" means `setTimeout(() => { // do time consuming stuff here }, 0)` in this case.

**Comment by sunjay** [comment]
I am also experiencing this. This package adds a lot to the startup time.

![screenshot from 2017-04-04 20-25-19](https://cloud.githubusercontent.com/assets/530939/24684554/e65af6ce-1974-11e7-9fa2-5f51e924b37f.png)

**Comment by Arcanemagus** [comment]
Okay, I've got a version that goes from an average of 177 ms "activation" time down to 7 ms "activation" time. Note that TimeCop is a bit deceptive here as it counts loading the main file as part of the activation time, not part of the package loading.

As it stands, the current breakdown on my machine for the state of this branch is:
* Total "activation" time: 7.5 ms
* Atom figuring out where the main file is: 1.9 ms
* Ensuring the main file exists: 0.1 ms
* Loading the main file 1.4 ms
  * Finding the file: 0.7 ms
  * Reading and checking if it should compile: 0.3 ms
  * "compiling" the file: 0.3 ms
    * computing/checking the hash: 0.1 ms
    * **Actually** loading the code: 0.2 ms
* `activate()` function: 1.1 ms
  * Includes all command registration and setting observation
* Atom handling service registration: 1.9 ms
* Any remainder is Atom internal code running

So at this point the only things we have control over are the file size (0.2 ms) and registering all commands and observing all settings (1.1 ms).

I'll be pushing this up once #873 gets merged.

**Comment by Arcanemagus** [comment]
Published in v8.1.6! 🎉
