### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-eslint#88]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by iam4x** [comment]
@AsaAyers I'll take care of this one, got a working version: https://github.com/iam4x/linter-plus-eslint

**Comment by AsaAyers** [comment]
Just to clarify, the plan is to fold those changes back into this repo so users can just use the normal upgrade process, right?

**Comment by iam4x** [comment]
Absolutely

**Comment by iam4x** [comment]
Version 1.0 is out with these changes.
