### ISSUE TITLE
[Linter-ESLint] Worker died unexpectedly

### ISSUE THREAD

**Issue by ansmonjol** [AtomLinter/linter-eslint#893]
## Issue Type
Got a bug since I've updated my linter-eslint pckage on atom.

## Issue Description
Every time the linter have to check for errors, I have this error (cf screenshot) and the animated linter icon (white on the screenshot) keep turning.

I know this error appear on different issues already fixed but every time it've been solved with a patch. Does any one else get the same output message ? 
I don't have any new linter-eslint version to update

## Versions
linter-eslint: 8.1.6

```
[Linter-ESLint] Worker died unexpectedly
Check your console for more info. A new worker will be spawned instantly.
```
![image](https://cloud.githubusercontent.com/assets/5517077/25280224/7c921dac-26a9-11e7-86f9-0e214a817b23.png)

Thanks in advance for your answers

**Comment by IanVS** [comment]
Have you tried restarting atom?  Are you able to post the output of the `Linter Eslint: Debug` command, as requested in the issue template?

**Comment by ansmonjol** [comment]
I've restarted but the messsage still show

**Comment by IanVS** [comment]
Are you able to post the output of the Linter Eslint: Debug command, as requested in the issue template?  It is in the command palette.

**Comment by ansmonjol** [comment]
My bad, is that what you was asking for ?

```
Atom version: 1.14.0
linter-eslint version: 8.1.6
ESLint version: 2.13.1
Hours since last Atom restart: 1
Platform: darwin
Using local project ESLint from: /Users/alexandre/Developer/YoungApp/glace/app/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.block.es",
  "meta.static",
  "meta.function.body",
  "meta.block.es",
  "meta.block.es",
  "string.quoted.single.js",
  "punctuation.definition.string.end.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
Looks like your project's ESLint configuration is referencing an `estraverse-fb` module that isn't installed in your project. Installing that _should_ fix this for you.

Note that your version of ESLint is _very_ old and has several known bugs. If at all possible you should look into updating your configuration. Check out the [migration guide](http://eslint.org/docs/user-guide/migrating-to-3.0.0) for things to watch out for.

**Comment by ansmonjol** [comment]
I've juste updated my linter version to 3.19 but the linter still not working.

Maybe there is something to do to "restart" the linter ? I've tried to restart atom and reinstall the linter eslint package 

```
Atom version: 1.14.0
linter-eslint version: 8.1.6
ESLint version: 3.19.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/alexandre/Developer/YoungApp/glace/app/node_modules/eslint
Current file's scopes: [
  "source.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "meta.structure.dictionary.json",
  "meta.structure.dictionary.value.json",
  "string.quoted.double.json"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by IanVS** [comment]
@ansmonjol does ESLint run correctly from the command line, without Atom?

**Comment by ansmonjol** [comment]
Yes it is.

I just have to `--no-eslintrc` because I'm using an external git repo for the rules (I've updated his eslint package version too)

**Comment by IanVS** [comment]
What happens if you don't run with `--no-eslintrc`?

**Comment by ansmonjol** [comment]
Fixed by updating all my `eslint` and `eslint-*` in `package.json` and my personal rules as node modules.

Thank you guys !
