### ISSUE TITLE
Newbie question: how to display the red bars?

### ISSUE THREAD

**Issue by tdkehoe** [AtomLinter/linter-eslint#91]
I installed linter-eslint but I don't see any differences when I'm coding, i.e., there are no red bars to indicate mistakes. Either I haven't made any mistakes yet :-)  or something's not installed. What I did was this in the directory with my files:

    apm install linter-eslint

That seemed to install correctly. Then I quit Atom and restarted it. Is there something else I have to do? Edit a .json file? Change configurations?

**Comment by iam4x** [comment]
In order to make it work you have to install Linter too, `$ apm install linter`
