### ISSUE TITLE
Invalid position given by 'null'

### ISSUE THREAD

**Issue by sandrina-p** [AtomLinter/linter-eslint#917]
ESLint returned a point that did not exist in the document being edited.
Rule: `null`
Requested range: 27:12

Debug information:
```json
{
  "atomVersion": "1.12.7",
  "linterEslintVersion": "8.1.7",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "3.19.0",
  "hoursSinceRestart": 3.2,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "/Volumes/osx/ss/git/s008080/node_modules/eslint",
  "editorScopes": [
    "source.js.jsx",
    "meta",
    "meta.function.body",
    "meta.block.es",
    "meta.block.es",
    "string.quoted.double.js",
    "punctuation.definition.string.end.js"
  ]
}
```

**Comment by IanVS** [comment]
Hm, interesting. Are you able to share the section of code that caused this error? Did you have a syntax error?

You seem to have a fairly old version of atom, you could try updating, but I'm not certain it would solve this error.

**Comment by sandrina-p** [comment]
Hey! It is caused when I have a sintax error on an object, when I miss a `,` between the value and the next key.

I updated the Atom, and the error disappears and it shows the right one.  `Parsing error: Unexpected token "key" (Fatal)`.

:)

**Comment by IanVS** [comment]
That's correct, a parsing error will always prevent other linting, because it means your javascript is invalid.
