### ISSUE TITLE
Question: linter-eslint wants `0`, `1` or `2` for severity, but is it possible to get it to accept false?

### ISSUE THREAD

**Issue by Huanzhang89** [AtomLinter/linter-eslint#919]
## Issue Type

Question

## Issue Description

The `eslintrc` file for the project I am currently working on uses only true/false for linting rules but this throws an error in linter-eslint. Not everyone on the project uses atom/linter-eslint. Is there a way around this that I can implement locally?

I know I can just global ignore the eslintrc file but that would also mean any changes made to the file will need to be manually updated.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
Configuration for rule "react/require-default-props" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'false').
```

**Comment by IanVS** [comment]
Can you please post a part of your `.eslintrc` as well as the version of eslint that you are using?

**Comment by Huanzhang89** [comment]
Thanks for the quick response

version that throws error
```
  "react/require-default-props": [false],
    "react/forbid-prop-types": [false],
```

version that works 
```
    "react/require-default-props": [0],
    "react/forbid-prop-types": [0],
```

**Comment by IanVS** [comment]
`[false]` is not a valid configuration.  The configuration of rules is explained in http://eslint.org/docs/user-guide/configuring#configuring-rules, but you can use `"off", "warn", "error"` or `0, 1, 2`, but not `true, false`.

**Comment by Huanzhang89** [comment]
Ok thanks a lot, that does seem to be more logical 😄
