### ISSUE TITLE
Invalid position given by 'null'

### ISSUE THREAD

**Issue by naurizali96** [AtomLinter/linter-eslint#931]
ESLint returned a point that did not exist in the document being edited.
Rule: `null`
Requested range: 36:8

    import React, { Component } from 'react';
    import { View, Text } from 'react-native';
    import { Card, CardSection, Button } from './common';

    class StartPage extends Component{ 
      render() {
        return (
          <Card>
            <CardSection>
              <View style={styles.headerContentStyle}>
            <Text style={styles.headerTextStyle}>
              Отправлять  вещи теперь  проще простого!
            </Text>
          </View>
        </CardSection>

        <CardSection>
          <View style={styles.headerContentStyle}>
            <Text style={styles.middleTextStyle}>
              Вместе с ALIM
            </Text>
          </View>
        </CardSection>

        <CardSection>
          <Button>
            Начать
          </Button>
        </CardSection>
      </Card>
    );
     }

     const styles = {
    headerContentStyle: {

      alignItems: 'center',
      marginLeft: 50,
      marginRight: 50
    },
    headerTextStyle: {
      fontSize: 18
    },
    middleTextStyle: {
      fontSize: 24,
      fontWeight: 'bold'
       }
      }
    }

    export default StartPage;

Debug information:
```json
{
  "atomVersion": "1.17.2",
  "linterEslintVersion": "8.1.7",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "3.19.0",
  "hoursSinceRestart": 0.8,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "/Users/nauka/react/bereke/node_modules/eslint",
  "editorScopes": [
    "source.js"
  ]
}
```

**Comment by IanVS** [comment]
This happens sometimes when ESLint hits a parsing error (in this case, using `const` inside your class) and reports a point (line:column) which doesn't exist in the file.  Unfortunately there's not really anything we can do for this within linter-eslint.  But thanks for reporting!
