### ISSUE TITLE
Run "fix-errors" on current opened file

### ISSUE THREAD

**Issue by daveyx** [AtomLinter/linter-eslint#940]
## Issue Type
Question

## Issue Description
- Installed package in atom
- leave "Fix errors on save" unchecked
- plugin shows errors in file

How can i run "fix errors" only on the current opened file?
I can not find something in the contextmenu or in the linter view.
Is there a keyboardshortcut?

**Comment by IanVS** [comment]
You can run `Linter eslint: Fix file` from the atom command palette.  On mac the keyboard shortcut is `cmd-shift-p`.  On linux/windows it is `ctrl-shift-p`
