### ISSUE TITLE
Error description no longer linking to ESLint website with error info

### ISSUE THREAD

**Issue by adamreisnz** [AtomLinter/linter-eslint#949]
## Issue Type
Bug

## Issue Description
The list of errors no longer provides a link to the ES Lint rule page: 

![image](https://user-images.githubusercontent.com/490562/27453989-6900245e-57ec-11e7-819f-a4279a524ad8.png)

Nothing in there is clickable, except the line number.

This used to work ok before the new linter layout was introduced.

**Comment by Arcanemagus** [comment]
You should file this over in [linter-ui-default](https://github.com/steelbrain/linter-ui-default/issues), we're providing the information, it just doesn't show it in the panel (only tooltips for some reason).

**Comment by adamreisnz** [comment]
Will do 👍
