### ISSUE TITLE
linter-eslint breaks after 4.0.0-beta.0

### ISSUE THREAD

**Issue by almadsen** [AtomLinter/linter-eslint#952]
linter-eslint gives an error after updating to anything higher, and including, eslint 4.0.0-beta.0

Guess you already know this but can't find issue about it here and just wanted to know of any chances of fix for this in not so remote future?

**Comment by IanVS** [comment]
Can you please give a few more details? In what way is it breaking?

**Comment by Arcanemagus** [comment]
The only known issue with v4 is https://github.com/AtomLinter/linter-eslint/issues/908 currently, so no we don't know this 😛.

**Comment by almadsen** [comment]
This is weird, reinstalled eslint up to v4.1.1 again and now it's working again.
So I'll get back if it happens again and with some more details.
