### ISSUE TITLE
The linter show file import errors where the eslint cli doesn't

### ISSUE THREAD

**Issue by fernandofleury** [AtomLinter/linter-eslint#960]
## Issue Type
Question

## Issue Description
I've a different output of `linter-eslint` versus `eslint cli`.
It's complaining along with the `eslint-plugin-import` on the init of every single file:

![image](https://user-images.githubusercontent.com/2780941/28417989-60947382-6d5a-11e7-8ec5-b01ec9d62d2f.png)

and also with the usage of `eslint-import-resolver-webpack` it's not being able to resolve my alias (as shown on the last line of the print)

Maybe I'm missing something?

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.18.0
linter-eslint version: 8.2.1
ESLint version: 3.19.0
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /Users/fleury/projects/cw-dev-buyer/node_modules/eslint
Current file's scopes: [
  "source.js.jsx"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by IanVS** [comment]
Thanks @fernandofleury, is it possible this could be related to https://github.com/AtomLinter/linter-eslint/issues/610?

**Comment by fernandofleury** [comment]
Hi @IanVS thanks for the quick reply. Yes, it looks like. Let me explain a bit further:

I have an alias on webpack to `app/assets/client/`, and was referencing the config with the webpack import/resolver. after changing to the node import/resolver:

```json
"import/resolver": {
      "node": {
        "paths": ["./app/assets/client"]
      }
}
```

I suppose I should close this issue and open one at [eslint-import-resolver-webpack)[https://github.com/benmosher/eslint-plugin-import/issues] right?
