### ISSUE TITLE
Support specifying file extensions to lint

### ISSUE THREAD

**Issue by weizhenye** [AtomLinter/linter-eslint#966]
## Issue Type

Feature Request

## Issue Description

I'm using [eslint-plugin-vue@3](https://github.com/vuejs/eslint-plugin-vue) to lint [`.vue`](https://vuejs.org/v2/guide/single-file-components.html) files, but the `<template>` part is not lint by linter-eslint.

When `eslint-plugin-vue` is in version 2, it uses `eslint-plugin-html` internally, so after I turning `Lint HTML files` on it just works as expected. In version 3 of `eslint-plugin-vue`, it use its own parser instead of depending `eslint-plugin-html`, so now it can lint Vue template syntax.

The command `eslint Demo.vue --ext=vue` works fine, but `.vue` files will not lint by linter-eslint default. After turning `Lint HTML files` on, only the `<script>` part can be lint. To be precise, if there are lint errors in both `<template>` and `<script>`, modifying the `<template>` part **will not** trigger linter-eslint to lint this file and not errors are showed, but modifying the `<script>` part **will** lint this file and both errors are showed.

Maybe a `Lint Vue files` config can be added which requires users to install `eslint-plugin-vue`, but I'm wondering if it's possible to support specifying custom file extensions.

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.18.0
linter-eslint version: 8.2.1
ESLint version: 3.19.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/xxx/projects/xxx/node_modules/eslint
Current file's scopes: [
  "text.html.vue"
]
linter-eslint configuration: {
  "lintHtmlFiles": true,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
You need to put the cursor within one of these `<template>` blocks, run the `Editor: Log Cursor Scope` command from the Command Palette and then in your settings add the top scope to the "List of scopes..." setting. It should be something like `source.____`.

**Comment by weizhenye** [comment]
It works, thanks!

**Comment by msokk** [comment]
@weizhenye did you add `text.html.vue` to scope? The same top level scope is in `<style>` block too, so CSS gets linted...

@Arcanemagus is there any way to exclude scopes? Could blacklist `<style>` block with second level scope - `source.css.scss.embedded.html`. Unfortunately `<template>` block contains no deeper useful scopes.

**Comment by weizhenye** [comment]
@msokk Yes, but it seems not lint errors show in `<style>`. I'm using cssnext syntax.

**Comment by msokk** [comment]
@weizhenye I'm only getting `max-len` (max 100ch) errors for long `background`statements. Maybe you don't have any? :)

**Comment by weizhenye** [comment]
@msokk I tested just now, got this error too.

**Comment by msokk** [comment]
I'll ask in `vue-eslint-parser` repo, as this is not related to atom linter anymore.

**Comment by Arcanemagus** [comment]
> is there any way to exclude scopes?

@msokk Nope, if you are trying to exclude scopes maybe you need a more specific activation scope?

**Comment by msokk** [comment]
Unfortunately the only scope in some parts of the `<template>` tag is `text.html.vue`, but I managed to work around the `max-len` issues and it is a known limitation of `vue-eslint-parser` - https://github.com/mysticatea/vue-eslint-parser/issues/15#issuecomment-322093990
