### ISSUE TITLE
Regressions since a recent release

### ISSUE THREAD

**Issue by tzusman** [AtomLinter/linter-eslint#967]
## Issue Type
Bug

## Issue Description
The package used to perform fantastically and consistently.  Now I frequently need to restart Atom, or close and re-open the file to get the correct behavior.  Sometimes it seems as if the linter freezes and so any changes I make don't update the UI's red error labels, I just see the blinking yellow dot in the bar at the bottom.

## Bug Checklist
There is no debug output, just a blinking yellow dot.

## Versions
atom: 1.18.0 x64
linter: 2.2.0
linter-eslint: 8.2.1
linter-ui-default: 1.6.3

---
I wish I could give more accurate details, but the behavior is very erratic.  No rhyme or reason on when it happens, what file it happens to, or even the fix.  Sometimes its a full atom restart, sometimes just close and reopen the file.

Happy to walk through debugging steps to help resolve.

**Comment by IanVS** [comment]
There have been a number of reports of high memory usage (e.g. https://github.com/AtomLinter/linter-eslint/issues/925, https://github.com/AtomLinter/linter-eslint/issues/927, https://github.com/AtomLinter/linter-eslint/issues/930) after we started to use the Atom task api in version `8.2.0`.  However, troubleshooting the exact cause or causes has been fruitless so far.  Unfortunately, your only real option for now is to downgrade to 7.3.2 using `apm install linter-eslint@7.3.2` until a fix can be found.

**Comment by ctcpip** [comment]
There is specifically a problem with the `8.2.1` release.  Look at its `package.json` - it is using old version of ESLint, etc..  It looks like a release tag may have been mistakenly created.

**Comment by brandondurham** [comment]
Amazingly linter-eslint is still not working for me. I have to stay on 7.3.2.

**Comment by skylize** [comment]
Not enough info here to differentiate it from #927. Let us know if you have details on more specific bugs besides that one. For now closing as duplicate.
