### ISSUE TITLE
The eslint-import-resolver-babel-plugin-root-import reports errors under Atom that aren't displayed using the CLI

### ISSUE THREAD

**Issue by timothyarmes** [AtomLinter/linter-eslint#971]
## Issue Type

Bug

## Issue Description

The eslint-import-resolver-babel-plugin-root-import reports errors under Atom that aren't displayed using the CLI. The errors are displayed from imports in files that are in _subdirectories_, but not files that are in the root. 

I've tracked this down to the fact that the plugin starts a search for the .bablerc file from the cwd:

````
const opts = getConfigFromBabel(process.cwd(), babelrc);
````

I would expect the linter-eslint plugin to also operate from the project root, which would fix this issue, however there may be other issues with doing that which I don't realise.

**Comment by Arcanemagus** [comment]
Would you mind trying out the [current `master` ](https://github.com/AtomLinter/linter-eslint/tree/cd7de8d392926363cef29ca5dcb27e36b389423c) branch? It sounds like this might have been already fixed by https://github.com/AtomLinter/linter-eslint/pull/965.

**Comment by timothyarmes** [comment]
Hi. Great, thanks.

Having read the thread I also discovered the .eslintignore workaround. That's even better for me since open a parent folder into Atom.
