### ISSUE TITLE
Invalid position given by 'jsx-quotes'

### ISSUE THREAD

**Issue by mikefey** [AtomLinter/linter-eslint#976]
ESLint returned a point that did not exist in the document being edited.
Rule: `jsx-quotes`
Requested range: 90:52

Debug information:
```json
{
  "atomVersion": "1.18.0",
  "linterEslintVersion": "8.1.5",
  "linterEslintConfig": {
    "eslintRulesDir": "tools/eslint",
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "2.13.1",
  "hoursSinceRestart": 1.3,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "node_modules/eslint",
  "editorScopes": [
    "source.js.jsx",
    "tag.open.js",
    "meta.brace.curly.js",
    "punctuation.definition.brace.curly.end.js"
  ]
}
```

**Comment by Arcanemagus** [comment]
Your ESLint and `linter-eslint` versions are both out of date, the important one here being that your ESLint is v2.13.1 while the current version is v4.4.1. Can you please update to the latest version of ESLint, taking care to read over the migration guides for [v3.0.0](http://eslint.org/docs/user-guide/migrating-to-3.0.0) and [v4.0.0](http://eslint.org/docs/user-guide/migrating-to-4.0.0).

**Comment by mikefey** [comment]
Thanks, will do. But it turns out this error was caused by invisible characters that were copied and pasted into the file, so after removing them everything works as expected with the current version also.
