### ISSUE TITLE
AtomLinter no longer reporting ESLint issues

### ISSUE THREAD

**Issue by michaelfich** [AtomLinter/linter-eslint#977]
## Issue Type

Bug

## Issue Description

The linter-eslint plugin is no longer displaying the linting errors, however I have several other AtomLinter packages installed and those are still working.  When running `apm list | grep lint`, here are the following linters.  ESLint is the only one that has produced any issues:

```
├── linter@2.2.0
├── linter-elixirc@1.7.0
├── linter-erb@1.1.0
├── linter-eslint@8.2.1
├── linter-handlebars@2.5.0
├── linter-markdown@5.1.0
├── linter-pycodestyle@2.0.2
├── linter-rubocop@2.1.1
├── linter-scss-lint@3.1.0
├── linter-ui-default@1.6.3
```

## Bug Checklist
- Running `eslint` (and a path to a file or folder) works just fine.
- I restarted Atom
- I then shut down atom, removed my `node_modules` and reinstalled my packages.
- I globally uninstalled `eslint` and reinstalled
- I have uninstalled and reinstalled `linter-eslint` as well
- I read through [this existing issue](https://github.com/AtomLinter/linter-eslint/issues/834) and opened a new issue as suggested at the end of it

```
Atom version: 1.19.0
linter-eslint version: 8.2.1
ESLint version: 3.19.0
Hours since last Atom restart: 0.3
Platform: darwin
Using local project ESLint from: /Users/michaelfich/Development/next/node_modules/eslint
Current file's scopes: [
  "source.js.extended",
  "meta.objectliteral.js",
  "punctuation.definition.block.js"
]
linter-eslint configuration: {
  "fixOnSave": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment]
It looks like you have installed some package into Atom that is changing the scope of JavaScript files to `source.js.extended`. You can add that to the list of supported scopes in the settings for `linter-eslint`, or you can switch the language in Atom to the default JavaScript one.

**Comment by michaelfich** [comment]
@Arcanemagus Thank you so much for the help!  That makes sense.  An ember syntax highlighter package made that change.  I appreciate the quick response!
