### ISSUE TITLE
Cannot make linter-eslint to work with .jsx files

### ISSUE THREAD

**Issue by peterKaleta** [AtomLinter/linter-eslint#98]
Is there any flag I can set to get linter-eslint working with .jsx files as well?

**Comment by bjoerge** [comment]
I'm also having this issue

**Comment by philostler** [comment]
Have you tried this in your `.eslintrc` file?

```json
{
  "ecmaFeatures": {
    "jsx": true
  },
  "env": {
    "es6": true
  }
}
````

**Comment by iam4x** [comment]
You must have https://github.com/orktes/atom-react installed to have the syntax recognised.

**Comment by peterKaleta** [comment]
It works after latest update. Thanks !

**Comment by jackocnr** [comment]
FYI the `.eslintrc` syntax is now:
```json
{
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true
  }
}
```
Source: https://github.com/yannickcr/eslint-plugin-react
