### ISSUE TITLE
Invalid position given by 'comma-dangle'

### ISSUE THREAD

**Issue by lil5** [AtomLinter/linter-eslint#980]
ESLint returned a point that did not exist in the document being edited.
Rule: `comma-dangle`
Requested range: 5:13

```javascript
module.exports = {
```
on line 1

Debug information:
```json
{
  "atomVersion": "1.17.2",
  "linterEslintVersion": "8.2.1",
  "linterEslintConfig": {
    "fixOnSave": true,
    "globalNodePath": "/home/lil/.nvm/versions/node/v8.2.1",
    "lintHtmlFiles": true,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "4.4.1",
  "hoursSinceRestart": 2,
  "platform": "linux",
  "eslintType": "local project",
  "eslintPath": "<Project>/node_modules/eslint",
  "editorScopes": [
    "source.js"
  ]
}
```

**Comment by Arcanemagus** [comment]
Are you able to share code that reproduces this?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response unfortunately as it looked like this was a valid ESLint bug that needed to be reported there...

**Comment by lil5** [comment]
Turned out to be an unrelated typo.
Sorry for the hassle.

**Comment by Arcanemagus** [comment]
@lil5 The fact that it showed this at all means that ESLint reported a point that didn't exist in the document itself, which usually means either a race condition which we guard against (but there is still a ~3 ms window where it could happen), or a bug in ESLint.

Getting a state of code where these reproduce is usually somewhat difficult to determine though.
