### ISSUE TITLE
Normalize paths in settings

### ISSUE THREAD

**Issue by mickyginger** [AtomLinter/linter-eslint#985]
This is not a bug, more an inconsistency with the settings.

I can set the location of my eslintrc file with a tilde like so:

```
~/.eslintrc
```

However, setting the Global Node Installation Path to

```
~/.config/yarn/global
```

does not work, but

```
/Users/mickyginger/.config/yarn/global
```
works fine

**Comment by IanVS** [comment]
@mickyginger I agree completely.  Would you be willing to take a crack at a PR?  The team that maintains this package is basically just two people, and we're unfortunately a bit swamped right now.  Any help you can give would be awesome.
