### ISSUE TITLE
Linter error status when typing covers auto complete

### ISSUE THREAD

**Issue by neurosnap** [AtomLinter/linter-eslint#986]
## Issue Type
Polish

## Issue Description
Type a line of code
Linter displays error about invalid syntax

CURRENT
Error display covers autocomplete

EXPECTED
The error message to be out of the way of the text I am typing as well as autocomplete

![screen shot 2017-08-15 at 9 06 56 am](https://user-images.githubusercontent.com/1940365/29317329-6b824f1e-8199-11e7-92de-0870afb6e19e.png)

**Comment by Arcanemagus** [comment]
This package has nothing to do with the Linter interface, you can find the current issue for this at https://github.com/steelbrain/linter-ui-default/issues/415.

**Comment by Arcanemagus** [comment]
Duplicate of https://github.com/steelbrain/linter-ui-default/issues/415
