### ISSUE TITLE
What are the keybinds?

### ISSUE THREAD

**Issue by KonradHoeffner** [AtomLinter/linter-eslint#990]
## Question
What are the keybindings for next/previous warning and next/previous error? And what are their identifiers for customizing them in the Atom keymap?

**Comment by Arcanemagus** [comment]
This package has nothing to do with the interface, you'll want to look at [linter-ui-default](https://github.com/steelbrain/linter-ui-default) for this question.

**Comment by KonradHoeffner** [comment]
Oh sorry, didn't know that, thanks for the link!
