### ISSUE TITLE
Uncaught Error: Column start (1) greater than line length (0) for line 11

### ISSUE THREAD

**Issue by djake** [AtomLinter/linter-eslint#995]
[Enter steps to reproduce:]

1. Open a file in a project that does not have eslint, with 'Disable when no ESLint config is found'. (I don't know if this is relevant.)

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.2.1

### Stack Trace

Uncaught Error: Column start (1) greater than line length (0) for line 11

```
At /Users/jake/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:181

Error: Column start (1) greater than line length (0) for line 11
    at generateRange (/packages/linter-eslint/node_modules/atom-linter/lib/index.js:181:11)
    at getRange (/packages/linter-js-standard/lib/utils/linter.js:16:10)
    at /packages/linter-js-standard/lib/utils/linter.js:39:19
    at Array.forEach (native)
    at Object.module.exports (/packages/linter-js-standard/lib/utils/linter.js:29:8)
    at /Users/jake/Documents/repos/v/services/pages/node_modules/standard-engine/index.js:177:5
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:13.1.0 core:close (atom-pane.pane)
     -4:22.8.0 snippets:next-tab-stop (input.hidden-input)
     -4:22.8.0 snippets:expand (input.hidden-input)
     -4:22.8.0 editor:indent (input.hidden-input)
     -4:07.9.0 settings-view:open (input.hidden-input)
  4x -3:26.3.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.2 
autocomplete-modules 1.7.0 
busy-signal 1.4.3 
change-case 0.6.5 
color-picker 2.2.5 
custom-title 1.0.1 
double-tag 0.9.0 
goto-definition 1.3.4 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 4.0.0 
linter-jsonlint 1.3.0 
linter-sass-lint 1.7.6 
linter-ui-default 1.6.8 
pretty-json 1.6.4 
project-manager 3.3.5 
react 0.16.2 
```

**Comment by Arcanemagus** [comment]
> `at Object.module.exports (/packages/linter-js-standard/lib/utils/linter.js:29:8)`

This is coming from `linter-js-standard`, not `linter-eslint`. (It just happens that Atom is using the same `atom-linter` instance for both.

Also, just as a note `standard` is a wrapper around ESLint 😉.

**Comment by djake** [comment]
Thanks - regarding your last commend, if a project uses the standard package (i.e. npmjs.org/standard), do you expect linter-eslint to work on its own? I use eslintrc to extend standard, but not all the projects I work on do...

**Comment by Arcanemagus** [comment]
If there is no ESLint configuration `linter-eslint` by default does nothing, so normally it wouldn't work if the project was just using `standard` (even though `eslint` would be installed in the project).
