### ISSUE TITLE
Add mechanism to disable an error on next line

### ISSUE THREAD

**Issue by adamreisnz** [AtomLinter/linter-eslint#999]
## Issue Type
Feature request

## Issue Description
Is it possible to add a mechanism to quickly include a 

```js
//eslint-disable-next-line <error-rule-here>
```

directive, for example when right clicking on an error? 

So if a `no-unused-vars` error appears, and you want to ignore it, you'd right click, select something like "Disable error" and it would generate a comment above the erroring line:

```js
//eslint-disable-next-line no-unused-vars
```

Would save us the hassle of having to type it out and know/remember/look up the specific error codes.

**Comment by Arcanemagus** [comment]
I'm going to close this as `wontfix`.

The only way we could easily implement this is to specify a "fix" for the message that would add that text. The problem with this solution is that ESLint already has a `fix` for most messages reported, so this would only inconsistently apply.

A much better solution for this would be for you to add a Snippet that inserts this text for you. You can find details on how to do this in the [Snippets](http://flight-manual.atom.io/using-atom/sections/snippets/) section of Atom's Flight Manual.

Thanks for taking the time to file an issue about this!

**Comment by adamreisnz** [comment]
A snippet would not be useful, because the snippet doesn't know which error is causing the problem. ESLint linter does however, so it would be perfect for the job.

I feel like maybe you missed what I was trying to bring across.

**Comment by Arcanemagus** [comment]
No, I know exactly what you are trying to do, it's just quite complex to do correctly here and not something we want to take on the responsibility of maintaining.

To do this you would need to register a command that:
1. When triggered checks the list of messages under the last cursor added to Atom
2. If there _is_ a message, and it's one that was sent by `linter-eslint` then pull out the rule that is associated with the message (if there is one)
3. Generate an `//eslint-disable-next-line rule-name` comment
4. Determine the indent level to insert at
5. Insert a new line above the current one, insert the appropriate indentation, and insert the disable comment

You _could_ simplify steps 1 and 2 by keeping a local cache of the messages here in `linter-eslint` and handling it that way.

I suggested a snippet as that would be a quick way to insert the `// eslint-disable-next-line ` part, then you would just need to manually fill in the rule name.

**Comment by adamreisnz** [comment]
Ok thanks for clarifying 👍 

I was under the impression that steps 1 and 2 would be quite simple, as the package basically "knows" which line has which error. Maybe it doesn't work that way under the hood.

Steps 3-5 are pretty much one step, and I can't imagine it being overly complicated, but I understand if you don't want this package to do that kind of work.

I'll make a snippet and work with what we've got.
